/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/core_wrapTMR.sv                                                             *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:16                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/core_wrap.sv                                                                  *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-12 14:35:25.981269                                         *
 *           File Size         : 3316                                                               *
 *           MD5 hash          : bf9ec976dfe55476408b4ffbd770e36f                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module core_wrapTMR import croc_pkg::*; (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic ref_clk_iA,
  input logic ref_clk_iB,
  input logic ref_clk_iC,
  input logic test_enable_iA,
  input logic test_enable_iB,
  input logic test_enable_iC,
  input logic [15:0] irqs_iA,
  input logic [15:0] irqs_iB,
  input logic [15:0] irqs_iC,
  input logic timer0_irq_iA,
  input logic timer0_irq_iB,
  input logic timer0_irq_iC,
  input logic [31:0] boot_addr_iA,
  input logic [31:0] boot_addr_iB,
  input logic [31:0] boot_addr_iC,
  output logic instr_req_oA,
  output logic instr_req_oB,
  output logic instr_req_oC,
  input logic instr_gnt_iA,
  input logic instr_gnt_iB,
  input logic instr_gnt_iC,
  input logic instr_rvalid_iA,
  input logic instr_rvalid_iB,
  input logic instr_rvalid_iC,
  output logic [31:0] instr_addr_oA,
  output logic [31:0] instr_addr_oB,
  output logic [31:0] instr_addr_oC,
  input logic [31:0] instr_rdata_iA,
  input logic [31:0] instr_rdata_iB,
  input logic [31:0] instr_rdata_iC,
  input logic instr_err_iA,
  input logic instr_err_iB,
  input logic instr_err_iC,
  output logic data_req_oA,
  output logic data_req_oB,
  output logic data_req_oC,
  input logic data_gnt_iA,
  input logic data_gnt_iB,
  input logic data_gnt_iC,
  input logic data_rvalid_iA,
  input logic data_rvalid_iB,
  input logic data_rvalid_iC,
  output logic data_we_oA,
  output logic data_we_oB,
  output logic data_we_oC,
  output logic [3:0] data_be_oA,
  output logic [3:0] data_be_oB,
  output logic [3:0] data_be_oC,
  output logic [31:0] data_addr_oA,
  output logic [31:0] data_addr_oB,
  output logic [31:0] data_addr_oC,
  output logic [31:0] data_wdata_oA,
  output logic [31:0] data_wdata_oB,
  output logic [31:0] data_wdata_oC,
  input logic [31:0] data_rdata_iA,
  input logic [31:0] data_rdata_iB,
  input logic [31:0] data_rdata_iC,
  input logic data_err_iA,
  input logic data_err_iB,
  input logic data_err_iC,
  input logic debug_req_iA,
  input logic debug_req_iB,
  input logic debug_req_iC,
  input logic fetch_enable_iA,
  input logic fetch_enable_iB,
  input logic fetch_enable_iC,
  output logic core_busy_oA,
  output logic core_busy_oB,
  output logic core_busy_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_ibextmrErrorC;
wire i_ibextmrErrorB;
wire i_ibextmrErrorA;
logic [31:0] ibex_boot_addrA;
logic [31:0] ibex_boot_addrB;
logic [31:0] ibex_boot_addrC;
assign ibex_boot_addrA = boot_addr_iA&32'hFFFFFF00;
assign ibex_boot_addrB = boot_addr_iB&32'hFFFFFF00;
assign ibex_boot_addrC = boot_addr_iC&32'hFFFFFF00;

cve2_coreTMR #(.PMPEnable(1'b0), .PMPGranularity(0), .PMPNumRegions(4), .MHPMCounterNum(0), .MHPMCounterWidth(40), .RV32E(0), .RV32M(cve2_pkg::RV32MNone), .RV32B(cve2_pkg::RV32BNone), .DbgTriggerEn(1'b1), .DbgHwBreakNum(1), .DmHaltAddr(DebugAddrOffset + dm::HaltAddress[31:0]), .DmExceptionAddr(DebugAddrOffset + dm::ExceptionAddress[31:0])) i_ibex (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_en_iA(test_enable_iA),
    .test_en_iB(test_enable_iB),
    .test_en_iC(test_enable_iC),
    .hart_id_iA(HartId),
    .hart_id_iB(HartId),
    .hart_id_iC(HartId),
    .boot_addr_iA(ibex_boot_addrA),
    .boot_addr_iB(ibex_boot_addrB),
    .boot_addr_iC(ibex_boot_addrC),
    .instr_req_oA(instr_req_oA),
    .instr_req_oB(instr_req_oB),
    .instr_req_oC(instr_req_oC),
    .instr_gnt_iA(instr_gnt_iA),
    .instr_gnt_iB(instr_gnt_iB),
    .instr_gnt_iC(instr_gnt_iC),
    .instr_rdata_iA(instr_rdata_iA),
    .instr_rdata_iB(instr_rdata_iB),
    .instr_rdata_iC(instr_rdata_iC),
    .instr_rvalid_iA(instr_rvalid_iA),
    .instr_rvalid_iB(instr_rvalid_iB),
    .instr_rvalid_iC(instr_rvalid_iC),
    .instr_addr_oA(instr_addr_oA),
    .instr_addr_oB(instr_addr_oB),
    .instr_addr_oC(instr_addr_oC),
    .instr_err_iA(instr_err_iA),
    .instr_err_iB(instr_err_iB),
    .instr_err_iC(instr_err_iC),
    .data_req_oA(data_req_oA),
    .data_req_oB(data_req_oB),
    .data_req_oC(data_req_oC),
    .data_gnt_iA(data_gnt_iA),
    .data_gnt_iB(data_gnt_iB),
    .data_gnt_iC(data_gnt_iC),
    .data_rvalid_iA(data_rvalid_iA),
    .data_rvalid_iB(data_rvalid_iB),
    .data_rvalid_iC(data_rvalid_iC),
    .data_we_oA(data_we_oA),
    .data_we_oB(data_we_oB),
    .data_we_oC(data_we_oC),
    .data_be_oA(data_be_oA),
    .data_be_oB(data_be_oB),
    .data_be_oC(data_be_oC),
    .data_addr_oA(data_addr_oA),
    .data_addr_oB(data_addr_oB),
    .data_addr_oC(data_addr_oC),
    .data_wdata_oA(data_wdata_oA),
    .data_wdata_oB(data_wdata_oB),
    .data_wdata_oC(data_wdata_oC),
    .data_rdata_iA(data_rdata_iA),
    .data_rdata_iB(data_rdata_iB),
    .data_rdata_iC(data_rdata_iC),
    .data_err_iA(data_err_iA),
    .data_err_iB(data_err_iB),
    .data_err_iC(data_err_iC),
    .irq_software_iA(1'b0),
    .irq_software_iB(1'b0),
    .irq_software_iC(1'b0),
    .irq_timer_iA(timer0_irq_iA),
    .irq_timer_iB(timer0_irq_iB),
    .irq_timer_iC(timer0_irq_iC),
    .irq_external_iA(1'b0),
    .irq_external_iB(1'b0),
    .irq_external_iC(1'b0),
    .irq_fast_iA(irqs_iA),
    .irq_fast_iB(irqs_iB),
    .irq_fast_iC(irqs_iC),
    .irq_nm_iA(1'b0),
    .irq_nm_iB(1'b0),
    .irq_nm_iC(1'b0),
    .irq_pending_oA(),
    .irq_pending_oB(),
    .irq_pending_oC(),
    .crash_dump_oA(),
    .crash_dump_oB(),
    .crash_dump_oC(),
    .debug_req_iA(debug_req_iA),
    .debug_req_iB(debug_req_iB),
    .debug_req_iC(debug_req_iC),
    .fetch_enable_iA(fetch_enable_iA),
    .fetch_enable_iB(fetch_enable_iB),
    .fetch_enable_iC(fetch_enable_iC),
    .core_busy_oA(core_busy_oA),
    .core_busy_oB(core_busy_oB),
    .core_busy_oC(core_busy_oC),
    .tmrErrorA(i_ibextmrErrorA),
    .tmrErrorB(i_ibextmrErrorB),
    .tmrErrorC(i_ibextmrErrorC)
  );
assign tmrErrorA = i_ibextmrErrorA;
assign tmrErrorB = i_ibextmrErrorB;
assign tmrErrorC = i_ibextmrErrorC;
endmodule

