/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/counterTMR.sv                                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:07                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/counter.sv                                                                    *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.997269                                         *
 *           File Size         : 1712                                                               *
 *           MD5 hash          : dd4df8c4a3b59d2194e89e890f8dd952                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module counterTMR #(
  parameter int unsigned WIDTH = 4,
  parameter bit STICKY_OVERFLOW = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic clear_iA,
  input logic clear_iB,
  input logic clear_iC,
  input logic en_iA,
  input logic en_iB,
  input logic en_iC,
  input logic load_iA,
  input logic load_iB,
  input logic load_iC,
  input logic down_iA,
  input logic down_iB,
  input logic down_iC,
  input logic [WIDTH - 1:0] d_iA,
  input logic [WIDTH - 1:0] d_iB,
  input logic [WIDTH - 1:0] d_iC,
  output logic [WIDTH - 1:0] q_oA,
  output logic [WIDTH - 1:0] q_oB,
  output logic [WIDTH - 1:0] q_oC,
  output logic overflow_oA,
  output logic overflow_oB,
  output logic overflow_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_countertmrErrorC;
wire i_countertmrErrorB;
wire i_countertmrErrorA;

delta_counterTMR #(.WIDTH(WIDTH), .STICKY_OVERFLOW(STICKY_OVERFLOW)) i_counter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .clear_iA(clear_iA),
    .clear_iB(clear_iB),
    .clear_iC(clear_iC),
    .en_iA(en_iA),
    .en_iB(en_iB),
    .en_iC(en_iC),
    .load_iA(load_iA),
    .load_iB(load_iB),
    .load_iC(load_iC),
    .down_iA(down_iA),
    .down_iB(down_iB),
    .down_iC(down_iC),
    .delta_iA({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .delta_iB({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .delta_iC({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .d_iA(d_iA),
    .d_iB(d_iB),
    .d_iC(d_iC),
    .q_oA(q_oA),
    .q_oB(q_oB),
    .q_oC(q_oC),
    .overflow_oA(overflow_oA),
    .overflow_oB(overflow_oB),
    .overflow_oC(overflow_oC),
    .tmrErrorA(i_countertmrErrorA),
    .tmrErrorB(i_countertmrErrorB),
    .tmrErrorC(i_countertmrErrorC)
  );
assign tmrErrorA = i_countertmrErrorA;
assign tmrErrorB = i_countertmrErrorB;
assign tmrErrorC = i_countertmrErrorC;
endmodule

