/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/croc_socTMR.sv                                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:19                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/croc_soc.sv                                                                   *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.902268                                         *
 *           File Size         : 3490                                                               *
 *           MD5 hash          : 4082493e28351ba81959c49f3d569351                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module croc_socTMR import croc_pkg::*; #(
  parameter int unsigned GpioCount = 16
) (
  input logic clk_i,
  input logic rst_ni,
  input logic ref_clk_i,
  input logic testmode_i,
  input logic fetch_en_i,
  output logic status_o,
  input logic jtag_tck_i,
  input logic jtag_tdi_i,
  output logic jtag_tdo_o,
  input logic jtag_tms_i,
  input logic jtag_trst_ni,
  input logic uart_rx_i,
  output logic uart_tx_o,
  input logic [GpioCount - 1:0] gpio_i,
  output logic [GpioCount - 1:0] gpio_o,
  output logic [GpioCount - 1:0] gpio_out_en_o
  // output tmrError,
  // output tmrErrorA,
  // output tmrErrorB,
  // output tmrErrorC
);
wire uart_rx_iC;
wire uart_rx_iB;
wire uart_rx_iA;
wire testmode_iC;
wire testmode_iB;
wire testmode_iA;
wire rst_niC;
wire rst_niB;
wire rst_niA;
wire ref_clk_iC;
wire ref_clk_iB;
wire ref_clk_iA;
wire jtag_trst_niC;
wire jtag_trst_niB;
wire jtag_trst_niA;
wire jtag_tms_iC;
wire jtag_tms_iB;
wire jtag_tms_iA;
wire jtag_tdi_iC;
wire jtag_tdi_iB;
wire jtag_tdi_iA;
wire jtag_tck_iC;
wire jtag_tck_iB;
wire jtag_tck_iA;
wire [ (GpioCount-1) :0] gpio_iC;
wire [ (GpioCount-1) :0] gpio_iB;
wire [ (GpioCount-1) :0] gpio_iA;
wire fetch_en_iC;
wire fetch_en_iB;
wire fetch_en_iA;
wire clk_iC;
wire clk_iB;
wire clk_iA;
wire i_usertmrErrorC;
wire i_ext_intr_synctmrErrorC;
wire i_croctmrErrorC;
wire i_usertmrErrorB;
wire i_ext_intr_synctmrErrorB;
wire i_croctmrErrorB;
wire i_usertmrErrorA;
wire i_ext_intr_synctmrErrorA;
wire i_croctmrErrorA;
wire uart_tx_oTmrError;
wire status_oTmrError;
wire jtag_tdo_oTmrError;
wire gpio_out_en_oTmrError;
wire gpio_oTmrError;
wire uart_tx_oC;
wire uart_tx_oB;
wire uart_tx_oA;
wire status_oC;
wire status_oB;
wire status_oA;
wire jtag_tdo_oC;
wire jtag_tdo_oB;
wire jtag_tdo_oA;
wire [ (GpioCount-1) :0] gpio_out_en_oC;
wire [ (GpioCount-1) :0] gpio_out_en_oB;
wire [ (GpioCount-1) :0] gpio_out_en_oA;
wire [ (GpioCount-1) :0] gpio_oC;
wire [ (GpioCount-1) :0] gpio_oB;
wire [ (GpioCount-1) :0] gpio_oA;
logic synced_rst_nA;
logic synced_rst_nB;
logic synced_rst_nC;
logic synced_fetch_enA;
logic synced_fetch_enB;
logic synced_fetch_enC;

wire soc_faults;

rstgen i_rstgenA (
    .clk_i(clk_iA),
    .rst_ni(rst_niA),
    .test_mode_i(testmode_iA),
    .rst_no(synced_rst_nA),
    .init_no()
  );

rstgen i_rstgenB (
    .clk_i(clk_iB),
    .rst_ni(rst_niB),
    .test_mode_i(testmode_iB),
    .rst_no(synced_rst_nB),
    .init_no()
  );

rstgen i_rstgenC (
    .clk_i(clk_iC),
    .rst_ni(rst_niC),
    .test_mode_i(testmode_iC),
    .rst_no(synced_rst_nC),
    .init_no()
  );

syncTMR #(.STAGES(2), .ResetValue(1'b0)) i_ext_intr_sync (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(synced_rst_nA),
    .rst_niB(synced_rst_nB),
    .rst_niC(synced_rst_nC),
    .serial_iA(fetch_en_iA),
    .serial_iB(fetch_en_iB),
    .serial_iC(fetch_en_iC),
    .serial_oA(synced_fetch_enA),
    .serial_oB(synced_fetch_enB),
    .serial_oC(synced_fetch_enC),
    .tmrErrorA(i_ext_intr_synctmrErrorA),
    .tmrErrorB(i_ext_intr_synctmrErrorB),
    .tmrErrorC(i_ext_intr_synctmrErrorC)
  );
sbr_obi_req_t user_sbr_obi_reqA;
sbr_obi_req_t user_sbr_obi_reqB;
sbr_obi_req_t user_sbr_obi_reqC;
sbr_obi_rsp_t user_sbr_obi_rspA;
sbr_obi_rsp_t user_sbr_obi_rspB;
sbr_obi_rsp_t user_sbr_obi_rspC;
mgr_obi_req_t user_mgr_obi_reqA;
mgr_obi_req_t user_mgr_obi_reqB;
mgr_obi_req_t user_mgr_obi_reqC;
mgr_obi_rsp_t user_mgr_obi_rspA;
mgr_obi_rsp_t user_mgr_obi_rspB;
mgr_obi_rsp_t user_mgr_obi_rspC;
logic [NumExternalIrqs - 1:0] interruptsA;
logic [NumExternalIrqs - 1:0] interruptsB;
logic [NumExternalIrqs - 1:0] interruptsC;
logic [GpioCount - 1:0] gpio_in_syncA;
logic [GpioCount - 1:0] gpio_in_syncB;
logic [GpioCount - 1:0] gpio_in_syncC;

croc_domainTMR #(.GpioCount(GpioCount)) i_croc (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(synced_rst_nA),
    .rst_niB(synced_rst_nB),
    .rst_niC(synced_rst_nC),
    .ref_clk_iA(ref_clk_iA),
    .ref_clk_iB(ref_clk_iB),
    .ref_clk_iC(ref_clk_iC),
    .testmode_iA(testmode_iA),
    .testmode_iB(testmode_iB),
    .testmode_iC(testmode_iC),
    .fetch_en_iA(synced_fetch_enA),
    .fetch_en_iB(synced_fetch_enB),
    .fetch_en_iC(synced_fetch_enC),
    .jtag_tck_iA(jtag_tck_iA),
    .jtag_tck_iB(jtag_tck_iB),
    .jtag_tck_iC(jtag_tck_iC),
    .jtag_tdi_iA(jtag_tdi_iA),
    .jtag_tdi_iB(jtag_tdi_iB),
    .jtag_tdi_iC(jtag_tdi_iC),
    .jtag_tdo_oA(jtag_tdo_oA),
    .jtag_tdo_oB(jtag_tdo_oB),
    .jtag_tdo_oC(jtag_tdo_oC),
    .jtag_tms_iA(jtag_tms_iA),
    .jtag_tms_iB(jtag_tms_iB),
    .jtag_tms_iC(jtag_tms_iC),
    .jtag_trst_niA(jtag_trst_niA),
    .jtag_trst_niB(jtag_trst_niB),
    .jtag_trst_niC(jtag_trst_niC),
    .uart_rx_iA(uart_rx_iA),
    .uart_rx_iB(uart_rx_iB),
    .uart_rx_iC(uart_rx_iC),
    .uart_tx_oA(uart_tx_oA),
    .uart_tx_oB(uart_tx_oB),
    .uart_tx_oC(uart_tx_oC),
    .gpio_iA(gpio_iA),
    .gpio_iB(gpio_iB),
    .gpio_iC(gpio_iC),
    .gpio_oA(gpio_oA),
    .gpio_oB(gpio_oB),
    .gpio_oC(gpio_oC),
    .gpio_out_en_oA(gpio_out_en_oA),
    .gpio_out_en_oB(gpio_out_en_oB),
    .gpio_out_en_oC(gpio_out_en_oC),
    .gpio_in_sync_oA(gpio_in_syncA),
    .gpio_in_sync_oB(gpio_in_syncB),
    .gpio_in_sync_oC(gpio_in_syncC),
    .user_sbr_obi_req_oA(user_sbr_obi_reqA),
    .user_sbr_obi_req_oB(user_sbr_obi_reqB),
    .user_sbr_obi_req_oC(user_sbr_obi_reqC),
    .user_sbr_obi_rsp_iA(user_sbr_obi_rspA),
    .user_sbr_obi_rsp_iB(user_sbr_obi_rspB),
    .user_sbr_obi_rsp_iC(user_sbr_obi_rspC),
    .user_mgr_obi_req_iA(user_mgr_obi_reqA),
    .user_mgr_obi_req_iB(user_mgr_obi_reqB),
    .user_mgr_obi_req_iC(user_mgr_obi_reqC),
    .user_mgr_obi_rsp_oA(user_mgr_obi_rspA),
    .user_mgr_obi_rsp_oB(user_mgr_obi_rspB),
    .user_mgr_obi_rsp_oC(user_mgr_obi_rspC),
    .interrupts_iA(interruptsA),
    .interrupts_iB(interruptsB),
    .interrupts_iC(interruptsC),
    .core_busy_oA(status_oA),
    .core_busy_oB(status_oB),
    .core_busy_oC(status_oC),
    .tmrErrorA(i_croctmrErrorA),
    .tmrErrorB(i_croctmrErrorB),
    .tmrErrorC(i_croctmrErrorC),
    .faults_i(soc_faults)
  );

user_domainTMR #(.GpioCount(GpioCount)) i_user (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(synced_rst_nA),
    .rst_niB(synced_rst_nB),
    .rst_niC(synced_rst_nC),
    .ref_clk_iA(ref_clk_iA),
    .ref_clk_iB(ref_clk_iB),
    .ref_clk_iC(ref_clk_iC),
    .testmode_iA(testmode_iA),
    .testmode_iB(testmode_iB),
    .testmode_iC(testmode_iC),
    .user_sbr_obi_req_iA(user_sbr_obi_reqA),
    .user_sbr_obi_req_iB(user_sbr_obi_reqB),
    .user_sbr_obi_req_iC(user_sbr_obi_reqC),
    .user_sbr_obi_rsp_oA(user_sbr_obi_rspA),
    .user_sbr_obi_rsp_oB(user_sbr_obi_rspB),
    .user_sbr_obi_rsp_oC(user_sbr_obi_rspC),
    .user_mgr_obi_req_oA(user_mgr_obi_reqA),
    .user_mgr_obi_req_oB(user_mgr_obi_reqB),
    .user_mgr_obi_req_oC(user_mgr_obi_reqC),
    .user_mgr_obi_rsp_iA(user_mgr_obi_rspA),
    .user_mgr_obi_rsp_iB(user_mgr_obi_rspB),
    .user_mgr_obi_rsp_iC(user_mgr_obi_rspC),
    .gpio_in_sync_iA(gpio_in_syncA),
    .gpio_in_sync_iB(gpio_in_syncB),
    .gpio_in_sync_iC(gpio_in_syncC),
    .interrupts_oA(interruptsA),
    .interrupts_oB(interruptsB),
    .interrupts_oC(interruptsC),
    .tmrErrorA(i_usertmrErrorA),
    .tmrErrorB(i_usertmrErrorB),
    .tmrErrorC(i_usertmrErrorC)
  );

majorityVoter #(.WIDTH( ((((GpioCount-1)>0) ? (GpioCount-1) : - ( GpioCount-1 ) )+1) )) gpio_oVoter (
    .inA(gpio_oA),
    .inB(gpio_oB),
    .inC(gpio_oC),
    .out(gpio_o),
    .tmrErr(gpio_oTmrError)
  );

majorityVoter #(.WIDTH( ((((GpioCount-1)>0) ? (GpioCount-1) : - ( GpioCount-1 ) )+1) )) gpio_out_en_oVoter (
    .inA(gpio_out_en_oA),
    .inB(gpio_out_en_oB),
    .inC(gpio_out_en_oC),
    .out(gpio_out_en_o),
    .tmrErr(gpio_out_en_oTmrError)
  );

majorityVoter jtag_tdo_oVoter (
    .inA(jtag_tdo_oA),
    .inB(jtag_tdo_oB),
    .inC(jtag_tdo_oC),
    .out(jtag_tdo_o),
    .tmrErr(jtag_tdo_oTmrError)
  );

majorityVoter status_oVoter (
    .inA(status_oA),
    .inB(status_oB),
    .inC(status_oC),
    .out(status_o),
    .tmrErr(status_oTmrError)
  );

majorityVoter uart_tx_oVoter (
    .inA(uart_tx_oA),
    .inB(uart_tx_oB),
    .inC(uart_tx_oC),
    .out(uart_tx_o),
    .tmrErr(uart_tx_oTmrError)
  );
assign tmrError = gpio_oTmrError|gpio_out_en_oTmrError|jtag_tdo_oTmrError|status_oTmrError|uart_tx_oTmrError;
assign tmrErrorA = i_ext_intr_synctmrErrorA|i_usertmrErrorA;
assign tmrErrorB = i_ext_intr_synctmrErrorB|i_usertmrErrorB;
assign tmrErrorC = i_ext_intr_synctmrErrorC|i_usertmrErrorC;
assign soc_faults = tmrError | tmrErrorA | tmrErrorB | tmrErrorC;

fanout clk_iFanout (
    .in(clk_i),
    .outA(clk_iA),
    .outB(clk_iB),
    .outC(clk_iC)
  );

fanout fetch_en_iFanout (
    .in(fetch_en_i),
    .outA(fetch_en_iA),
    .outB(fetch_en_iB),
    .outC(fetch_en_iC)
  );

fanout #(.WIDTH( ((((GpioCount-1)>0) ? (GpioCount-1) : - ( GpioCount-1 ) )+1) )) gpio_iFanout (
    .in(gpio_i),
    .outA(gpio_iA),
    .outB(gpio_iB),
    .outC(gpio_iC)
  );

fanout jtag_tck_iFanout (
    .in(jtag_tck_i),
    .outA(jtag_tck_iA),
    .outB(jtag_tck_iB),
    .outC(jtag_tck_iC)
  );

fanout jtag_tdi_iFanout (
    .in(jtag_tdi_i),
    .outA(jtag_tdi_iA),
    .outB(jtag_tdi_iB),
    .outC(jtag_tdi_iC)
  );

fanout jtag_tms_iFanout (
    .in(jtag_tms_i),
    .outA(jtag_tms_iA),
    .outB(jtag_tms_iB),
    .outC(jtag_tms_iC)
  );

fanout jtag_trst_niFanout (
    .in(jtag_trst_ni),
    .outA(jtag_trst_niA),
    .outB(jtag_trst_niB),
    .outC(jtag_trst_niC)
  );

fanout ref_clk_iFanout (
    .in(ref_clk_i),
    .outA(ref_clk_iA),
    .outB(ref_clk_iB),
    .outC(ref_clk_iC)
  );

fanout rst_niFanout (
    .in(rst_ni),
    .outA(rst_niA),
    .outB(rst_niB),
    .outC(rst_niC)
  );

fanout testmode_iFanout (
    .in(testmode_i),
    .outA(testmode_iA),
    .outB(testmode_iB),
    .outC(testmode_iC)
  );

fanout uart_rx_iFanout (
    .in(uart_rx_i),
    .outA(uart_rx_iA),
    .outB(uart_rx_iB),
    .outC(uart_rx_iC)
  );
endmodule



// /scratch/chenwu/tmrg/tmrg/../common/voter.v
module majorityVoter #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] inA,
  input wire  [WIDTH-1:0] inB,
  input wire  [WIDTH-1:0] inC,
  output wire [WIDTH-1:0] out,
  output reg              tmrErr
);
  assign out = (inA&inB) | (inA&inC) | (inB&inC);
  // always @(inA or inB or inC) begin
  always_comb begin
    if (inA!=inB || inA!=inC || inB!=inC)
      tmrErr = 1;
    else
      tmrErr = 0;
  end
endmodule


// /scratch/chenwu/tmrg/tmrg/../common/fanout.v
module fanout #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] in,
  output wire [WIDTH-1:0] outA,
  output wire [WIDTH-1:0] outB,
  output wire [WIDTH-1:0] outC
);
  assign outA = in;
  assign outB = in;
  assign outC = in;
endmodule
