set sdc_version 1.3

set tmrgSucces 0
set tmrgFailed 0
proc constrainNet netName {
  global tmrgSucces
  global tmrgFailed
  # find nets matching netName pattern
  set nets [dc::get_net $netName]
  if {[llength $nets] != 0} {
    set_dont_touch $nets
    incr tmrgSucces
  } else {
    puts "\[TMRG\] Warning! Net(s) '$netName' not found"
    incr tmrgFailed
  }
}

constrainNet /clk_i
constrainNet /clk_iA
constrainNet /clk_iB
constrainNet /clk_iC
constrainNet /fetch_en_i
constrainNet /fetch_en_iA
constrainNet /fetch_en_iB
constrainNet /fetch_en_iC
constrainNet /gpio_iA[*]
constrainNet /gpio_iB[*]
constrainNet /gpio_iC[*]
constrainNet /gpio_i[*]
constrainNet /gpio_oA[*]
constrainNet /gpio_oB[*]
constrainNet /gpio_oC[*]
constrainNet /gpio_o[*]
constrainNet /gpio_out_en_oA[*]
constrainNet /gpio_out_en_oB[*]
constrainNet /gpio_out_en_oC[*]
constrainNet /gpio_out_en_o[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcounters_variable_i/counter_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcountinhibit_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/mcycle_counter_i/counter_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/minstret_counter_i/counter_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qA
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qB
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qC
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/priv_lvl_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dcsr_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_depc_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch0_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_dscratch1_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mcause_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mepc_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mie_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mscratch_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_cause_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstack_epc_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mstatus_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtval_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_mtvec_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_addr_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_cfg_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_pmp_mseccfg/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_control_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tmatch_value_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/cs_registers_i/u_tselect_csr/shadow_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qA
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qB
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qC
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_by_zero_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/div_counter_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/md_state_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/mult_state_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/multdiv_count_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_a_shift_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_b_shift_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_numerator_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/ex_block_i/multdiv_i/op_quotient_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_jump_set_done_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/branch_set_raw_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/ctrl_fsm_csVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/debug_mode_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/do_single_step_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/enter_debug_mode_prio_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/exc_req_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/illegal_insn_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/load_err_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/nmi_mode_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/controller_i/store_err_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/decoder_i/use_rs3_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qC
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/id_stage_i/id_fsm_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/illegal_c_insn_id_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_plus2_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_fetch_err_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_is_compressed_id_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_new_id_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_alu_id_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_c_id_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_rdata_id_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/instr_valid_id_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/pc_id_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/branch_discard_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/discard_req_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fetch_addr_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/err_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/instr_addr_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/fifo_i/valid_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/rdata_outstanding_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/stored_addr_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qC
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/if_stage_i/prefetch_buffer_i/valid_req_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/addr_last_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_sign_ext_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_type_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/data_we_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/handle_misaligned_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/ls_fsm_csVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/lsu_err_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qVotedA
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qVotedB
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/pmp_err_qVotedC
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_offset_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/load_store_unit_i/rdata_qVotedC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qC[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qVotedA[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qVotedB[*]
constrainNet /i_croc/i_core_wrap/i_ibex/register_file_i/rf_reg_qVotedC[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qA[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qB[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qC[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qVotedA[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qVotedB[*]
constrainNet /i_croc/i_gpio/i_reg_file/id_qVotedC[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qA[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qB[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qC[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qVotedA[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qVotedB[*]
constrainNet /i_croc/i_gpio/i_reg_file/read_addr_qVotedC[*]
constrainNet /i_croc/i_gpio/i_reg_file/reg_qA
constrainNet /i_croc/i_gpio/i_reg_file/reg_qB
constrainNet /i_croc/i_gpio/i_reg_file/reg_qC
constrainNet /i_croc/i_gpio/i_reg_file/reg_qVotedA
constrainNet /i_croc/i_gpio/i_reg_file/reg_qVotedB
constrainNet /i_croc/i_gpio/i_reg_file/reg_qVotedC
constrainNet /i_croc/i_gpio/i_reg_file/req_qA
constrainNet /i_croc/i_gpio/i_reg_file/req_qB
constrainNet /i_croc/i_gpio/i_reg_file/req_qC
constrainNet /i_croc/i_gpio/i_reg_file/req_qVotedA
constrainNet /i_croc/i_gpio/i_reg_file/req_qVotedB
constrainNet /i_croc/i_gpio/i_reg_file/req_qVotedC
constrainNet /i_croc/i_gpio/i_reg_file/valid_qA
constrainNet /i_croc/i_gpio/i_reg_file/valid_qB
constrainNet /i_croc/i_gpio/i_reg_file/valid_qC
constrainNet /i_croc/i_gpio/i_reg_file/valid_qVotedA
constrainNet /i_croc/i_gpio/i_reg_file/valid_qVotedB
constrainNet /i_croc/i_gpio/i_reg_file/valid_qVotedC
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qA
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qB
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qC
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qVotedA
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qVotedB
constrainNet /i_croc/i_gpio/i_reg_file/w_err_qVotedC
constrainNet /i_croc/i_gpio/i_reg_file/we_qA
constrainNet /i_croc/i_gpio/i_reg_file/we_qB
constrainNet /i_croc/i_gpio/i_reg_file/we_qC
constrainNet /i_croc/i_gpio/i_reg_file/we_qVotedA
constrainNet /i_croc/i_gpio/i_reg_file/we_qVotedB
constrainNet /i_croc/i_gpio/i_reg_file/we_qVotedC
constrainNet /i_croc/i_gpio/i_sync/reg_qA[*]
constrainNet /i_croc/i_gpio/i_sync/reg_qB[*]
constrainNet /i_croc/i_gpio/i_sync/reg_qC[*]
constrainNet /i_croc/i_gpio/i_sync/reg_qVotedA[*]
constrainNet /i_croc/i_gpio/i_sync/reg_qVotedB[*]
constrainNet /i_croc/i_gpio/i_sync/reg_qVotedC[*]
constrainNet /i_croc/i_gpio/serial_qA
constrainNet /i_croc/i_gpio/serial_qB
constrainNet /i_croc/i_gpio/serial_qC
constrainNet /i_croc/i_gpio/serial_qVotedA
constrainNet /i_croc/i_gpio/serial_qVotedB
constrainNet /i_croc/i_gpio/serial_qVotedC
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qA[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qB[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qC[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/counter_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qA
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qB
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qC
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qVotedA
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qVotedB
constrainNet /i_croc/i_main_xbar/i_demux/i_counter/overflow_qVotedC
constrainNet /i_croc/i_main_xbar/i_demux/select_qA
constrainNet /i_croc/i_main_xbar/i_demux/select_qB
constrainNet /i_croc/i_main_xbar/i_demux/select_qC
constrainNet /i_croc/i_main_xbar/i_demux/select_qVotedA
constrainNet /i_croc/i_main_xbar/i_demux/select_qVotedB
constrainNet /i_croc/i_main_xbar/i_demux/select_qVotedC
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/mem_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/read_pointer_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/status_cnt_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qC[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_err_sbr/i_id_fifo/write_pointer_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/mem_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/read_pointer_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/status_cnt_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_fifo/write_pointer_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qA
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qB
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qC
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qVotedA
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qVotedB
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/lock_qVotedC
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qVotedA[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qVotedB[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/req_qVotedC[*]
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qA
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qB
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qC
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qVotedA
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qVotedB
constrainNet /i_croc/i_main_xbar/i_mux/i_rr_arb/rr_qVotedC
constrainNet /i_croc/i_obi_demux/i_counter/counter_qA[*]
constrainNet /i_croc/i_obi_demux/i_counter/counter_qB[*]
constrainNet /i_croc/i_obi_demux/i_counter/counter_qC[*]
constrainNet /i_croc/i_obi_demux/i_counter/counter_qVotedA[*]
constrainNet /i_croc/i_obi_demux/i_counter/counter_qVotedB[*]
constrainNet /i_croc/i_obi_demux/i_counter/counter_qVotedC[*]
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qA
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qB
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qC
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qVotedA
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qVotedB
constrainNet /i_croc/i_obi_demux/i_counter/overflow_qVotedC
constrainNet /i_croc/i_obi_demux/select_qA
constrainNet /i_croc/i_obi_demux/select_qB
constrainNet /i_croc/i_obi_demux/select_qC
constrainNet /i_croc/i_obi_demux/select_qVotedA
constrainNet /i_croc/i_obi_demux/select_qVotedB
constrainNet /i_croc/i_obi_demux/select_qVotedC
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qVotedA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qVotedB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/mem_qVotedC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qVotedA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qVotedB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/read_pointer_qVotedC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qVotedA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qVotedB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/status_cnt_qVotedC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qC[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qVotedA[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qVotedB[*]
constrainNet /i_croc/i_periph_err/i_id_fifo/write_pointer_qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qA[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qB[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qC[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qVotedA[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qVotedB[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qA
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qB
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qC
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qVotedA
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qVotedB
constrainNet /i_croc/i_soc_ctrl/u_bootaddr/qe_qVotedC
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qA[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qB[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qC[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qVotedA[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qVotedB[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qA
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qB
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qC
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qVotedA
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qVotedB
constrainNet /i_croc/i_soc_ctrl/u_bootmode/qe_qVotedC
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qA[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qB[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qC[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qVotedA[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qVotedB[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qA
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qB
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qC
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qVotedA
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qVotedB
constrainNet /i_croc/i_soc_ctrl/u_corestatus/qe_qVotedC
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qA[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qB[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qC[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qVotedA[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qVotedB[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qA
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qB
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qC
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qVotedA
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qVotedB
constrainNet /i_croc/i_soc_ctrl/u_fetchen/qe_qVotedC
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qA[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qB[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qC[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qVotedA[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qVotedB[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qVotedC[*]
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qA
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qB
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qC
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qVotedA
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qVotedB
constrainNet /i_croc/i_soc_ctrl/u_sram_dly/qe_qVotedC
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qA[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qB[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qC[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qVotedA[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qVotedB[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_id_qVotedC[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qA
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qB
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qC
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qVotedA
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qVotedB
constrainNet /i_croc/i_soc_ctrl_translate/r_opc_qVotedC
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qA[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qB[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qC[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qVotedA[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qVotedB[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_rdata_qVotedC[*]
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qA
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qB
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qC
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qVotedA
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qVotedB
constrainNet /i_croc/i_soc_ctrl_translate/r_valid_qVotedC
constrainNet /i_croc/i_sram_shim/id_qA[*]
constrainNet /i_croc/i_sram_shim/id_qB[*]
constrainNet /i_croc/i_sram_shim/id_qC[*]
constrainNet /i_croc/i_sram_shim/id_qVotedA[*]
constrainNet /i_croc/i_sram_shim/id_qVotedB[*]
constrainNet /i_croc/i_sram_shim/id_qVotedC[*]
constrainNet /i_croc/i_sram_shim/rvalid_qA
constrainNet /i_croc/i_sram_shim/rvalid_qB
constrainNet /i_croc/i_sram_shim/rvalid_qC
constrainNet /i_croc/i_sram_shim/rvalid_qVotedA
constrainNet /i_croc/i_sram_shim/rvalid_qVotedB
constrainNet /i_croc/i_sram_shim/rvalid_qVotedC
constrainNet /i_croc/i_timer/CSA[*]
constrainNet /i_croc/i_timer/CSB[*]
constrainNet /i_croc/i_timer/CSC[*]
constrainNet /i_croc/i_timer/CSVotedA[*]
constrainNet /i_croc/i_timer/CSVotedB[*]
constrainNet /i_croc/i_timer/CSVotedC[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regA[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regB[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regC[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regVotedA[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regVotedB[*]
constrainNet /i_croc/i_timer/counter_hi_i/s_count_regVotedC[*]
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qA
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qB
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qC
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qVotedA
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qVotedB
constrainNet /i_croc/i_timer/counter_hi_i/target_reached_qVotedC
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regA[*]
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regB[*]
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regC[*]
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regVotedA[*]
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regVotedB[*]
constrainNet /i_croc/i_timer/counter_lo_i/s_count_regVotedC[*]
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qA
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qB
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qC
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qVotedA
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qVotedB
constrainNet /i_croc/i_timer/counter_lo_i/target_reached_qVotedC
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regA[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regB[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regC[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regVotedA[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regVotedB[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/s_count_regVotedC[*]
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qA
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qB
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qC
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qVotedA
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qVotedB
constrainNet /i_croc/i_timer/prescaler_hi_i/target_reached_qVotedC
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regA[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regB[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regC[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regVotedA[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regVotedB[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/s_count_regVotedC[*]
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qA
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qB
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qC
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qVotedA
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qVotedB
constrainNet /i_croc/i_timer/prescaler_lo_i/target_reached_qVotedC
constrainNet /i_croc/i_timer/r_id_qA[*]
constrainNet /i_croc/i_timer/r_id_qB[*]
constrainNet /i_croc/i_timer/r_id_qC[*]
constrainNet /i_croc/i_timer/r_id_qVotedA[*]
constrainNet /i_croc/i_timer/r_id_qVotedB[*]
constrainNet /i_croc/i_timer/r_id_qVotedC[*]
constrainNet /i_croc/i_timer/s_addrA[*]
constrainNet /i_croc/i_timer/s_addrB[*]
constrainNet /i_croc/i_timer/s_addrC[*]
constrainNet /i_croc/i_timer/s_addrVotedA[*]
constrainNet /i_croc/i_timer/s_addrVotedB[*]
constrainNet /i_croc/i_timer/s_addrVotedC[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regA[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regB[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regC[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regVotedA[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regVotedB[*]
constrainNet /i_croc/i_timer/s_cfg_hi_regVotedC[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regA[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regB[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regC[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regVotedA[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regVotedB[*]
constrainNet /i_croc/i_timer/s_cfg_lo_regVotedC[*]
constrainNet /i_croc/i_timer/s_ref_clk0A
constrainNet /i_croc/i_timer/s_ref_clk0B
constrainNet /i_croc/i_timer/s_ref_clk0C
constrainNet /i_croc/i_timer/s_ref_clk0VotedA
constrainNet /i_croc/i_timer/s_ref_clk0VotedB
constrainNet /i_croc/i_timer/s_ref_clk0VotedC
constrainNet /i_croc/i_timer/s_ref_clk1A
constrainNet /i_croc/i_timer/s_ref_clk1B
constrainNet /i_croc/i_timer/s_ref_clk1C
constrainNet /i_croc/i_timer/s_ref_clk1VotedA
constrainNet /i_croc/i_timer/s_ref_clk1VotedB
constrainNet /i_croc/i_timer/s_ref_clk1VotedC
constrainNet /i_croc/i_timer/s_ref_clk2A
constrainNet /i_croc/i_timer/s_ref_clk2B
constrainNet /i_croc/i_timer/s_ref_clk2C
constrainNet /i_croc/i_timer/s_ref_clk2VotedA
constrainNet /i_croc/i_timer/s_ref_clk2VotedB
constrainNet /i_croc/i_timer/s_ref_clk2VotedC
constrainNet /i_croc/i_timer/s_ref_clk3A
constrainNet /i_croc/i_timer/s_ref_clk3B
constrainNet /i_croc/i_timer/s_ref_clk3C
constrainNet /i_croc/i_timer/s_ref_clk3VotedA
constrainNet /i_croc/i_timer/s_ref_clk3VotedB
constrainNet /i_croc/i_timer/s_ref_clk3VotedC
constrainNet /i_croc/i_timer/s_reqA
constrainNet /i_croc/i_timer/s_reqB
constrainNet /i_croc/i_timer/s_reqC
constrainNet /i_croc/i_timer/s_reqVotedA
constrainNet /i_croc/i_timer/s_reqVotedB
constrainNet /i_croc/i_timer/s_reqVotedC
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regA[*]
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regB[*]
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regC[*]
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regVotedA[*]
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regVotedB[*]
constrainNet /i_croc/i_timer/s_timer_cmp_hi_regVotedC[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regA[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regB[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regC[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regVotedA[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regVotedB[*]
constrainNet /i_croc/i_timer/s_timer_cmp_lo_regVotedC[*]
constrainNet /i_croc/i_timer/s_wenA
constrainNet /i_croc/i_timer/s_wenB
constrainNet /i_croc/i_timer/s_wenC
constrainNet /i_croc/i_timer/s_wenVotedA
constrainNet /i_croc/i_timer/s_wenVotedB
constrainNet /i_croc/i_timer/s_wenVotedC
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qA
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qB
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qC
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qVotedA
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qVotedB
constrainNet /i_croc/i_uart/i_uart_baudgen/clear_double_qVotedC
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qA[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qB[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qC[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/counter_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qA
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qB
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qC
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qVotedA
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qVotedB
constrainNet /i_croc/i_uart/i_uart_baudgen/i_baudrate_counter/i_counter/overflow_qVotedC
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qA[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qB[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qC[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/counter_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qA
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qB
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qC
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qVotedA
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qVotedB
constrainNet /i_croc/i_uart/i_uart_baudgen/i_oversample_counter/i_counter/overflow_qVotedC
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qA
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qB
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qC
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qVotedA
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qVotedB
constrainNet /i_croc/i_uart/i_uart_interrupts/intrpt_reg_qVotedC
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cd/reg_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_cts/reg_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_dsr/reg_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qC[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_modem/i_sync_ri/reg_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qA
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qB
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qC
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qVotedA
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qVotedB
constrainNet /i_croc/i_uart/i_uart_modem/sync_cd_n_qVotedC
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qA
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qB
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qC
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qVotedA
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qVotedB
constrainNet /i_croc/i_uart/i_uart_modem/sync_cts_n_qVotedC
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qA
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qB
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qC
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qVotedA
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qVotedB
constrainNet /i_croc/i_uart/i_uart_modem/sync_dsr_n_qVotedC
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qA
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qB
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qC
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qVotedA
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qVotedB
constrainNet /i_croc/i_uart/i_uart_modem/sync_ri_n_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/id_qA[*]
constrainNet /i_croc/i_uart/i_uart_register/id_qB[*]
constrainNet /i_croc/i_uart/i_uart_register/id_qC[*]
constrainNet /i_croc/i_uart/i_uart_register/id_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_register/id_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_register/id_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_register/reg_qA
constrainNet /i_croc/i_uart/i_uart_register/reg_qB
constrainNet /i_croc/i_uart/i_uart_register/reg_qC
constrainNet /i_croc/i_uart/i_uart_register/reg_qVotedA
constrainNet /i_croc/i_uart/i_uart_register/reg_qVotedB
constrainNet /i_croc/i_uart/i_uart_register/reg_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/req_qA
constrainNet /i_croc/i_uart/i_uart_register/req_qB
constrainNet /i_croc/i_uart/i_uart_register/req_qC
constrainNet /i_croc/i_uart/i_uart_register/req_qVotedA
constrainNet /i_croc/i_uart/i_uart_register/req_qVotedB
constrainNet /i_croc/i_uart/i_uart_register/req_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/valid_qA
constrainNet /i_croc/i_uart/i_uart_register/valid_qB
constrainNet /i_croc/i_uart/i_uart_register/valid_qC
constrainNet /i_croc/i_uart/i_uart_register/valid_qVotedA
constrainNet /i_croc/i_uart/i_uart_register/valid_qVotedB
constrainNet /i_croc/i_uart/i_uart_register/valid_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/w_err_qA
constrainNet /i_croc/i_uart/i_uart_register/w_err_qB
constrainNet /i_croc/i_uart/i_uart_register/w_err_qC
constrainNet /i_croc/i_uart/i_uart_register/w_err_qVotedA
constrainNet /i_croc/i_uart/i_uart_register/w_err_qVotedB
constrainNet /i_croc/i_uart/i_uart_register/w_err_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/we_qA
constrainNet /i_croc/i_uart/i_uart_register/we_qB
constrainNet /i_croc/i_uart/i_uart_register/we_qC
constrainNet /i_croc/i_uart/i_uart_register/we_qVotedA
constrainNet /i_croc/i_uart/i_uart_register/we_qVotedB
constrainNet /i_croc/i_uart/i_uart_register/we_qVotedC
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qA[*]
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qB[*]
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qC[*]
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_register/word_addr_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/bitcount_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/break_qA
constrainNet /i_croc/i_uart/i_uart_rx/break_qB
constrainNet /i_croc/i_uart/i_uart_rx/break_qC
constrainNet /i_croc/i_uart/i_uart_rx/break_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/break_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/break_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/fifo_error_index_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qA
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qB
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qC
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/filtered_rxd_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qA
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qB
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qC
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/framing_err_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/high_count_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/counter_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qA
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qB
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qC
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/i_counter/i_counter/overflow_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/mem_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/read_pointer_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/status_cnt_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_fifo_v3/write_pointer_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/i_sync/reg_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qA
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qB
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qC
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/parity_err_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qA
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qB
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qC
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/rhr_full_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/rsr_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/state_qA
constrainNet /i_croc/i_uart/i_uart_rx/state_qB
constrainNet /i_croc/i_uart/i_uart_rx/state_qC
constrainNet /i_croc/i_uart/i_uart_rx/state_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/state_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/state_qVotedC
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qA[*]
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qB[*]
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qC[*]
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_rx/timeout_count_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qA
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qB
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qC
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qVotedA
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qVotedB
constrainNet /i_croc/i_uart/i_uart_rx/timing_bit_center_qVotedC
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/mem_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/read_pointer_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/status_cnt_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/i_fifo_v3/write_pointer_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/state_qA
constrainNet /i_croc/i_uart/i_uart_tx/state_qB
constrainNet /i_croc/i_uart/i_uart_tx/state_qC
constrainNet /i_croc/i_uart/i_uart_tx/state_qVotedA
constrainNet /i_croc/i_uart/i_uart_tx/state_qVotedB
constrainNet /i_croc/i_uart/i_uart_tx/state_qVotedC
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qA
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qB
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qC
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qVotedA
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qVotedB
constrainNet /i_croc/i_uart/i_uart_tx/thr_full_qVotedC
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_count_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qA[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qB[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qC[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qVotedA[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qVotedB[*]
constrainNet /i_croc/i_uart/i_uart_tx/tsr_qVotedC[*]
constrainNet /i_croc/i_uart/i_uart_tx/txd_qA
constrainNet /i_croc/i_uart/i_uart_tx/txd_qB
constrainNet /i_croc/i_uart/i_uart_tx/txd_qC
constrainNet /i_croc/i_uart/i_uart_tx/txd_qVotedA
constrainNet /i_croc/i_uart/i_uart_tx/txd_qVotedB
constrainNet /i_croc/i_uart/i_uart_tx/txd_qVotedC
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qVotedA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qVotedB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/mem_qVotedC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qVotedA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qVotedB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/read_pointer_qVotedC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qVotedA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qVotedB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/status_cnt_qVotedC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qC[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qVotedA[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qVotedB[*]
constrainNet /i_croc/i_xbar_err/i_id_fifo/write_pointer_qVotedC[*]
constrainNet /i_ext_intr_sync/reg_qA[*]
constrainNet /i_ext_intr_sync/reg_qB[*]
constrainNet /i_ext_intr_sync/reg_qC[*]
constrainNet /i_ext_intr_sync/reg_qVotedA[*]
constrainNet /i_ext_intr_sync/reg_qVotedB[*]
constrainNet /i_ext_intr_sync/reg_qVotedC[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qA[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qB[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qC[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qVotedA[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qVotedB[*]
constrainNet /i_user/i_obi_demux/i_counter/counter_qVotedC[*]
constrainNet /i_user/i_obi_demux/i_counter/overflow_qA
constrainNet /i_user/i_obi_demux/i_counter/overflow_qB
constrainNet /i_user/i_obi_demux/i_counter/overflow_qC
constrainNet /i_user/i_obi_demux/i_counter/overflow_qVotedA
constrainNet /i_user/i_obi_demux/i_counter/overflow_qVotedB
constrainNet /i_user/i_obi_demux/i_counter/overflow_qVotedC
constrainNet /i_user/i_obi_demux/select_qA
constrainNet /i_user/i_obi_demux/select_qB
constrainNet /i_user/i_obi_demux/select_qC
constrainNet /i_user/i_obi_demux/select_qVotedA
constrainNet /i_user/i_obi_demux/select_qVotedB
constrainNet /i_user/i_obi_demux/select_qVotedC
constrainNet /i_user/i_user_err/i_id_fifo/mem_qA[*]
constrainNet /i_user/i_user_err/i_id_fifo/mem_qB[*]
constrainNet /i_user/i_user_err/i_id_fifo/mem_qC[*]
constrainNet /i_user/i_user_err/i_id_fifo/mem_qVotedA[*]
constrainNet /i_user/i_user_err/i_id_fifo/mem_qVotedB[*]
constrainNet /i_user/i_user_err/i_id_fifo/mem_qVotedC[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qA[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qB[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qC[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qVotedA[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qVotedB[*]
constrainNet /i_user/i_user_err/i_id_fifo/read_pointer_qVotedC[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qA[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qB[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qC[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qVotedA[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qVotedB[*]
constrainNet /i_user/i_user_err/i_id_fifo/status_cnt_qVotedC[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qA[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qB[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qC[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qVotedA[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qVotedB[*]
constrainNet /i_user/i_user_err/i_id_fifo/write_pointer_qVotedC[*]
constrainNet /jtag_tck_i
constrainNet /jtag_tck_iA
constrainNet /jtag_tck_iB
constrainNet /jtag_tck_iC
constrainNet /jtag_tdi_i
constrainNet /jtag_tdi_iA
constrainNet /jtag_tdi_iB
constrainNet /jtag_tdi_iC
constrainNet /jtag_tdo_o
constrainNet /jtag_tdo_oA
constrainNet /jtag_tdo_oB
constrainNet /jtag_tdo_oC
constrainNet /jtag_tms_i
constrainNet /jtag_tms_iA
constrainNet /jtag_tms_iB
constrainNet /jtag_tms_iC
constrainNet /jtag_trst_ni
constrainNet /jtag_trst_niA
constrainNet /jtag_trst_niB
constrainNet /jtag_trst_niC
constrainNet /ref_clk_i
constrainNet /ref_clk_iA
constrainNet /ref_clk_iB
constrainNet /ref_clk_iC
constrainNet /rst_ni
constrainNet /rst_niA
constrainNet /rst_niB
constrainNet /rst_niC
constrainNet /status_o
constrainNet /status_oA
constrainNet /status_oB
constrainNet /status_oC
constrainNet /testmode_i
constrainNet /testmode_iA
constrainNet /testmode_iB
constrainNet /testmode_iC
constrainNet /uart_rx_i
constrainNet /uart_rx_iA
constrainNet /uart_rx_iB
constrainNet /uart_rx_iC
constrainNet /uart_tx_o
constrainNet /uart_tx_oA
constrainNet /uart_tx_oB
constrainNet /uart_tx_oC


    puts "TMRG successful  $tmrgSucces failed $tmrgFailed"
