/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_csrTMR.sv                                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:11                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_csr.sv                                                                   *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc ( M tmrg_src/cve2_csr.sv) *
 *           Modification time : 2025-11-12 14:35:26.127270                                         *
 *           File Size         : 1452                                                               *
 *           MD5 hash          : 826433613eada94d8a2f896e9142f452                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_csrTMR #(
  parameter int unsigned Width = 32,
  parameter bit ShadowCopy = 1'b0,
  parameter bit [Width - 1:0] ResetValue = '0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [Width - 1:0] wr_data_iA,
  input logic [Width - 1:0] wr_data_iB,
  input logic [Width - 1:0] wr_data_iC,
  input logic wr_en_iA,
  input logic wr_en_iB,
  input logic wr_en_iC,
  output logic [Width - 1:0] rd_data_oA,
  output logic [Width - 1:0] rd_data_oB,
  output logic [Width - 1:0] rd_data_oC,
  output logic rd_error_oA,
  output logic rd_error_oB,
  output logic rd_error_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor shadow_qTmrErrorC;
wor rdata_qTmrErrorC;
wor shadow_qTmrErrorB;
wor rdata_qTmrErrorB;
wor shadow_qTmrErrorA;
wor rdata_qTmrErrorA;
logic [Width - 1:0] rdata_qA;
logic [Width - 1:0] rdata_qB;
logic [Width - 1:0] rdata_qC;
logic [Width - 1:0] rdata_qVotedA;
logic [Width - 1:0] rdata_qVotedB;
logic [Width - 1:0] rdata_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        rdata_qA <= ResetValue;
      end
    else
      if (wr_en_iA)
        begin
          rdata_qA <= wr_data_iA;
        end

  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        rdata_qB <= ResetValue;
      end
    else
      if (wr_en_iB)
        begin
          rdata_qB <= wr_data_iB;
        end

  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        rdata_qC <= ResetValue;
      end
    else
      if (wr_en_iC)
        begin
          rdata_qC <= wr_data_iC;
        end

  end
assign rd_data_oA = rdata_qVotedA;
assign rd_data_oB = rdata_qVotedB;
assign rd_data_oC = rdata_qVotedC;
logic [Width - 1:0] shadow_qA;
logic [Width - 1:0] shadow_qB;
logic [Width - 1:0] shadow_qC;
logic [Width - 1:0] shadow_qVotedA;
logic [Width - 1:0] shadow_qVotedB;
logic [Width - 1:0] shadow_qVotedC;
if (ShadowCopy)
  begin : gen_shadow

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            shadow_qA <= ~ResetValue;
          end
        else
          if (wr_en_iA)
            begin
              shadow_qA <= ~wr_data_iA;
            end

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            shadow_qB <= ~ResetValue;
          end
        else
          if (wr_en_iB)
            begin
              shadow_qB <= ~wr_data_iB;
            end

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            shadow_qC <= ~ResetValue;
          end
        else
          if (wr_en_iC)
            begin
              shadow_qC <= ~wr_data_iC;
            end

      end
    assign rd_error_oA = rdata_qVotedA!=~shadow_qVotedA;
    assign rd_error_oB = rdata_qVotedB!=~shadow_qVotedB;
    assign rd_error_oC = rdata_qVotedC!=~shadow_qVotedC;
  end

else
  begin : gen_no_shadow
    assign rd_error_oA = 1'b0;
    assign rd_error_oB = 1'b0;
    assign rd_error_oC = 1'b0;
    assign shadow_qA = '0;
    assign shadow_qB = '0;
    assign shadow_qC = '0;
  end

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) rdata_qVoterA (
    .inA(rdata_qA),
    .inB(rdata_qB),
    .inC(rdata_qC),
    .out(rdata_qVotedA),
    .tmrErr(rdata_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) shadow_qVoterA (
    .inA(shadow_qA),
    .inB(shadow_qB),
    .inC(shadow_qC),
    .out(shadow_qVotedA),
    .tmrErr(shadow_qTmrErrorA)
  );
assign tmrErrorA = rdata_qTmrErrorA|shadow_qTmrErrorA;

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) rdata_qVoterB (
    .inA(rdata_qA),
    .inB(rdata_qB),
    .inC(rdata_qC),
    .out(rdata_qVotedB),
    .tmrErr(rdata_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) shadow_qVoterB (
    .inA(shadow_qA),
    .inB(shadow_qB),
    .inC(shadow_qC),
    .out(shadow_qVotedB),
    .tmrErr(shadow_qTmrErrorB)
  );
assign tmrErrorB = rdata_qTmrErrorB|shadow_qTmrErrorB;

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) rdata_qVoterC (
    .inA(rdata_qA),
    .inB(rdata_qB),
    .inC(rdata_qC),
    .out(rdata_qVotedC),
    .tmrErr(rdata_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((Width-1)>0) ? (Width-1) : - ( Width-1 ) )+1) )) shadow_qVoterC (
    .inA(shadow_qA),
    .inB(shadow_qB),
    .inC(shadow_qC),
    .out(shadow_qVotedC),
    .tmrErr(shadow_qTmrErrorC)
  );
assign tmrErrorC = rdata_qTmrErrorC|shadow_qTmrErrorC;
endmodule

