/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_wbTMR.sv                                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:25                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_wb.sv                                                                    *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-12 14:35:26.322272                                         *
 *           File Size         : 2512                                                               *
 *           MD5 hash          : 0268b0a682c241083d716e2ee6cc41bc                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_wbTMR (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic en_wb_iA,
  input logic en_wb_iB,
  input logic en_wb_iC,
  input logic instr_is_compressed_id_iA,
  input logic instr_is_compressed_id_iB,
  input logic instr_is_compressed_id_iC,
  input logic instr_perf_count_id_iA,
  input logic instr_perf_count_id_iB,
  input logic instr_perf_count_id_iC,
  output logic perf_instr_ret_wb_oA,
  output logic perf_instr_ret_wb_oB,
  output logic perf_instr_ret_wb_oC,
  output logic perf_instr_ret_compressed_wb_oA,
  output logic perf_instr_ret_compressed_wb_oB,
  output logic perf_instr_ret_compressed_wb_oC,
  input logic [4:0] rf_waddr_id_iA,
  input logic [4:0] rf_waddr_id_iB,
  input logic [4:0] rf_waddr_id_iC,
  input logic [31:0] rf_wdata_id_iA,
  input logic [31:0] rf_wdata_id_iB,
  input logic [31:0] rf_wdata_id_iC,
  input logic rf_we_id_iA,
  input logic rf_we_id_iB,
  input logic rf_we_id_iC,
  input logic [31:0] rf_wdata_lsu_iA,
  input logic [31:0] rf_wdata_lsu_iB,
  input logic [31:0] rf_wdata_lsu_iC,
  input logic rf_we_lsu_iA,
  input logic rf_we_lsu_iB,
  input logic rf_we_lsu_iC,
  output logic [4:0] rf_waddr_wb_oA,
  output logic [4:0] rf_waddr_wb_oB,
  output logic [4:0] rf_waddr_wb_oC,
  output logic [31:0] rf_wdata_wb_oA,
  output logic [31:0] rf_wdata_wb_oB,
  output logic [31:0] rf_wdata_wb_oC,
  output logic rf_we_wb_oA,
  output logic rf_we_wb_oB,
  output logic rf_we_wb_oC,
  input logic lsu_resp_valid_iA,
  input logic lsu_resp_valid_iB,
  input logic lsu_resp_valid_iC,
  input logic lsu_resp_err_iA,
  input logic lsu_resp_err_iB,
  input logic lsu_resp_err_iC
);
import cve2_pkg::*;
logic [31:0] rf_wdata_wb_muxA [2];
logic [31:0] rf_wdata_wb_muxB [2];
logic [31:0] rf_wdata_wb_muxC [2];
logic [1:0] rf_wdata_wb_mux_weA;
logic [1:0] rf_wdata_wb_mux_weB;
logic [1:0] rf_wdata_wb_mux_weC;
assign rf_waddr_wb_oA = rf_waddr_id_iA;
assign rf_waddr_wb_oB = rf_waddr_id_iB;
assign rf_waddr_wb_oC = rf_waddr_id_iC;
assign rf_wdata_wb_muxA[0] = rf_wdata_id_iA;
assign rf_wdata_wb_muxB[0] = rf_wdata_id_iB;
assign rf_wdata_wb_muxC[0] = rf_wdata_id_iC;
assign rf_wdata_wb_mux_weA[0] = rf_we_id_iA;
assign rf_wdata_wb_mux_weB[0] = rf_we_id_iB;
assign rf_wdata_wb_mux_weC[0] = rf_we_id_iC;
assign perf_instr_ret_wb_oA = instr_perf_count_id_iA&en_wb_iA&~ (lsu_resp_valid_iA&lsu_resp_err_iA) ;
assign perf_instr_ret_wb_oB = instr_perf_count_id_iB&en_wb_iB&~ (lsu_resp_valid_iB&lsu_resp_err_iB) ;
assign perf_instr_ret_wb_oC = instr_perf_count_id_iC&en_wb_iC&~ (lsu_resp_valid_iC&lsu_resp_err_iC) ;
assign perf_instr_ret_compressed_wb_oA = perf_instr_ret_wb_oA&instr_is_compressed_id_iA;
assign perf_instr_ret_compressed_wb_oB = perf_instr_ret_wb_oB&instr_is_compressed_id_iB;
assign perf_instr_ret_compressed_wb_oC = perf_instr_ret_wb_oC&instr_is_compressed_id_iC;
assign rf_wdata_wb_muxA[1] = rf_wdata_lsu_iA;
assign rf_wdata_wb_muxB[1] = rf_wdata_lsu_iB;
assign rf_wdata_wb_muxC[1] = rf_wdata_lsu_iC;
assign rf_wdata_wb_mux_weA[1] = rf_we_lsu_iA;
assign rf_wdata_wb_mux_weB[1] = rf_we_lsu_iB;
assign rf_wdata_wb_mux_weC[1] = rf_we_lsu_iC;
assign rf_wdata_wb_oA =  ({ 32 {rf_wdata_wb_mux_weA[0]} } &rf_wdata_wb_muxA[0]) | ({ 32 {rf_wdata_wb_mux_weA[1]} } &rf_wdata_wb_muxA[1]) ;
assign rf_wdata_wb_oB =  ({ 32 {rf_wdata_wb_mux_weB[0]} } &rf_wdata_wb_muxB[0]) | ({ 32 {rf_wdata_wb_mux_weB[1]} } &rf_wdata_wb_muxB[1]) ;
assign rf_wdata_wb_oC =  ({ 32 {rf_wdata_wb_mux_weC[0]} } &rf_wdata_wb_muxC[0]) | ({ 32 {rf_wdata_wb_mux_weC[1]} } &rf_wdata_wb_muxC[1]) ;
assign rf_we_wb_oA = |rf_wdata_wb_mux_weA;
assign rf_we_wb_oB = |rf_wdata_wb_mux_weB;
assign rf_we_wb_oC = |rf_wdata_wb_mux_weC;
endmodule

