/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_ex_blockTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:11                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_ex_block.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:26.159271                                         *
 *           File Size         : 6755                                                               *
 *           MD5 hash          : 67bb7d5334cb5337b5762b5f4c85ddd2                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_ex_blockTMR #(
  parameter cve2_pkg::rv32m_e RV32M = cve2_pkg::RV32MFast,
  parameter cve2_pkg::rv32b_e RV32B = cve2_pkg::RV32BNone
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input cve2_pkg::alu_op_e alu_operator_iA,
  input cve2_pkg::alu_op_e alu_operator_iB,
  input cve2_pkg::alu_op_e alu_operator_iC,
  input logic [31:0] alu_operand_a_iA,
  input logic [31:0] alu_operand_a_iB,
  input logic [31:0] alu_operand_a_iC,
  input logic [31:0] alu_operand_b_iA,
  input logic [31:0] alu_operand_b_iB,
  input logic [31:0] alu_operand_b_iC,
  input logic alu_instr_first_cycle_iA,
  input logic alu_instr_first_cycle_iB,
  input logic alu_instr_first_cycle_iC,
  input cve2_pkg::md_op_e multdiv_operator_iA,
  input cve2_pkg::md_op_e multdiv_operator_iB,
  input cve2_pkg::md_op_e multdiv_operator_iC,
  input logic mult_en_iA,
  input logic mult_en_iB,
  input logic mult_en_iC,
  input logic div_en_iA,
  input logic div_en_iB,
  input logic div_en_iC,
  input logic mult_sel_iA,
  input logic mult_sel_iB,
  input logic mult_sel_iC,
  input logic div_sel_iA,
  input logic div_sel_iB,
  input logic div_sel_iC,
  input logic [1:0] multdiv_signed_mode_iA,
  input logic [1:0] multdiv_signed_mode_iB,
  input logic [1:0] multdiv_signed_mode_iC,
  input logic [31:0] multdiv_operand_a_iA,
  input logic [31:0] multdiv_operand_a_iB,
  input logic [31:0] multdiv_operand_a_iC,
  input logic [31:0] multdiv_operand_b_iA,
  input logic [31:0] multdiv_operand_b_iB,
  input logic [31:0] multdiv_operand_b_iC,
  output logic [1:0] imd_val_we_oA,
  output logic [1:0] imd_val_we_oB,
  output logic [1:0] imd_val_we_oC,
  output logic [33:0] imd_val_d_oA [2],
  output logic [33:0] imd_val_d_oB [2],
  output logic [33:0] imd_val_d_oC [2],
  input logic [33:0] imd_val_q_iA [2],
  input logic [33:0] imd_val_q_iB [2],
  input logic [33:0] imd_val_q_iC [2],
  output logic [31:0] alu_adder_result_ex_oA,
  output logic [31:0] alu_adder_result_ex_oB,
  output logic [31:0] alu_adder_result_ex_oC,
  output logic [31:0] result_ex_oA,
  output logic [31:0] result_ex_oB,
  output logic [31:0] result_ex_oC,
  output logic [31:0] branch_target_oA,
  output logic [31:0] branch_target_oB,
  output logic [31:0] branch_target_oC,
  output logic branch_decision_oA,
  output logic branch_decision_oB,
  output logic branch_decision_oC,
  output logic ex_valid_oA,
  output logic ex_valid_oB,
  output logic ex_valid_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import cve2_pkg::*;
wor multdiv_itmrErrorC;
wor multdiv_itmrErrorB;
wor multdiv_itmrErrorA;
logic [31:0] alu_resultA;
logic [31:0] alu_resultB;
logic [31:0] alu_resultC;
logic [31:0] multdiv_resultA;
logic [31:0] multdiv_resultB;
logic [31:0] multdiv_resultC;
logic [32:0] multdiv_alu_operand_bA;
logic [32:0] multdiv_alu_operand_bB;
logic [32:0] multdiv_alu_operand_bC;
logic [32:0] multdiv_alu_operand_aA;
logic [32:0] multdiv_alu_operand_aB;
logic [32:0] multdiv_alu_operand_aC;
logic [33:0] alu_adder_result_extA;
logic [33:0] alu_adder_result_extB;
logic [33:0] alu_adder_result_extC;
logic alu_cmp_resultA;
logic alu_cmp_resultB;
logic alu_cmp_resultC;
logic alu_is_equal_resultA;
logic alu_is_equal_resultB;
logic alu_is_equal_resultC;
logic multdiv_validA;
logic multdiv_validB;
logic multdiv_validC;
logic multdiv_selA;
logic multdiv_selB;
logic multdiv_selC;
logic [31:0] alu_imd_val_qA [2];
logic [31:0] alu_imd_val_qB [2];
logic [31:0] alu_imd_val_qC [2];
logic [31:0] alu_imd_val_dA [2];
logic [31:0] alu_imd_val_dB [2];
logic [31:0] alu_imd_val_dC [2];
logic [1:0] alu_imd_val_weA;
logic [1:0] alu_imd_val_weB;
logic [1:0] alu_imd_val_weC;
logic [33:0] multdiv_imd_val_dA [2];
logic [33:0] multdiv_imd_val_dB [2];
logic [33:0] multdiv_imd_val_dC [2];
logic [1:0] multdiv_imd_val_weA;
logic [1:0] multdiv_imd_val_weB;
logic [1:0] multdiv_imd_val_weC;
if (RV32M!=RV32MNone)
  begin : gen_multdiv_m
    assign multdiv_selA = mult_sel_iA|div_sel_iA;
    assign multdiv_selB = mult_sel_iB|div_sel_iB;
    assign multdiv_selC = mult_sel_iC|div_sel_iC;
  end

else
  begin : gen_multdiv_no_m
    assign multdiv_selA = 1'b0;
    assign multdiv_selB = 1'b0;
    assign multdiv_selC = 1'b0;
  end
assign imd_val_d_oA[0] = multdiv_selA ? multdiv_imd_val_dA[0] : {2'b0, alu_imd_val_dA[0]};
assign imd_val_d_oB[0] = multdiv_selB ? multdiv_imd_val_dB[0] : {2'b0, alu_imd_val_dB[0]};
assign imd_val_d_oC[0] = multdiv_selC ? multdiv_imd_val_dC[0] : {2'b0, alu_imd_val_dC[0]};
assign imd_val_d_oA[1] = multdiv_selA ? multdiv_imd_val_dA[1] : {2'b0, alu_imd_val_dA[1]};
assign imd_val_d_oB[1] = multdiv_selB ? multdiv_imd_val_dB[1] : {2'b0, alu_imd_val_dB[1]};
assign imd_val_d_oC[1] = multdiv_selC ? multdiv_imd_val_dC[1] : {2'b0, alu_imd_val_dC[1]};
assign imd_val_we_oA = multdiv_selA ? multdiv_imd_val_weA : alu_imd_val_weA;
assign imd_val_we_oB = multdiv_selB ? multdiv_imd_val_weB : alu_imd_val_weB;
assign imd_val_we_oC = multdiv_selC ? multdiv_imd_val_weC : alu_imd_val_weC;
assign alu_imd_val_qA = '{imd_val_q_iA[0][31:0], imd_val_q_iA[1][31:0]};
assign alu_imd_val_qB = '{imd_val_q_iB[0][31:0], imd_val_q_iB[1][31:0]};
assign alu_imd_val_qC = '{imd_val_q_iC[0][31:0], imd_val_q_iC[1][31:0]};
assign result_ex_oA = multdiv_selA ? multdiv_resultA : alu_resultA;
assign result_ex_oB = multdiv_selB ? multdiv_resultB : alu_resultB;
assign result_ex_oC = multdiv_selC ? multdiv_resultC : alu_resultC;
assign branch_decision_oA = alu_cmp_resultA;
assign branch_decision_oB = alu_cmp_resultB;
assign branch_decision_oC = alu_cmp_resultC;
assign branch_target_oA = alu_adder_result_ex_oA;
assign branch_target_oB = alu_adder_result_ex_oB;
assign branch_target_oC = alu_adder_result_ex_oC;

cve2_aluTMR #(.RV32B(RV32B)) alu_i (
    .operator_iA(alu_operator_iA),
    .operator_iB(alu_operator_iB),
    .operator_iC(alu_operator_iC),
    .operand_a_iA(alu_operand_a_iA),
    .operand_a_iB(alu_operand_a_iB),
    .operand_a_iC(alu_operand_a_iC),
    .operand_b_iA(alu_operand_b_iA),
    .operand_b_iB(alu_operand_b_iB),
    .operand_b_iC(alu_operand_b_iC),
    .instr_first_cycle_iA(alu_instr_first_cycle_iA),
    .instr_first_cycle_iB(alu_instr_first_cycle_iB),
    .instr_first_cycle_iC(alu_instr_first_cycle_iC),
    .imd_val_q_iA(alu_imd_val_qA),
    .imd_val_q_iB(alu_imd_val_qB),
    .imd_val_q_iC(alu_imd_val_qC),
    .imd_val_we_oA(alu_imd_val_weA),
    .imd_val_we_oB(alu_imd_val_weB),
    .imd_val_we_oC(alu_imd_val_weC),
    .imd_val_d_oA(alu_imd_val_dA),
    .imd_val_d_oB(alu_imd_val_dB),
    .imd_val_d_oC(alu_imd_val_dC),
    .multdiv_operand_a_iA(multdiv_alu_operand_aA),
    .multdiv_operand_a_iB(multdiv_alu_operand_aB),
    .multdiv_operand_a_iC(multdiv_alu_operand_aC),
    .multdiv_operand_b_iA(multdiv_alu_operand_bA),
    .multdiv_operand_b_iB(multdiv_alu_operand_bB),
    .multdiv_operand_b_iC(multdiv_alu_operand_bC),
    .multdiv_sel_iA(multdiv_selA),
    .multdiv_sel_iB(multdiv_selB),
    .multdiv_sel_iC(multdiv_selC),
    .adder_result_oA(alu_adder_result_ex_oA),
    .adder_result_oB(alu_adder_result_ex_oB),
    .adder_result_oC(alu_adder_result_ex_oC),
    .adder_result_ext_oA(alu_adder_result_extA),
    .adder_result_ext_oB(alu_adder_result_extB),
    .adder_result_ext_oC(alu_adder_result_extC),
    .result_oA(alu_resultA),
    .result_oB(alu_resultB),
    .result_oC(alu_resultC),
    .comparison_result_oA(alu_cmp_resultA),
    .comparison_result_oB(alu_cmp_resultB),
    .comparison_result_oC(alu_cmp_resultC),
    .is_equal_result_oA(alu_is_equal_resultA),
    .is_equal_result_oB(alu_is_equal_resultB),
    .is_equal_result_oC(alu_is_equal_resultC)
  );
if (RV32M==RV32MSlow)
  begin : gen_multdiv_slow

    cve2_multdiv_slowTMR multdiv_i (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .mult_en_iA(mult_en_iA),
        .mult_en_iB(mult_en_iB),
        .mult_en_iC(mult_en_iC),
        .div_en_iA(div_en_iA),
        .div_en_iB(div_en_iB),
        .div_en_iC(div_en_iC),
        .mult_sel_iA(mult_sel_iA),
        .mult_sel_iB(mult_sel_iB),
        .mult_sel_iC(mult_sel_iC),
        .div_sel_iA(div_sel_iA),
        .div_sel_iB(div_sel_iB),
        .div_sel_iC(div_sel_iC),
        .operator_iA(multdiv_operator_iA),
        .operator_iB(multdiv_operator_iB),
        .operator_iC(multdiv_operator_iC),
        .signed_mode_iA(multdiv_signed_mode_iA),
        .signed_mode_iB(multdiv_signed_mode_iB),
        .signed_mode_iC(multdiv_signed_mode_iC),
        .op_a_iA(multdiv_operand_a_iA),
        .op_a_iB(multdiv_operand_a_iB),
        .op_a_iC(multdiv_operand_a_iC),
        .op_b_iA(multdiv_operand_b_iA),
        .op_b_iB(multdiv_operand_b_iB),
        .op_b_iC(multdiv_operand_b_iC),
        .alu_adder_ext_iA(alu_adder_result_extA),
        .alu_adder_ext_iB(alu_adder_result_extB),
        .alu_adder_ext_iC(alu_adder_result_extC),
        .alu_adder_iA(alu_adder_result_ex_oA),
        .alu_adder_iB(alu_adder_result_ex_oB),
        .alu_adder_iC(alu_adder_result_ex_oC),
        .equal_to_zero_iA(alu_is_equal_resultA),
        .equal_to_zero_iB(alu_is_equal_resultB),
        .equal_to_zero_iC(alu_is_equal_resultC),
        .valid_oA(multdiv_validA),
        .valid_oB(multdiv_validB),
        .valid_oC(multdiv_validC),
        .alu_operand_a_oA(multdiv_alu_operand_aA),
        .alu_operand_a_oB(multdiv_alu_operand_aB),
        .alu_operand_a_oC(multdiv_alu_operand_aC),
        .alu_operand_b_oA(multdiv_alu_operand_bA),
        .alu_operand_b_oB(multdiv_alu_operand_bB),
        .alu_operand_b_oC(multdiv_alu_operand_bC),
        .imd_val_q_iA(imd_val_q_iA),
        .imd_val_q_iB(imd_val_q_iB),
        .imd_val_q_iC(imd_val_q_iC),
        .imd_val_d_oA(multdiv_imd_val_dA),
        .imd_val_d_oB(multdiv_imd_val_dB),
        .imd_val_d_oC(multdiv_imd_val_dC),
        .imd_val_we_oA(multdiv_imd_val_weA),
        .imd_val_we_oB(multdiv_imd_val_weB),
        .imd_val_we_oC(multdiv_imd_val_weC),
        .multdiv_ready_id_iA(1'b1),
        .multdiv_ready_id_iB(1'b1),
        .multdiv_ready_id_iC(1'b1),
        .multdiv_result_oA(multdiv_resultA),
        .multdiv_result_oB(multdiv_resultB),
        .multdiv_result_oC(multdiv_resultC),
        .tmrErrorA(multdiv_itmrErrorA),
        .tmrErrorB(multdiv_itmrErrorB),
        .tmrErrorC(multdiv_itmrErrorC)
      );
  end

else
  if (RV32M==RV32MFast||RV32M==RV32MSingleCycle)
      begin : gen_multdiv_fast

      cve2_multdiv_fastTMR #(.RV32M(RV32M)) multdiv_i (
          .clk_iA(clk_iA),
          .clk_iB(clk_iB),
          .clk_iC(clk_iC),
          .rst_niA(rst_niA),
          .rst_niB(rst_niB),
          .rst_niC(rst_niC),
          .mult_en_iA(mult_en_iA),
          .mult_en_iB(mult_en_iB),
          .mult_en_iC(mult_en_iC),
          .div_en_iA(div_en_iA),
          .div_en_iB(div_en_iB),
          .div_en_iC(div_en_iC),
          .mult_sel_iA(mult_sel_iA),
          .mult_sel_iB(mult_sel_iB),
          .mult_sel_iC(mult_sel_iC),
          .div_sel_iA(div_sel_iA),
          .div_sel_iB(div_sel_iB),
          .div_sel_iC(div_sel_iC),
          .operator_iA(multdiv_operator_iA),
          .operator_iB(multdiv_operator_iB),
          .operator_iC(multdiv_operator_iC),
          .signed_mode_iA(multdiv_signed_mode_iA),
          .signed_mode_iB(multdiv_signed_mode_iB),
          .signed_mode_iC(multdiv_signed_mode_iC),
          .op_a_iA(multdiv_operand_a_iA),
          .op_a_iB(multdiv_operand_a_iB),
          .op_a_iC(multdiv_operand_a_iC),
          .op_b_iA(multdiv_operand_b_iA),
          .op_b_iB(multdiv_operand_b_iB),
          .op_b_iC(multdiv_operand_b_iC),
          .alu_operand_a_oA(multdiv_alu_operand_aA),
          .alu_operand_a_oB(multdiv_alu_operand_aB),
          .alu_operand_a_oC(multdiv_alu_operand_aC),
          .alu_operand_b_oA(multdiv_alu_operand_bA),
          .alu_operand_b_oB(multdiv_alu_operand_bB),
          .alu_operand_b_oC(multdiv_alu_operand_bC),
          .alu_adder_ext_iA(alu_adder_result_extA),
          .alu_adder_ext_iB(alu_adder_result_extB),
          .alu_adder_ext_iC(alu_adder_result_extC),
          .alu_adder_iA(alu_adder_result_ex_oA),
          .alu_adder_iB(alu_adder_result_ex_oB),
          .alu_adder_iC(alu_adder_result_ex_oC),
          .equal_to_zero_iA(alu_is_equal_resultA),
          .equal_to_zero_iB(alu_is_equal_resultB),
          .equal_to_zero_iC(alu_is_equal_resultC),
          .imd_val_q_iA(imd_val_q_iA),
          .imd_val_q_iB(imd_val_q_iB),
          .imd_val_q_iC(imd_val_q_iC),
          .imd_val_d_oA(multdiv_imd_val_dA),
          .imd_val_d_oB(multdiv_imd_val_dB),
          .imd_val_d_oC(multdiv_imd_val_dC),
          .imd_val_we_oA(multdiv_imd_val_weA),
          .imd_val_we_oB(multdiv_imd_val_weB),
          .imd_val_we_oC(multdiv_imd_val_weC),
          .valid_oA(multdiv_validA),
          .valid_oB(multdiv_validB),
          .valid_oC(multdiv_validC),
          .multdiv_result_oA(multdiv_resultA),
          .multdiv_result_oB(multdiv_resultB),
          .multdiv_result_oC(multdiv_resultC),
          .tmrErrorA(multdiv_itmrErrorA),
          .tmrErrorB(multdiv_itmrErrorB),
          .tmrErrorC(multdiv_itmrErrorC)
        );
    end

  else
      begin
      assign multdiv_alu_operand_aA = '0;
      assign multdiv_alu_operand_aB = '0;
      assign multdiv_alu_operand_aC = '0;
      assign multdiv_alu_operand_bA = '0;
      assign multdiv_alu_operand_bB = '0;
      assign multdiv_alu_operand_bC = '0;
      assign multdiv_resultA = '0;
      assign multdiv_resultB = '0;
      assign multdiv_resultC = '0;
      assign multdiv_validA = '0;
      assign multdiv_validB = '0;
      assign multdiv_validC = '0;
      assign multdiv_itmrErrorA = 1'b0;
      assign multdiv_itmrErrorB = 1'b0;
      assign multdiv_itmrErrorC = 1'b0;
    end
assign ex_valid_oA = multdiv_selA ? multdiv_validA : ~ ( | alu_imd_val_weA  ) ;
assign ex_valid_oB = multdiv_selB ? multdiv_validB : ~ ( | alu_imd_val_weB  ) ;
assign ex_valid_oC = multdiv_selC ? multdiv_validC : ~ ( | alu_imd_val_weC  ) ;
assign tmrErrorA = multdiv_itmrErrorA;
assign tmrErrorB = multdiv_itmrErrorB;
assign tmrErrorC = multdiv_itmrErrorC;
endmodule

