/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_pmpTMR.sv                                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:19                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_pmp.sv                                                                   *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:26.274272                                         *
 *           File Size         : 8653                                                               *
 *           MD5 hash          : 97c07f37b9c53b49015bd9fe0d069729                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_pmpTMR #(
  parameter int unsigned PMPGranularity = 0,
  parameter int unsigned PMPNumChan = 2,
  parameter int unsigned PMPNumRegions = 4
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input cve2_pkg::pmp_cfg_t csr_pmp_cfg_iA [PMPNumRegions],
  input cve2_pkg::pmp_cfg_t csr_pmp_cfg_iB [PMPNumRegions],
  input cve2_pkg::pmp_cfg_t csr_pmp_cfg_iC [PMPNumRegions],
  input logic [33:0] csr_pmp_addr_iA [PMPNumRegions],
  input logic [33:0] csr_pmp_addr_iB [PMPNumRegions],
  input logic [33:0] csr_pmp_addr_iC [PMPNumRegions],
  input cve2_pkg::pmp_mseccfg_t csr_pmp_mseccfg_iA,
  input cve2_pkg::pmp_mseccfg_t csr_pmp_mseccfg_iB,
  input cve2_pkg::pmp_mseccfg_t csr_pmp_mseccfg_iC,
  input cve2_pkg::priv_lvl_e priv_mode_iA [PMPNumChan],
  input cve2_pkg::priv_lvl_e priv_mode_iB [PMPNumChan],
  input cve2_pkg::priv_lvl_e priv_mode_iC [PMPNumChan],
  input logic [33:0] pmp_req_addr_iA [PMPNumChan],
  input logic [33:0] pmp_req_addr_iB [PMPNumChan],
  input logic [33:0] pmp_req_addr_iC [PMPNumChan],
  input cve2_pkg::pmp_req_e pmp_req_type_iA [PMPNumChan],
  input cve2_pkg::pmp_req_e pmp_req_type_iB [PMPNumChan],
  input cve2_pkg::pmp_req_e pmp_req_type_iC [PMPNumChan],
  output logic pmp_req_err_oA [PMPNumChan],
  output logic pmp_req_err_oB [PMPNumChan],
  output logic pmp_req_err_oC [PMPNumChan]
);
import cve2_pkg::*;
logic [33:0] region_start_addrA [PMPNumRegions];
logic [33:0] region_start_addrB [PMPNumRegions];
logic [33:0] region_start_addrC [PMPNumRegions];
logic [33:PMPGranularity + 2] region_addr_maskA [PMPNumRegions];
logic [33:PMPGranularity + 2] region_addr_maskB [PMPNumRegions];
logic [33:PMPGranularity + 2] region_addr_maskC [PMPNumRegions];
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_gtA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_gtB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_gtC;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_ltA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_ltB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_ltC;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_eqA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_eqB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_eqC;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_allA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_allB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_match_allC;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_basic_perm_checkA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_basic_perm_checkB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_basic_perm_checkC;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_mml_perm_checkA;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_mml_perm_checkB;
logic [PMPNumChan - 1:0] [PMPNumRegions - 1:0] region_mml_perm_checkC;
logic [PMPNumChan - 1:0] access_faultA;
logic [PMPNumChan - 1:0] access_faultB;
logic [PMPNumChan - 1:0] access_faultC;
for(genvar r = 0; r<PMPNumRegions; r++)
  begin : g_addr_exp
    if (r==0)
          begin : g_entry0
        assign region_start_addrA[r] = (csr_pmp_cfg_iA[r].mode==PMP_MODE_TOR) ? 34'h000000000 : csr_pmp_addr_iA[r];
        assign region_start_addrB[r] = (csr_pmp_cfg_iB[r].mode==PMP_MODE_TOR) ? 34'h000000000 : csr_pmp_addr_iB[r];
        assign region_start_addrC[r] = (csr_pmp_cfg_iC[r].mode==PMP_MODE_TOR) ? 34'h000000000 : csr_pmp_addr_iC[r];
      end

    else
          begin : g_oth
        assign region_start_addrA[r] = (csr_pmp_cfg_iA[r].mode==PMP_MODE_TOR) ? csr_pmp_addr_iA[r-1] : csr_pmp_addr_iA[r];
        assign region_start_addrB[r] = (csr_pmp_cfg_iB[r].mode==PMP_MODE_TOR) ? csr_pmp_addr_iB[r-1] : csr_pmp_addr_iB[r];
        assign region_start_addrC[r] = (csr_pmp_cfg_iC[r].mode==PMP_MODE_TOR) ? csr_pmp_addr_iC[r-1] : csr_pmp_addr_iC[r];
      end
    for(genvar b = PMPGranularity + 2; b<34; b++)
          begin : g_bitmask
        if (b==2)
                  begin : g_bit0
            assign region_addr_maskA[r][b] =  (csr_pmp_cfg_iA[r].mode!=PMP_MODE_NAPOT) ;
            assign region_addr_maskB[r][b] =  (csr_pmp_cfg_iB[r].mode!=PMP_MODE_NAPOT) ;
            assign region_addr_maskC[r][b] =  (csr_pmp_cfg_iC[r].mode!=PMP_MODE_NAPOT) ;
          end

        else
                  begin : g_others
            if (PMPGranularity==0)
                          begin : g_region_addr_mask_zero_granularity
                assign region_addr_maskA[r][b] =  (csr_pmp_cfg_iA[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iA[r][b - 1:2];
                assign region_addr_maskB[r][b] =  (csr_pmp_cfg_iB[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iB[r][b - 1:2];
                assign region_addr_maskC[r][b] =  (csr_pmp_cfg_iC[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iC[r][b - 1:2];
              end

            else
                          begin : g_region_addr_mask_other_granularity
                assign region_addr_maskA[r][b] =  (csr_pmp_cfg_iA[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iA[r][b - 1:PMPGranularity + 1];
                assign region_addr_maskB[r][b] =  (csr_pmp_cfg_iB[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iB[r][b - 1:PMPGranularity + 1];
                assign region_addr_maskC[r][b] =  (csr_pmp_cfg_iC[r].mode!=PMP_MODE_NAPOT) |~&csr_pmp_addr_iC[r][b - 1:PMPGranularity + 1];
              end
          end
      end
  end
for(genvar c = 0; c<PMPNumChan; c++)
  begin : g_access_check
    for(genvar r = 0; r<PMPNumRegions; r++)
          begin : g_regions
        assign region_match_eqA[c][r] =  (pmp_req_addr_iA[c][33:PMPGranularity + 2]&region_addr_maskA[r]) == (region_start_addrA[r][33:PMPGranularity + 2]&region_addr_maskA[r]) ;
        assign region_match_eqB[c][r] =  (pmp_req_addr_iB[c][33:PMPGranularity + 2]&region_addr_maskB[r]) == (region_start_addrB[r][33:PMPGranularity + 2]&region_addr_maskB[r]) ;
        assign region_match_eqC[c][r] =  (pmp_req_addr_iC[c][33:PMPGranularity + 2]&region_addr_maskC[r]) == (region_start_addrC[r][33:PMPGranularity + 2]&region_addr_maskC[r]) ;
        assign region_match_gtA[c][r] = pmp_req_addr_iA[c][33:PMPGranularity + 2]>region_start_addrA[r][33:PMPGranularity + 2];
        assign region_match_gtB[c][r] = pmp_req_addr_iB[c][33:PMPGranularity + 2]>region_start_addrB[r][33:PMPGranularity + 2];
        assign region_match_gtC[c][r] = pmp_req_addr_iC[c][33:PMPGranularity + 2]>region_start_addrC[r][33:PMPGranularity + 2];
        assign region_match_ltA[c][r] = pmp_req_addr_iA[c][33:PMPGranularity + 2]<csr_pmp_addr_iA[r][33:PMPGranularity + 2];
        assign region_match_ltB[c][r] = pmp_req_addr_iB[c][33:PMPGranularity + 2]<csr_pmp_addr_iB[r][33:PMPGranularity + 2];
        assign region_match_ltC[c][r] = pmp_req_addr_iC[c][33:PMPGranularity + 2]<csr_pmp_addr_iC[r][33:PMPGranularity + 2];

        always_comb
          begin
            region_match_allA[c][r] = 1'b0;
            unique case (csr_pmp_cfg_iA[r].mode)
              PMP_MODE_OFF : region_match_allA[c][r] = 1'b0;
              PMP_MODE_NA4 : region_match_allA[c][r] = region_match_eqA[c][r];
              PMP_MODE_NAPOT : region_match_allA[c][r] = region_match_eqA[c][r];
              PMP_MODE_TOR : 
                begin
                  region_match_allA[c][r] =  (region_match_eqA[c][r]|region_match_gtA[c][r]) &region_match_ltA[c][r];
                end
              default : region_match_allA[c][r] = 1'b0;
            endcase
          end

        always_comb
          begin
            region_match_allB[c][r] = 1'b0;
            unique case (csr_pmp_cfg_iB[r].mode)
              PMP_MODE_OFF : region_match_allB[c][r] = 1'b0;
              PMP_MODE_NA4 : region_match_allB[c][r] = region_match_eqB[c][r];
              PMP_MODE_NAPOT : region_match_allB[c][r] = region_match_eqB[c][r];
              PMP_MODE_TOR : 
                begin
                  region_match_allB[c][r] =  (region_match_eqB[c][r]|region_match_gtB[c][r]) &region_match_ltB[c][r];
                end
              default : region_match_allB[c][r] = 1'b0;
            endcase
          end

        always_comb
          begin
            region_match_allC[c][r] = 1'b0;
            unique case (csr_pmp_cfg_iC[r].mode)
              PMP_MODE_OFF : region_match_allC[c][r] = 1'b0;
              PMP_MODE_NA4 : region_match_allC[c][r] = region_match_eqC[c][r];
              PMP_MODE_NAPOT : region_match_allC[c][r] = region_match_eqC[c][r];
              PMP_MODE_TOR : 
                begin
                  region_match_allC[c][r] =  (region_match_eqC[c][r]|region_match_gtC[c][r]) &region_match_ltC[c][r];
                end
              default : region_match_allC[c][r] = 1'b0;
            endcase
          end
        assign region_basic_perm_checkA[c][r] =  ((pmp_req_type_iA[c]==PMP_ACC_EXEC)&csr_pmp_cfg_iA[r].exec) | ((pmp_req_type_iA[c]==PMP_ACC_WRITE)&csr_pmp_cfg_iA[r].write) | ((pmp_req_type_iA[c]==PMP_ACC_READ)&csr_pmp_cfg_iA[r].read) ;
        assign region_basic_perm_checkB[c][r] =  ((pmp_req_type_iB[c]==PMP_ACC_EXEC)&csr_pmp_cfg_iB[r].exec) | ((pmp_req_type_iB[c]==PMP_ACC_WRITE)&csr_pmp_cfg_iB[r].write) | ((pmp_req_type_iB[c]==PMP_ACC_READ)&csr_pmp_cfg_iB[r].read) ;
        assign region_basic_perm_checkC[c][r] =  ((pmp_req_type_iC[c]==PMP_ACC_EXEC)&csr_pmp_cfg_iC[r].exec) | ((pmp_req_type_iC[c]==PMP_ACC_WRITE)&csr_pmp_cfg_iC[r].write) | ((pmp_req_type_iC[c]==PMP_ACC_READ)&csr_pmp_cfg_iC[r].read) ;

        always_comb
          begin
            region_mml_perm_checkA[c][r] = 1'b0;
            if (!csr_pmp_cfg_iA[r].read&&csr_pmp_cfg_iA[r].write)
              begin
                unique case ({csr_pmp_cfg_iA[r].lock, csr_pmp_cfg_iA[r].exec})
                  2'b00 : region_mml_perm_checkA[c][r] =  (pmp_req_type_iA[c]==PMP_ACC_READ) | ((pmp_req_type_iA[c]==PMP_ACC_WRITE)&(priv_mode_iA[c]==PRIV_LVL_M)) ;
                  2'b01 : region_mml_perm_checkA[c][r] =  (pmp_req_type_iA[c]==PMP_ACC_READ) | (pmp_req_type_iA[c]==PMP_ACC_WRITE) ;
                  2'b10 : region_mml_perm_checkA[c][r] =  (pmp_req_type_iA[c]==PMP_ACC_EXEC) ;
                  2'b11 : region_mml_perm_checkA[c][r] =  (pmp_req_type_iA[c]==PMP_ACC_EXEC) | ((pmp_req_type_iA[c]==PMP_ACC_READ)&(priv_mode_iA[c]==PRIV_LVL_M)) ;
                  default : ;
                endcase
              end
            else
              begin
                if (csr_pmp_cfg_iA[r].read&csr_pmp_cfg_iA[r].write&csr_pmp_cfg_iA[r].exec&csr_pmp_cfg_iA[r].lock)
                  begin
                    region_mml_perm_checkA[c][r] = pmp_req_type_iA[c]==PMP_ACC_READ;
                  end
                else
                  begin
                    region_mml_perm_checkA[c][r] = priv_mode_iA[c]==PRIV_LVL_M ? csr_pmp_cfg_iA[r].lock&region_basic_perm_checkA[c][r] : ~ csr_pmp_cfg_iA[r].lock & region_basic_perm_checkA[c][r] ;
                  end
              end
          end

        always_comb
          begin
            region_mml_perm_checkB[c][r] = 1'b0;
            if (!csr_pmp_cfg_iB[r].read&&csr_pmp_cfg_iB[r].write)
              begin
                unique case ({csr_pmp_cfg_iB[r].lock, csr_pmp_cfg_iB[r].exec})
                  2'b00 : region_mml_perm_checkB[c][r] =  (pmp_req_type_iB[c]==PMP_ACC_READ) | ((pmp_req_type_iB[c]==PMP_ACC_WRITE)&(priv_mode_iB[c]==PRIV_LVL_M)) ;
                  2'b01 : region_mml_perm_checkB[c][r] =  (pmp_req_type_iB[c]==PMP_ACC_READ) | (pmp_req_type_iB[c]==PMP_ACC_WRITE) ;
                  2'b10 : region_mml_perm_checkB[c][r] =  (pmp_req_type_iB[c]==PMP_ACC_EXEC) ;
                  2'b11 : region_mml_perm_checkB[c][r] =  (pmp_req_type_iB[c]==PMP_ACC_EXEC) | ((pmp_req_type_iB[c]==PMP_ACC_READ)&(priv_mode_iB[c]==PRIV_LVL_M)) ;
                  default : ;
                endcase
              end
            else
              begin
                if (csr_pmp_cfg_iB[r].read&csr_pmp_cfg_iB[r].write&csr_pmp_cfg_iB[r].exec&csr_pmp_cfg_iB[r].lock)
                  begin
                    region_mml_perm_checkB[c][r] = pmp_req_type_iB[c]==PMP_ACC_READ;
                  end
                else
                  begin
                    region_mml_perm_checkB[c][r] = priv_mode_iB[c]==PRIV_LVL_M ? csr_pmp_cfg_iB[r].lock&region_basic_perm_checkB[c][r] : ~ csr_pmp_cfg_iB[r].lock & region_basic_perm_checkB[c][r] ;
                  end
              end
          end

        always_comb
          begin
            region_mml_perm_checkC[c][r] = 1'b0;
            if (!csr_pmp_cfg_iC[r].read&&csr_pmp_cfg_iC[r].write)
              begin
                unique case ({csr_pmp_cfg_iC[r].lock, csr_pmp_cfg_iC[r].exec})
                  2'b00 : region_mml_perm_checkC[c][r] =  (pmp_req_type_iC[c]==PMP_ACC_READ) | ((pmp_req_type_iC[c]==PMP_ACC_WRITE)&(priv_mode_iC[c]==PRIV_LVL_M)) ;
                  2'b01 : region_mml_perm_checkC[c][r] =  (pmp_req_type_iC[c]==PMP_ACC_READ) | (pmp_req_type_iC[c]==PMP_ACC_WRITE) ;
                  2'b10 : region_mml_perm_checkC[c][r] =  (pmp_req_type_iC[c]==PMP_ACC_EXEC) ;
                  2'b11 : region_mml_perm_checkC[c][r] =  (pmp_req_type_iC[c]==PMP_ACC_EXEC) | ((pmp_req_type_iC[c]==PMP_ACC_READ)&(priv_mode_iC[c]==PRIV_LVL_M)) ;
                  default : ;
                endcase
              end
            else
              begin
                if (csr_pmp_cfg_iC[r].read&csr_pmp_cfg_iC[r].write&csr_pmp_cfg_iC[r].exec&csr_pmp_cfg_iC[r].lock)
                  begin
                    region_mml_perm_checkC[c][r] = pmp_req_type_iC[c]==PMP_ACC_READ;
                  end
                else
                  begin
                    region_mml_perm_checkC[c][r] = priv_mode_iC[c]==PRIV_LVL_M ? csr_pmp_cfg_iC[r].lock&region_basic_perm_checkC[c][r] : ~ csr_pmp_cfg_iC[r].lock & region_basic_perm_checkC[c][r] ;
                  end
              end
          end
      end

    always_comb
      begin
        access_faultA[c] = csr_pmp_mseccfg_iA.mmwp| (priv_mode_iA[c]!=PRIV_LVL_M) ;
        for(int r = PMPNumRegions - 1; r>=0; r--)
        begin
          if (region_match_allA[c][r])
            begin
              if (csr_pmp_mseccfg_iA.mml)
                begin
                  access_faultA[c] = ~region_mml_perm_checkA[c][r];
                end
              else
                begin
                  access_faultA[c] = (priv_mode_iA[c]==PRIV_LVL_M) ? (csr_pmp_cfg_iA[r].lock&~region_basic_perm_checkA[c][r]) : ~ region_basic_perm_checkA[c][r] ;
                end
            end

        end
      end

    always_comb
      begin
        access_faultB[c] = csr_pmp_mseccfg_iB.mmwp| (priv_mode_iB[c]!=PRIV_LVL_M) ;
        for(int r = PMPNumRegions - 1; r>=0; r--)
        begin
          if (region_match_allB[c][r])
            begin
              if (csr_pmp_mseccfg_iB.mml)
                begin
                  access_faultB[c] = ~region_mml_perm_checkB[c][r];
                end
              else
                begin
                  access_faultB[c] = (priv_mode_iB[c]==PRIV_LVL_M) ? (csr_pmp_cfg_iB[r].lock&~region_basic_perm_checkB[c][r]) : ~ region_basic_perm_checkB[c][r] ;
                end
            end

        end
      end

    always_comb
      begin
        access_faultC[c] = csr_pmp_mseccfg_iC.mmwp| (priv_mode_iC[c]!=PRIV_LVL_M) ;
        for(int r = PMPNumRegions - 1; r>=0; r--)
        begin
          if (region_match_allC[c][r])
            begin
              if (csr_pmp_mseccfg_iC.mml)
                begin
                  access_faultC[c] = ~region_mml_perm_checkC[c][r];
                end
              else
                begin
                  access_faultC[c] = (priv_mode_iC[c]==PRIV_LVL_M) ? (csr_pmp_cfg_iC[r].lock&~region_basic_perm_checkC[c][r]) : ~ region_basic_perm_checkC[c][r] ;
                end
            end

        end
      end
    assign pmp_req_err_oA[c] = access_faultA[c];
    assign pmp_req_err_oB[c] = access_faultB[c];
    assign pmp_req_err_oC[c] = access_faultC[c];
  end
logic unused_csr_pmp_mseccfg_rlbA;
logic unused_csr_pmp_mseccfg_rlbB;
logic unused_csr_pmp_mseccfg_rlbC;
assign unused_csr_pmp_mseccfg_rlbA = csr_pmp_mseccfg_iA.rlb;
assign unused_csr_pmp_mseccfg_rlbB = csr_pmp_mseccfg_iB.rlb;
assign unused_csr_pmp_mseccfg_rlbC = csr_pmp_mseccfg_iC.rlb;
endmodule

