/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_if_stageTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:16                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_if_stage.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc ( M tmrg_src/cve2_if_stage.sv) *
 *           Modification time : 2025-11-12 14:35:26.208271                                         *
 *           File Size         : 13325                                                              *
 *           MD5 hash          : 383f14306e2472596e37eb52bf2f8ade                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_if_stageTMR import cve2_pkg::*; #(
  parameter int unsigned DmHaltAddr = 32'h1A110800,
  parameter int unsigned DmExceptionAddr = 32'h1A110808
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [31:0] boot_addr_iA,
  input logic [31:0] boot_addr_iB,
  input logic [31:0] boot_addr_iC,
  input logic req_iA,
  input logic req_iB,
  input logic req_iC,
  output logic instr_req_oA,
  output logic instr_req_oB,
  output logic instr_req_oC,
  output logic [31:0] instr_addr_oA,
  output logic [31:0] instr_addr_oB,
  output logic [31:0] instr_addr_oC,
  input logic instr_gnt_iA,
  input logic instr_gnt_iB,
  input logic instr_gnt_iC,
  input logic instr_rvalid_iA,
  input logic instr_rvalid_iB,
  input logic instr_rvalid_iC,
  input logic [31:0] instr_rdata_iA,
  input logic [31:0] instr_rdata_iB,
  input logic [31:0] instr_rdata_iC,
  input logic instr_err_iA,
  input logic instr_err_iB,
  input logic instr_err_iC,
  output logic instr_valid_id_oA,
  output logic instr_valid_id_oB,
  output logic instr_valid_id_oC,
  output logic instr_new_id_oA,
  output logic instr_new_id_oB,
  output logic instr_new_id_oC,
  output logic [31:0] instr_rdata_id_oA,
  output logic [31:0] instr_rdata_id_oB,
  output logic [31:0] instr_rdata_id_oC,
  output logic [31:0] instr_rdata_alu_id_oA,
  output logic [31:0] instr_rdata_alu_id_oB,
  output logic [31:0] instr_rdata_alu_id_oC,
  output logic [15:0] instr_rdata_c_id_oA,
  output logic [15:0] instr_rdata_c_id_oB,
  output logic [15:0] instr_rdata_c_id_oC,
  output logic instr_is_compressed_id_oA,
  output logic instr_is_compressed_id_oB,
  output logic instr_is_compressed_id_oC,
  output logic instr_fetch_err_oA,
  output logic instr_fetch_err_oB,
  output logic instr_fetch_err_oC,
  output logic instr_fetch_err_plus2_oA,
  output logic instr_fetch_err_plus2_oB,
  output logic instr_fetch_err_plus2_oC,
  output logic illegal_c_insn_id_oA,
  output logic illegal_c_insn_id_oB,
  output logic illegal_c_insn_id_oC,
  output logic [31:0] pc_if_oA,
  output logic [31:0] pc_if_oB,
  output logic [31:0] pc_if_oC,
  output logic [31:0] pc_id_oA,
  output logic [31:0] pc_id_oB,
  output logic [31:0] pc_id_oC,
  input logic pmp_err_if_iA,
  input logic pmp_err_if_iB,
  input logic pmp_err_if_iC,
  input logic pmp_err_if_plus2_iA,
  input logic pmp_err_if_plus2_iB,
  input logic pmp_err_if_plus2_iC,
  input logic instr_valid_clear_iA,
  input logic instr_valid_clear_iB,
  input logic instr_valid_clear_iC,
  input logic pc_set_iA,
  input logic pc_set_iB,
  input logic pc_set_iC,
  input pc_sel_e pc_mux_iA,
  input pc_sel_e pc_mux_iB,
  input pc_sel_e pc_mux_iC,
  input exc_pc_sel_e exc_pc_mux_iA,
  input exc_pc_sel_e exc_pc_mux_iB,
  input exc_pc_sel_e exc_pc_mux_iC,
  input exc_cause_e exc_causeA,
  input exc_cause_e exc_causeB,
  input exc_cause_e exc_causeC,
  input logic [31:0] branch_target_ex_iA,
  input logic [31:0] branch_target_ex_iB,
  input logic [31:0] branch_target_ex_iC,
  input logic [31:0] csr_mepc_iA,
  input logic [31:0] csr_mepc_iB,
  input logic [31:0] csr_mepc_iC,
  input logic [31:0] csr_depc_iA,
  input logic [31:0] csr_depc_iB,
  input logic [31:0] csr_depc_iC,
  input logic [31:0] csr_mtvec_iA,
  input logic [31:0] csr_mtvec_iB,
  input logic [31:0] csr_mtvec_iC,
  output logic csr_mtvec_init_oA,
  output logic csr_mtvec_init_oB,
  output logic csr_mtvec_init_oC,
  input logic id_in_ready_iA,
  input logic id_in_ready_iB,
  input logic id_in_ready_iC,
  output logic if_busy_oA,
  output logic if_busy_oB,
  output logic if_busy_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor prefetch_buffer_itmrErrorC;
wor pc_id_qTmrErrorC;
wor instr_valid_id_qTmrErrorC;
wor instr_rdata_id_qTmrErrorC;
wor instr_rdata_c_id_qTmrErrorC;
wor instr_rdata_alu_id_qTmrErrorC;
wor instr_new_id_qTmrErrorC;
wor instr_is_compressed_id_qTmrErrorC;
wor instr_fetch_err_qTmrErrorC;
wor instr_fetch_err_plus2_qTmrErrorC;
wor illegal_c_insn_id_qTmrErrorC;
wor prefetch_buffer_itmrErrorB;
wor pc_id_qTmrErrorB;
wor instr_valid_id_qTmrErrorB;
wor instr_rdata_id_qTmrErrorB;
wor instr_rdata_c_id_qTmrErrorB;
wor instr_rdata_alu_id_qTmrErrorB;
wor instr_new_id_qTmrErrorB;
wor instr_is_compressed_id_qTmrErrorB;
wor instr_fetch_err_qTmrErrorB;
wor instr_fetch_err_plus2_qTmrErrorB;
wor illegal_c_insn_id_qTmrErrorB;
wor prefetch_buffer_itmrErrorA;
wor pc_id_qTmrErrorA;
wor instr_valid_id_qTmrErrorA;
wor instr_rdata_id_qTmrErrorA;
wor instr_rdata_c_id_qTmrErrorA;
wor instr_rdata_alu_id_qTmrErrorA;
wor instr_new_id_qTmrErrorA;
wor instr_is_compressed_id_qTmrErrorA;
wor instr_fetch_err_qTmrErrorA;
wor instr_fetch_err_plus2_qTmrErrorA;
wor illegal_c_insn_id_qTmrErrorA;
logic [31:0] instr_rdata_id_qA;
logic [31:0] instr_rdata_id_qB;
logic [31:0] instr_rdata_id_qC;
logic [31:0] instr_rdata_id_qVotedA;
logic [31:0] instr_rdata_id_qVotedB;
logic [31:0] instr_rdata_id_qVotedC;
logic [31:0] instr_rdata_alu_id_qA;
logic [31:0] instr_rdata_alu_id_qB;
logic [31:0] instr_rdata_alu_id_qC;
logic [31:0] instr_rdata_alu_id_qVotedA;
logic [31:0] instr_rdata_alu_id_qVotedB;
logic [31:0] instr_rdata_alu_id_qVotedC;
logic instr_fetch_err_qA;
logic instr_fetch_err_qB;
logic instr_fetch_err_qC;
logic instr_fetch_err_qVotedA;
logic instr_fetch_err_qVotedB;
logic instr_fetch_err_qVotedC;
logic instr_fetch_err_plus2_qA;
logic instr_fetch_err_plus2_qB;
logic instr_fetch_err_plus2_qC;
logic instr_fetch_err_plus2_qVotedA;
logic instr_fetch_err_plus2_qVotedB;
logic instr_fetch_err_plus2_qVotedC;
logic [15:0] instr_rdata_c_id_qA;
logic [15:0] instr_rdata_c_id_qB;
logic [15:0] instr_rdata_c_id_qC;
logic [15:0] instr_rdata_c_id_qVotedA;
logic [15:0] instr_rdata_c_id_qVotedB;
logic [15:0] instr_rdata_c_id_qVotedC;
logic instr_is_compressed_id_qA;
logic instr_is_compressed_id_qB;
logic instr_is_compressed_id_qC;
logic instr_is_compressed_id_qVotedA;
logic instr_is_compressed_id_qVotedB;
logic instr_is_compressed_id_qVotedC;
logic illegal_c_insn_id_qA;
logic illegal_c_insn_id_qB;
logic illegal_c_insn_id_qC;
logic illegal_c_insn_id_qVotedA;
logic illegal_c_insn_id_qVotedB;
logic illegal_c_insn_id_qVotedC;
logic [31:0] pc_id_qA;
logic [31:0] pc_id_qB;
logic [31:0] pc_id_qC;
logic [31:0] pc_id_qVotedA;
logic [31:0] pc_id_qVotedB;
logic [31:0] pc_id_qVotedC;
assign instr_rdata_id_oA = instr_rdata_id_qVotedA;
assign instr_rdata_id_oB = instr_rdata_id_qVotedB;
assign instr_rdata_id_oC = instr_rdata_id_qVotedC;
assign instr_rdata_alu_id_oA = instr_rdata_alu_id_qVotedA;
assign instr_rdata_alu_id_oB = instr_rdata_alu_id_qVotedB;
assign instr_rdata_alu_id_oC = instr_rdata_alu_id_qVotedC;
assign instr_fetch_err_oA = instr_fetch_err_qVotedA;
assign instr_fetch_err_oB = instr_fetch_err_qVotedB;
assign instr_fetch_err_oC = instr_fetch_err_qVotedC;
assign instr_fetch_err_plus2_oA = instr_fetch_err_plus2_qVotedA;
assign instr_fetch_err_plus2_oB = instr_fetch_err_plus2_qVotedB;
assign instr_fetch_err_plus2_oC = instr_fetch_err_plus2_qVotedC;
assign instr_rdata_c_id_oA = instr_rdata_c_id_qVotedA;
assign instr_rdata_c_id_oB = instr_rdata_c_id_qVotedB;
assign instr_rdata_c_id_oC = instr_rdata_c_id_qVotedC;
assign instr_is_compressed_id_oA = instr_is_compressed_id_qVotedA;
assign instr_is_compressed_id_oB = instr_is_compressed_id_qVotedB;
assign instr_is_compressed_id_oC = instr_is_compressed_id_qVotedC;
assign illegal_c_insn_id_oA = illegal_c_insn_id_qVotedA;
assign illegal_c_insn_id_oB = illegal_c_insn_id_qVotedB;
assign illegal_c_insn_id_oC = illegal_c_insn_id_qVotedC;
assign pc_id_oA = pc_id_qVotedA;
assign pc_id_oB = pc_id_qVotedB;
assign pc_id_oC = pc_id_qVotedC;
logic instr_valid_id_dA;
logic instr_valid_id_dB;
logic instr_valid_id_dC;
logic instr_valid_id_qA;
logic instr_valid_id_qB;
logic instr_valid_id_qC;
logic instr_valid_id_qVotedA;
logic instr_valid_id_qVotedB;
logic instr_valid_id_qVotedC;
logic instr_new_id_dA;
logic instr_new_id_dB;
logic instr_new_id_dC;
logic instr_new_id_qA;
logic instr_new_id_qB;
logic instr_new_id_qC;
logic instr_new_id_qVotedA;
logic instr_new_id_qVotedB;
logic instr_new_id_qVotedC;
logic prefetch_busyA;
logic prefetch_busyB;
logic prefetch_busyC;
logic branch_reqA;
logic branch_reqB;
logic branch_reqC;
logic [31:0] fetch_addr_nA;
logic [31:0] fetch_addr_nB;
logic [31:0] fetch_addr_nC;
logic unused_fetch_addr_n0A;
logic unused_fetch_addr_n0B;
logic unused_fetch_addr_n0C;
logic fetch_validA;
logic fetch_validB;
logic fetch_validC;
logic fetch_readyA;
logic fetch_readyB;
logic fetch_readyC;
logic [31:0] fetch_rdataA;
logic [31:0] fetch_rdataB;
logic [31:0] fetch_rdataC;
logic [31:0] fetch_addrA;
logic [31:0] fetch_addrB;
logic [31:0] fetch_addrC;
logic fetch_errA;
logic fetch_errB;
logic fetch_errC;
logic fetch_err_plus2A;
logic fetch_err_plus2B;
logic fetch_err_plus2C;
logic [31:0] instr_decompressedA;
logic [31:0] instr_decompressedB;
logic [31:0] instr_decompressedC;
logic illegal_c_insnA;
logic illegal_c_insnB;
logic illegal_c_insnC;
logic instr_is_compressedA;
logic instr_is_compressedB;
logic instr_is_compressedC;
logic if_instr_pmp_errA;
logic if_instr_pmp_errB;
logic if_instr_pmp_errC;
logic if_instr_errA;
logic if_instr_errB;
logic if_instr_errC;
logic if_instr_err_plus2A;
logic if_instr_err_plus2B;
logic if_instr_err_plus2C;
logic [31:0] exc_pcA;
logic [31:0] exc_pcB;
logic [31:0] exc_pcC;
logic [6:0] irq_idA;
logic [6:0] irq_idB;
logic [6:0] irq_idC;
logic unused_irq_bitA;
logic unused_irq_bitB;
logic unused_irq_bitC;
logic if_id_pipe_reg_weA;
logic if_id_pipe_reg_weB;
logic if_id_pipe_reg_weC;
cve2_pkg::pc_sel_e pc_mux_internalA;
cve2_pkg::pc_sel_e pc_mux_internalB;
cve2_pkg::pc_sel_e pc_mux_internalC;
logic [7:0] unused_boot_addrA;
logic [7:0] unused_boot_addrB;
logic [7:0] unused_boot_addrC;
logic [7:0] unused_csr_mtvecA;
logic [7:0] unused_csr_mtvecB;
logic [7:0] unused_csr_mtvecC;
assign unused_boot_addrA = boot_addr_iA[7:0];
assign unused_boot_addrB = boot_addr_iB[7:0];
assign unused_boot_addrC = boot_addr_iC[7:0];
assign unused_csr_mtvecA = csr_mtvec_iA[7:0];
assign unused_csr_mtvecB = csr_mtvec_iB[7:0];
assign unused_csr_mtvecC = csr_mtvec_iC[7:0];
assign irq_idA = {exc_causeA};
assign irq_idB = {exc_causeB};
assign irq_idC = {exc_causeC};
assign unused_irq_bitA = irq_idA[6];
assign unused_irq_bitB = irq_idB[6];
assign unused_irq_bitC = irq_idC[6];

always_comb
  begin : exc_pc_muxA
    unique case (exc_pc_mux_iA)
      EXC_PC_EXC : exc_pcA = {csr_mtvec_iA[31:8], 8'h00};
      EXC_PC_IRQ : exc_pcA = {csr_mtvec_iA[31:8], irq_idA[5:0], 2'b00};
      EXC_PC_DBD : exc_pcA = DmHaltAddr;
      EXC_PC_DBG_EXC : exc_pcA = DmExceptionAddr;
      default : exc_pcA = {csr_mtvec_iA[31:8], 8'h00};
    endcase
  end

always_comb
  begin : exc_pc_muxB
    unique case (exc_pc_mux_iB)
      EXC_PC_EXC : exc_pcB = {csr_mtvec_iB[31:8], 8'h00};
      EXC_PC_IRQ : exc_pcB = {csr_mtvec_iB[31:8], irq_idB[5:0], 2'b00};
      EXC_PC_DBD : exc_pcB = DmHaltAddr;
      EXC_PC_DBG_EXC : exc_pcB = DmExceptionAddr;
      default : exc_pcB = {csr_mtvec_iB[31:8], 8'h00};
    endcase
  end

always_comb
  begin : exc_pc_muxC
    unique case (exc_pc_mux_iC)
      EXC_PC_EXC : exc_pcC = {csr_mtvec_iC[31:8], 8'h00};
      EXC_PC_IRQ : exc_pcC = {csr_mtvec_iC[31:8], irq_idC[5:0], 2'b00};
      EXC_PC_DBD : exc_pcC = DmHaltAddr;
      EXC_PC_DBG_EXC : exc_pcC = DmExceptionAddr;
      default : exc_pcC = {csr_mtvec_iC[31:8], 8'h00};
    endcase
  end
assign pc_mux_internalA = pc_mux_iA;
assign pc_mux_internalB = pc_mux_iB;
assign pc_mux_internalC = pc_mux_iC;

always_comb
  begin : fetch_addr_muxA
    unique case (pc_mux_internalA)
      PC_BOOT : fetch_addr_nA = {boot_addr_iA[31:8], 8'h00};
      PC_JUMP : fetch_addr_nA = branch_target_ex_iA;
      PC_EXC : fetch_addr_nA = exc_pcA;
      PC_ERET : fetch_addr_nA = csr_mepc_iA;
      PC_DRET : fetch_addr_nA = csr_depc_iA;
      default : fetch_addr_nA = {boot_addr_iA[31:8], 8'h00};
    endcase
  end

always_comb
  begin : fetch_addr_muxB
    unique case (pc_mux_internalB)
      PC_BOOT : fetch_addr_nB = {boot_addr_iB[31:8], 8'h00};
      PC_JUMP : fetch_addr_nB = branch_target_ex_iB;
      PC_EXC : fetch_addr_nB = exc_pcB;
      PC_ERET : fetch_addr_nB = csr_mepc_iB;
      PC_DRET : fetch_addr_nB = csr_depc_iB;
      default : fetch_addr_nB = {boot_addr_iB[31:8], 8'h00};
    endcase
  end

always_comb
  begin : fetch_addr_muxC
    unique case (pc_mux_internalC)
      PC_BOOT : fetch_addr_nC = {boot_addr_iC[31:8], 8'h00};
      PC_JUMP : fetch_addr_nC = branch_target_ex_iC;
      PC_EXC : fetch_addr_nC = exc_pcC;
      PC_ERET : fetch_addr_nC = csr_mepc_iC;
      PC_DRET : fetch_addr_nC = csr_depc_iC;
      default : fetch_addr_nC = {boot_addr_iC[31:8], 8'h00};
    endcase
  end
assign csr_mtvec_init_oA =  (pc_mux_iA==PC_BOOT) &pc_set_iA;
assign csr_mtvec_init_oB =  (pc_mux_iB==PC_BOOT) &pc_set_iB;
assign csr_mtvec_init_oC =  (pc_mux_iC==PC_BOOT) &pc_set_iC;

cve2_prefetch_bufferTMR prefetch_buffer_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .req_iA(req_iA),
    .req_iB(req_iB),
    .req_iC(req_iC),
    .branch_iA(branch_reqA),
    .branch_iB(branch_reqB),
    .branch_iC(branch_reqC),
    .addr_iA({fetch_addr_nA[31:1], 1'b0}),
    .addr_iB({fetch_addr_nB[31:1], 1'b0}),
    .addr_iC({fetch_addr_nC[31:1], 1'b0}),
    .ready_iA(fetch_readyA),
    .ready_iB(fetch_readyB),
    .ready_iC(fetch_readyC),
    .valid_oA(fetch_validA),
    .valid_oB(fetch_validB),
    .valid_oC(fetch_validC),
    .rdata_oA(fetch_rdataA),
    .rdata_oB(fetch_rdataB),
    .rdata_oC(fetch_rdataC),
    .addr_oA(fetch_addrA),
    .addr_oB(fetch_addrB),
    .addr_oC(fetch_addrC),
    .err_oA(fetch_errA),
    .err_oB(fetch_errB),
    .err_oC(fetch_errC),
    .err_plus2_oA(fetch_err_plus2A),
    .err_plus2_oB(fetch_err_plus2B),
    .err_plus2_oC(fetch_err_plus2C),
    .instr_req_oA(instr_req_oA),
    .instr_req_oB(instr_req_oB),
    .instr_req_oC(instr_req_oC),
    .instr_addr_oA(instr_addr_oA),
    .instr_addr_oB(instr_addr_oB),
    .instr_addr_oC(instr_addr_oC),
    .instr_gnt_iA(instr_gnt_iA),
    .instr_gnt_iB(instr_gnt_iB),
    .instr_gnt_iC(instr_gnt_iC),
    .instr_rvalid_iA(instr_rvalid_iA),
    .instr_rvalid_iB(instr_rvalid_iB),
    .instr_rvalid_iC(instr_rvalid_iC),
    .instr_rdata_iA(instr_rdata_iA),
    .instr_rdata_iB(instr_rdata_iB),
    .instr_rdata_iC(instr_rdata_iC),
    .instr_err_iA(instr_err_iA),
    .instr_err_iB(instr_err_iB),
    .instr_err_iC(instr_err_iC),
    .busy_oA(prefetch_busyA),
    .busy_oB(prefetch_busyB),
    .busy_oC(prefetch_busyC),
    .tmrErrorA(prefetch_buffer_itmrErrorA),
    .tmrErrorB(prefetch_buffer_itmrErrorB),
    .tmrErrorC(prefetch_buffer_itmrErrorC)
  );
assign unused_fetch_addr_n0A = fetch_addr_nA[0];
assign unused_fetch_addr_n0B = fetch_addr_nB[0];
assign unused_fetch_addr_n0C = fetch_addr_nC[0];
assign branch_reqA = pc_set_iA;
assign branch_reqB = pc_set_iB;
assign branch_reqC = pc_set_iC;
assign pc_if_oA = fetch_addrA;
assign pc_if_oB = fetch_addrB;
assign pc_if_oC = fetch_addrC;
assign if_busy_oA = prefetch_busyA;
assign if_busy_oB = prefetch_busyB;
assign if_busy_oC = prefetch_busyC;
assign if_instr_pmp_errA = pmp_err_if_iA| (fetch_addrA[2]&~instr_is_compressedA&pmp_err_if_plus2_iA) ;
assign if_instr_pmp_errB = pmp_err_if_iB| (fetch_addrB[2]&~instr_is_compressedB&pmp_err_if_plus2_iB) ;
assign if_instr_pmp_errC = pmp_err_if_iC| (fetch_addrC[2]&~instr_is_compressedC&pmp_err_if_plus2_iC) ;
assign if_instr_errA = fetch_errA|if_instr_pmp_errA;
assign if_instr_errB = fetch_errB|if_instr_pmp_errB;
assign if_instr_errC = fetch_errC|if_instr_pmp_errC;
assign if_instr_err_plus2A =  ((fetch_addrA[2]&~instr_is_compressedA&pmp_err_if_plus2_iA)|fetch_err_plus2A) &~pmp_err_if_iA;
assign if_instr_err_plus2B =  ((fetch_addrB[2]&~instr_is_compressedB&pmp_err_if_plus2_iB)|fetch_err_plus2B) &~pmp_err_if_iB;
assign if_instr_err_plus2C =  ((fetch_addrC[2]&~instr_is_compressedC&pmp_err_if_plus2_iC)|fetch_err_plus2C) &~pmp_err_if_iC;

cve2_compressed_decoderTMR compressed_decoder_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .valid_iA(fetch_validA&~fetch_errA),
    .valid_iB(fetch_validB&~fetch_errB),
    .valid_iC(fetch_validC&~fetch_errC),
    .instr_iA(fetch_rdataA),
    .instr_iB(fetch_rdataB),
    .instr_iC(fetch_rdataC),
    .instr_oA(instr_decompressedA),
    .instr_oB(instr_decompressedB),
    .instr_oC(instr_decompressedC),
    .is_compressed_oA(instr_is_compressedA),
    .is_compressed_oB(instr_is_compressedB),
    .is_compressed_oC(instr_is_compressedC),
    .illegal_instr_oA(illegal_c_insnA),
    .illegal_instr_oB(illegal_c_insnB),
    .illegal_instr_oC(illegal_c_insnC)
  );
assign instr_valid_id_dA =  (fetch_validA&id_in_ready_iA&~pc_set_iA) | (instr_valid_id_qVotedA&~instr_valid_clear_iA) ;
assign instr_valid_id_dB =  (fetch_validB&id_in_ready_iB&~pc_set_iB) | (instr_valid_id_qVotedB&~instr_valid_clear_iB) ;
assign instr_valid_id_dC =  (fetch_validC&id_in_ready_iC&~pc_set_iC) | (instr_valid_id_qVotedC&~instr_valid_clear_iC) ;
assign instr_new_id_dA = fetch_validA&id_in_ready_iA;
assign instr_new_id_dB = fetch_validB&id_in_ready_iB;
assign instr_new_id_dC = fetch_validC&id_in_ready_iC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        instr_valid_id_qA <= 1'b0;
        instr_new_id_qA <= 1'b0;
      end
    else
      begin
        instr_valid_id_qA <= instr_valid_id_dA;
        instr_new_id_qA <= instr_new_id_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        instr_valid_id_qB <= 1'b0;
        instr_new_id_qB <= 1'b0;
      end
    else
      begin
        instr_valid_id_qB <= instr_valid_id_dB;
        instr_new_id_qB <= instr_new_id_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        instr_valid_id_qC <= 1'b0;
        instr_new_id_qC <= 1'b0;
      end
    else
      begin
        instr_valid_id_qC <= instr_valid_id_dC;
        instr_new_id_qC <= instr_new_id_dC;
      end
  end
assign instr_valid_id_oA = instr_valid_id_qVotedA;
assign instr_valid_id_oB = instr_valid_id_qVotedB;
assign instr_valid_id_oC = instr_valid_id_qVotedC;
assign instr_new_id_oA = instr_new_id_qVotedA;
assign instr_new_id_oB = instr_new_id_qVotedB;
assign instr_new_id_oC = instr_new_id_qVotedC;
assign if_id_pipe_reg_weA = instr_new_id_dA;
assign if_id_pipe_reg_weB = instr_new_id_dB;
assign if_id_pipe_reg_weC = instr_new_id_dC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        instr_rdata_id_qA <= '0;
        instr_rdata_alu_id_qA <= '0;
        instr_fetch_err_qA <= '0;
        instr_fetch_err_plus2_qA <= '0;
        instr_rdata_c_id_qA <= '0;
        instr_is_compressed_id_qA <= '0;
        illegal_c_insn_id_qA <= '0;
        pc_id_qA <= '0;
      end
    else
      if (if_id_pipe_reg_weA)
        begin
          instr_rdata_id_qA <= instr_decompressedA;
          instr_rdata_alu_id_qA <= instr_decompressedA;
          instr_fetch_err_qA <= if_instr_errA;
          instr_fetch_err_plus2_qA <= if_instr_err_plus2A;
          instr_rdata_c_id_qA <= fetch_rdataA[15:0];
          instr_is_compressed_id_qA <= instr_is_compressedA;
          illegal_c_insn_id_qA <= illegal_c_insnA;
          pc_id_qA <= pc_if_oA;
        end

  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        instr_rdata_id_qB <= '0;
        instr_rdata_alu_id_qB <= '0;
        instr_fetch_err_qB <= '0;
        instr_fetch_err_plus2_qB <= '0;
        instr_rdata_c_id_qB <= '0;
        instr_is_compressed_id_qB <= '0;
        illegal_c_insn_id_qB <= '0;
        pc_id_qB <= '0;
      end
    else
      if (if_id_pipe_reg_weB)
        begin
          instr_rdata_id_qB <= instr_decompressedB;
          instr_rdata_alu_id_qB <= instr_decompressedB;
          instr_fetch_err_qB <= if_instr_errB;
          instr_fetch_err_plus2_qB <= if_instr_err_plus2B;
          instr_rdata_c_id_qB <= fetch_rdataB[15:0];
          instr_is_compressed_id_qB <= instr_is_compressedB;
          illegal_c_insn_id_qB <= illegal_c_insnB;
          pc_id_qB <= pc_if_oB;
        end

  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        instr_rdata_id_qC <= '0;
        instr_rdata_alu_id_qC <= '0;
        instr_fetch_err_qC <= '0;
        instr_fetch_err_plus2_qC <= '0;
        instr_rdata_c_id_qC <= '0;
        instr_is_compressed_id_qC <= '0;
        illegal_c_insn_id_qC <= '0;
        pc_id_qC <= '0;
      end
    else
      if (if_id_pipe_reg_weC)
        begin
          instr_rdata_id_qC <= instr_decompressedC;
          instr_rdata_alu_id_qC <= instr_decompressedC;
          instr_fetch_err_qC <= if_instr_errC;
          instr_fetch_err_plus2_qC <= if_instr_err_plus2C;
          instr_rdata_c_id_qC <= fetch_rdataC[15:0];
          instr_is_compressed_id_qC <= instr_is_compressedC;
          illegal_c_insn_id_qC <= illegal_c_insnC;
          pc_id_qC <= pc_if_oC;
        end

  end
assign fetch_readyA = id_in_ready_iA;
assign fetch_readyB = id_in_ready_iB;
assign fetch_readyC = id_in_ready_iC;

majorityVoter illegal_c_insn_id_qVoterA (
    .inA(illegal_c_insn_id_qA),
    .inB(illegal_c_insn_id_qB),
    .inC(illegal_c_insn_id_qC),
    .out(illegal_c_insn_id_qVotedA),
    .tmrErr(illegal_c_insn_id_qTmrErrorA)
  );

majorityVoter instr_fetch_err_plus2_qVoterA (
    .inA(instr_fetch_err_plus2_qA),
    .inB(instr_fetch_err_plus2_qB),
    .inC(instr_fetch_err_plus2_qC),
    .out(instr_fetch_err_plus2_qVotedA),
    .tmrErr(instr_fetch_err_plus2_qTmrErrorA)
  );

majorityVoter instr_fetch_err_qVoterA (
    .inA(instr_fetch_err_qA),
    .inB(instr_fetch_err_qB),
    .inC(instr_fetch_err_qC),
    .out(instr_fetch_err_qVotedA),
    .tmrErr(instr_fetch_err_qTmrErrorA)
  );

majorityVoter instr_is_compressed_id_qVoterA (
    .inA(instr_is_compressed_id_qA),
    .inB(instr_is_compressed_id_qB),
    .inC(instr_is_compressed_id_qC),
    .out(instr_is_compressed_id_qVotedA),
    .tmrErr(instr_is_compressed_id_qTmrErrorA)
  );

majorityVoter instr_new_id_qVoterA (
    .inA(instr_new_id_qA),
    .inB(instr_new_id_qB),
    .inC(instr_new_id_qC),
    .out(instr_new_id_qVotedA),
    .tmrErr(instr_new_id_qTmrErrorA)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_alu_id_qVoterA (
    .inA(instr_rdata_alu_id_qA),
    .inB(instr_rdata_alu_id_qB),
    .inC(instr_rdata_alu_id_qC),
    .out(instr_rdata_alu_id_qVotedA),
    .tmrErr(instr_rdata_alu_id_qTmrErrorA)
  );

majorityVoter #(.WIDTH(16)) instr_rdata_c_id_qVoterA (
    .inA(instr_rdata_c_id_qA),
    .inB(instr_rdata_c_id_qB),
    .inC(instr_rdata_c_id_qC),
    .out(instr_rdata_c_id_qVotedA),
    .tmrErr(instr_rdata_c_id_qTmrErrorA)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_id_qVoterA (
    .inA(instr_rdata_id_qA),
    .inB(instr_rdata_id_qB),
    .inC(instr_rdata_id_qC),
    .out(instr_rdata_id_qVotedA),
    .tmrErr(instr_rdata_id_qTmrErrorA)
  );

majorityVoter instr_valid_id_qVoterA (
    .inA(instr_valid_id_qA),
    .inB(instr_valid_id_qB),
    .inC(instr_valid_id_qC),
    .out(instr_valid_id_qVotedA),
    .tmrErr(instr_valid_id_qTmrErrorA)
  );

majorityVoter #(.WIDTH(32)) pc_id_qVoterA (
    .inA(pc_id_qA),
    .inB(pc_id_qB),
    .inC(pc_id_qC),
    .out(pc_id_qVotedA),
    .tmrErr(pc_id_qTmrErrorA)
  );
assign tmrErrorA = illegal_c_insn_id_qTmrErrorA|instr_fetch_err_plus2_qTmrErrorA|instr_fetch_err_qTmrErrorA|instr_is_compressed_id_qTmrErrorA|instr_new_id_qTmrErrorA|instr_rdata_alu_id_qTmrErrorA|instr_rdata_c_id_qTmrErrorA|instr_rdata_id_qTmrErrorA|instr_valid_id_qTmrErrorA|pc_id_qTmrErrorA|prefetch_buffer_itmrErrorA;

majorityVoter illegal_c_insn_id_qVoterB (
    .inA(illegal_c_insn_id_qA),
    .inB(illegal_c_insn_id_qB),
    .inC(illegal_c_insn_id_qC),
    .out(illegal_c_insn_id_qVotedB),
    .tmrErr(illegal_c_insn_id_qTmrErrorB)
  );

majorityVoter instr_fetch_err_plus2_qVoterB (
    .inA(instr_fetch_err_plus2_qA),
    .inB(instr_fetch_err_plus2_qB),
    .inC(instr_fetch_err_plus2_qC),
    .out(instr_fetch_err_plus2_qVotedB),
    .tmrErr(instr_fetch_err_plus2_qTmrErrorB)
  );

majorityVoter instr_fetch_err_qVoterB (
    .inA(instr_fetch_err_qA),
    .inB(instr_fetch_err_qB),
    .inC(instr_fetch_err_qC),
    .out(instr_fetch_err_qVotedB),
    .tmrErr(instr_fetch_err_qTmrErrorB)
  );

majorityVoter instr_is_compressed_id_qVoterB (
    .inA(instr_is_compressed_id_qA),
    .inB(instr_is_compressed_id_qB),
    .inC(instr_is_compressed_id_qC),
    .out(instr_is_compressed_id_qVotedB),
    .tmrErr(instr_is_compressed_id_qTmrErrorB)
  );

majorityVoter instr_new_id_qVoterB (
    .inA(instr_new_id_qA),
    .inB(instr_new_id_qB),
    .inC(instr_new_id_qC),
    .out(instr_new_id_qVotedB),
    .tmrErr(instr_new_id_qTmrErrorB)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_alu_id_qVoterB (
    .inA(instr_rdata_alu_id_qA),
    .inB(instr_rdata_alu_id_qB),
    .inC(instr_rdata_alu_id_qC),
    .out(instr_rdata_alu_id_qVotedB),
    .tmrErr(instr_rdata_alu_id_qTmrErrorB)
  );

majorityVoter #(.WIDTH(16)) instr_rdata_c_id_qVoterB (
    .inA(instr_rdata_c_id_qA),
    .inB(instr_rdata_c_id_qB),
    .inC(instr_rdata_c_id_qC),
    .out(instr_rdata_c_id_qVotedB),
    .tmrErr(instr_rdata_c_id_qTmrErrorB)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_id_qVoterB (
    .inA(instr_rdata_id_qA),
    .inB(instr_rdata_id_qB),
    .inC(instr_rdata_id_qC),
    .out(instr_rdata_id_qVotedB),
    .tmrErr(instr_rdata_id_qTmrErrorB)
  );

majorityVoter instr_valid_id_qVoterB (
    .inA(instr_valid_id_qA),
    .inB(instr_valid_id_qB),
    .inC(instr_valid_id_qC),
    .out(instr_valid_id_qVotedB),
    .tmrErr(instr_valid_id_qTmrErrorB)
  );

majorityVoter #(.WIDTH(32)) pc_id_qVoterB (
    .inA(pc_id_qA),
    .inB(pc_id_qB),
    .inC(pc_id_qC),
    .out(pc_id_qVotedB),
    .tmrErr(pc_id_qTmrErrorB)
  );
assign tmrErrorB = illegal_c_insn_id_qTmrErrorB|instr_fetch_err_plus2_qTmrErrorB|instr_fetch_err_qTmrErrorB|instr_is_compressed_id_qTmrErrorB|instr_new_id_qTmrErrorB|instr_rdata_alu_id_qTmrErrorB|instr_rdata_c_id_qTmrErrorB|instr_rdata_id_qTmrErrorB|instr_valid_id_qTmrErrorB|pc_id_qTmrErrorB|prefetch_buffer_itmrErrorB;

majorityVoter illegal_c_insn_id_qVoterC (
    .inA(illegal_c_insn_id_qA),
    .inB(illegal_c_insn_id_qB),
    .inC(illegal_c_insn_id_qC),
    .out(illegal_c_insn_id_qVotedC),
    .tmrErr(illegal_c_insn_id_qTmrErrorC)
  );

majorityVoter instr_fetch_err_plus2_qVoterC (
    .inA(instr_fetch_err_plus2_qA),
    .inB(instr_fetch_err_plus2_qB),
    .inC(instr_fetch_err_plus2_qC),
    .out(instr_fetch_err_plus2_qVotedC),
    .tmrErr(instr_fetch_err_plus2_qTmrErrorC)
  );

majorityVoter instr_fetch_err_qVoterC (
    .inA(instr_fetch_err_qA),
    .inB(instr_fetch_err_qB),
    .inC(instr_fetch_err_qC),
    .out(instr_fetch_err_qVotedC),
    .tmrErr(instr_fetch_err_qTmrErrorC)
  );

majorityVoter instr_is_compressed_id_qVoterC (
    .inA(instr_is_compressed_id_qA),
    .inB(instr_is_compressed_id_qB),
    .inC(instr_is_compressed_id_qC),
    .out(instr_is_compressed_id_qVotedC),
    .tmrErr(instr_is_compressed_id_qTmrErrorC)
  );

majorityVoter instr_new_id_qVoterC (
    .inA(instr_new_id_qA),
    .inB(instr_new_id_qB),
    .inC(instr_new_id_qC),
    .out(instr_new_id_qVotedC),
    .tmrErr(instr_new_id_qTmrErrorC)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_alu_id_qVoterC (
    .inA(instr_rdata_alu_id_qA),
    .inB(instr_rdata_alu_id_qB),
    .inC(instr_rdata_alu_id_qC),
    .out(instr_rdata_alu_id_qVotedC),
    .tmrErr(instr_rdata_alu_id_qTmrErrorC)
  );

majorityVoter #(.WIDTH(16)) instr_rdata_c_id_qVoterC (
    .inA(instr_rdata_c_id_qA),
    .inB(instr_rdata_c_id_qB),
    .inC(instr_rdata_c_id_qC),
    .out(instr_rdata_c_id_qVotedC),
    .tmrErr(instr_rdata_c_id_qTmrErrorC)
  );

majorityVoter #(.WIDTH(32)) instr_rdata_id_qVoterC (
    .inA(instr_rdata_id_qA),
    .inB(instr_rdata_id_qB),
    .inC(instr_rdata_id_qC),
    .out(instr_rdata_id_qVotedC),
    .tmrErr(instr_rdata_id_qTmrErrorC)
  );

majorityVoter instr_valid_id_qVoterC (
    .inA(instr_valid_id_qA),
    .inB(instr_valid_id_qB),
    .inC(instr_valid_id_qC),
    .out(instr_valid_id_qVotedC),
    .tmrErr(instr_valid_id_qTmrErrorC)
  );

majorityVoter #(.WIDTH(32)) pc_id_qVoterC (
    .inA(pc_id_qA),
    .inB(pc_id_qB),
    .inC(pc_id_qC),
    .out(pc_id_qVotedC),
    .tmrErr(pc_id_qTmrErrorC)
  );
assign tmrErrorC = illegal_c_insn_id_qTmrErrorC|instr_fetch_err_plus2_qTmrErrorC|instr_fetch_err_qTmrErrorC|instr_is_compressed_id_qTmrErrorC|instr_new_id_qTmrErrorC|instr_rdata_alu_id_qTmrErrorC|instr_rdata_c_id_qTmrErrorC|instr_rdata_id_qTmrErrorC|instr_valid_id_qTmrErrorC|pc_id_qTmrErrorC|prefetch_buffer_itmrErrorC;
endmodule

