/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_compressed_decoderTMR.sv                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:23                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_compressed_decoder.sv                                                    *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-12 14:35:26.045269                                         *
 *           File Size         : 10892                                                              *
 *           MD5 hash          : 6b4d58b6f035d669125fd40874d0d3b1                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_compressed_decoderTMR (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  input logic [31:0] instr_iA,
  input logic [31:0] instr_iB,
  input logic [31:0] instr_iC,
  output logic [31:0] instr_oA,
  output logic [31:0] instr_oB,
  output logic [31:0] instr_oC,
  output logic is_compressed_oA,
  output logic is_compressed_oB,
  output logic is_compressed_oC,
  output logic illegal_instr_oA,
  output logic illegal_instr_oB,
  output logic illegal_instr_oC
);
import cve2_pkg::*;
logic unused_validA;
logic unused_validB;
logic unused_validC;
assign unused_validA = valid_iA;
assign unused_validB = valid_iB;
assign unused_validC = valid_iC;

always_comb
  begin
    instr_oA = instr_iA;
    illegal_instr_oA = 1'b0;
    unique case (instr_iA[1:0])
      2'b00 : 
        begin
          unique case (instr_iA[15:13])
            3'b000 : 
              begin
                instr_oA = {2'b0, instr_iA[10:7], instr_iA[12:11], instr_iA[5], instr_iA[6], 2'b00, 5'h02, 3'b000, 2'b01, instr_iA[4:2], {OPCODE_OP_IMM}};
                if (instr_iA[12:5]==8'b0)
                  illegal_instr_oA = 1'b1;

              end
            3'b010 : 
              begin
                instr_oA = {5'b0, instr_iA[5], instr_iA[12:10], instr_iA[6], 2'b00, 2'b01, instr_iA[9:7], 3'b010, 2'b01, instr_iA[4:2], {OPCODE_LOAD}};
              end
            3'b110 : 
              begin
                instr_oA = {5'b0, instr_iA[5], instr_iA[12], 2'b01, instr_iA[4:2], 2'b01, instr_iA[9:7], 3'b010, instr_iA[11:10], instr_iA[6], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b100, 3'b101, 3'b111 : 
              begin
                illegal_instr_oA = 1'b1;
              end
            default : 
              begin
                illegal_instr_oA = 1'b1;
              end
          endcase
        end
      2'b01 : 
        begin
          unique case (instr_iA[15:13])
            3'b000 : 
              begin
                instr_oA = {{ 6 {instr_iA[12]} } , instr_iA[12], instr_iA[6:2], instr_iA[11:7], 3'b0, instr_iA[11:7], {OPCODE_OP_IMM}};
              end
            3'b001, 3'b101 : 
              begin
                instr_oA = {instr_iA[12], instr_iA[8], instr_iA[10:9], instr_iA[6], instr_iA[7], instr_iA[2], instr_iA[11], instr_iA[5:3], { 9 {instr_iA[12]} } , 4'b0, ~instr_iA[15], {OPCODE_JAL}};
              end
            3'b010 : 
              begin
                instr_oA = {{ 6 {instr_iA[12]} } , instr_iA[12], instr_iA[6:2], 5'b0, 3'b0, instr_iA[11:7], {OPCODE_OP_IMM}};
              end
            3'b011 : 
              begin
                instr_oA = {{ 15 {instr_iA[12]} } , instr_iA[6:2], instr_iA[11:7], {OPCODE_LUI}};
                if (instr_iA[11:7]==5'h02)
                  begin
                    instr_oA = {{ 3 {instr_iA[12]} } , instr_iA[4:3], instr_iA[5], instr_iA[2], instr_iA[6], 4'b0, 5'h02, 3'b000, 5'h02, {OPCODE_OP_IMM}};
                  end

                if ({instr_iA[12], instr_iA[6:2]}==6'b0)
                  illegal_instr_oA = 1'b1;

              end
            3'b100 : 
              begin
                unique case (instr_iA[11:10])
                  2'b00, 2'b01 : 
                    begin
                      instr_oA = {1'b0, instr_iA[10], 5'b0, instr_iA[6:2], 2'b01, instr_iA[9:7], 3'b101, 2'b01, instr_iA[9:7], {OPCODE_OP_IMM}};
                      if (instr_iA[12]==1'b1)
                        illegal_instr_oA = 1'b1;

                    end
                  2'b10 : 
                    begin
                      instr_oA = {{ 6 {instr_iA[12]} } , instr_iA[12], instr_iA[6:2], 2'b01, instr_iA[9:7], 3'b111, 2'b01, instr_iA[9:7], {OPCODE_OP_IMM}};
                    end
                  2'b11 : 
                    begin
                      unique case ({instr_iA[12], instr_iA[6:5]})
                        3'b000 : 
                          begin
                            instr_oA = {2'b01, 5'b0, 2'b01, instr_iA[4:2], 2'b01, instr_iA[9:7], 3'b000, 2'b01, instr_iA[9:7], {OPCODE_OP}};
                          end
                        3'b001 : 
                          begin
                            instr_oA = {7'b0, 2'b01, instr_iA[4:2], 2'b01, instr_iA[9:7], 3'b100, 2'b01, instr_iA[9:7], {OPCODE_OP}};
                          end
                        3'b010 : 
                          begin
                            instr_oA = {7'b0, 2'b01, instr_iA[4:2], 2'b01, instr_iA[9:7], 3'b110, 2'b01, instr_iA[9:7], {OPCODE_OP}};
                          end
                        3'b011 : 
                          begin
                            instr_oA = {7'b0, 2'b01, instr_iA[4:2], 2'b01, instr_iA[9:7], 3'b111, 2'b01, instr_iA[9:7], {OPCODE_OP}};
                          end
                        3'b100, 3'b101, 3'b110, 3'b111 : 
                          begin
                            illegal_instr_oA = 1'b1;
                          end
                        default : 
                          begin
                            illegal_instr_oA = 1'b1;
                          end
                      endcase
                    end
                  default : 
                    begin
                      illegal_instr_oA = 1'b1;
                    end
                endcase
              end
            3'b110, 3'b111 : 
              begin
                instr_oA = {{ 4 {instr_iA[12]} } , instr_iA[6:5], instr_iA[2], 5'b0, 2'b01, instr_iA[9:7], 2'b00, instr_iA[13], instr_iA[11:10], instr_iA[4:3], instr_iA[12], {OPCODE_BRANCH}};
              end
            default : 
              begin
                illegal_instr_oA = 1'b1;
              end
          endcase
        end
      2'b10 : 
        begin
          unique case (instr_iA[15:13])
            3'b000 : 
              begin
                instr_oA = {7'b0, instr_iA[6:2], instr_iA[11:7], 3'b001, instr_iA[11:7], {OPCODE_OP_IMM}};
                if (instr_iA[12]==1'b1)
                  illegal_instr_oA = 1'b1;

              end
            3'b010 : 
              begin
                instr_oA = {4'b0, instr_iA[3:2], instr_iA[12], instr_iA[6:4], 2'b00, 5'h02, 3'b010, instr_iA[11:7], OPCODE_LOAD};
                if (instr_iA[11:7]==5'b0)
                  illegal_instr_oA = 1'b1;

              end
            3'b100 : 
              begin
                if (instr_iA[12]==1'b0)
                  begin
                    if (instr_iA[6:2]!=5'b0)
                      begin
                        instr_oA = {7'b0, instr_iA[6:2], 5'b0, 3'b0, instr_iA[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        instr_oA = {12'b0, instr_iA[11:7], 3'b0, 5'b0, {OPCODE_JALR}};
                        if (instr_iA[11:7]==5'b0)
                          illegal_instr_oA = 1'b1;

                      end
                  end
                else
                  begin
                    if (instr_iA[6:2]!=5'b0)
                      begin
                        instr_oA = {7'b0, instr_iA[6:2], instr_iA[11:7], 3'b0, instr_iA[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        if (instr_iA[11:7]==5'b0)
                          begin
                            instr_oA = {32'h00_10_00_73};
                          end
                        else
                          begin
                            instr_oA = {12'b0, instr_iA[11:7], 3'b000, 5'b00001, {OPCODE_JALR}};
                          end
                      end
                  end
              end
            3'b110 : 
              begin
                instr_oA = {4'b0, instr_iA[8:7], instr_iA[12], instr_iA[6:2], 5'h02, 3'b010, instr_iA[11:9], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b101, 3'b111 : 
              begin
                illegal_instr_oA = 1'b1;
              end
            default : 
              begin
                illegal_instr_oA = 1'b1;
              end
          endcase
        end
      2'b11 : ;
      default : 
        begin
          illegal_instr_oA = 1'b1;
        end
    endcase
  end

always_comb
  begin
    instr_oB = instr_iB;
    illegal_instr_oB = 1'b0;
    unique case (instr_iB[1:0])
      2'b00 : 
        begin
          unique case (instr_iB[15:13])
            3'b000 : 
              begin
                instr_oB = {2'b0, instr_iB[10:7], instr_iB[12:11], instr_iB[5], instr_iB[6], 2'b00, 5'h02, 3'b000, 2'b01, instr_iB[4:2], {OPCODE_OP_IMM}};
                if (instr_iB[12:5]==8'b0)
                  illegal_instr_oB = 1'b1;

              end
            3'b010 : 
              begin
                instr_oB = {5'b0, instr_iB[5], instr_iB[12:10], instr_iB[6], 2'b00, 2'b01, instr_iB[9:7], 3'b010, 2'b01, instr_iB[4:2], {OPCODE_LOAD}};
              end
            3'b110 : 
              begin
                instr_oB = {5'b0, instr_iB[5], instr_iB[12], 2'b01, instr_iB[4:2], 2'b01, instr_iB[9:7], 3'b010, instr_iB[11:10], instr_iB[6], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b100, 3'b101, 3'b111 : 
              begin
                illegal_instr_oB = 1'b1;
              end
            default : 
              begin
                illegal_instr_oB = 1'b1;
              end
          endcase
        end
      2'b01 : 
        begin
          unique case (instr_iB[15:13])
            3'b000 : 
              begin
                instr_oB = {{ 6 {instr_iB[12]} } , instr_iB[12], instr_iB[6:2], instr_iB[11:7], 3'b0, instr_iB[11:7], {OPCODE_OP_IMM}};
              end
            3'b001, 3'b101 : 
              begin
                instr_oB = {instr_iB[12], instr_iB[8], instr_iB[10:9], instr_iB[6], instr_iB[7], instr_iB[2], instr_iB[11], instr_iB[5:3], { 9 {instr_iB[12]} } , 4'b0, ~instr_iB[15], {OPCODE_JAL}};
              end
            3'b010 : 
              begin
                instr_oB = {{ 6 {instr_iB[12]} } , instr_iB[12], instr_iB[6:2], 5'b0, 3'b0, instr_iB[11:7], {OPCODE_OP_IMM}};
              end
            3'b011 : 
              begin
                instr_oB = {{ 15 {instr_iB[12]} } , instr_iB[6:2], instr_iB[11:7], {OPCODE_LUI}};
                if (instr_iB[11:7]==5'h02)
                  begin
                    instr_oB = {{ 3 {instr_iB[12]} } , instr_iB[4:3], instr_iB[5], instr_iB[2], instr_iB[6], 4'b0, 5'h02, 3'b000, 5'h02, {OPCODE_OP_IMM}};
                  end

                if ({instr_iB[12], instr_iB[6:2]}==6'b0)
                  illegal_instr_oB = 1'b1;

              end
            3'b100 : 
              begin
                unique case (instr_iB[11:10])
                  2'b00, 2'b01 : 
                    begin
                      instr_oB = {1'b0, instr_iB[10], 5'b0, instr_iB[6:2], 2'b01, instr_iB[9:7], 3'b101, 2'b01, instr_iB[9:7], {OPCODE_OP_IMM}};
                      if (instr_iB[12]==1'b1)
                        illegal_instr_oB = 1'b1;

                    end
                  2'b10 : 
                    begin
                      instr_oB = {{ 6 {instr_iB[12]} } , instr_iB[12], instr_iB[6:2], 2'b01, instr_iB[9:7], 3'b111, 2'b01, instr_iB[9:7], {OPCODE_OP_IMM}};
                    end
                  2'b11 : 
                    begin
                      unique case ({instr_iB[12], instr_iB[6:5]})
                        3'b000 : 
                          begin
                            instr_oB = {2'b01, 5'b0, 2'b01, instr_iB[4:2], 2'b01, instr_iB[9:7], 3'b000, 2'b01, instr_iB[9:7], {OPCODE_OP}};
                          end
                        3'b001 : 
                          begin
                            instr_oB = {7'b0, 2'b01, instr_iB[4:2], 2'b01, instr_iB[9:7], 3'b100, 2'b01, instr_iB[9:7], {OPCODE_OP}};
                          end
                        3'b010 : 
                          begin
                            instr_oB = {7'b0, 2'b01, instr_iB[4:2], 2'b01, instr_iB[9:7], 3'b110, 2'b01, instr_iB[9:7], {OPCODE_OP}};
                          end
                        3'b011 : 
                          begin
                            instr_oB = {7'b0, 2'b01, instr_iB[4:2], 2'b01, instr_iB[9:7], 3'b111, 2'b01, instr_iB[9:7], {OPCODE_OP}};
                          end
                        3'b100, 3'b101, 3'b110, 3'b111 : 
                          begin
                            illegal_instr_oB = 1'b1;
                          end
                        default : 
                          begin
                            illegal_instr_oB = 1'b1;
                          end
                      endcase
                    end
                  default : 
                    begin
                      illegal_instr_oB = 1'b1;
                    end
                endcase
              end
            3'b110, 3'b111 : 
              begin
                instr_oB = {{ 4 {instr_iB[12]} } , instr_iB[6:5], instr_iB[2], 5'b0, 2'b01, instr_iB[9:7], 2'b00, instr_iB[13], instr_iB[11:10], instr_iB[4:3], instr_iB[12], {OPCODE_BRANCH}};
              end
            default : 
              begin
                illegal_instr_oB = 1'b1;
              end
          endcase
        end
      2'b10 : 
        begin
          unique case (instr_iB[15:13])
            3'b000 : 
              begin
                instr_oB = {7'b0, instr_iB[6:2], instr_iB[11:7], 3'b001, instr_iB[11:7], {OPCODE_OP_IMM}};
                if (instr_iB[12]==1'b1)
                  illegal_instr_oB = 1'b1;

              end
            3'b010 : 
              begin
                instr_oB = {4'b0, instr_iB[3:2], instr_iB[12], instr_iB[6:4], 2'b00, 5'h02, 3'b010, instr_iB[11:7], OPCODE_LOAD};
                if (instr_iB[11:7]==5'b0)
                  illegal_instr_oB = 1'b1;

              end
            3'b100 : 
              begin
                if (instr_iB[12]==1'b0)
                  begin
                    if (instr_iB[6:2]!=5'b0)
                      begin
                        instr_oB = {7'b0, instr_iB[6:2], 5'b0, 3'b0, instr_iB[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        instr_oB = {12'b0, instr_iB[11:7], 3'b0, 5'b0, {OPCODE_JALR}};
                        if (instr_iB[11:7]==5'b0)
                          illegal_instr_oB = 1'b1;

                      end
                  end
                else
                  begin
                    if (instr_iB[6:2]!=5'b0)
                      begin
                        instr_oB = {7'b0, instr_iB[6:2], instr_iB[11:7], 3'b0, instr_iB[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        if (instr_iB[11:7]==5'b0)
                          begin
                            instr_oB = {32'h00_10_00_73};
                          end
                        else
                          begin
                            instr_oB = {12'b0, instr_iB[11:7], 3'b000, 5'b00001, {OPCODE_JALR}};
                          end
                      end
                  end
              end
            3'b110 : 
              begin
                instr_oB = {4'b0, instr_iB[8:7], instr_iB[12], instr_iB[6:2], 5'h02, 3'b010, instr_iB[11:9], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b101, 3'b111 : 
              begin
                illegal_instr_oB = 1'b1;
              end
            default : 
              begin
                illegal_instr_oB = 1'b1;
              end
          endcase
        end
      2'b11 : ;
      default : 
        begin
          illegal_instr_oB = 1'b1;
        end
    endcase
  end

always_comb
  begin
    instr_oC = instr_iC;
    illegal_instr_oC = 1'b0;
    unique case (instr_iC[1:0])
      2'b00 : 
        begin
          unique case (instr_iC[15:13])
            3'b000 : 
              begin
                instr_oC = {2'b0, instr_iC[10:7], instr_iC[12:11], instr_iC[5], instr_iC[6], 2'b00, 5'h02, 3'b000, 2'b01, instr_iC[4:2], {OPCODE_OP_IMM}};
                if (instr_iC[12:5]==8'b0)
                  illegal_instr_oC = 1'b1;

              end
            3'b010 : 
              begin
                instr_oC = {5'b0, instr_iC[5], instr_iC[12:10], instr_iC[6], 2'b00, 2'b01, instr_iC[9:7], 3'b010, 2'b01, instr_iC[4:2], {OPCODE_LOAD}};
              end
            3'b110 : 
              begin
                instr_oC = {5'b0, instr_iC[5], instr_iC[12], 2'b01, instr_iC[4:2], 2'b01, instr_iC[9:7], 3'b010, instr_iC[11:10], instr_iC[6], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b100, 3'b101, 3'b111 : 
              begin
                illegal_instr_oC = 1'b1;
              end
            default : 
              begin
                illegal_instr_oC = 1'b1;
              end
          endcase
        end
      2'b01 : 
        begin
          unique case (instr_iC[15:13])
            3'b000 : 
              begin
                instr_oC = {{ 6 {instr_iC[12]} } , instr_iC[12], instr_iC[6:2], instr_iC[11:7], 3'b0, instr_iC[11:7], {OPCODE_OP_IMM}};
              end
            3'b001, 3'b101 : 
              begin
                instr_oC = {instr_iC[12], instr_iC[8], instr_iC[10:9], instr_iC[6], instr_iC[7], instr_iC[2], instr_iC[11], instr_iC[5:3], { 9 {instr_iC[12]} } , 4'b0, ~instr_iC[15], {OPCODE_JAL}};
              end
            3'b010 : 
              begin
                instr_oC = {{ 6 {instr_iC[12]} } , instr_iC[12], instr_iC[6:2], 5'b0, 3'b0, instr_iC[11:7], {OPCODE_OP_IMM}};
              end
            3'b011 : 
              begin
                instr_oC = {{ 15 {instr_iC[12]} } , instr_iC[6:2], instr_iC[11:7], {OPCODE_LUI}};
                if (instr_iC[11:7]==5'h02)
                  begin
                    instr_oC = {{ 3 {instr_iC[12]} } , instr_iC[4:3], instr_iC[5], instr_iC[2], instr_iC[6], 4'b0, 5'h02, 3'b000, 5'h02, {OPCODE_OP_IMM}};
                  end

                if ({instr_iC[12], instr_iC[6:2]}==6'b0)
                  illegal_instr_oC = 1'b1;

              end
            3'b100 : 
              begin
                unique case (instr_iC[11:10])
                  2'b00, 2'b01 : 
                    begin
                      instr_oC = {1'b0, instr_iC[10], 5'b0, instr_iC[6:2], 2'b01, instr_iC[9:7], 3'b101, 2'b01, instr_iC[9:7], {OPCODE_OP_IMM}};
                      if (instr_iC[12]==1'b1)
                        illegal_instr_oC = 1'b1;

                    end
                  2'b10 : 
                    begin
                      instr_oC = {{ 6 {instr_iC[12]} } , instr_iC[12], instr_iC[6:2], 2'b01, instr_iC[9:7], 3'b111, 2'b01, instr_iC[9:7], {OPCODE_OP_IMM}};
                    end
                  2'b11 : 
                    begin
                      unique case ({instr_iC[12], instr_iC[6:5]})
                        3'b000 : 
                          begin
                            instr_oC = {2'b01, 5'b0, 2'b01, instr_iC[4:2], 2'b01, instr_iC[9:7], 3'b000, 2'b01, instr_iC[9:7], {OPCODE_OP}};
                          end
                        3'b001 : 
                          begin
                            instr_oC = {7'b0, 2'b01, instr_iC[4:2], 2'b01, instr_iC[9:7], 3'b100, 2'b01, instr_iC[9:7], {OPCODE_OP}};
                          end
                        3'b010 : 
                          begin
                            instr_oC = {7'b0, 2'b01, instr_iC[4:2], 2'b01, instr_iC[9:7], 3'b110, 2'b01, instr_iC[9:7], {OPCODE_OP}};
                          end
                        3'b011 : 
                          begin
                            instr_oC = {7'b0, 2'b01, instr_iC[4:2], 2'b01, instr_iC[9:7], 3'b111, 2'b01, instr_iC[9:7], {OPCODE_OP}};
                          end
                        3'b100, 3'b101, 3'b110, 3'b111 : 
                          begin
                            illegal_instr_oC = 1'b1;
                          end
                        default : 
                          begin
                            illegal_instr_oC = 1'b1;
                          end
                      endcase
                    end
                  default : 
                    begin
                      illegal_instr_oC = 1'b1;
                    end
                endcase
              end
            3'b110, 3'b111 : 
              begin
                instr_oC = {{ 4 {instr_iC[12]} } , instr_iC[6:5], instr_iC[2], 5'b0, 2'b01, instr_iC[9:7], 2'b00, instr_iC[13], instr_iC[11:10], instr_iC[4:3], instr_iC[12], {OPCODE_BRANCH}};
              end
            default : 
              begin
                illegal_instr_oC = 1'b1;
              end
          endcase
        end
      2'b10 : 
        begin
          unique case (instr_iC[15:13])
            3'b000 : 
              begin
                instr_oC = {7'b0, instr_iC[6:2], instr_iC[11:7], 3'b001, instr_iC[11:7], {OPCODE_OP_IMM}};
                if (instr_iC[12]==1'b1)
                  illegal_instr_oC = 1'b1;

              end
            3'b010 : 
              begin
                instr_oC = {4'b0, instr_iC[3:2], instr_iC[12], instr_iC[6:4], 2'b00, 5'h02, 3'b010, instr_iC[11:7], OPCODE_LOAD};
                if (instr_iC[11:7]==5'b0)
                  illegal_instr_oC = 1'b1;

              end
            3'b100 : 
              begin
                if (instr_iC[12]==1'b0)
                  begin
                    if (instr_iC[6:2]!=5'b0)
                      begin
                        instr_oC = {7'b0, instr_iC[6:2], 5'b0, 3'b0, instr_iC[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        instr_oC = {12'b0, instr_iC[11:7], 3'b0, 5'b0, {OPCODE_JALR}};
                        if (instr_iC[11:7]==5'b0)
                          illegal_instr_oC = 1'b1;

                      end
                  end
                else
                  begin
                    if (instr_iC[6:2]!=5'b0)
                      begin
                        instr_oC = {7'b0, instr_iC[6:2], instr_iC[11:7], 3'b0, instr_iC[11:7], {OPCODE_OP}};
                      end
                    else
                      begin
                        if (instr_iC[11:7]==5'b0)
                          begin
                            instr_oC = {32'h00_10_00_73};
                          end
                        else
                          begin
                            instr_oC = {12'b0, instr_iC[11:7], 3'b000, 5'b00001, {OPCODE_JALR}};
                          end
                      end
                  end
              end
            3'b110 : 
              begin
                instr_oC = {4'b0, instr_iC[8:7], instr_iC[12], instr_iC[6:2], 5'h02, 3'b010, instr_iC[11:9], 2'b00, {OPCODE_STORE}};
              end
            3'b001, 3'b011, 3'b101, 3'b111 : 
              begin
                illegal_instr_oC = 1'b1;
              end
            default : 
              begin
                illegal_instr_oC = 1'b1;
              end
          endcase
        end
      2'b11 : ;
      default : 
        begin
          illegal_instr_oC = 1'b1;
        end
    endcase
  end
assign is_compressed_oA =  (instr_iA[1:0]!=2'b11) ;
assign is_compressed_oB =  (instr_iB[1:0]!=2'b11) ;
assign is_compressed_oC =  (instr_iC[1:0]!=2'b11) ;
endmodule

