/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_id_stageTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:13                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_id_stage.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc ( M tmrg_src/cve2_id_stage.sv) *
 *           Modification time : 2025-11-12 14:35:26.192271                                         *
 *           File Size         : 29920                                                              *
 *           MD5 hash          : fe6edb974b6736a3cbff00af7ab9b971                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_id_stageTMR #(
  parameter bit RV32E = 0,
  parameter cve2_pkg::rv32m_e RV32M = cve2_pkg::RV32MFast,
  parameter cve2_pkg::rv32b_e RV32B = cve2_pkg::RV32BNone
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic fetch_enable_iA,
  input logic fetch_enable_iB,
  input logic fetch_enable_iC,
  output logic ctrl_busy_oA,
  output logic ctrl_busy_oB,
  output logic ctrl_busy_oC,
  output logic illegal_insn_oA,
  output logic illegal_insn_oB,
  output logic illegal_insn_oC,
  input logic instr_valid_iA,
  input logic instr_valid_iB,
  input logic instr_valid_iC,
  input logic [31:0] instr_rdata_iA,
  input logic [31:0] instr_rdata_iB,
  input logic [31:0] instr_rdata_iC,
  input logic [31:0] instr_rdata_alu_iA,
  input logic [31:0] instr_rdata_alu_iB,
  input logic [31:0] instr_rdata_alu_iC,
  input logic [15:0] instr_rdata_c_iA,
  input logic [15:0] instr_rdata_c_iB,
  input logic [15:0] instr_rdata_c_iC,
  input logic instr_is_compressed_iA,
  input logic instr_is_compressed_iB,
  input logic instr_is_compressed_iC,
  output logic instr_req_oA,
  output logic instr_req_oB,
  output logic instr_req_oC,
  output logic instr_first_cycle_id_oA,
  output logic instr_first_cycle_id_oB,
  output logic instr_first_cycle_id_oC,
  output logic instr_valid_clear_oA,
  output logic instr_valid_clear_oB,
  output logic instr_valid_clear_oC,
  output logic id_in_ready_oA,
  output logic id_in_ready_oB,
  output logic id_in_ready_oC,
  input logic branch_decision_iA,
  input logic branch_decision_iB,
  input logic branch_decision_iC,
  output logic pc_set_oA,
  output logic pc_set_oB,
  output logic pc_set_oC,
  output cve2_pkg::pc_sel_e pc_mux_oA,
  output cve2_pkg::pc_sel_e pc_mux_oB,
  output cve2_pkg::pc_sel_e pc_mux_oC,
  output cve2_pkg::exc_pc_sel_e exc_pc_mux_oA,
  output cve2_pkg::exc_pc_sel_e exc_pc_mux_oB,
  output cve2_pkg::exc_pc_sel_e exc_pc_mux_oC,
  output cve2_pkg::exc_cause_e exc_cause_oA,
  output cve2_pkg::exc_cause_e exc_cause_oB,
  output cve2_pkg::exc_cause_e exc_cause_oC,
  input logic illegal_c_insn_iA,
  input logic illegal_c_insn_iB,
  input logic illegal_c_insn_iC,
  input logic instr_fetch_err_iA,
  input logic instr_fetch_err_iB,
  input logic instr_fetch_err_iC,
  input logic instr_fetch_err_plus2_iA,
  input logic instr_fetch_err_plus2_iB,
  input logic instr_fetch_err_plus2_iC,
  input logic [31:0] pc_id_iA,
  input logic [31:0] pc_id_iB,
  input logic [31:0] pc_id_iC,
  input logic ex_valid_iA,
  input logic ex_valid_iB,
  input logic ex_valid_iC,
  input logic lsu_resp_valid_iA,
  input logic lsu_resp_valid_iB,
  input logic lsu_resp_valid_iC,
  output cve2_pkg::alu_op_e alu_operator_ex_oA,
  output cve2_pkg::alu_op_e alu_operator_ex_oB,
  output cve2_pkg::alu_op_e alu_operator_ex_oC,
  output logic [31:0] alu_operand_a_ex_oA,
  output logic [31:0] alu_operand_a_ex_oB,
  output logic [31:0] alu_operand_a_ex_oC,
  output logic [31:0] alu_operand_b_ex_oA,
  output logic [31:0] alu_operand_b_ex_oB,
  output logic [31:0] alu_operand_b_ex_oC,
  input logic [1:0] imd_val_we_ex_iA,
  input logic [1:0] imd_val_we_ex_iB,
  input logic [1:0] imd_val_we_ex_iC,
  input logic [33:0] imd_val_d_ex_iA [2],
  input logic [33:0] imd_val_d_ex_iB [2],
  input logic [33:0] imd_val_d_ex_iC [2],
  output logic [33:0] imd_val_q_ex_oA [2],
  output logic [33:0] imd_val_q_ex_oB [2],
  output logic [33:0] imd_val_q_ex_oC [2],
  output logic mult_en_ex_oA,
  output logic mult_en_ex_oB,
  output logic mult_en_ex_oC,
  output logic div_en_ex_oA,
  output logic div_en_ex_oB,
  output logic div_en_ex_oC,
  output logic mult_sel_ex_oA,
  output logic mult_sel_ex_oB,
  output logic mult_sel_ex_oC,
  output logic div_sel_ex_oA,
  output logic div_sel_ex_oB,
  output logic div_sel_ex_oC,
  output cve2_pkg::md_op_e multdiv_operator_ex_oA,
  output cve2_pkg::md_op_e multdiv_operator_ex_oB,
  output cve2_pkg::md_op_e multdiv_operator_ex_oC,
  output logic [1:0] multdiv_signed_mode_ex_oA,
  output logic [1:0] multdiv_signed_mode_ex_oB,
  output logic [1:0] multdiv_signed_mode_ex_oC,
  output logic [31:0] multdiv_operand_a_ex_oA,
  output logic [31:0] multdiv_operand_a_ex_oB,
  output logic [31:0] multdiv_operand_a_ex_oC,
  output logic [31:0] multdiv_operand_b_ex_oA,
  output logic [31:0] multdiv_operand_b_ex_oB,
  output logic [31:0] multdiv_operand_b_ex_oC,
  output logic csr_access_oA,
  output logic csr_access_oB,
  output logic csr_access_oC,
  output cve2_pkg::csr_op_e csr_op_oA,
  output cve2_pkg::csr_op_e csr_op_oB,
  output cve2_pkg::csr_op_e csr_op_oC,
  output logic csr_op_en_oA,
  output logic csr_op_en_oB,
  output logic csr_op_en_oC,
  output logic csr_save_if_oA,
  output logic csr_save_if_oB,
  output logic csr_save_if_oC,
  output logic csr_save_id_oA,
  output logic csr_save_id_oB,
  output logic csr_save_id_oC,
  output logic csr_restore_mret_id_oA,
  output logic csr_restore_mret_id_oB,
  output logic csr_restore_mret_id_oC,
  output logic csr_restore_dret_id_oA,
  output logic csr_restore_dret_id_oB,
  output logic csr_restore_dret_id_oC,
  output logic csr_save_cause_oA,
  output logic csr_save_cause_oB,
  output logic csr_save_cause_oC,
  output logic [31:0] csr_mtval_oA,
  output logic [31:0] csr_mtval_oB,
  output logic [31:0] csr_mtval_oC,
  input cve2_pkg::priv_lvl_e priv_mode_iA,
  input cve2_pkg::priv_lvl_e priv_mode_iB,
  input cve2_pkg::priv_lvl_e priv_mode_iC,
  input logic csr_mstatus_tw_iA,
  input logic csr_mstatus_tw_iB,
  input logic csr_mstatus_tw_iC,
  input logic illegal_csr_insn_iA,
  input logic illegal_csr_insn_iB,
  input logic illegal_csr_insn_iC,
  output logic lsu_req_oA,
  output logic lsu_req_oB,
  output logic lsu_req_oC,
  output logic lsu_we_oA,
  output logic lsu_we_oB,
  output logic lsu_we_oC,
  output logic [1:0] lsu_type_oA,
  output logic [1:0] lsu_type_oB,
  output logic [1:0] lsu_type_oC,
  output logic lsu_sign_ext_oA,
  output logic lsu_sign_ext_oB,
  output logic lsu_sign_ext_oC,
  output logic [31:0] lsu_wdata_oA,
  output logic [31:0] lsu_wdata_oB,
  output logic [31:0] lsu_wdata_oC,
  input logic lsu_addr_incr_req_iA,
  input logic lsu_addr_incr_req_iB,
  input logic lsu_addr_incr_req_iC,
  input logic [31:0] lsu_addr_last_iA,
  input logic [31:0] lsu_addr_last_iB,
  input logic [31:0] lsu_addr_last_iC,
  input logic csr_mstatus_mie_iA,
  input logic csr_mstatus_mie_iB,
  input logic csr_mstatus_mie_iC,
  input logic irq_pending_iA,
  input logic irq_pending_iB,
  input logic irq_pending_iC,
  input cve2_pkg::irqs_t irqs_iA,
  input cve2_pkg::irqs_t irqs_iB,
  input cve2_pkg::irqs_t irqs_iC,
  input logic irq_nm_iA,
  input logic irq_nm_iB,
  input logic irq_nm_iC,
  output logic nmi_mode_oA,
  output logic nmi_mode_oB,
  output logic nmi_mode_oC,
  input logic lsu_load_err_iA,
  input logic lsu_load_err_iB,
  input logic lsu_load_err_iC,
  input logic lsu_store_err_iA,
  input logic lsu_store_err_iB,
  input logic lsu_store_err_iC,
  output logic debug_mode_oA,
  output logic debug_mode_oB,
  output logic debug_mode_oC,
  output cve2_pkg::dbg_cause_e debug_cause_oA,
  output cve2_pkg::dbg_cause_e debug_cause_oB,
  output cve2_pkg::dbg_cause_e debug_cause_oC,
  output logic debug_csr_save_oA,
  output logic debug_csr_save_oB,
  output logic debug_csr_save_oC,
  input logic debug_req_iA,
  input logic debug_req_iB,
  input logic debug_req_iC,
  input logic debug_single_step_iA,
  input logic debug_single_step_iB,
  input logic debug_single_step_iC,
  input logic debug_ebreakm_iA,
  input logic debug_ebreakm_iB,
  input logic debug_ebreakm_iC,
  input logic debug_ebreaku_iA,
  input logic debug_ebreaku_iB,
  input logic debug_ebreaku_iC,
  input logic trigger_match_iA,
  input logic trigger_match_iB,
  input logic trigger_match_iC,
  input logic [31:0] result_ex_iA,
  input logic [31:0] result_ex_iB,
  input logic [31:0] result_ex_iC,
  input logic [31:0] csr_rdata_iA,
  input logic [31:0] csr_rdata_iB,
  input logic [31:0] csr_rdata_iC,
  output logic [4:0] rf_raddr_a_oA,
  output logic [4:0] rf_raddr_a_oB,
  output logic [4:0] rf_raddr_a_oC,
  input logic [31:0] rf_rdata_a_iA,
  input logic [31:0] rf_rdata_a_iB,
  input logic [31:0] rf_rdata_a_iC,
  output logic [4:0] rf_raddr_b_oA,
  output logic [4:0] rf_raddr_b_oB,
  output logic [4:0] rf_raddr_b_oC,
  input logic [31:0] rf_rdata_b_iA,
  input logic [31:0] rf_rdata_b_iB,
  input logic [31:0] rf_rdata_b_iC,
  output logic rf_ren_a_oA,
  output logic rf_ren_a_oB,
  output logic rf_ren_a_oC,
  output logic rf_ren_b_oA,
  output logic rf_ren_b_oB,
  output logic rf_ren_b_oC,
  output logic [4:0] rf_waddr_id_oA,
  output logic [4:0] rf_waddr_id_oB,
  output logic [4:0] rf_waddr_id_oC,
  output logic [31:0] rf_wdata_id_oA,
  output logic [31:0] rf_wdata_id_oB,
  output logic [31:0] rf_wdata_id_oC,
  output logic rf_we_id_oA,
  output logic rf_we_id_oB,
  output logic rf_we_id_oC,
  output logic en_wb_oA,
  output logic en_wb_oB,
  output logic en_wb_oC,
  output logic instr_perf_count_id_oA,
  output logic instr_perf_count_id_oB,
  output logic instr_perf_count_id_oC,
  output logic perf_jump_oA,
  output logic perf_jump_oB,
  output logic perf_jump_oC,
  output logic perf_branch_oA,
  output logic perf_branch_oB,
  output logic perf_branch_oC,
  output logic perf_tbranch_oA,
  output logic perf_tbranch_oB,
  output logic perf_tbranch_oC,
  output logic perf_dside_wait_oA,
  output logic perf_dside_wait_oB,
  output logic perf_dside_wait_oC,
  output logic perf_wfi_wait_oA,
  output logic perf_wfi_wait_oB,
  output logic perf_wfi_wait_oC,
  output logic perf_div_wait_oA,
  output logic perf_div_wait_oB,
  output logic perf_div_wait_oC,
  output logic instr_id_done_oA,
  output logic instr_id_done_oB,
  output logic instr_id_done_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import cve2_pkg::*;
typedef enum logic { FIRST_CYCLE, MULTI_CYCLE } id_fsm_e;
wire id_fsm_qTmrErrorC;
wire decoder_itmrErrorC;
wire controller_itmrErrorC;
wire branch_set_raw_qTmrErrorC;
wire branch_jump_set_done_qTmrErrorC;
wire id_fsm_qTmrErrorB;
wire decoder_itmrErrorB;
wire controller_itmrErrorB;
wire branch_set_raw_qTmrErrorB;
wire branch_jump_set_done_qTmrErrorB;
wire id_fsm_qTmrErrorA;
wire decoder_itmrErrorA;
wire controller_itmrErrorA;
wire branch_set_raw_qTmrErrorA;
wire branch_jump_set_done_qTmrErrorA;
logic illegal_insn_decA;
logic illegal_insn_decB;
logic illegal_insn_decC;
logic ebrk_insnA;
logic ebrk_insnB;
logic ebrk_insnC;
logic mret_insn_decA;
logic mret_insn_decB;
logic mret_insn_decC;
logic dret_insn_decA;
logic dret_insn_decB;
logic dret_insn_decC;
logic ecall_insn_decA;
logic ecall_insn_decB;
logic ecall_insn_decC;
logic wfi_insn_decA;
logic wfi_insn_decB;
logic wfi_insn_decC;
logic branch_in_decA;
logic branch_in_decB;
logic branch_in_decC;
logic branch_setA;
logic branch_setB;
logic branch_setC;
logic branch_set_rawA;
logic branch_set_rawB;
logic branch_set_rawC;
logic branch_set_raw_dA;
logic branch_set_raw_dB;
logic branch_set_raw_dC;
logic branch_jump_set_done_qA;
logic branch_jump_set_done_qB;
logic branch_jump_set_done_qC;
logic branch_jump_set_done_dA;
logic branch_jump_set_done_dB;
logic branch_jump_set_done_dC;
logic branch_jump_set_done_qVotedA;
logic branch_jump_set_done_qVotedB;
logic branch_jump_set_done_qVotedC;
logic jump_in_decA;
logic jump_in_decB;
logic jump_in_decC;
logic jump_set_decA;
logic jump_set_decB;
logic jump_set_decC;
logic jump_setA;
logic jump_setB;
logic jump_setC;
logic jump_set_rawA;
logic jump_set_rawB;
logic jump_set_rawC;
logic instr_first_cycleA;
logic instr_first_cycleB;
logic instr_first_cycleC;
logic instr_executing_specA;
logic instr_executing_specB;
logic instr_executing_specC;
logic instr_executingA;
logic instr_executingB;
logic instr_executingC;
logic instr_doneA;
logic instr_doneB;
logic instr_doneC;
logic controller_runA;
logic controller_runB;
logic controller_runC;
logic stall_memA;
logic stall_memB;
logic stall_memC;
logic stall_multdivA;
logic stall_multdivB;
logic stall_multdivC;
logic stall_branchA;
logic stall_branchB;
logic stall_branchC;
logic stall_jumpA;
logic stall_jumpB;
logic stall_jumpC;
logic stall_idA;
logic stall_idB;
logic stall_idC;
logic flush_idA;
logic flush_idB;
logic flush_idC;
logic multicycle_doneA;
logic multicycle_doneB;
logic multicycle_doneC;
logic [31:0] imm_i_typeA;
logic [31:0] imm_i_typeB;
logic [31:0] imm_i_typeC;
logic [31:0] imm_s_typeA;
logic [31:0] imm_s_typeB;
logic [31:0] imm_s_typeC;
logic [31:0] imm_b_typeA;
logic [31:0] imm_b_typeB;
logic [31:0] imm_b_typeC;
logic [31:0] imm_u_typeA;
logic [31:0] imm_u_typeB;
logic [31:0] imm_u_typeC;
logic [31:0] imm_j_typeA;
logic [31:0] imm_j_typeB;
logic [31:0] imm_j_typeC;
logic [31:0] zimm_rs1_typeA;
logic [31:0] zimm_rs1_typeB;
logic [31:0] zimm_rs1_typeC;
logic [31:0] imm_aA;
logic [31:0] imm_aB;
logic [31:0] imm_aC;
logic [31:0] imm_bA;
logic [31:0] imm_bB;
logic [31:0] imm_bC;
rf_wd_sel_e rf_wdata_selA;
rf_wd_sel_e rf_wdata_selB;
rf_wd_sel_e rf_wdata_selC;
logic rf_we_decA;
logic rf_we_decB;
logic rf_we_decC;
logic rf_we_rawA;
logic rf_we_rawB;
logic rf_we_rawC;
logic rf_ren_aA;
logic rf_ren_aB;
logic rf_ren_aC;
logic rf_ren_bA;
logic rf_ren_bB;
logic rf_ren_bC;
logic rf_ren_a_decA;
logic rf_ren_a_decB;
logic rf_ren_a_decC;
logic rf_ren_b_decA;
logic rf_ren_b_decB;
logic rf_ren_b_decC;
assign rf_ren_aA = instr_valid_iA&~instr_fetch_err_iA&~illegal_insn_oA&rf_ren_a_decA;
assign rf_ren_aB = instr_valid_iB&~instr_fetch_err_iB&~illegal_insn_oB&rf_ren_a_decB;
assign rf_ren_aC = instr_valid_iC&~instr_fetch_err_iC&~illegal_insn_oC&rf_ren_a_decC;
assign rf_ren_bA = instr_valid_iA&~instr_fetch_err_iA&~illegal_insn_oA&rf_ren_b_decA;
assign rf_ren_bB = instr_valid_iB&~instr_fetch_err_iB&~illegal_insn_oB&rf_ren_b_decB;
assign rf_ren_bC = instr_valid_iC&~instr_fetch_err_iC&~illegal_insn_oC&rf_ren_b_decC;
assign rf_ren_a_oA = rf_ren_aA;
assign rf_ren_a_oB = rf_ren_aB;
assign rf_ren_a_oC = rf_ren_aC;
assign rf_ren_b_oA = rf_ren_bA;
assign rf_ren_b_oB = rf_ren_bB;
assign rf_ren_b_oC = rf_ren_bC;
logic [31:0] rf_rdata_a_fwdA;
logic [31:0] rf_rdata_a_fwdB;
logic [31:0] rf_rdata_a_fwdC;
logic [31:0] rf_rdata_b_fwdA;
logic [31:0] rf_rdata_b_fwdB;
logic [31:0] rf_rdata_b_fwdC;
alu_op_e alu_operatorA;
alu_op_e alu_operatorB;
alu_op_e alu_operatorC;
op_a_sel_e alu_op_a_mux_selA;
op_a_sel_e alu_op_a_mux_selB;
op_a_sel_e alu_op_a_mux_selC;
op_a_sel_e alu_op_a_mux_sel_decA;
op_a_sel_e alu_op_a_mux_sel_decB;
op_a_sel_e alu_op_a_mux_sel_decC;
op_b_sel_e alu_op_b_mux_selA;
op_b_sel_e alu_op_b_mux_selB;
op_b_sel_e alu_op_b_mux_selC;
op_b_sel_e alu_op_b_mux_sel_decA;
op_b_sel_e alu_op_b_mux_sel_decB;
op_b_sel_e alu_op_b_mux_sel_decC;
logic alu_multicycle_decA;
logic alu_multicycle_decB;
logic alu_multicycle_decC;
logic stall_aluA;
logic stall_aluB;
logic stall_aluC;
logic [33:0] imd_val_qA [2];
logic [33:0] imd_val_qB [2];
logic [33:0] imd_val_qC [2];
logic [33:0] imd_val_qVotedA [2];
logic [33:0] imd_val_qVotedB [2];
logic [33:0] imd_val_qVotedC [2];
assign imd_val_qVotedA[0] = imd_val_qA[0];
assign imd_val_qVotedB[0] = imd_val_qB[0];
assign imd_val_qVotedC[0] = imd_val_qC[0];
assign imd_val_qVotedA[1] = imd_val_qA[1];
assign imd_val_qVotedB[1] = imd_val_qB[1];
assign imd_val_qVotedC[1] = imd_val_qC[1];
imm_a_sel_e imm_a_mux_selA;
imm_a_sel_e imm_a_mux_selB;
imm_a_sel_e imm_a_mux_selC;
imm_b_sel_e imm_b_mux_selA;
imm_b_sel_e imm_b_mux_selB;
imm_b_sel_e imm_b_mux_selC;
imm_b_sel_e imm_b_mux_sel_decA;
imm_b_sel_e imm_b_mux_sel_decB;
imm_b_sel_e imm_b_mux_sel_decC;
logic mult_en_idA;
logic mult_en_idB;
logic mult_en_idC;
logic mult_en_decA;
logic mult_en_decB;
logic mult_en_decC;
logic div_en_idA;
logic div_en_idB;
logic div_en_idC;
logic div_en_decA;
logic div_en_decB;
logic div_en_decC;
logic multdiv_en_decA;
logic multdiv_en_decB;
logic multdiv_en_decC;
md_op_e multdiv_operatorA;
md_op_e multdiv_operatorB;
md_op_e multdiv_operatorC;
logic [1:0] multdiv_signed_modeA;
logic [1:0] multdiv_signed_modeB;
logic [1:0] multdiv_signed_modeC;
logic lsu_weA;
logic lsu_weB;
logic lsu_weC;
logic [1:0] lsu_typeA;
logic [1:0] lsu_typeB;
logic [1:0] lsu_typeC;
logic lsu_sign_extA;
logic lsu_sign_extB;
logic lsu_sign_extC;
logic lsu_reqA;
logic lsu_reqB;
logic lsu_reqC;
logic lsu_req_decA;
logic lsu_req_decB;
logic lsu_req_decC;
logic data_req_allowedA;
logic data_req_allowedB;
logic data_req_allowedC;
logic csr_pipe_flushA;
logic csr_pipe_flushB;
logic csr_pipe_flushC;
logic [31:0] alu_operand_aA;
logic [31:0] alu_operand_aB;
logic [31:0] alu_operand_aC;
logic [31:0] alu_operand_bA;
logic [31:0] alu_operand_bB;
logic [31:0] alu_operand_bC;
assign alu_op_a_mux_selA = lsu_addr_incr_req_iA ? OP_A_FWD : alu_op_a_mux_sel_decA;
assign alu_op_a_mux_selB = lsu_addr_incr_req_iB ? OP_A_FWD : alu_op_a_mux_sel_decB;
assign alu_op_a_mux_selC = lsu_addr_incr_req_iC ? OP_A_FWD : alu_op_a_mux_sel_decC;
assign alu_op_b_mux_selA = lsu_addr_incr_req_iA ? OP_B_IMM : alu_op_b_mux_sel_decA;
assign alu_op_b_mux_selB = lsu_addr_incr_req_iB ? OP_B_IMM : alu_op_b_mux_sel_decB;
assign alu_op_b_mux_selC = lsu_addr_incr_req_iC ? OP_B_IMM : alu_op_b_mux_sel_decC;
assign imm_b_mux_selA = lsu_addr_incr_req_iA ? IMM_B_INCR_ADDR : imm_b_mux_sel_decA;
assign imm_b_mux_selB = lsu_addr_incr_req_iB ? IMM_B_INCR_ADDR : imm_b_mux_sel_decB;
assign imm_b_mux_selC = lsu_addr_incr_req_iC ? IMM_B_INCR_ADDR : imm_b_mux_sel_decC;
assign imm_aA = (imm_a_mux_selA==IMM_A_Z) ? zimm_rs1_typeA : '0;
assign imm_aB = (imm_a_mux_selB==IMM_A_Z) ? zimm_rs1_typeB : '0;
assign imm_aC = (imm_a_mux_selC==IMM_A_Z) ? zimm_rs1_typeC : '0;

always_comb
  begin : alu_operand_a_muxA
    unique case (alu_op_a_mux_selA)
      OP_A_REG_A : alu_operand_aA = rf_rdata_a_fwdA;
      OP_A_FWD : alu_operand_aA = lsu_addr_last_iA;
      OP_A_CURRPC : alu_operand_aA = pc_id_iA;
      OP_A_IMM : alu_operand_aA = imm_aA;
      default : alu_operand_aA = pc_id_iA;
    endcase
  end

always_comb
  begin : alu_operand_a_muxB
    unique case (alu_op_a_mux_selB)
      OP_A_REG_A : alu_operand_aB = rf_rdata_a_fwdB;
      OP_A_FWD : alu_operand_aB = lsu_addr_last_iB;
      OP_A_CURRPC : alu_operand_aB = pc_id_iB;
      OP_A_IMM : alu_operand_aB = imm_aB;
      default : alu_operand_aB = pc_id_iB;
    endcase
  end

always_comb
  begin : alu_operand_a_muxC
    unique case (alu_op_a_mux_selC)
      OP_A_REG_A : alu_operand_aC = rf_rdata_a_fwdC;
      OP_A_FWD : alu_operand_aC = lsu_addr_last_iC;
      OP_A_CURRPC : alu_operand_aC = pc_id_iC;
      OP_A_IMM : alu_operand_aC = imm_aC;
      default : alu_operand_aC = pc_id_iC;
    endcase
  end
op_a_sel_e unused_a_mux_selA;
op_a_sel_e unused_a_mux_selB;
op_a_sel_e unused_a_mux_selC;
imm_b_sel_e unused_b_mux_selA;
imm_b_sel_e unused_b_mux_selB;
imm_b_sel_e unused_b_mux_selC;

always_comb
  begin : immediate_b_muxA
    unique case (imm_b_mux_selA)
      IMM_B_I : imm_bA = imm_i_typeA;
      IMM_B_S : imm_bA = imm_s_typeA;
      IMM_B_B : imm_bA = imm_b_typeA;
      IMM_B_U : imm_bA = imm_u_typeA;
      IMM_B_J : imm_bA = imm_j_typeA;
      IMM_B_INCR_PC : imm_bA = instr_is_compressed_iA ? 32'h2 : 32'h4;
      IMM_B_INCR_ADDR : imm_bA = 32'h4;
      default : imm_bA = 32'h4;
    endcase
  end

always_comb
  begin : immediate_b_muxB
    unique case (imm_b_mux_selB)
      IMM_B_I : imm_bB = imm_i_typeB;
      IMM_B_S : imm_bB = imm_s_typeB;
      IMM_B_B : imm_bB = imm_b_typeB;
      IMM_B_U : imm_bB = imm_u_typeB;
      IMM_B_J : imm_bB = imm_j_typeB;
      IMM_B_INCR_PC : imm_bB = instr_is_compressed_iB ? 32'h2 : 32'h4;
      IMM_B_INCR_ADDR : imm_bB = 32'h4;
      default : imm_bB = 32'h4;
    endcase
  end

always_comb
  begin : immediate_b_muxC
    unique case (imm_b_mux_selC)
      IMM_B_I : imm_bC = imm_i_typeC;
      IMM_B_S : imm_bC = imm_s_typeC;
      IMM_B_B : imm_bC = imm_b_typeC;
      IMM_B_U : imm_bC = imm_u_typeC;
      IMM_B_J : imm_bC = imm_j_typeC;
      IMM_B_INCR_PC : imm_bC = instr_is_compressed_iC ? 32'h2 : 32'h4;
      IMM_B_INCR_ADDR : imm_bC = 32'h4;
      default : imm_bC = 32'h4;
    endcase
  end
assign alu_operand_bA = (alu_op_b_mux_selA==OP_B_IMM) ? imm_bA : rf_rdata_b_fwdA;
assign alu_operand_bB = (alu_op_b_mux_selB==OP_B_IMM) ? imm_bB : rf_rdata_b_fwdB;
assign alu_operand_bC = (alu_op_b_mux_selC==OP_B_IMM) ? imm_bC : rf_rdata_b_fwdC;
for(genvar i = 0; i<2; i++)
  begin : gen_intermediate_val_reg

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : intermediate_val_regA
        if (!rst_niA)
          begin
            imd_val_qA[i] <= '0;
          end
        else
          if (imd_val_we_ex_iA[i])
            begin
              imd_val_qA[i] <= imd_val_d_ex_iA[i];
            end

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : intermediate_val_regB
        if (!rst_niB)
          begin
            imd_val_qB[i] <= '0;
          end
        else
          if (imd_val_we_ex_iB[i])
            begin
              imd_val_qB[i] <= imd_val_d_ex_iB[i];
            end

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : intermediate_val_regC
        if (!rst_niC)
          begin
            imd_val_qC[i] <= '0;
          end
        else
          if (imd_val_we_ex_iC[i])
            begin
              imd_val_qC[i] <= imd_val_d_ex_iC[i];
            end

      end
  end
assign imd_val_q_ex_oA = imd_val_qVotedA;
assign imd_val_q_ex_oB = imd_val_qVotedB;
assign imd_val_q_ex_oC = imd_val_qVotedC;
assign rf_we_id_oA = rf_we_rawA&instr_executingA&~illegal_csr_insn_iA;
assign rf_we_id_oB = rf_we_rawB&instr_executingB&~illegal_csr_insn_iB;
assign rf_we_id_oC = rf_we_rawC&instr_executingC&~illegal_csr_insn_iC;

always_comb
  begin : rf_wdata_id_muxA
    unique case (rf_wdata_selA)
      RF_WD_EX : rf_wdata_id_oA = result_ex_iA;
      RF_WD_CSR : rf_wdata_id_oA = csr_rdata_iA;
      default : rf_wdata_id_oA = result_ex_iA;
    endcase
  end

always_comb
  begin : rf_wdata_id_muxB
    unique case (rf_wdata_selB)
      RF_WD_EX : rf_wdata_id_oB = result_ex_iB;
      RF_WD_CSR : rf_wdata_id_oB = csr_rdata_iB;
      default : rf_wdata_id_oB = result_ex_iB;
    endcase
  end

always_comb
  begin : rf_wdata_id_muxC
    unique case (rf_wdata_selC)
      RF_WD_EX : rf_wdata_id_oC = result_ex_iC;
      RF_WD_CSR : rf_wdata_id_oC = csr_rdata_iC;
      default : rf_wdata_id_oC = result_ex_iC;
    endcase
  end

cve2_decoderTMR #(.RV32E(RV32E), .RV32M(RV32M), .RV32B(RV32B)) decoder_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .illegal_insn_oA(illegal_insn_decA),
    .illegal_insn_oB(illegal_insn_decB),
    .illegal_insn_oC(illegal_insn_decC),
    .ebrk_insn_oA(ebrk_insnA),
    .ebrk_insn_oB(ebrk_insnB),
    .ebrk_insn_oC(ebrk_insnC),
    .mret_insn_oA(mret_insn_decA),
    .mret_insn_oB(mret_insn_decB),
    .mret_insn_oC(mret_insn_decC),
    .dret_insn_oA(dret_insn_decA),
    .dret_insn_oB(dret_insn_decB),
    .dret_insn_oC(dret_insn_decC),
    .ecall_insn_oA(ecall_insn_decA),
    .ecall_insn_oB(ecall_insn_decB),
    .ecall_insn_oC(ecall_insn_decC),
    .wfi_insn_oA(wfi_insn_decA),
    .wfi_insn_oB(wfi_insn_decB),
    .wfi_insn_oC(wfi_insn_decC),
    .jump_set_oA(jump_set_decA),
    .jump_set_oB(jump_set_decB),
    .jump_set_oC(jump_set_decC),
    .instr_first_cycle_iA(instr_first_cycleA),
    .instr_first_cycle_iB(instr_first_cycleB),
    .instr_first_cycle_iC(instr_first_cycleC),
    .instr_rdata_iA(instr_rdata_iA),
    .instr_rdata_iB(instr_rdata_iB),
    .instr_rdata_iC(instr_rdata_iC),
    .instr_rdata_alu_iA(instr_rdata_alu_iA),
    .instr_rdata_alu_iB(instr_rdata_alu_iB),
    .instr_rdata_alu_iC(instr_rdata_alu_iC),
    .illegal_c_insn_iA(illegal_c_insn_iA),
    .illegal_c_insn_iB(illegal_c_insn_iB),
    .illegal_c_insn_iC(illegal_c_insn_iC),
    .imm_a_mux_sel_oA(imm_a_mux_selA),
    .imm_a_mux_sel_oB(imm_a_mux_selB),
    .imm_a_mux_sel_oC(imm_a_mux_selC),
    .imm_b_mux_sel_oA(imm_b_mux_sel_decA),
    .imm_b_mux_sel_oB(imm_b_mux_sel_decB),
    .imm_b_mux_sel_oC(imm_b_mux_sel_decC),
    .imm_i_type_oA(imm_i_typeA),
    .imm_i_type_oB(imm_i_typeB),
    .imm_i_type_oC(imm_i_typeC),
    .imm_s_type_oA(imm_s_typeA),
    .imm_s_type_oB(imm_s_typeB),
    .imm_s_type_oC(imm_s_typeC),
    .imm_b_type_oA(imm_b_typeA),
    .imm_b_type_oB(imm_b_typeB),
    .imm_b_type_oC(imm_b_typeC),
    .imm_u_type_oA(imm_u_typeA),
    .imm_u_type_oB(imm_u_typeB),
    .imm_u_type_oC(imm_u_typeC),
    .imm_j_type_oA(imm_j_typeA),
    .imm_j_type_oB(imm_j_typeB),
    .imm_j_type_oC(imm_j_typeC),
    .zimm_rs1_type_oA(zimm_rs1_typeA),
    .zimm_rs1_type_oB(zimm_rs1_typeB),
    .zimm_rs1_type_oC(zimm_rs1_typeC),
    .rf_wdata_sel_oA(rf_wdata_selA),
    .rf_wdata_sel_oB(rf_wdata_selB),
    .rf_wdata_sel_oC(rf_wdata_selC),
    .rf_we_oA(rf_we_decA),
    .rf_we_oB(rf_we_decB),
    .rf_we_oC(rf_we_decC),
    .rf_raddr_a_oA(rf_raddr_a_oA),
    .rf_raddr_a_oB(rf_raddr_a_oB),
    .rf_raddr_a_oC(rf_raddr_a_oC),
    .rf_raddr_b_oA(rf_raddr_b_oA),
    .rf_raddr_b_oB(rf_raddr_b_oB),
    .rf_raddr_b_oC(rf_raddr_b_oC),
    .rf_waddr_oA(rf_waddr_id_oA),
    .rf_waddr_oB(rf_waddr_id_oB),
    .rf_waddr_oC(rf_waddr_id_oC),
    .rf_ren_a_oA(rf_ren_a_decA),
    .rf_ren_a_oB(rf_ren_a_decB),
    .rf_ren_a_oC(rf_ren_a_decC),
    .rf_ren_b_oA(rf_ren_b_decA),
    .rf_ren_b_oB(rf_ren_b_decB),
    .rf_ren_b_oC(rf_ren_b_decC),
    .alu_operator_oA(alu_operatorA),
    .alu_operator_oB(alu_operatorB),
    .alu_operator_oC(alu_operatorC),
    .alu_op_a_mux_sel_oA(alu_op_a_mux_sel_decA),
    .alu_op_a_mux_sel_oB(alu_op_a_mux_sel_decB),
    .alu_op_a_mux_sel_oC(alu_op_a_mux_sel_decC),
    .alu_op_b_mux_sel_oA(alu_op_b_mux_sel_decA),
    .alu_op_b_mux_sel_oB(alu_op_b_mux_sel_decB),
    .alu_op_b_mux_sel_oC(alu_op_b_mux_sel_decC),
    .alu_multicycle_oA(alu_multicycle_decA),
    .alu_multicycle_oB(alu_multicycle_decB),
    .alu_multicycle_oC(alu_multicycle_decC),
    .mult_en_oA(mult_en_decA),
    .mult_en_oB(mult_en_decB),
    .mult_en_oC(mult_en_decC),
    .div_en_oA(div_en_decA),
    .div_en_oB(div_en_decB),
    .div_en_oC(div_en_decC),
    .mult_sel_oA(mult_sel_ex_oA),
    .mult_sel_oB(mult_sel_ex_oB),
    .mult_sel_oC(mult_sel_ex_oC),
    .div_sel_oA(div_sel_ex_oA),
    .div_sel_oB(div_sel_ex_oB),
    .div_sel_oC(div_sel_ex_oC),
    .multdiv_operator_oA(multdiv_operatorA),
    .multdiv_operator_oB(multdiv_operatorB),
    .multdiv_operator_oC(multdiv_operatorC),
    .multdiv_signed_mode_oA(multdiv_signed_modeA),
    .multdiv_signed_mode_oB(multdiv_signed_modeB),
    .multdiv_signed_mode_oC(multdiv_signed_modeC),
    .csr_access_oA(csr_access_oA),
    .csr_access_oB(csr_access_oB),
    .csr_access_oC(csr_access_oC),
    .csr_op_oA(csr_op_oA),
    .csr_op_oB(csr_op_oB),
    .csr_op_oC(csr_op_oC),
    .data_req_oA(lsu_req_decA),
    .data_req_oB(lsu_req_decB),
    .data_req_oC(lsu_req_decC),
    .data_we_oA(lsu_weA),
    .data_we_oB(lsu_weB),
    .data_we_oC(lsu_weC),
    .data_type_oA(lsu_typeA),
    .data_type_oB(lsu_typeB),
    .data_type_oC(lsu_typeC),
    .data_sign_extension_oA(lsu_sign_extA),
    .data_sign_extension_oB(lsu_sign_extB),
    .data_sign_extension_oC(lsu_sign_extC),
    .jump_in_dec_oA(jump_in_decA),
    .jump_in_dec_oB(jump_in_decB),
    .jump_in_dec_oC(jump_in_decC),
    .branch_in_dec_oA(branch_in_decA),
    .branch_in_dec_oB(branch_in_decB),
    .branch_in_dec_oC(branch_in_decC),
    .tmrErrorA(decoder_itmrErrorA),
    .tmrErrorB(decoder_itmrErrorB),
    .tmrErrorC(decoder_itmrErrorC)
  );

always_comb
  begin : csr_pipeline_flushesA
    csr_pipe_flushA = 1'b0;
    if (csr_op_en_oA==1'b1&&(csr_op_oA==CSR_OP_WRITE||csr_op_oA==CSR_OP_SET))
      begin
        if (csr_num_e'(instr_rdata_iA[31:20])==CSR_MSTATUS||csr_num_e'(instr_rdata_iA[31:20])==CSR_MIE||csr_num_e'(instr_rdata_iA[31:20])==CSR_MSECCFG||instr_rdata_iA[31:25]==7'h1D)
          begin
            csr_pipe_flushA = 1'b1;
          end

      end
    else
      if (csr_op_en_oA==1'b1&&csr_op_oA!=CSR_OP_READ)
        begin
          if (csr_num_e'(instr_rdata_iA[31:20])==CSR_DCSR||csr_num_e'(instr_rdata_iA[31:20])==CSR_DPC||csr_num_e'(instr_rdata_iA[31:20])==CSR_DSCRATCH0||csr_num_e'(instr_rdata_iA[31:20])==CSR_DSCRATCH1)
            begin
              csr_pipe_flushA = 1'b1;
            end

        end

  end

always_comb
  begin : csr_pipeline_flushesB
    csr_pipe_flushB = 1'b0;
    if (csr_op_en_oB==1'b1&&(csr_op_oB==CSR_OP_WRITE||csr_op_oB==CSR_OP_SET))
      begin
        if (csr_num_e'(instr_rdata_iB[31:20])==CSR_MSTATUS||csr_num_e'(instr_rdata_iB[31:20])==CSR_MIE||csr_num_e'(instr_rdata_iB[31:20])==CSR_MSECCFG||instr_rdata_iB[31:25]==7'h1D)
          begin
            csr_pipe_flushB = 1'b1;
          end

      end
    else
      if (csr_op_en_oB==1'b1&&csr_op_oB!=CSR_OP_READ)
        begin
          if (csr_num_e'(instr_rdata_iB[31:20])==CSR_DCSR||csr_num_e'(instr_rdata_iB[31:20])==CSR_DPC||csr_num_e'(instr_rdata_iB[31:20])==CSR_DSCRATCH0||csr_num_e'(instr_rdata_iB[31:20])==CSR_DSCRATCH1)
            begin
              csr_pipe_flushB = 1'b1;
            end

        end

  end

always_comb
  begin : csr_pipeline_flushesC
    csr_pipe_flushC = 1'b0;
    if (csr_op_en_oC==1'b1&&(csr_op_oC==CSR_OP_WRITE||csr_op_oC==CSR_OP_SET))
      begin
        if (csr_num_e'(instr_rdata_iC[31:20])==CSR_MSTATUS||csr_num_e'(instr_rdata_iC[31:20])==CSR_MIE||csr_num_e'(instr_rdata_iC[31:20])==CSR_MSECCFG||instr_rdata_iC[31:25]==7'h1D)
          begin
            csr_pipe_flushC = 1'b1;
          end

      end
    else
      if (csr_op_en_oC==1'b1&&csr_op_oC!=CSR_OP_READ)
        begin
          if (csr_num_e'(instr_rdata_iC[31:20])==CSR_DCSR||csr_num_e'(instr_rdata_iC[31:20])==CSR_DPC||csr_num_e'(instr_rdata_iC[31:20])==CSR_DSCRATCH0||csr_num_e'(instr_rdata_iC[31:20])==CSR_DSCRATCH1)
            begin
              csr_pipe_flushC = 1'b1;
            end

        end

  end
assign illegal_insn_oA = instr_valid_iA& (illegal_insn_decA|illegal_csr_insn_iA) ;
assign illegal_insn_oB = instr_valid_iB& (illegal_insn_decB|illegal_csr_insn_iB) ;
assign illegal_insn_oC = instr_valid_iC& (illegal_insn_decC|illegal_csr_insn_iC) ;

cve2_controllerTMR controller_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .fetch_enable_iA(fetch_enable_iA),
    .fetch_enable_iB(fetch_enable_iB),
    .fetch_enable_iC(fetch_enable_iC),
    .ctrl_busy_oA(ctrl_busy_oA),
    .ctrl_busy_oB(ctrl_busy_oB),
    .ctrl_busy_oC(ctrl_busy_oC),
    .illegal_insn_iA(illegal_insn_oA),
    .illegal_insn_iB(illegal_insn_oB),
    .illegal_insn_iC(illegal_insn_oC),
    .ecall_insn_iA(ecall_insn_decA),
    .ecall_insn_iB(ecall_insn_decB),
    .ecall_insn_iC(ecall_insn_decC),
    .mret_insn_iA(mret_insn_decA),
    .mret_insn_iB(mret_insn_decB),
    .mret_insn_iC(mret_insn_decC),
    .dret_insn_iA(dret_insn_decA),
    .dret_insn_iB(dret_insn_decB),
    .dret_insn_iC(dret_insn_decC),
    .wfi_insn_iA(wfi_insn_decA),
    .wfi_insn_iB(wfi_insn_decB),
    .wfi_insn_iC(wfi_insn_decC),
    .ebrk_insn_iA(ebrk_insnA),
    .ebrk_insn_iB(ebrk_insnB),
    .ebrk_insn_iC(ebrk_insnC),
    .csr_pipe_flush_iA(csr_pipe_flushA),
    .csr_pipe_flush_iB(csr_pipe_flushB),
    .csr_pipe_flush_iC(csr_pipe_flushC),
    .instr_valid_iA(instr_valid_iA),
    .instr_valid_iB(instr_valid_iB),
    .instr_valid_iC(instr_valid_iC),
    .instr_iA(instr_rdata_iA),
    .instr_iB(instr_rdata_iB),
    .instr_iC(instr_rdata_iC),
    .instr_compressed_iA(instr_rdata_c_iA),
    .instr_compressed_iB(instr_rdata_c_iB),
    .instr_compressed_iC(instr_rdata_c_iC),
    .instr_is_compressed_iA(instr_is_compressed_iA),
    .instr_is_compressed_iB(instr_is_compressed_iB),
    .instr_is_compressed_iC(instr_is_compressed_iC),
    .instr_fetch_err_iA(instr_fetch_err_iA),
    .instr_fetch_err_iB(instr_fetch_err_iB),
    .instr_fetch_err_iC(instr_fetch_err_iC),
    .instr_fetch_err_plus2_iA(instr_fetch_err_plus2_iA),
    .instr_fetch_err_plus2_iB(instr_fetch_err_plus2_iB),
    .instr_fetch_err_plus2_iC(instr_fetch_err_plus2_iC),
    .pc_id_iA(pc_id_iA),
    .pc_id_iB(pc_id_iB),
    .pc_id_iC(pc_id_iC),
    .instr_valid_clear_oA(instr_valid_clear_oA),
    .instr_valid_clear_oB(instr_valid_clear_oB),
    .instr_valid_clear_oC(instr_valid_clear_oC),
    .id_in_ready_oA(id_in_ready_oA),
    .id_in_ready_oB(id_in_ready_oB),
    .id_in_ready_oC(id_in_ready_oC),
    .controller_run_oA(controller_runA),
    .controller_run_oB(controller_runB),
    .controller_run_oC(controller_runC),
    .instr_req_oA(instr_req_oA),
    .instr_req_oB(instr_req_oB),
    .instr_req_oC(instr_req_oC),
    .pc_set_oA(pc_set_oA),
    .pc_set_oB(pc_set_oB),
    .pc_set_oC(pc_set_oC),
    .pc_mux_oA(pc_mux_oA),
    .pc_mux_oB(pc_mux_oB),
    .pc_mux_oC(pc_mux_oC),
    .exc_pc_mux_oA(exc_pc_mux_oA),
    .exc_pc_mux_oB(exc_pc_mux_oB),
    .exc_pc_mux_oC(exc_pc_mux_oC),
    .exc_cause_oA(exc_cause_oA),
    .exc_cause_oB(exc_cause_oB),
    .exc_cause_oC(exc_cause_oC),
    .lsu_addr_last_iA(lsu_addr_last_iA),
    .lsu_addr_last_iB(lsu_addr_last_iB),
    .lsu_addr_last_iC(lsu_addr_last_iC),
    .load_err_iA(lsu_load_err_iA),
    .load_err_iB(lsu_load_err_iB),
    .load_err_iC(lsu_load_err_iC),
    .store_err_iA(lsu_store_err_iA),
    .store_err_iB(lsu_store_err_iB),
    .store_err_iC(lsu_store_err_iC),
    .branch_set_iA(branch_setA),
    .branch_set_iB(branch_setB),
    .branch_set_iC(branch_setC),
    .jump_set_iA(jump_setA),
    .jump_set_iB(jump_setB),
    .jump_set_iC(jump_setC),
    .csr_mstatus_mie_iA(csr_mstatus_mie_iA),
    .csr_mstatus_mie_iB(csr_mstatus_mie_iB),
    .csr_mstatus_mie_iC(csr_mstatus_mie_iC),
    .irq_pending_iA(irq_pending_iA),
    .irq_pending_iB(irq_pending_iB),
    .irq_pending_iC(irq_pending_iC),
    .irqs_iA(irqs_iA),
    .irqs_iB(irqs_iB),
    .irqs_iC(irqs_iC),
    .irq_nm_iA(irq_nm_iA),
    .irq_nm_iB(irq_nm_iB),
    .irq_nm_iC(irq_nm_iC),
    .nmi_mode_oA(nmi_mode_oA),
    .nmi_mode_oB(nmi_mode_oB),
    .nmi_mode_oC(nmi_mode_oC),
    .csr_save_if_oA(csr_save_if_oA),
    .csr_save_if_oB(csr_save_if_oB),
    .csr_save_if_oC(csr_save_if_oC),
    .csr_save_id_oA(csr_save_id_oA),
    .csr_save_id_oB(csr_save_id_oB),
    .csr_save_id_oC(csr_save_id_oC),
    .csr_restore_mret_id_oA(csr_restore_mret_id_oA),
    .csr_restore_mret_id_oB(csr_restore_mret_id_oB),
    .csr_restore_mret_id_oC(csr_restore_mret_id_oC),
    .csr_restore_dret_id_oA(csr_restore_dret_id_oA),
    .csr_restore_dret_id_oB(csr_restore_dret_id_oB),
    .csr_restore_dret_id_oC(csr_restore_dret_id_oC),
    .csr_save_cause_oA(csr_save_cause_oA),
    .csr_save_cause_oB(csr_save_cause_oB),
    .csr_save_cause_oC(csr_save_cause_oC),
    .csr_mtval_oA(csr_mtval_oA),
    .csr_mtval_oB(csr_mtval_oB),
    .csr_mtval_oC(csr_mtval_oC),
    .priv_mode_iA(priv_mode_iA),
    .priv_mode_iB(priv_mode_iB),
    .priv_mode_iC(priv_mode_iC),
    .csr_mstatus_tw_iA(csr_mstatus_tw_iA),
    .csr_mstatus_tw_iB(csr_mstatus_tw_iB),
    .csr_mstatus_tw_iC(csr_mstatus_tw_iC),
    .debug_mode_oA(debug_mode_oA),
    .debug_mode_oB(debug_mode_oB),
    .debug_mode_oC(debug_mode_oC),
    .debug_cause_oA(debug_cause_oA),
    .debug_cause_oB(debug_cause_oB),
    .debug_cause_oC(debug_cause_oC),
    .debug_csr_save_oA(debug_csr_save_oA),
    .debug_csr_save_oB(debug_csr_save_oB),
    .debug_csr_save_oC(debug_csr_save_oC),
    .debug_req_iA(debug_req_iA),
    .debug_req_iB(debug_req_iB),
    .debug_req_iC(debug_req_iC),
    .debug_single_step_iA(debug_single_step_iA),
    .debug_single_step_iB(debug_single_step_iB),
    .debug_single_step_iC(debug_single_step_iC),
    .debug_ebreakm_iA(debug_ebreakm_iA),
    .debug_ebreakm_iB(debug_ebreakm_iB),
    .debug_ebreakm_iC(debug_ebreakm_iC),
    .debug_ebreaku_iA(debug_ebreaku_iA),
    .debug_ebreaku_iB(debug_ebreaku_iB),
    .debug_ebreaku_iC(debug_ebreaku_iC),
    .trigger_match_iA(trigger_match_iA),
    .trigger_match_iB(trigger_match_iB),
    .trigger_match_iC(trigger_match_iC),
    .stall_id_iA(stall_idA),
    .stall_id_iB(stall_idB),
    .stall_id_iC(stall_idC),
    .flush_id_oA(flush_idA),
    .flush_id_oB(flush_idB),
    .flush_id_oC(flush_idC),
    .perf_jump_oA(perf_jump_oA),
    .perf_jump_oB(perf_jump_oB),
    .perf_jump_oC(perf_jump_oC),
    .perf_tbranch_oA(perf_tbranch_oA),
    .perf_tbranch_oB(perf_tbranch_oB),
    .perf_tbranch_oC(perf_tbranch_oC),
    .tmrErrorA(controller_itmrErrorA),
    .tmrErrorB(controller_itmrErrorB),
    .tmrErrorC(controller_itmrErrorC)
  );
assign multdiv_en_decA = mult_en_decA|div_en_decA;
assign multdiv_en_decB = mult_en_decB|div_en_decB;
assign multdiv_en_decC = mult_en_decC|div_en_decC;
assign lsu_reqA = instr_executingA ? data_req_allowedA&lsu_req_decA : 1'b0;
assign lsu_reqB = instr_executingB ? data_req_allowedB&lsu_req_decB : 1'b0;
assign lsu_reqC = instr_executingC ? data_req_allowedC&lsu_req_decC : 1'b0;
assign mult_en_idA = instr_executingA ? mult_en_decA : 1'b0;
assign mult_en_idB = instr_executingB ? mult_en_decB : 1'b0;
assign mult_en_idC = instr_executingC ? mult_en_decC : 1'b0;
assign div_en_idA = instr_executingA ? div_en_decA : 1'b0;
assign div_en_idB = instr_executingB ? div_en_decB : 1'b0;
assign div_en_idC = instr_executingC ? div_en_decC : 1'b0;
assign lsu_req_oA = lsu_reqA;
assign lsu_req_oB = lsu_reqB;
assign lsu_req_oC = lsu_reqC;
assign lsu_we_oA = lsu_weA;
assign lsu_we_oB = lsu_weB;
assign lsu_we_oC = lsu_weC;
assign lsu_type_oA = lsu_typeA;
assign lsu_type_oB = lsu_typeB;
assign lsu_type_oC = lsu_typeC;
assign lsu_sign_ext_oA = lsu_sign_extA;
assign lsu_sign_ext_oB = lsu_sign_extB;
assign lsu_sign_ext_oC = lsu_sign_extC;
assign lsu_wdata_oA = rf_rdata_b_fwdA;
assign lsu_wdata_oB = rf_rdata_b_fwdB;
assign lsu_wdata_oC = rf_rdata_b_fwdC;
assign csr_op_en_oA = csr_access_oA&instr_executingA&instr_id_done_oA;
assign csr_op_en_oB = csr_access_oB&instr_executingB&instr_id_done_oB;
assign csr_op_en_oC = csr_access_oC&instr_executingC&instr_id_done_oC;
assign alu_operator_ex_oA = alu_operatorA;
assign alu_operator_ex_oB = alu_operatorB;
assign alu_operator_ex_oC = alu_operatorC;
assign alu_operand_a_ex_oA = alu_operand_aA;
assign alu_operand_a_ex_oB = alu_operand_aB;
assign alu_operand_a_ex_oC = alu_operand_aC;
assign alu_operand_b_ex_oA = alu_operand_bA;
assign alu_operand_b_ex_oB = alu_operand_bB;
assign alu_operand_b_ex_oC = alu_operand_bC;
assign mult_en_ex_oA = mult_en_idA;
assign mult_en_ex_oB = mult_en_idB;
assign mult_en_ex_oC = mult_en_idC;
assign div_en_ex_oA = div_en_idA;
assign div_en_ex_oB = div_en_idB;
assign div_en_ex_oC = div_en_idC;
assign multdiv_operator_ex_oA = multdiv_operatorA;
assign multdiv_operator_ex_oB = multdiv_operatorB;
assign multdiv_operator_ex_oC = multdiv_operatorC;
assign multdiv_signed_mode_ex_oA = multdiv_signed_modeA;
assign multdiv_signed_mode_ex_oB = multdiv_signed_modeB;
assign multdiv_signed_mode_ex_oC = multdiv_signed_modeC;
assign multdiv_operand_a_ex_oA = rf_rdata_a_fwdA;
assign multdiv_operand_a_ex_oB = rf_rdata_a_fwdB;
assign multdiv_operand_a_ex_oC = rf_rdata_a_fwdC;
assign multdiv_operand_b_ex_oA = rf_rdata_b_fwdA;
assign multdiv_operand_b_ex_oB = rf_rdata_b_fwdB;
assign multdiv_operand_b_ex_oC = rf_rdata_b_fwdC;
logic branch_set_raw_qA;
logic branch_set_raw_qB;
logic branch_set_raw_qC;
logic branch_set_raw_qVotedA;
logic branch_set_raw_qVotedB;
logic branch_set_raw_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        branch_set_raw_qA <= 1'b0;
      end
    else
      begin
        branch_set_raw_qA <= branch_set_raw_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        branch_set_raw_qB <= 1'b0;
      end
    else
      begin
        branch_set_raw_qB <= branch_set_raw_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        branch_set_raw_qC <= 1'b0;
      end
    else
      begin
        branch_set_raw_qC <= branch_set_raw_dC;
      end
  end
assign branch_set_rawA = branch_set_raw_qVotedA;
assign branch_set_rawB = branch_set_raw_qVotedB;
assign branch_set_rawC = branch_set_raw_qVotedC;
assign branch_jump_set_done_dA =  (branch_set_rawA|jump_set_rawA|branch_jump_set_done_qVotedA) &~instr_valid_clear_oA;
assign branch_jump_set_done_dB =  (branch_set_rawB|jump_set_rawB|branch_jump_set_done_qVotedB) &~instr_valid_clear_oB;
assign branch_jump_set_done_dC =  (branch_set_rawC|jump_set_rawC|branch_jump_set_done_qVotedC) &~instr_valid_clear_oC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        branch_jump_set_done_qA <= 1'b0;
      end
    else
      begin
        branch_jump_set_done_qA <= branch_jump_set_done_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        branch_jump_set_done_qB <= 1'b0;
      end
    else
      begin
        branch_jump_set_done_qB <= branch_jump_set_done_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        branch_jump_set_done_qC <= 1'b0;
      end
    else
      begin
        branch_jump_set_done_qC <= branch_jump_set_done_dC;
      end
  end
assign jump_setA = jump_set_rawA&~branch_jump_set_done_qVotedA;
assign jump_setB = jump_set_rawB&~branch_jump_set_done_qVotedB;
assign jump_setC = jump_set_rawC&~branch_jump_set_done_qVotedC;
assign branch_setA = branch_set_rawA&~branch_jump_set_done_qVotedA;
assign branch_setB = branch_set_rawB&~branch_jump_set_done_qVotedB;
assign branch_setC = branch_set_rawC&~branch_jump_set_done_qVotedC;
id_fsm_e id_fsm_qA, id_fsm_dA, id_fsm_qVotedA;
id_fsm_e id_fsm_qB, id_fsm_dB, id_fsm_qVotedB;
id_fsm_e id_fsm_qC, id_fsm_dC, id_fsm_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : id_pipeline_regA
    if (!rst_niA)
      begin
        id_fsm_qA <= FIRST_CYCLE;
      end
    else
      if (instr_executingA)
        begin
          id_fsm_qA <= id_fsm_dA;
        end

  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : id_pipeline_regB
    if (!rst_niB)
      begin
        id_fsm_qB <= FIRST_CYCLE;
      end
    else
      if (instr_executingB)
        begin
          id_fsm_qB <= id_fsm_dB;
        end

  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : id_pipeline_regC
    if (!rst_niC)
      begin
        id_fsm_qC <= FIRST_CYCLE;
      end
    else
      if (instr_executingC)
        begin
          id_fsm_qC <= id_fsm_dC;
        end

  end

always_comb
  begin
    id_fsm_dA = id_fsm_qVotedA;
    rf_we_rawA = rf_we_decA;
    stall_multdivA = 1'b0;
    stall_jumpA = 1'b0;
    stall_branchA = 1'b0;
    stall_aluA = 1'b0;
    branch_set_raw_dA = 1'b0;
    jump_set_rawA = 1'b0;
    perf_branch_oA = 1'b0;
    if (instr_executing_specA)
      begin
        unique case (id_fsm_qVotedA)
          FIRST_CYCLE : 
            begin
              unique case (1'b1)
                lsu_req_decA: begin
                  begin
                    id_fsm_dA = MULTI_CYCLE;
                  end
                end
                multdiv_en_decA: begin
                  if (~ex_valid_iA)
                    begin
                      id_fsm_dA = MULTI_CYCLE;
                      rf_we_rawA = 1'b0;
                      stall_multdivA = 1'b1;
                    end
                end
                branch_in_decA: begin
                  id_fsm_dA = (branch_decision_iA) ? MULTI_CYCLE : FIRST_CYCLE;
                  stall_branchA = branch_decision_iA;
                  branch_set_raw_dA = branch_decision_iA;
                  perf_branch_oA = 1'b1;
                end
                jump_in_decA: begin
                  id_fsm_dA = MULTI_CYCLE;
                  stall_jumpA = 1'b1;
                  jump_set_rawA = jump_set_decA;
                end
                alu_multicycle_decA: begin
                  stall_aluA = 1'b1;
                  id_fsm_dA = MULTI_CYCLE;
                  rf_we_rawA = 1'b0;
                end
                default: begin
                  id_fsm_dA = FIRST_CYCLE;
                end
              endcase
            end
          MULTI_CYCLE : 
            begin
              if (multdiv_en_decA)
                begin
                  rf_we_rawA = rf_we_decA&ex_valid_iA;
                end

              if (multicycle_doneA)
                begin
                  id_fsm_dA = FIRST_CYCLE;
                end
              else
                begin
                  stall_multdivA = multdiv_en_decA;
                  stall_branchA = branch_in_decA;
                  stall_jumpA = jump_in_decA;
                end
            end
          default : 
            begin
              id_fsm_dA = FIRST_CYCLE;
            end
        endcase
      end

  end

always_comb
  begin
    id_fsm_dB = id_fsm_qVotedB;
    rf_we_rawB = rf_we_decB;
    stall_multdivB = 1'b0;
    stall_jumpB = 1'b0;
    stall_branchB = 1'b0;
    stall_aluB = 1'b0;
    branch_set_raw_dB = 1'b0;
    jump_set_rawB = 1'b0;
    perf_branch_oB = 1'b0;
    if (instr_executing_specB)
      begin
        unique case (id_fsm_qVotedB)
          FIRST_CYCLE : 
            begin
              unique case (1'b1)
                lsu_req_decB: begin
                  begin
                    id_fsm_dB = MULTI_CYCLE;
                  end
                end
                multdiv_en_decB: begin
                  if (~ex_valid_iB) begin
                    id_fsm_dB = MULTI_CYCLE;
                    rf_we_rawB = 1'b0;
                    stall_multdivB = 1'b1;
                  end
                end
                branch_in_decB: begin
                  id_fsm_dB = (branch_decision_iB) ? MULTI_CYCLE : FIRST_CYCLE;
                  stall_branchB = branch_decision_iB;
                  branch_set_raw_dB = branch_decision_iB;
                  perf_branch_oB = 1'b1;
                end
                jump_in_decB: begin
                  id_fsm_dB = MULTI_CYCLE;
                  stall_jumpB = 1'b1;
                  jump_set_rawB = jump_set_decB;
                end
                alu_multicycle_decB: begin
                  stall_aluB = 1'b1;
                  id_fsm_dB = MULTI_CYCLE;
                  rf_we_rawB = 1'b0;
                end
                default: begin
                  id_fsm_dB = FIRST_CYCLE;
                end
              endcase
            end
          MULTI_CYCLE : 
            begin
              if (multdiv_en_decB)
                begin
                  rf_we_rawB = rf_we_decB&ex_valid_iB;
                end

              if (multicycle_doneB)
                begin
                  id_fsm_dB = FIRST_CYCLE;
                end
              else
                begin
                  stall_multdivB = multdiv_en_decB;
                  stall_branchB = branch_in_decB;
                  stall_jumpB = jump_in_decB;
                end
            end
          default : 
            begin
              id_fsm_dB = FIRST_CYCLE;
            end
        endcase
      end

  end

always_comb
  begin
    id_fsm_dC = id_fsm_qVotedC;
    rf_we_rawC = rf_we_decC;
    stall_multdivC = 1'b0;
    stall_jumpC = 1'b0;
    stall_branchC = 1'b0;
    stall_aluC = 1'b0;
    branch_set_raw_dC = 1'b0;
    jump_set_rawC = 1'b0;
    perf_branch_oC = 1'b0;
    if (instr_executing_specC)
      begin
        unique case (id_fsm_qVotedC)
          FIRST_CYCLE : 
            begin
              unique case (1'b1)
                lsu_req_decC: begin
                  begin
                    id_fsm_dC = MULTI_CYCLE;
                  end
                end 
                multdiv_en_decC: begin
                  if (~ex_valid_iC)
                    begin
                      id_fsm_dC = MULTI_CYCLE;
                      rf_we_rawC = 1'b0;
                      stall_multdivC = 1'b1;
                    end
                end
                branch_in_decC: begin
                  id_fsm_dC = (branch_decision_iC) ? MULTI_CYCLE : FIRST_CYCLE;
                  stall_branchC = branch_decision_iC;
                  branch_set_raw_dC = branch_decision_iC;
                  perf_branch_oC = 1'b1;
                end
                jump_in_decC: begin
                  id_fsm_dC = MULTI_CYCLE;
                  stall_jumpC = 1'b1;
                  jump_set_rawC = jump_set_decC;
                end
                alu_multicycle_decC: begin
                  stall_aluC = 1'b1;
                  id_fsm_dC = MULTI_CYCLE;
                  rf_we_rawC = 1'b0;
                end
                default: begin
                  id_fsm_dC = FIRST_CYCLE;
                end
              endcase
            end
          MULTI_CYCLE : 
            begin
              if (multdiv_en_decC)
                begin
                  rf_we_rawC = rf_we_decC&ex_valid_iC;
                end

              if (multicycle_doneC)
                begin
                  id_fsm_dC = FIRST_CYCLE;
                end
              else
                begin
                  stall_multdivC = multdiv_en_decC;
                  stall_branchC = branch_in_decC;
                  stall_jumpC = jump_in_decC;
                end
            end
          default : 
            begin
              id_fsm_dC = FIRST_CYCLE;
            end
        endcase
      end

  end
assign stall_idA = stall_memA|stall_multdivA|stall_jumpA|stall_branchA|stall_aluA;
assign stall_idB = stall_memB|stall_multdivB|stall_jumpB|stall_branchB|stall_aluB;
assign stall_idC = stall_memC|stall_multdivC|stall_jumpC|stall_branchC|stall_aluC;
assign instr_doneA = ~stall_idA&~flush_idA&instr_executingA;
assign instr_doneB = ~stall_idB&~flush_idB&instr_executingB;
assign instr_doneC = ~stall_idC&~flush_idC&instr_executingC;
assign instr_first_cycleA = instr_valid_iA& (id_fsm_qVotedA==FIRST_CYCLE) ;
assign instr_first_cycleB = instr_valid_iB& (id_fsm_qVotedB==FIRST_CYCLE) ;
assign instr_first_cycleC = instr_valid_iC& (id_fsm_qVotedC==FIRST_CYCLE) ;
assign instr_first_cycle_id_oA = instr_first_cycleA;
assign instr_first_cycle_id_oB = instr_first_cycleB;
assign instr_first_cycle_id_oC = instr_first_cycleC;
assign multicycle_doneA = lsu_req_decA ? lsu_resp_valid_iA : ex_valid_iA;
assign multicycle_doneB = lsu_req_decB ? lsu_resp_valid_iB : ex_valid_iB;
assign multicycle_doneC = lsu_req_decC ? lsu_resp_valid_iC : ex_valid_iC;
assign data_req_allowedA = instr_first_cycleA;
assign data_req_allowedB = instr_first_cycleB;
assign data_req_allowedC = instr_first_cycleC;
assign stall_memA = instr_valid_iA& (lsu_req_decA&(~ lsu_resp_valid_iA | instr_first_cycleA )) ;
assign stall_memB = instr_valid_iB& (lsu_req_decB&(~ lsu_resp_valid_iB | instr_first_cycleB )) ;
assign stall_memC = instr_valid_iC& (lsu_req_decC&(~ lsu_resp_valid_iC | instr_first_cycleC )) ;
assign instr_executing_specA = instr_valid_iA&~instr_fetch_err_iA&controller_runA;
assign instr_executing_specB = instr_valid_iB&~instr_fetch_err_iB&controller_runB;
assign instr_executing_specC = instr_valid_iC&~instr_fetch_err_iC&controller_runC;
assign instr_executingA = instr_executing_specA;
assign instr_executingB = instr_executing_specB;
assign instr_executingC = instr_executing_specC;
assign rf_rdata_a_fwdA = rf_rdata_a_iA;
assign rf_rdata_a_fwdB = rf_rdata_a_iB;
assign rf_rdata_a_fwdC = rf_rdata_a_iC;
assign rf_rdata_b_fwdA = rf_rdata_b_iA;
assign rf_rdata_b_fwdB = rf_rdata_b_iB;
assign rf_rdata_b_fwdC = rf_rdata_b_iC;
logic unused_data_req_done_exA;
logic unused_data_req_done_exB;
logic unused_data_req_done_exC;
assign perf_dside_wait_oA = instr_executingA&lsu_req_decA&~lsu_resp_valid_iA;
assign perf_dside_wait_oB = instr_executingB&lsu_req_decB&~lsu_resp_valid_iB;
assign perf_dside_wait_oC = instr_executingC&lsu_req_decC&~lsu_resp_valid_iC;
assign instr_id_done_oA = instr_doneA;
assign instr_id_done_oB = instr_doneB;
assign instr_id_done_oC = instr_doneC;
assign instr_perf_count_id_oA = ~ebrk_insnA&~ecall_insn_decA&~illegal_insn_decA&~ (dret_insn_decA&~debug_mode_oA) &~illegal_csr_insn_iA&~instr_fetch_err_iA;
assign instr_perf_count_id_oB = ~ebrk_insnB&~ecall_insn_decB&~illegal_insn_decB&~ (dret_insn_decB&~debug_mode_oB) &~illegal_csr_insn_iB&~instr_fetch_err_iB;
assign instr_perf_count_id_oC = ~ebrk_insnC&~ecall_insn_decC&~illegal_insn_decC&~ (dret_insn_decC&~debug_mode_oC) &~illegal_csr_insn_iC&~instr_fetch_err_iC;
assign en_wb_oA = instr_doneA;
assign en_wb_oB = instr_doneB;
assign en_wb_oC = instr_doneC;
assign perf_wfi_wait_oA = wfi_insn_decA;
assign perf_wfi_wait_oB = wfi_insn_decB;
assign perf_wfi_wait_oC = wfi_insn_decC;
assign perf_div_wait_oA = stall_multdivA&div_en_decA;
assign perf_div_wait_oB = stall_multdivB&div_en_decB;
assign perf_div_wait_oC = stall_multdivC&div_en_decC;

majorityVoter branch_jump_set_done_qVoterA (
    .inA(branch_jump_set_done_qA),
    .inB(branch_jump_set_done_qB),
    .inC(branch_jump_set_done_qC),
    .out(branch_jump_set_done_qVotedA),
    .tmrErr(branch_jump_set_done_qTmrErrorA)
  );

majorityVoter branch_set_raw_qVoterA (
    .inA(branch_set_raw_qA),
    .inB(branch_set_raw_qB),
    .inC(branch_set_raw_qC),
    .out(branch_set_raw_qVotedA),
    .tmrErr(branch_set_raw_qTmrErrorA)
  );

majorityVoter id_fsm_qVoterA (
    .inA(id_fsm_qA),
    .inB(id_fsm_qB),
    .inC(id_fsm_qC),
    .out({id_fsm_qVotedA}),
    .tmrErr(id_fsm_qTmrErrorA)
  );
assign tmrErrorA = branch_jump_set_done_qTmrErrorA|branch_set_raw_qTmrErrorA|controller_itmrErrorA|decoder_itmrErrorA|id_fsm_qTmrErrorA;

majorityVoter branch_jump_set_done_qVoterB (
    .inA(branch_jump_set_done_qA),
    .inB(branch_jump_set_done_qB),
    .inC(branch_jump_set_done_qC),
    .out(branch_jump_set_done_qVotedB),
    .tmrErr(branch_jump_set_done_qTmrErrorB)
  );

majorityVoter branch_set_raw_qVoterB (
    .inA(branch_set_raw_qA),
    .inB(branch_set_raw_qB),
    .inC(branch_set_raw_qC),
    .out(branch_set_raw_qVotedB),
    .tmrErr(branch_set_raw_qTmrErrorB)
  );

majorityVoter id_fsm_qVoterB (
    .inA(id_fsm_qA),
    .inB(id_fsm_qB),
    .inC(id_fsm_qC),
    .out({id_fsm_qVotedB}),
    .tmrErr(id_fsm_qTmrErrorB)
  );
assign tmrErrorB = branch_jump_set_done_qTmrErrorB|branch_set_raw_qTmrErrorB|controller_itmrErrorB|decoder_itmrErrorB|id_fsm_qTmrErrorB;

majorityVoter branch_jump_set_done_qVoterC (
    .inA(branch_jump_set_done_qA),
    .inB(branch_jump_set_done_qB),
    .inC(branch_jump_set_done_qC),
    .out(branch_jump_set_done_qVotedC),
    .tmrErr(branch_jump_set_done_qTmrErrorC)
  );

majorityVoter branch_set_raw_qVoterC (
    .inA(branch_set_raw_qA),
    .inB(branch_set_raw_qB),
    .inC(branch_set_raw_qC),
    .out(branch_set_raw_qVotedC),
    .tmrErr(branch_set_raw_qTmrErrorC)
  );

majorityVoter id_fsm_qVoterC (
    .inA(id_fsm_qA),
    .inB(id_fsm_qB),
    .inC(id_fsm_qC),
    .out({id_fsm_qVotedC}),
    .tmrErr(id_fsm_qTmrErrorC)
  );
assign tmrErrorC = branch_jump_set_done_qTmrErrorC|branch_set_raw_qTmrErrorC|controller_itmrErrorC|decoder_itmrErrorC|id_fsm_qTmrErrorC;
endmodule

