/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/cve2_counterTMR.sv                                                          *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:11                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/cve2_counter.sv                                                               *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc ( M tmrg_src/cve2_counter.sv) *
 *           Modification time : 2025-11-12 14:38:37.196065                                         *
 *           File Size         : 3203                                                               *
 *           MD5 hash          : 3b2a94c0cbdbd8a87f77d458b281aa6f                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module cve2_counterTMR #(
  parameter int CounterWidth = 32,
  parameter bit ProvideValUpd = 0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic counter_inc_iA,
  input logic counter_inc_iB,
  input logic counter_inc_iC,
  input logic counterh_we_iA,
  input logic counterh_we_iB,
  input logic counterh_we_iC,
  input logic counter_we_iA,
  input logic counter_we_iB,
  input logic counter_we_iC,
  input logic [31:0] counter_val_iA,
  input logic [31:0] counter_val_iB,
  input logic [31:0] counter_val_iC,
  output logic [63:0] counter_val_oA,
  output logic [63:0] counter_val_oB,
  output logic [63:0] counter_val_oC,
  output logic [63:0] counter_val_upd_oA,
  output logic [63:0] counter_val_upd_oB,
  output logic [63:0] counter_val_upd_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire counter_qTmrErrorC;
wire counter_qTmrErrorB;
wire counter_qTmrErrorA;
logic [63:0] counterA;
logic [63:0] counterB;
logic [63:0] counterC;
logic [CounterWidth - 1:0] counter_updA;
logic [CounterWidth - 1:0] counter_updB;
logic [CounterWidth - 1:0] counter_updC;
logic [63:0] counter_loadA;
logic [63:0] counter_loadB;
logic [63:0] counter_loadC;
logic weA;
logic weB;
logic weC;
logic [CounterWidth - 1:0] counter_dA;
logic [CounterWidth - 1:0] counter_dB;
logic [CounterWidth - 1:0] counter_dC;
assign counter_updA = counterA[CounterWidth - 1:0] + {{ CounterWidth - 1 {1'b0} } , 1'b1};
assign counter_updB = counterB[CounterWidth - 1:0] + {{ CounterWidth - 1 {1'b0} } , 1'b1};
assign counter_updC = counterC[CounterWidth - 1:0] + {{ CounterWidth - 1 {1'b0} } , 1'b1};

always_comb
  begin
    weA = counter_we_iA|counterh_we_iA;
    counter_loadA[63:32] = counterA[63:32];
    counter_loadA[31:0] = counter_val_iA;
    if (counterh_we_iA)
      begin
        counter_loadA[63:32] = counter_val_iA;
        counter_loadA[31:0] = counterA[31:0];
      end

    if (weA)
      begin
        counter_dA = counter_loadA[CounterWidth - 1:0];
      end
    else
      if (counter_inc_iA)
        begin
          counter_dA = counter_updA[CounterWidth - 1:0];
        end
      else
        begin
          counter_dA = counterA[CounterWidth - 1:0];
        end
  end

always_comb
  begin
    weB = counter_we_iB|counterh_we_iB;
    counter_loadB[63:32] = counterB[63:32];
    counter_loadB[31:0] = counter_val_iB;
    if (counterh_we_iB)
      begin
        counter_loadB[63:32] = counter_val_iB;
        counter_loadB[31:0] = counterB[31:0];
      end

    if (weB)
      begin
        counter_dB = counter_loadB[CounterWidth - 1:0];
      end
    else
      if (counter_inc_iB)
        begin
          counter_dB = counter_updB[CounterWidth - 1:0];
        end
      else
        begin
          counter_dB = counterB[CounterWidth - 1:0];
        end
  end

always_comb
  begin
    weC = counter_we_iC|counterh_we_iC;
    counter_loadC[63:32] = counterC[63:32];
    counter_loadC[31:0] = counter_val_iC;
    if (counterh_we_iC)
      begin
        counter_loadC[63:32] = counter_val_iC;
        counter_loadC[31:0] = counterC[31:0];
      end

    if (weC)
      begin
        counter_dC = counter_loadC[CounterWidth - 1:0];
      end
    else
      if (counter_inc_iC)
        begin
          counter_dC = counter_updC[CounterWidth - 1:0];
        end
      else
        begin
          counter_dC = counterC[CounterWidth - 1:0];
        end
  end
logic [CounterWidth - 1:0] counter_qA;
logic [CounterWidth - 1:0] counter_qB;
logic [CounterWidth - 1:0] counter_qC;
logic [CounterWidth - 1:0] counter_qVotedA;
logic [CounterWidth - 1:0] counter_qVotedB;
logic [CounterWidth - 1:0] counter_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        counter_qA <= '0;
      end
    else
      begin
        counter_qA <= counter_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        counter_qB <= '0;
      end
    else
      begin
        counter_qB <= counter_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        counter_qC <= '0;
      end
    else
      begin
        counter_qC <= counter_dC;
      end
  end
if (CounterWidth<64)
  begin : g_counter_narrow
logic [63:CounterWidth] unused_counter_loadA;
logic [63:CounterWidth] unused_counter_loadB;
logic [63:CounterWidth] unused_counter_loadC;
    assign counterA[CounterWidth - 1:0] = counter_qVotedA;
    assign counterB[CounterWidth - 1:0] = counter_qVotedB;
    assign counterC[CounterWidth - 1:0] = counter_qVotedC;
    assign counterA[63:CounterWidth] = '0;
    assign counterB[63:CounterWidth] = '0;
    assign counterC[63:CounterWidth] = '0;
    if (ProvideValUpd)
          begin : g_counter_val_upd_o
        assign counter_val_upd_oA[CounterWidth - 1:0] = counter_updA;
        assign counter_val_upd_oB[CounterWidth - 1:0] = counter_updB;
        assign counter_val_upd_oC[CounterWidth - 1:0] = counter_updC;
      end

    else
          begin : g_no_counter_val_upd_o
        assign counter_val_upd_oA[CounterWidth - 1:0] = '0;
        assign counter_val_upd_oB[CounterWidth - 1:0] = '0;
        assign counter_val_upd_oC[CounterWidth - 1:0] = '0;
      end
    assign counter_val_upd_oA[63:CounterWidth] = '0;
    assign counter_val_upd_oB[63:CounterWidth] = '0;
    assign counter_val_upd_oC[63:CounterWidth] = '0;
    assign unused_counter_loadA = counter_loadA[63:CounterWidth];
    assign unused_counter_loadB = counter_loadB[63:CounterWidth];
    assign unused_counter_loadC = counter_loadC[63:CounterWidth];
  end

else
  begin : g_counter_full
    assign counterA = counter_qVotedA;
    assign counterB = counter_qVotedB;
    assign counterC = counter_qVotedC;
    if (ProvideValUpd)
          begin : g_counter_val_upd_o
        assign counter_val_upd_oA = counter_updA;
        assign counter_val_upd_oB = counter_updB;
        assign counter_val_upd_oC = counter_updC;
      end

    else
          begin : g_no_counter_val_upd_o
        assign counter_val_upd_oA = '0;
        assign counter_val_upd_oB = '0;
        assign counter_val_upd_oC = '0;
      end
  end
assign counter_val_oA = counterA;
assign counter_val_oB = counterB;
assign counter_val_oC = counterC;

majorityVoter #(.WIDTH( ((((CounterWidth-1)>0) ? (CounterWidth-1) : - ( CounterWidth-1 ) )+1) )) counter_qVoterA (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedA),
    .tmrErr(counter_qTmrErrorA)
  );
assign tmrErrorA = counter_qTmrErrorA;

majorityVoter #(.WIDTH( ((((CounterWidth-1)>0) ? (CounterWidth-1) : - ( CounterWidth-1 ) )+1) )) counter_qVoterB (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedB),
    .tmrErr(counter_qTmrErrorB)
  );
assign tmrErrorB = counter_qTmrErrorB;

majorityVoter #(.WIDTH( ((((CounterWidth-1)>0) ? (CounterWidth-1) : - ( CounterWidth-1 ) )+1) )) counter_qVoterC (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedC),
    .tmrErr(counter_qTmrErrorC)
  );
assign tmrErrorC = counter_qTmrErrorC;
endmodule

`undef COUNTER_FLOP_RST
