/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/delta_counterTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:06                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/delta_counter.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:26.338272                                         *
 *           File Size         : 3167                                                               *
 *           MD5 hash          : a1f44d1d8964e60301bea35d7494b15e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module delta_counterTMR #(
  parameter int unsigned WIDTH = 4,
  parameter bit STICKY_OVERFLOW = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic clear_iA,
  input logic clear_iB,
  input logic clear_iC,
  input logic en_iA,
  input logic en_iB,
  input logic en_iC,
  input logic load_iA,
  input logic load_iB,
  input logic load_iC,
  input logic down_iA,
  input logic down_iB,
  input logic down_iC,
  input logic [WIDTH - 1:0] delta_iA,
  input logic [WIDTH - 1:0] delta_iB,
  input logic [WIDTH - 1:0] delta_iC,
  input logic [WIDTH - 1:0] d_iA,
  input logic [WIDTH - 1:0] d_iB,
  input logic [WIDTH - 1:0] d_iC,
  output logic [WIDTH - 1:0] q_oA,
  output logic [WIDTH - 1:0] q_oB,
  output logic [WIDTH - 1:0] q_oC,
  output logic overflow_oA,
  output logic overflow_oB,
  output logic overflow_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor overflow_qTmrErrorC;
wor counter_qTmrErrorC;
wor overflow_qTmrErrorB;
wor counter_qTmrErrorB;
wor overflow_qTmrErrorA;
wor counter_qTmrErrorA;
logic [WIDTH:0] counter_qA;
logic [WIDTH:0] counter_qB;
logic [WIDTH:0] counter_qC;
logic [WIDTH:0] counter_dA;
logic [WIDTH:0] counter_dB;
logic [WIDTH:0] counter_dC;
logic [WIDTH:0] counter_qVotedA;
logic [WIDTH:0] counter_qVotedB;
logic [WIDTH:0] counter_qVotedC;
logic overflow_dA;
logic overflow_dB;
logic overflow_dC;
logic overflow_qA;
logic overflow_qB;
logic overflow_qC;
logic overflow_qVotedA;
logic overflow_qVotedB;
logic overflow_qVotedC;
if (STICKY_OVERFLOW)
  begin : gen_sticky_overflow

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            overflow_qA <= 1'b0;
          end
        else
          begin
            overflow_qA <= overflow_dA;
          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            overflow_qB <= 1'b0;
          end
        else
          begin
            overflow_qB <= overflow_dB;
          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            overflow_qC <= 1'b0;
          end
        else
          begin
            overflow_qC <= overflow_dC;
          end
      end

    always_comb
      begin
        overflow_dA = overflow_qVotedA;
        if (clear_iA||load_iA)
          begin
            overflow_dA = 1'b0;
          end
        else
          if (!overflow_qVotedA&&en_iA)
            begin
              if (down_iA)
                begin
                  overflow_dA = delta_iA>counter_qVotedA[WIDTH - 1:0];
                end
              else
                begin
                  overflow_dA = counter_qVotedA[WIDTH - 1:0]> ({ WIDTH {1'b1} } -delta_iA) ;
                end
            end

      end

    always_comb
      begin
        overflow_dB = overflow_qVotedB;
        if (clear_iB||load_iB)
          begin
            overflow_dB = 1'b0;
          end
        else
          if (!overflow_qVotedB&&en_iB)
            begin
              if (down_iB)
                begin
                  overflow_dB = delta_iB>counter_qVotedB[WIDTH - 1:0];
                end
              else
                begin
                  overflow_dB = counter_qVotedB[WIDTH - 1:0]> ({ WIDTH {1'b1} } -delta_iB) ;
                end
            end

      end

    always_comb
      begin
        overflow_dC = overflow_qVotedC;
        if (clear_iC||load_iC)
          begin
            overflow_dC = 1'b0;
          end
        else
          if (!overflow_qVotedC&&en_iC)
            begin
              if (down_iC)
                begin
                  overflow_dC = delta_iC>counter_qVotedC[WIDTH - 1:0];
                end
              else
                begin
                  overflow_dC = counter_qVotedC[WIDTH - 1:0]> ({ WIDTH {1'b1} } -delta_iC) ;
                end
            end

      end
    assign overflow_oA = overflow_qVotedA;
    assign overflow_oB = overflow_qVotedB;
    assign overflow_oC = overflow_qVotedC;
  end

else
  begin : gen_transient_overflow
    assign overflow_oA = counter_qVotedA[WIDTH];
    assign overflow_oB = counter_qVotedB[WIDTH];
    assign overflow_oC = counter_qVotedC[WIDTH];
    assign overflow_qA = '0;
    assign overflow_qB = '0;
    assign overflow_qC = '0;
  end
assign q_oA = counter_qVotedA[WIDTH - 1:0];
assign q_oB = counter_qVotedB[WIDTH - 1:0];
assign q_oC = counter_qVotedC[WIDTH - 1:0];

always_comb
  begin
    counter_dA = counter_qVotedA;
    if (clear_iA)
      begin
        counter_dA = '0;
      end
    else
      if (load_iA)
        begin
          counter_dA = {1'b0, d_iA};
        end
      else
        if (en_iA)
          begin
            if (down_iA)
              begin
                counter_dA = counter_qVotedA - delta_iA;
              end
            else
              begin
                counter_dA = counter_qVotedA + delta_iA;
              end
          end

  end

always_comb
  begin
    counter_dB = counter_qVotedB;
    if (clear_iB)
      begin
        counter_dB = '0;
      end
    else
      if (load_iB)
        begin
          counter_dB = {1'b0, d_iB};
        end
      else
        if (en_iB)
          begin
            if (down_iB)
              begin
                counter_dB = counter_qVotedB - delta_iB;
              end
            else
              begin
                counter_dB = counter_qVotedB + delta_iB;
              end
          end

  end

always_comb
  begin
    counter_dC = counter_qVotedC;
    if (clear_iC)
      begin
        counter_dC = '0;
      end
    else
      if (load_iC)
        begin
          counter_dC = {1'b0, d_iC};
        end
      else
        if (en_iC)
          begin
            if (down_iC)
              begin
                counter_dC = counter_qVotedC - delta_iC;
              end
            else
              begin
                counter_dC = counter_qVotedC + delta_iC;
              end
          end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        counter_qA <= '0;
      end
    else
      begin
        counter_qA <= counter_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        counter_qB <= '0;
      end
    else
      begin
        counter_qB <= counter_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        counter_qC <= '0;
      end
    else
      begin
        counter_qC <= counter_dC;
      end
  end

majorityVoter #(.WIDTH( (((WIDTH>0) ? WIDTH : - WIDTH )+1) )) counter_qVoterA (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedA),
    .tmrErr(counter_qTmrErrorA)
  );

majorityVoter overflow_qVoterA (
    .inA(overflow_qA),
    .inB(overflow_qB),
    .inC(overflow_qC),
    .out(overflow_qVotedA),
    .tmrErr(overflow_qTmrErrorA)
  );
assign tmrErrorA = counter_qTmrErrorA|overflow_qTmrErrorA;

majorityVoter #(.WIDTH( (((WIDTH>0) ? WIDTH : - WIDTH )+1) )) counter_qVoterB (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedB),
    .tmrErr(counter_qTmrErrorB)
  );

majorityVoter overflow_qVoterB (
    .inA(overflow_qA),
    .inB(overflow_qB),
    .inC(overflow_qC),
    .out(overflow_qVotedB),
    .tmrErr(overflow_qTmrErrorB)
  );
assign tmrErrorB = counter_qTmrErrorB|overflow_qTmrErrorB;

majorityVoter #(.WIDTH( (((WIDTH>0) ? WIDTH : - WIDTH )+1) )) counter_qVoterC (
    .inA(counter_qA),
    .inB(counter_qB),
    .inC(counter_qC),
    .out(counter_qVotedC),
    .tmrErr(counter_qTmrErrorC)
  );

majorityVoter overflow_qVoterC (
    .inA(overflow_qA),
    .inB(overflow_qB),
    .inC(overflow_qC),
    .out(overflow_qVotedC),
    .tmrErr(overflow_qTmrErrorC)
  );
assign tmrErrorC = counter_qTmrErrorC|overflow_qTmrErrorC;
endmodule

