/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/fifo_v3TMR.sv                                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:12                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/fifo_v3.sv                                                                    *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-21 16:45:24.249282                                         *
 *           File Size         : 6369                                                               *
 *           MD5 hash          : 5f82663a10a75b5c12be9fdcbfbcbca3                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module fifo_v3TMR #(
  parameter bit FALL_THROUGH = 1'b0,
  parameter int unsigned DATA_WIDTH = 32,
  parameter int unsigned DEPTH = 8,
  parameter type dtype = logic [DATA_WIDTH-1:0],
  parameter int unsigned ADDR_DEPTH = (DEPTH>1) ? $clog2(DEPTH) : 1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  input logic testmode_iA,
  input logic testmode_iB,
  input logic testmode_iC,
  output logic full_oA,
  output logic full_oB,
  output logic full_oC,
  output logic empty_oA,
  output logic empty_oB,
  output logic empty_oC,
  output logic [ADDR_DEPTH - 1:0] usage_oA,
  output logic [ADDR_DEPTH - 1:0] usage_oB,
  output logic [ADDR_DEPTH - 1:0] usage_oC,
  input dtype data_iA,
  input dtype data_iB,
  input dtype data_iC,
  input logic push_iA,
  input logic push_iB,
  input logic push_iC,
  output dtype data_oA,
  output dtype data_oB,
  output dtype data_oC,
  input logic pop_iA,
  input logic pop_iB,
  input logic pop_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
localparam int unsigned FifoDepth = (DEPTH>0) ? DEPTH : 1;
wire write_pointer_qTmrErrorC;
wire status_cnt_qTmrErrorC;
wire read_pointer_qTmrErrorC;
wire mem_qTmrErrorC;
wire write_pointer_qTmrErrorB;
wire status_cnt_qTmrErrorB;
wire read_pointer_qTmrErrorB;
wire mem_qTmrErrorB;
wire write_pointer_qTmrErrorA;
wire status_cnt_qTmrErrorA;
wire read_pointer_qTmrErrorA;
wire mem_qTmrErrorA;
logic gate_clockA;
logic gate_clockB;
logic gate_clockC;
logic [ADDR_DEPTH - 1:0] read_pointer_nA;
logic [ADDR_DEPTH - 1:0] read_pointer_nB;
logic [ADDR_DEPTH - 1:0] read_pointer_nC;
logic [ADDR_DEPTH - 1:0] read_pointer_qA;
logic [ADDR_DEPTH - 1:0] read_pointer_qB;
logic [ADDR_DEPTH - 1:0] read_pointer_qC;
logic [ADDR_DEPTH - 1:0] read_pointer_qVotedA;
logic [ADDR_DEPTH - 1:0] read_pointer_qVotedB;
logic [ADDR_DEPTH - 1:0] read_pointer_qVotedC;
logic [ADDR_DEPTH - 1:0] write_pointer_nA;
logic [ADDR_DEPTH - 1:0] write_pointer_nB;
logic [ADDR_DEPTH - 1:0] write_pointer_nC;
logic [ADDR_DEPTH - 1:0] write_pointer_qA;
logic [ADDR_DEPTH - 1:0] write_pointer_qB;
logic [ADDR_DEPTH - 1:0] write_pointer_qC;
logic [ADDR_DEPTH - 1:0] write_pointer_qVotedA;
logic [ADDR_DEPTH - 1:0] write_pointer_qVotedB;
logic [ADDR_DEPTH - 1:0] write_pointer_qVotedC;
logic [ADDR_DEPTH:0] status_cnt_nA;
logic [ADDR_DEPTH:0] status_cnt_nB;
logic [ADDR_DEPTH:0] status_cnt_nC;
logic [ADDR_DEPTH:0] status_cnt_qA;
logic [ADDR_DEPTH:0] status_cnt_qB;
logic [ADDR_DEPTH:0] status_cnt_qC;
logic [ADDR_DEPTH:0] status_cnt_qVotedA;
logic [ADDR_DEPTH:0] status_cnt_qVotedB;
logic [ADDR_DEPTH:0] status_cnt_qVotedC;
dtype [FifoDepth - 1:0] mem_nA;
dtype [FifoDepth - 1:0] mem_nB;
dtype [FifoDepth - 1:0] mem_nC;
dtype [FifoDepth - 1:0] mem_qA;
dtype [FifoDepth - 1:0] mem_qB;
dtype [FifoDepth - 1:0] mem_qC;
dtype [FifoDepth - 1:0] mem_qVotedA;
dtype [FifoDepth - 1:0] mem_qVotedB;
dtype [FifoDepth - 1:0] mem_qVotedC;
assign usage_oA = status_cnt_qVotedA[ADDR_DEPTH - 1:0];
assign usage_oB = status_cnt_qVotedB[ADDR_DEPTH - 1:0];
assign usage_oC = status_cnt_qVotedC[ADDR_DEPTH - 1:0];
if (DEPTH==0)
  begin : gen_pass_through
    assign empty_oA = ~push_iA;
    assign empty_oB = ~push_iB;
    assign empty_oC = ~push_iC;
    assign full_oA = ~pop_iA;
    assign full_oB = ~pop_iB;
    assign full_oC = ~pop_iC;
  end

else
  begin : gen_fifo
    assign full_oA =  (status_cnt_qVotedA==FifoDepth[ADDR_DEPTH:0]) ;
    assign full_oB =  (status_cnt_qVotedB==FifoDepth[ADDR_DEPTH:0]) ;
    assign full_oC =  (status_cnt_qVotedC==FifoDepth[ADDR_DEPTH:0]) ;
    assign empty_oA =  (status_cnt_qVotedA==0) &~ (FALL_THROUGH&push_iA) ;
    assign empty_oB =  (status_cnt_qVotedB==0) &~ (FALL_THROUGH&push_iB) ;
    assign empty_oC =  (status_cnt_qVotedC==0) &~ (FALL_THROUGH&push_iC) ;
  end

always_comb
  begin : read_write_combA
    read_pointer_nA = read_pointer_qVotedA;
    write_pointer_nA = write_pointer_qVotedA;
    status_cnt_nA = status_cnt_qVotedA;
    data_oA = (DEPTH==0) ? data_iA : mem_qVotedA[read_pointer_qVotedA];
    mem_nA = mem_qVotedA;
    gate_clockA = 1'b1;
    if (push_iA&&~full_oA)
      begin
        mem_nA[write_pointer_qVotedA] = data_iA;
        gate_clockA = 1'b0;
        if (write_pointer_qVotedA==FifoDepth[ADDR_DEPTH - 1:0]-1)
          write_pointer_nA = '0;
        else
          write_pointer_nA = write_pointer_qVotedA + 1;
        status_cnt_nA = status_cnt_qVotedA + 1;
      end

    if (pop_iA&&~empty_oA)
      begin
        if (read_pointer_nA==FifoDepth[ADDR_DEPTH - 1:0]-1)
          read_pointer_nA = '0;
        else
          read_pointer_nA = read_pointer_qVotedA + 1;
        status_cnt_nA = status_cnt_qVotedA - 1;
      end

    if (push_iA&&pop_iA&&~full_oA&&~empty_oA)
      status_cnt_nA = status_cnt_qVotedA;

    if (FALL_THROUGH&&(status_cnt_qVotedA==0)&&push_iA)
      begin
        data_oA = data_iA;
        if (pop_iA)
          begin
            status_cnt_nA = status_cnt_qVotedA;
            read_pointer_nA = read_pointer_qVotedA;
            write_pointer_nA = write_pointer_qVotedA;
          end

      end

  end

always_comb
  begin : read_write_combB
    read_pointer_nB = read_pointer_qVotedB;
    write_pointer_nB = write_pointer_qVotedB;
    status_cnt_nB = status_cnt_qVotedB;
    data_oB = (DEPTH==0) ? data_iB : mem_qVotedB[read_pointer_qVotedB];
    mem_nB = mem_qVotedB;
    gate_clockB = 1'b1;
    if (push_iB&&~full_oB)
      begin
        mem_nB[write_pointer_qVotedB] = data_iB;
        gate_clockB = 1'b0;
        if (write_pointer_qVotedB==FifoDepth[ADDR_DEPTH - 1:0]-1)
          write_pointer_nB = '0;
        else
          write_pointer_nB = write_pointer_qVotedB + 1;
        status_cnt_nB = status_cnt_qVotedB + 1;
      end

    if (pop_iB&&~empty_oB)
      begin
        if (read_pointer_nB==FifoDepth[ADDR_DEPTH - 1:0]-1)
          read_pointer_nB = '0;
        else
          read_pointer_nB = read_pointer_qVotedB + 1;
        status_cnt_nB = status_cnt_qVotedB - 1;
      end

    if (push_iB&&pop_iB&&~full_oB&&~empty_oB)
      status_cnt_nB = status_cnt_qVotedB;

    if (FALL_THROUGH&&(status_cnt_qVotedB==0)&&push_iB)
      begin
        data_oB = data_iB;
        if (pop_iB)
          begin
            status_cnt_nB = status_cnt_qVotedB;
            read_pointer_nB = read_pointer_qVotedB;
            write_pointer_nB = write_pointer_qVotedB;
          end

      end

  end

always_comb
  begin : read_write_combC
    read_pointer_nC = read_pointer_qVotedC;
    write_pointer_nC = write_pointer_qVotedC;
    status_cnt_nC = status_cnt_qVotedC;
    data_oC = (DEPTH==0) ? data_iC : mem_qVotedC[read_pointer_qVotedC];
    mem_nC = mem_qVotedC;
    gate_clockC = 1'b1;
    if (push_iC&&~full_oC)
      begin
        mem_nC[write_pointer_qVotedC] = data_iC;
        gate_clockC = 1'b0;
        if (write_pointer_qVotedC==FifoDepth[ADDR_DEPTH - 1:0]-1)
          write_pointer_nC = '0;
        else
          write_pointer_nC = write_pointer_qVotedC + 1;
        status_cnt_nC = status_cnt_qVotedC + 1;
      end

    if (pop_iC&&~empty_oC)
      begin
        if (read_pointer_nC==FifoDepth[ADDR_DEPTH - 1:0]-1)
          read_pointer_nC = '0;
        else
          read_pointer_nC = read_pointer_qVotedC + 1;
        status_cnt_nC = status_cnt_qVotedC - 1;
      end

    if (push_iC&&pop_iC&&~full_oC&&~empty_oC)
      status_cnt_nC = status_cnt_qVotedC;

    if (FALL_THROUGH&&(status_cnt_qVotedC==0)&&push_iC)
      begin
        data_oC = data_iC;
        if (pop_iC)
          begin
            status_cnt_nC = status_cnt_qVotedC;
            read_pointer_nC = read_pointer_qVotedC;
            write_pointer_nC = write_pointer_qVotedC;
          end

      end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (~rst_niA)
      begin
        read_pointer_qA <= '0;
        write_pointer_qA <= '0;
        status_cnt_qA <= '0;
      end
    else
      begin
        if (flush_iA)
          begin
            read_pointer_qA <= '0;
            write_pointer_qA <= '0;
            status_cnt_qA <= '0;
          end
        else
          begin
            read_pointer_qA <= read_pointer_nA;
            write_pointer_qA <= write_pointer_nA;
            status_cnt_qA <= status_cnt_nA;
          end
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (~rst_niB)
      begin
        read_pointer_qB <= '0;
        write_pointer_qB <= '0;
        status_cnt_qB <= '0;
      end
    else
      begin
        if (flush_iB)
          begin
            read_pointer_qB <= '0;
            write_pointer_qB <= '0;
            status_cnt_qB <= '0;
          end
        else
          begin
            read_pointer_qB <= read_pointer_nB;
            write_pointer_qB <= write_pointer_nB;
            status_cnt_qB <= status_cnt_nB;
          end
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (~rst_niC)
      begin
        read_pointer_qC <= '0;
        write_pointer_qC <= '0;
        status_cnt_qC <= '0;
      end
    else
      begin
        if (flush_iC)
          begin
            read_pointer_qC <= '0;
            write_pointer_qC <= '0;
            status_cnt_qC <= '0;
          end
        else
          begin
            read_pointer_qC <= read_pointer_nC;
            write_pointer_qC <= write_pointer_nC;
            status_cnt_qC <= status_cnt_nC;
          end
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (~rst_niA)
      begin
        mem_qA <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockA)
        begin
          mem_qA <= mem_nA;
        end
      else
        begin
          mem_qA <= mem_qVotedA;
        end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (~rst_niB)
      begin
        mem_qB <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockB)
        begin
          mem_qB <= mem_nB;
        end
      else
        begin
          mem_qB <= mem_qVotedB;
        end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (~rst_niC)
      begin
        mem_qC <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockC)
        begin
          mem_qC <= mem_nC;
        end
      else
        begin
          mem_qC <= mem_qVotedC;
        end
  end

majorityVoter #(.WIDTH( $size(dtype)*FifoDepth)) mem_qVoterA (
    .inA(mem_qA),
    .inB(mem_qB),
    .inC(mem_qC),
    .out(mem_qVotedA),
    .tmrErr(mem_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) read_pointer_qVoterA (
    .inA(read_pointer_qA),
    .inB(read_pointer_qB),
    .inC(read_pointer_qC),
    .out(read_pointer_qVotedA),
    .tmrErr(read_pointer_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH)>0) ? (ADDR_DEPTH) : - ( ADDR_DEPTH ) )+1) )) status_cnt_qVoterA (
    .inA(status_cnt_qA),
    .inB(status_cnt_qB),
    .inC(status_cnt_qC),
    .out(status_cnt_qVotedA),
    .tmrErr(status_cnt_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) write_pointer_qVoterA (
    .inA(write_pointer_qA),
    .inB(write_pointer_qB),
    .inC(write_pointer_qC),
    .out(write_pointer_qVotedA),
    .tmrErr(write_pointer_qTmrErrorA)
  );
assign tmrErrorA = mem_qTmrErrorA|read_pointer_qTmrErrorA|status_cnt_qTmrErrorA|write_pointer_qTmrErrorA;

majorityVoter #(.WIDTH( $size(dtype)*FifoDepth)) mem_qVoterB (
    .inA(mem_qA),
    .inB(mem_qB),
    .inC(mem_qC),
    .out(mem_qVotedB),
    .tmrErr(mem_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) read_pointer_qVoterB (
    .inA(read_pointer_qA),
    .inB(read_pointer_qB),
    .inC(read_pointer_qC),
    .out(read_pointer_qVotedB),
    .tmrErr(read_pointer_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH)>0) ? (ADDR_DEPTH) : - ( ADDR_DEPTH ) )+1) )) status_cnt_qVoterB (
    .inA(status_cnt_qA),
    .inB(status_cnt_qB),
    .inC(status_cnt_qC),
    .out(status_cnt_qVotedB),
    .tmrErr(status_cnt_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) write_pointer_qVoterB (
    .inA(write_pointer_qA),
    .inB(write_pointer_qB),
    .inC(write_pointer_qC),
    .out(write_pointer_qVotedB),
    .tmrErr(write_pointer_qTmrErrorB)
  );
assign tmrErrorB = mem_qTmrErrorB|read_pointer_qTmrErrorB|status_cnt_qTmrErrorB|write_pointer_qTmrErrorB;

majorityVoter #(.WIDTH( $size(dtype)*FifoDepth)) mem_qVoterC (
    .inA(mem_qA),
    .inB(mem_qB),
    .inC(mem_qC),
    .out(mem_qVotedC),
    .tmrErr(mem_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) read_pointer_qVoterC (
    .inA(read_pointer_qA),
    .inB(read_pointer_qB),
    .inC(read_pointer_qC),
    .out(read_pointer_qVotedC),
    .tmrErr(read_pointer_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH)>0) ? (ADDR_DEPTH) : - ( ADDR_DEPTH ) )+1) )) status_cnt_qVoterC (
    .inA(status_cnt_qA),
    .inB(status_cnt_qB),
    .inC(status_cnt_qC),
    .out(status_cnt_qVotedC),
    .tmrErr(status_cnt_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) write_pointer_qVoterC (
    .inA(write_pointer_qA),
    .inB(write_pointer_qB),
    .inC(write_pointer_qC),
    .out(write_pointer_qVotedC),
    .tmrErr(write_pointer_qTmrErrorC)
  );
assign tmrErrorC = mem_qTmrErrorC|read_pointer_qTmrErrorC|status_cnt_qTmrErrorC|write_pointer_qTmrErrorC;
endmodule

