/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/gpioTMR.sv                                                                  *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:09                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/gpio.sv                                                                       *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:26.401273                                         *
 *           File Size         : 6652                                                               *
 *           MD5 hash          : 520bd45e87b8309471dfc6a794453eaf                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module gpioTMR #(
  parameter obi_pkg::obi_cfg_t ObiCfg = obi_pkg::ObiDefaultConfig,
  parameter type obi_req_t         = logic,
  parameter type obi_rsp_t         = logic,
  parameter int NrSyncStages = 2,
  parameter int unsigned GpioCount = 16
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [GpioCount - 1:0] gpio_iA,
  input logic [GpioCount - 1:0] gpio_iB,
  input logic [GpioCount - 1:0] gpio_iC,
  output logic [GpioCount - 1:0] gpio_oA,
  output logic [GpioCount - 1:0] gpio_oB,
  output logic [GpioCount - 1:0] gpio_oC,
  output logic [GpioCount - 1:0] gpio_out_en_oA,
  output logic [GpioCount - 1:0] gpio_out_en_oB,
  output logic [GpioCount - 1:0] gpio_out_en_oC,
  output logic [GpioCount - 1:0] gpio_in_sync_oA,
  output logic [GpioCount - 1:0] gpio_in_sync_oB,
  output logic [GpioCount - 1:0] gpio_in_sync_oC,
  output logic interrupt_oA,
  output logic interrupt_oB,
  output logic interrupt_oC,
  input obi_req_t obi_req_iA,
  input obi_req_t obi_req_iB,
  input obi_req_t obi_req_iC,
  output obi_rsp_t obi_rsp_oA,
  output obi_rsp_t obi_rsp_oB,
  output obi_rsp_t obi_rsp_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import gpio_reg_pkg::*;
wor [GpioCount-1:0] serial_qTmrErrorC;
wor [GpioCount-1:0] i_synctmrErrorC;
wor i_reg_filetmrErrorC;
wor [GpioCount-1:0] serial_qTmrErrorB;
wor [GpioCount-1:0] i_synctmrErrorB;
wor i_reg_filetmrErrorB;
wor [GpioCount-1:0] serial_qTmrErrorA;
wor [GpioCount-1:0] i_synctmrErrorA;
wor i_reg_filetmrErrorA;
gpio_reg2hw_t [GpioCount - 1:0] reg2hwA;
gpio_reg2hw_t [GpioCount - 1:0] reg2hwB;
gpio_reg2hw_t [GpioCount - 1:0] reg2hwC;
gpio_hw2reg_t [GpioCount - 1:0] hw2regA;
gpio_hw2reg_t [GpioCount - 1:0] hw2regB;
gpio_hw2reg_t [GpioCount - 1:0] hw2regC;
logic [GpioCount - 1:0] gpio_in_syncA;
logic [GpioCount - 1:0] gpio_in_syncB;
logic [GpioCount - 1:0] gpio_in_syncC;
logic [GpioCount - 1:0] gpio_edgeA;
logic [GpioCount - 1:0] gpio_edgeB;
logic [GpioCount - 1:0] gpio_edgeC;
logic [GpioCount - 1:0] gpio_intrptA;
logic [GpioCount - 1:0] gpio_intrptB;
logic [GpioCount - 1:0] gpio_intrptC;
logic gpio_intrpt_pendingA;
logic gpio_intrpt_pendingB;
logic gpio_intrpt_pendingC;

gpio_reg_topTMR #(.obi_req_t(obi_req_t), .obi_rsp_t(obi_rsp_t), .GpioCount(GpioCount)) i_reg_file (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .obi_req_iA(obi_req_iA),
    .obi_req_iB(obi_req_iB),
    .obi_req_iC(obi_req_iC),
    .obi_rsp_oA(obi_rsp_oA),
    .obi_rsp_oB(obi_rsp_oB),
    .obi_rsp_oC(obi_rsp_oC),
    .reg2hwA(reg2hwA),
    .reg2hwB(reg2hwB),
    .reg2hwC(reg2hwC),
    .hw2regA(hw2regA),
    .hw2regB(hw2regB),
    .hw2regC(hw2regC),
    .tmrErrorA(i_reg_filetmrErrorA),
    .tmrErrorB(i_reg_filetmrErrorB),
    .tmrErrorC(i_reg_filetmrErrorC)
  );
assign gpio_in_sync_oA = gpio_in_syncA;
assign gpio_in_sync_oB = gpio_in_syncB;
assign gpio_in_sync_oC = gpio_in_syncC;
for(genvar idx = 0; idx<GpioCount; idx++)
  begin : gen_gpios
logic f_edgeA;
logic f_edgeB;
logic f_edgeC;
logic r_edgeA;
logic r_edgeB;
logic r_edgeC;
logic serial_dA;
logic serial_dB;
logic serial_dC;
logic serial_qA;
logic serial_qB;
logic serial_qC;
logic serial_qVotedA;
logic serial_qVotedB;
logic serial_qVotedC;

    syncTMR #(.STAGES(NrSyncStages)) i_sync (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .serial_iA(gpio_iA[idx]),
        .serial_iB(gpio_iB[idx]),
        .serial_iC(gpio_iC[idx]),
        .serial_oA(serial_dA),
        .serial_oB(serial_dB),
        .serial_oC(serial_dC),
        .tmrErrorA(i_synctmrErrorA[idx]),
        .tmrErrorB(i_synctmrErrorB[idx]),
        .tmrErrorC(i_synctmrErrorC[idx])
      );

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            serial_qA <= '0;
          end
        else
          begin
            serial_qA <= serial_dA;
          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            serial_qB <= '0;
          end
        else
          begin
            serial_qB <= serial_dB;
          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            serial_qC <= '0;
          end
        else
          begin
            serial_qC <= serial_dC;
          end
      end
    assign f_edgeA =  (~ serial_dA ) &serial_qVotedA;
    assign f_edgeB =  (~ serial_dB ) &serial_qVotedB;
    assign f_edgeC =  (~ serial_dC ) &serial_qVotedC;
    assign r_edgeA = serial_dA& (~ serial_qVotedA ) ;
    assign r_edgeB = serial_dB& (~ serial_qVotedB ) ;
    assign r_edgeC = serial_dC& (~ serial_qVotedC ) ;
    assign gpio_edgeA[idx] = reg2hwA[idx].intrpt_edge ? r_edgeA : f_edgeA;
    assign gpio_edgeB[idx] = reg2hwB[idx].intrpt_edge ? r_edgeB : f_edgeB;
    assign gpio_edgeC[idx] = reg2hwC[idx].intrpt_edge ? r_edgeC : f_edgeC;
    assign gpio_in_syncA[idx] = serial_qVotedA;
    assign gpio_in_syncB[idx] = serial_qVotedB;
    assign gpio_in_syncC[idx] = serial_qVotedC;
logic is_inputA;
logic is_inputB;
logic is_inputC;
logic is_outputA;
logic is_outputB;
logic is_outputC;
    assign is_inputA = reg2hwA[idx].en&~reg2hwA[idx].dir;
    assign is_inputB = reg2hwB[idx].en&~reg2hwB[idx].dir;
    assign is_inputC = reg2hwC[idx].en&~reg2hwC[idx].dir;
    assign is_outputA = reg2hwA[idx].en&reg2hwA[idx].dir;
    assign is_outputB = reg2hwB[idx].en&reg2hwB[idx].dir;
    assign is_outputC = reg2hwC[idx].en&reg2hwC[idx].dir;
    assign hw2regA[idx].sync_in = gpio_in_syncA[idx]&is_inputA;
    assign hw2regB[idx].sync_in = gpio_in_syncB[idx]&is_inputB;
    assign hw2regC[idx].sync_in = gpio_in_syncC[idx]&is_inputC;
    assign gpio_oA[idx] = reg2hwA[idx].out&is_outputA;
    assign gpio_oB[idx] = reg2hwB[idx].out&is_outputB;
    assign gpio_oC[idx] = reg2hwC[idx].out&is_outputC;
    assign gpio_out_en_oA[idx] = is_outputA;
    assign gpio_out_en_oB[idx] = is_outputB;
    assign gpio_out_en_oC[idx] = is_outputC;

    always_comb
      begin
        hw2regA[idx].out = '0;
        hw2regA[idx].out_valid = '0;
        if (is_outputA&reg2hwA[idx].toggle)
          begin
            hw2regA[idx].out = ~reg2hwA[idx].out;
            hw2regA[idx].out_valid = 1'b1;
          end

      end

    always_comb
      begin
        hw2regB[idx].out = '0;
        hw2regB[idx].out_valid = '0;
        if (is_outputB&reg2hwB[idx].toggle)
          begin
            hw2regB[idx].out = ~reg2hwB[idx].out;
            hw2regB[idx].out_valid = 1'b1;
          end

      end

    always_comb
      begin
        hw2regC[idx].out = '0;
        hw2regC[idx].out_valid = '0;
        if (is_outputC&reg2hwC[idx].toggle)
          begin
            hw2regC[idx].out = ~reg2hwC[idx].out;
            hw2regC[idx].out_valid = 1'b1;
          end

      end
    assign gpio_intrptA[idx] = gpio_edgeA[idx]&reg2hwA[idx].intrpt_en&is_inputA;
    assign gpio_intrptB[idx] = gpio_edgeB[idx]&reg2hwB[idx].intrpt_en&is_inputB;
    assign gpio_intrptC[idx] = gpio_edgeC[idx]&reg2hwC[idx].intrpt_en&is_inputC;
    assign hw2regA[idx].intrpt = gpio_intrptA[idx];
    assign hw2regB[idx].intrpt = gpio_intrptB[idx];
    assign hw2regC[idx].intrpt = gpio_intrptC[idx];
    assign hw2regA[idx].intrpt_valid = gpio_intrptA[idx];
    assign hw2regB[idx].intrpt_valid = gpio_intrptB[idx];
    assign hw2regC[idx].intrpt_valid = gpio_intrptC[idx];

    majorityVoter serial_qVoterA (
      .inA(serial_qA),
      .inB(serial_qB),
      .inC(serial_qC),
      .out(serial_qVotedA),
      .tmrErr(serial_qTmrErrorA[idx])
    );

    majorityVoter serial_qVoterB (
      .inA(serial_qA),
      .inB(serial_qB),
      .inC(serial_qC),
      .out(serial_qVotedB),
      .tmrErr(serial_qTmrErrorB[idx])
    );

    majorityVoter serial_qVoterC (
        .inA(serial_qA),
        .inB(serial_qB),
        .inC(serial_qC),
        .out(serial_qVotedC),
        .tmrErr(serial_qTmrErrorC[idx])
      );
  end

always_comb
  begin : proc_assign_gpioA
    gpio_intrpt_pendingA = 1'b0;
    for(int idx = 0; idx<GpioCount; idx++)
    begin
      gpio_intrpt_pendingA = gpio_intrpt_pendingA|reg2hwA[idx].intrpt;
    end
  end

always_comb
  begin : proc_assign_gpioB
    gpio_intrpt_pendingB = 1'b0;
    for(int idx = 0; idx<GpioCount; idx++)
    begin
      gpio_intrpt_pendingB = gpio_intrpt_pendingB|reg2hwB[idx].intrpt;
    end
  end

always_comb
  begin : proc_assign_gpioC
    gpio_intrpt_pendingC = 1'b0;
    for(int idx = 0; idx<GpioCount; idx++)
    begin
      gpio_intrpt_pendingC = gpio_intrpt_pendingC|reg2hwC[idx].intrpt;
    end
  end
assign interrupt_oA = gpio_intrpt_pendingA;
assign interrupt_oB = gpio_intrpt_pendingB;
assign interrupt_oC = gpio_intrpt_pendingC;

assign tmrErrorA = i_reg_filetmrErrorA|(|i_synctmrErrorA)|(|serial_qTmrErrorA);

assign tmrErrorB = i_reg_filetmrErrorB|(|i_synctmrErrorB)|(|serial_qTmrErrorB);

assign tmrErrorC = i_reg_filetmrErrorC|(|i_synctmrErrorC)|(|serial_qTmrErrorC);
endmodule

