/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_sram_shimTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:09                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_sram_shim.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.550265                                         *
 *           File Size         : 2403                                                               *
 *           MD5 hash          : 5dedb7536cf5743abd15a486f948521c                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module obi_sram_shimTMR #(
  parameter obi_pkg::obi_cfg_t ObiCfg = obi_pkg::ObiDefaultConfig,
  parameter type               obi_req_t = logic,
  parameter type               obi_rsp_t = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input obi_req_t obi_req_iA,
  input obi_req_t obi_req_iB,
  input obi_req_t obi_req_iC,
  output obi_rsp_t obi_rsp_oA,
  output obi_rsp_t obi_rsp_oB,
  output obi_rsp_t obi_rsp_oC,
  output logic req_oA,
  output logic req_oB,
  output logic req_oC,
  output logic we_oA,
  output logic we_oB,
  output logic we_oC,
  output logic [ObiCfg.AddrWidth - 1:0] addr_oA,
  output logic [ObiCfg.AddrWidth - 1:0] addr_oB,
  output logic [ObiCfg.AddrWidth - 1:0] addr_oC,
  output logic [ObiCfg.DataWidth - 1:0] wdata_oA,
  output logic [ObiCfg.DataWidth - 1:0] wdata_oB,
  output logic [ObiCfg.DataWidth - 1:0] wdata_oC,
  output logic [ObiCfg.DataWidth / 8 - 1:0] be_oA,
  output logic [ObiCfg.DataWidth / 8 - 1:0] be_oB,
  output logic [ObiCfg.DataWidth / 8 - 1:0] be_oC,
  input logic gnt_iA,
  input logic gnt_iB,
  input logic gnt_iC,
  input logic [ObiCfg.DataWidth - 1:0] rdata_iA,
  input logic [ObiCfg.DataWidth - 1:0] rdata_iB,
  input logic [ObiCfg.DataWidth - 1:0] rdata_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor rvalid_qTmrErrorC;
wor id_qTmrErrorC;
wor rvalid_qTmrErrorB;
wor id_qTmrErrorB;
wor rvalid_qTmrErrorA;
wor id_qTmrErrorA;
logic rvalid_dA;
logic rvalid_dB;
logic rvalid_dC;
logic rvalid_qA;
logic rvalid_qB;
logic rvalid_qC;
logic rvalid_qVotedA;
logic rvalid_qVotedB;
logic rvalid_qVotedC;
logic [ObiCfg.IdWidth - 1:0] id_dA;
logic [ObiCfg.IdWidth - 1:0] id_dB;
logic [ObiCfg.IdWidth - 1:0] id_dC;
logic [ObiCfg.IdWidth - 1:0] id_qA;
logic [ObiCfg.IdWidth - 1:0] id_qB;
logic [ObiCfg.IdWidth - 1:0] id_qC;
logic [ObiCfg.IdWidth - 1:0] id_qVotedA;
logic [ObiCfg.IdWidth - 1:0] id_qVotedB;
logic [ObiCfg.IdWidth - 1:0] id_qVotedC;
assign req_oA = obi_req_iA.req;
assign req_oB = obi_req_iB.req;
assign req_oC = obi_req_iC.req;
assign we_oA = obi_req_iA.a.we;
assign we_oB = obi_req_iB.a.we;
assign we_oC = obi_req_iC.a.we;
assign addr_oA = obi_req_iA.a.addr;
assign addr_oB = obi_req_iB.a.addr;
assign addr_oC = obi_req_iC.a.addr;
assign wdata_oA = obi_req_iA.a.wdata;
assign wdata_oB = obi_req_iB.a.wdata;
assign wdata_oC = obi_req_iC.a.wdata;
assign be_oA = obi_req_iA.a.be;
assign be_oB = obi_req_iB.a.be;
assign be_oC = obi_req_iC.a.be;

always_comb
  begin
    obi_rsp_oA = '0;
    obi_rsp_oA.gnt = gnt_iA;
    obi_rsp_oA.rvalid = rvalid_qVotedA;
    obi_rsp_oA.r.rdata = rdata_iA;
    obi_rsp_oA.r.rid = id_qVotedA;
    obi_rsp_oA.r.err = 1'b0;
  end

always_comb
  begin
    obi_rsp_oB = '0;
    obi_rsp_oB.gnt = gnt_iB;
    obi_rsp_oB.rvalid = rvalid_qVotedB;
    obi_rsp_oB.r.rdata = rdata_iB;
    obi_rsp_oB.r.rid = id_qVotedB;
    obi_rsp_oB.r.err = 1'b0;
  end

always_comb
  begin
    obi_rsp_oC = '0;
    obi_rsp_oC.gnt = gnt_iC;
    obi_rsp_oC.rvalid = rvalid_qVotedC;
    obi_rsp_oC.r.rdata = rdata_iC;
    obi_rsp_oC.r.rid = id_qVotedC;
    obi_rsp_oC.r.err = 1'b0;
  end
assign rvalid_dA = obi_req_iA.req&obi_rsp_oA.gnt;
assign rvalid_dB = obi_req_iB.req&obi_rsp_oB.gnt;
assign rvalid_dC = obi_req_iC.req&obi_rsp_oC.gnt;
assign id_dA = obi_req_iA.a.aid;
assign id_dB = obi_req_iB.a.aid;
assign id_dC = obi_req_iC.a.aid;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : proc_sram_stateA
    if (!rst_niA)
      begin
        rvalid_qA <= 1'b0;
        id_qA <= '0;
      end
    else
      begin
        rvalid_qA <= rvalid_dA;
        id_qA <= id_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : proc_sram_stateB
    if (!rst_niB)
      begin
        rvalid_qB <= 1'b0;
        id_qB <= '0;
      end
    else
      begin
        rvalid_qB <= rvalid_dB;
        id_qB <= id_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : proc_sram_stateC
    if (!rst_niC)
      begin
        rvalid_qC <= 1'b0;
        id_qC <= '0;
      end
    else
      begin
        rvalid_qC <= rvalid_dC;
        id_qC <= id_dC;
      end
  end

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterA (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedA),
    .tmrErr(id_qTmrErrorA)
  );

majorityVoter rvalid_qVoterA (
    .inA(rvalid_qA),
    .inB(rvalid_qB),
    .inC(rvalid_qC),
    .out(rvalid_qVotedA),
    .tmrErr(rvalid_qTmrErrorA)
  );
assign tmrErrorA = id_qTmrErrorA|rvalid_qTmrErrorA;

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterB (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedB),
    .tmrErr(id_qTmrErrorB)
  );

majorityVoter rvalid_qVoterB (
    .inA(rvalid_qA),
    .inB(rvalid_qB),
    .inC(rvalid_qC),
    .out(rvalid_qVotedB),
    .tmrErr(rvalid_qTmrErrorB)
  );
assign tmrErrorB = id_qTmrErrorB|rvalid_qTmrErrorB;

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterC (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedC),
    .tmrErr(id_qTmrErrorC)
  );

majorityVoter rvalid_qVoterC (
    .inA(rvalid_qA),
    .inB(rvalid_qB),
    .inC(rvalid_qC),
    .out(rvalid_qVotedC),
    .tmrErr(rvalid_qTmrErrorC)
  );
assign tmrErrorC = id_qTmrErrorC|rvalid_qTmrErrorC;
endmodule

