/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_uart_registerTMR.sv                                                     *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:13                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_uart_register.sv                                                          *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-12 14:35:25.630266                                         *
 *           File Size         : 11587                                                              *
 *           MD5 hash          : 51b41ff2d4a5a8253e155856e5b86413                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module obi_uart_registerTMR import obi_uart_pkg::*; #(
  parameter obi_pkg::obi_cfg_t ObiCfg = obi_pkg::ObiDefaultConfig,
  parameter type               obi_req_t = logic,
  parameter type               obi_rsp_t = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input obi_req_t obi_req_iA,
  input obi_req_t obi_req_iB,
  input obi_req_t obi_req_iC,
  output obi_rsp_t obi_rsp_oA,
  output obi_rsp_t obi_rsp_oB,
  output obi_rsp_t obi_rsp_oC,
  output reg_read_t reg_read_oA,
  output reg_read_t reg_read_oB,
  output reg_read_t reg_read_oC,
  input reg_write_t reg_write_iA,
  input reg_write_t reg_write_iB,
  input reg_write_t reg_write_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire word_addr_qTmrErrorC;
wire we_qTmrErrorC;
wire w_err_qTmrErrorC;
wire valid_qTmrErrorC;
wire req_qTmrErrorC;
wire reg_qTmrErrorC;
wire id_qTmrErrorC;
wire word_addr_qTmrErrorB;
wire we_qTmrErrorB;
wire w_err_qTmrErrorB;
wire valid_qTmrErrorB;
wire req_qTmrErrorB;
wire reg_qTmrErrorB;
wire id_qTmrErrorB;
wire word_addr_qTmrErrorA;
wire we_qTmrErrorA;
wire w_err_qTmrErrorA;
wire valid_qTmrErrorA;
wire req_qTmrErrorA;
wire reg_qTmrErrorA;
wire id_qTmrErrorA;
logic [ObiCfg.DataWidth - 1:0] rsp_dataA;
logic [ObiCfg.DataWidth - 1:0] rsp_dataB;
logic [ObiCfg.DataWidth - 1:0] rsp_dataC;
logic valid_dA;
logic valid_dB;
logic valid_dC;
logic valid_qA;
logic valid_qB;
logic valid_qC;
logic valid_qVotedA;
logic valid_qVotedB;
logic valid_qVotedC;
logic errA;
logic errB;
logic errC;
logic w_err_dA;
logic w_err_dB;
logic w_err_dC;
logic w_err_qA;
logic w_err_qB;
logic w_err_qC;
logic w_err_qVotedA;
logic w_err_qVotedB;
logic w_err_qVotedC;
logic [AddressBits - 1:0] word_addr_dA;
logic [AddressBits - 1:0] word_addr_dB;
logic [AddressBits - 1:0] word_addr_dC;
logic [AddressBits - 1:0] word_addr_qA;
logic [AddressBits - 1:0] word_addr_qB;
logic [AddressBits - 1:0] word_addr_qC;
logic [AddressBits - 1:0] word_addr_qVotedA;
logic [AddressBits - 1:0] word_addr_qVotedB;
logic [AddressBits - 1:0] word_addr_qVotedC;
logic [ObiCfg.IdWidth - 1:0] id_dA;
logic [ObiCfg.IdWidth - 1:0] id_dB;
logic [ObiCfg.IdWidth - 1:0] id_dC;
logic [ObiCfg.IdWidth - 1:0] id_qA;
logic [ObiCfg.IdWidth - 1:0] id_qB;
logic [ObiCfg.IdWidth - 1:0] id_qC;
logic [ObiCfg.IdWidth - 1:0] id_qVotedA;
logic [ObiCfg.IdWidth - 1:0] id_qVotedB;
logic [ObiCfg.IdWidth - 1:0] id_qVotedC;
logic we_dA;
logic we_dB;
logic we_dC;
logic we_qA;
logic we_qB;
logic we_qC;
logic we_qVotedA;
logic we_qVotedB;
logic we_qVotedC;
logic req_dA;
logic req_dB;
logic req_dC;
logic req_qA;
logic req_qB;
logic req_qC;
logic req_qVotedA;
logic req_qVotedB;
logic req_qVotedC;

always_comb
  begin
    obi_rsp_oA = '0;
    obi_rsp_oA.r.rdata = rsp_dataA;
    obi_rsp_oA.r.rid = id_qVotedA;
    obi_rsp_oA.r.err = errA;
    obi_rsp_oA.gnt = obi_req_iA.req;
    obi_rsp_oA.rvalid = valid_qVotedA;
  end

always_comb
  begin
    obi_rsp_oB = '0;
    obi_rsp_oB.r.rdata = rsp_dataB;
    obi_rsp_oB.r.rid = id_qVotedB;
    obi_rsp_oB.r.err = errB;
    obi_rsp_oB.gnt = obi_req_iB.req;
    obi_rsp_oB.rvalid = valid_qVotedB;
  end

always_comb
  begin
    obi_rsp_oC = '0;
    obi_rsp_oC.r.rdata = rsp_dataC;
    obi_rsp_oC.r.rid = id_qVotedC;
    obi_rsp_oC.r.err = errC;
    obi_rsp_oC.gnt = obi_req_iC.req;
    obi_rsp_oC.rvalid = valid_qVotedC;
  end
assign id_dA = obi_req_iA.a.aid;
assign id_dB = obi_req_iB.a.aid;
assign id_dC = obi_req_iC.a.aid;
assign valid_dA = obi_req_iA.req;
assign valid_dB = obi_req_iB.req;
assign valid_dC = obi_req_iC.req;
assign word_addr_dA = obi_req_iA.a.addr[AddressOffset+:AddressBits];
assign word_addr_dB = obi_req_iB.a.addr[AddressOffset+:AddressBits];
assign word_addr_dC = obi_req_iC.a.addr[AddressOffset+:AddressBits];
assign we_dA = obi_req_iA.a.we;
assign we_dB = obi_req_iB.a.we;
assign we_dC = obi_req_iC.a.we;
assign req_dA = obi_req_iA.req;
assign req_dB = obi_req_iB.req;
assign req_dC = obi_req_iC.req;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        id_qA <=  ('0) ;
      end
    else
      begin
        id_qA <=  (id_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        id_qB <=  ('0) ;
      end
    else
      begin
        id_qB <=  (id_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        id_qC <=  ('0) ;
      end
    else
      begin
        id_qC <=  (id_dC) ;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        valid_qA <=  ('0) ;
      end
    else
      begin
        valid_qA <=  (valid_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        valid_qB <=  ('0) ;
      end
    else
      begin
        valid_qB <=  (valid_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        valid_qC <=  ('0) ;
      end
    else
      begin
        valid_qC <=  (valid_dC) ;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        word_addr_qA <=  ('0) ;
      end
    else
      begin
        word_addr_qA <=  (word_addr_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        word_addr_qB <=  ('0) ;
      end
    else
      begin
        word_addr_qB <=  (word_addr_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        word_addr_qC <=  ('0) ;
      end
    else
      begin
        word_addr_qC <=  (word_addr_dC) ;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        we_qA <=  ('0) ;
      end
    else
      begin
        we_qA <=  (we_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        we_qB <=  ('0) ;
      end
    else
      begin
        we_qB <=  (we_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        we_qC <=  ('0) ;
      end
    else
      begin
        we_qC <=  (we_dC) ;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        w_err_qA <=  ('0) ;
      end
    else
      begin
        w_err_qA <=  (w_err_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        w_err_qB <=  ('0) ;
      end
    else
      begin
        w_err_qB <=  (w_err_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        w_err_qC <=  ('0) ;
      end
    else
      begin
        w_err_qC <=  (w_err_dC) ;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        req_qA <=  ('0) ;
      end
    else
      begin
        req_qA <=  (req_dA) ;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        req_qB <=  ('0) ;
      end
    else
      begin
        req_qB <=  (req_dB) ;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        req_qC <=  ('0) ;
      end
    else
      begin
        req_qC <=  (req_dC) ;
      end
  end
uart_reg_fields_t reg_dA;
uart_reg_fields_t reg_dB;
uart_reg_fields_t reg_dC;
uart_reg_fields_t reg_qA;
uart_reg_fields_t reg_qB;
uart_reg_fields_t reg_qC;
uart_reg_fields_t reg_qVotedA;
uart_reg_fields_t reg_qVotedB;
uart_reg_fields_t reg_qVotedC;
uart_reg_fields_t new_regA;
uart_reg_fields_t new_regB;
uart_reg_fields_t new_regC;
rx_reg_write_t write_rxA;
rx_reg_write_t write_rxB;
rx_reg_write_t write_rxC;
tx_reg_write_t write_txA;
tx_reg_write_t write_txB;
tx_reg_write_t write_txC;
assign write_txA = reg_write_iA.tx;
assign write_txB = reg_write_iB.tx;
assign write_txC = reg_write_iC.tx;
assign write_rxA = reg_write_iA.rx;
assign write_rxB = reg_write_iB.rx;
assign write_rxC = reg_write_iC.rx;
assign reg_read_oA.thr = reg_qVotedA.THR;
assign reg_read_oB.thr = reg_qVotedB.THR;
assign reg_read_oC.thr = reg_qVotedC.THR;
assign reg_read_oA.ier = reg_qVotedA.IER;
assign reg_read_oB.ier = reg_qVotedB.IER;
assign reg_read_oC.ier = reg_qVotedC.IER;
assign reg_read_oA.isr = reg_write_iA.isr;
assign reg_read_oB.isr = reg_write_iB.isr;
assign reg_read_oC.isr = reg_write_iC.isr;
assign reg_read_oA.fcr = reg_qVotedA.FCR;
assign reg_read_oB.fcr = reg_qVotedB.FCR;
assign reg_read_oC.fcr = reg_qVotedC.FCR;
assign reg_read_oA.lcr = reg_qVotedA.LCR;
assign reg_read_oB.lcr = reg_qVotedB.LCR;
assign reg_read_oC.lcr = reg_qVotedC.LCR;
assign reg_read_oA.mcr = reg_qVotedA.MCR;
assign reg_read_oB.mcr = reg_qVotedB.MCR;
assign reg_read_oC.mcr = reg_qVotedC.MCR;
assign reg_read_oA.dll = reg_qVotedA.DLL;
assign reg_read_oB.dll = reg_qVotedB.DLL;
assign reg_read_oC.dll = reg_qVotedC.DLL;
assign reg_read_oA.dlm = reg_qVotedA.DLM;
assign reg_read_oB.dlm = reg_qVotedB.DLM;
assign reg_read_oC.dlm = reg_qVotedC.DLM;

always_comb
  begin : hw_updateA
    new_regA = reg_qVotedA;
    new_regA.FCR.rx_fifo_rst = write_rxA.fifo_rst_valid ? write_rxA.fifo_rst : reg_qVotedA.FCR.rx_fifo_rst;
    new_regA.FCR.tx_fifo_rst = write_txA.fifo_rst_valid ? write_txA.fifo_rst : reg_qVotedA.FCR.tx_fifo_rst;
    new_regA.RHR = write_rxA.rhr_valid ? write_rxA.rhr : reg_qVotedA.RHR;
    new_regA.LSR.fifo_err = write_rxA.fifo_err_valid ? write_rxA.fifo_err : reg_qVotedA.LSR.fifo_err;
    new_regA.LSR.tx_empty = write_txA.empty_valid ? write_txA.tx_empty : reg_qVotedA.LSR.tx_empty;
    new_regA.LSR.thr_empty = write_txA.thr_valid ? write_txA.thr_empty : reg_qVotedA.LSR.thr_empty;
    new_regA.LSR.break_ind = write_rxA.break_valid ? write_rxA.break_ind : reg_qVotedA.LSR.break_ind;
    new_regA.LSR.frame_err = write_rxA.frame_valid ? write_rxA.frame_err : reg_qVotedA.LSR.frame_err;
    new_regA.LSR.par_err = write_rxA.par_valid ? write_rxA.par_err : reg_qVotedA.LSR.par_err;
    new_regA.LSR.data_ready = write_rxA.dr_valid ? write_rxA.data_ready : reg_qVotedA.LSR.data_ready;
    new_regA.LSR.overrun = write_rxA.overrun_valid ? write_rxA.overrun : reg_qVotedA.LSR.overrun;
    new_regA.MSR.cd = reg_write_iA.modem.cd;
    new_regA.MSR.ri = reg_write_iA.modem.ri;
    new_regA.MSR.dsr = reg_write_iA.modem.dsr;
    new_regA.MSR.cts = reg_write_iA.modem.cts;
    new_regA.MSR.d_cd = reg_qVotedA.MSR.d_cd|reg_write_iA.modem.d_cd;
    new_regA.MSR.te_ri = reg_qVotedA.MSR.te_ri|reg_write_iA.modem.te_ri;
    new_regA.MSR.d_dsr = reg_qVotedA.MSR.d_dsr|reg_write_iA.modem.d_dsr;
    new_regA.MSR.d_cts = reg_qVotedA.MSR.d_cts|reg_write_iA.modem.d_cts;
  end

always_comb
  begin : hw_updateB
    new_regB = reg_qVotedB;
    new_regB.FCR.rx_fifo_rst = write_rxB.fifo_rst_valid ? write_rxB.fifo_rst : reg_qVotedB.FCR.rx_fifo_rst;
    new_regB.FCR.tx_fifo_rst = write_txB.fifo_rst_valid ? write_txB.fifo_rst : reg_qVotedB.FCR.tx_fifo_rst;
    new_regB.RHR = write_rxB.rhr_valid ? write_rxB.rhr : reg_qVotedB.RHR;
    new_regB.LSR.fifo_err = write_rxB.fifo_err_valid ? write_rxB.fifo_err : reg_qVotedB.LSR.fifo_err;
    new_regB.LSR.tx_empty = write_txB.empty_valid ? write_txB.tx_empty : reg_qVotedB.LSR.tx_empty;
    new_regB.LSR.thr_empty = write_txB.thr_valid ? write_txB.thr_empty : reg_qVotedB.LSR.thr_empty;
    new_regB.LSR.break_ind = write_rxB.break_valid ? write_rxB.break_ind : reg_qVotedB.LSR.break_ind;
    new_regB.LSR.frame_err = write_rxB.frame_valid ? write_rxB.frame_err : reg_qVotedB.LSR.frame_err;
    new_regB.LSR.par_err = write_rxB.par_valid ? write_rxB.par_err : reg_qVotedB.LSR.par_err;
    new_regB.LSR.data_ready = write_rxB.dr_valid ? write_rxB.data_ready : reg_qVotedB.LSR.data_ready;
    new_regB.LSR.overrun = write_rxB.overrun_valid ? write_rxB.overrun : reg_qVotedB.LSR.overrun;
    new_regB.MSR.cd = reg_write_iB.modem.cd;
    new_regB.MSR.ri = reg_write_iB.modem.ri;
    new_regB.MSR.dsr = reg_write_iB.modem.dsr;
    new_regB.MSR.cts = reg_write_iB.modem.cts;
    new_regB.MSR.d_cd = reg_qVotedB.MSR.d_cd|reg_write_iB.modem.d_cd;
    new_regB.MSR.te_ri = reg_qVotedB.MSR.te_ri|reg_write_iB.modem.te_ri;
    new_regB.MSR.d_dsr = reg_qVotedB.MSR.d_dsr|reg_write_iB.modem.d_dsr;
    new_regB.MSR.d_cts = reg_qVotedB.MSR.d_cts|reg_write_iB.modem.d_cts;
  end

always_comb
  begin : hw_updateC
    new_regC = reg_qVotedC;
    new_regC.FCR.rx_fifo_rst = write_rxC.fifo_rst_valid ? write_rxC.fifo_rst : reg_qVotedC.FCR.rx_fifo_rst;
    new_regC.FCR.tx_fifo_rst = write_txC.fifo_rst_valid ? write_txC.fifo_rst : reg_qVotedC.FCR.tx_fifo_rst;
    new_regC.RHR = write_rxC.rhr_valid ? write_rxC.rhr : reg_qVotedC.RHR;
    new_regC.LSR.fifo_err = write_rxC.fifo_err_valid ? write_rxC.fifo_err : reg_qVotedC.LSR.fifo_err;
    new_regC.LSR.tx_empty = write_txC.empty_valid ? write_txC.tx_empty : reg_qVotedC.LSR.tx_empty;
    new_regC.LSR.thr_empty = write_txC.thr_valid ? write_txC.thr_empty : reg_qVotedC.LSR.thr_empty;
    new_regC.LSR.break_ind = write_rxC.break_valid ? write_rxC.break_ind : reg_qVotedC.LSR.break_ind;
    new_regC.LSR.frame_err = write_rxC.frame_valid ? write_rxC.frame_err : reg_qVotedC.LSR.frame_err;
    new_regC.LSR.par_err = write_rxC.par_valid ? write_rxC.par_err : reg_qVotedC.LSR.par_err;
    new_regC.LSR.data_ready = write_rxC.dr_valid ? write_rxC.data_ready : reg_qVotedC.LSR.data_ready;
    new_regC.LSR.overrun = write_rxC.overrun_valid ? write_rxC.overrun : reg_qVotedC.LSR.overrun;
    new_regC.MSR.cd = reg_write_iC.modem.cd;
    new_regC.MSR.ri = reg_write_iC.modem.ri;
    new_regC.MSR.dsr = reg_write_iC.modem.dsr;
    new_regC.MSR.cts = reg_write_iC.modem.cts;
    new_regC.MSR.d_cd = reg_qVotedC.MSR.d_cd|reg_write_iC.modem.d_cd;
    new_regC.MSR.te_ri = reg_qVotedC.MSR.te_ri|reg_write_iC.modem.te_ri;
    new_regC.MSR.d_dsr = reg_qVotedC.MSR.d_dsr|reg_write_iC.modem.d_dsr;
    new_regC.MSR.d_cts = reg_qVotedC.MSR.d_cts|reg_write_iC.modem.d_cts;
  end

always_comb
  begin
    errA = w_err_qVotedA;
    w_err_dA = 1'b0;
    reg_read_oA.obi_read_rhr = 1'b0;
    reg_read_oA.obi_read_isr = 1'b0;
    reg_read_oA.obi_read_lsr = 1'b0;
    reg_read_oA.obi_read_msr = 1'b0;
    reg_read_oA.obi_write_thr = 1'b0;
    reg_read_oA.obi_write_dllm = 1'b0;
    rsp_dataA = 32'h0;
    reg_dA = new_regA;
    if (obi_req_iA.req&obi_req_iA.a.we&obi_req_iA.a.be[0])
      begin
        w_err_dA = 1'b0;
        if (~reg_qVotedA.LCR[7])
          begin
            case (word_addr_dA)
              RegAddrTHR : 
                begin
                  reg_dA.THR = obi_req_iA.a.wdata[RegWidth - 1:0];
                  reg_read_oA.obi_write_thr = 1'b1;
                end
              RegAddrIER : 
                begin
                  reg_dA.IER = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrFCR : 
                begin
                  reg_dA.FCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dA.LCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dA.MCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dA = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_dA)
              RegAddrDLL : 
                begin
                  reg_dA.DLL = obi_req_iA.a.wdata[RegWidth - 1:0];
                  reg_read_oA.obi_write_dllm = 1'b1;
                end
              RegAddrDLM : 
                begin
                  reg_dA.DLM = obi_req_iA.a.wdata[RegWidth - 1:0];
                  reg_read_oA.obi_write_dllm = 1'b1;
                end
              RegAddrFCR : 
                begin
                  reg_dA.FCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dA.LCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dA.MCR = obi_req_iA.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dA = 1'b1;
                end
            endcase
          end
      end

    if (req_qVotedA&~we_qVotedA)
      begin
        errA = 1'b0;
        if (~reg_qVotedA.LCR[7])
          begin
            case (word_addr_qVotedA)
              RegAddrRHR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.RHR;
                  reg_read_oA.obi_read_rhr = 1'b1;
                end
              RegAddrIER : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.IER;
                end
              RegAddrISR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_write_iA.isr;
                  reg_read_oA.obi_read_isr = 1'b1;
                end
              RegAddrLCR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.LCR;
                end
              RegAddrMCR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.MCR;
                end
              RegAddrLSR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.LSR;
                  reg_read_oA.obi_read_lsr = 1'b1;
                end
              RegAddrMSR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.MSR;
                  reg_dA.MSR = reg_write_iA.modem;
                end
              RegAddrSPR : 
                begin
                  rsp_dataA[RegWidth - 1:0] = '0;
                end
              default : 
                begin
                  errA = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_qVotedA)
              RegAddrDLL : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.DLL;
                end
              RegAddrDLM : 
                begin
                  rsp_dataA[RegWidth - 1:0] = reg_qVotedA.DLM;
                end
              default : 
                begin
                  errA = 1'b1;
                end
            endcase
          end
      end

  end

always_comb
  begin
    errB = w_err_qVotedB;
    w_err_dB = 1'b0;
    reg_read_oB.obi_read_rhr = 1'b0;
    reg_read_oB.obi_read_isr = 1'b0;
    reg_read_oB.obi_read_lsr = 1'b0;
    reg_read_oB.obi_read_msr = 1'b0;
    reg_read_oB.obi_write_thr = 1'b0;
    reg_read_oB.obi_write_dllm = 1'b0;
    rsp_dataB = 32'h0;
    reg_dB = new_regB;
    if (obi_req_iB.req&obi_req_iB.a.we&obi_req_iB.a.be[0])
      begin
        w_err_dB = 1'b0;
        if (~reg_qVotedB.LCR[7])
          begin
            case (word_addr_dB)
              RegAddrTHR : 
                begin
                  reg_dB.THR = obi_req_iB.a.wdata[RegWidth - 1:0];
                  reg_read_oB.obi_write_thr = 1'b1;
                end
              RegAddrIER : 
                begin
                  reg_dB.IER = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrFCR : 
                begin
                  reg_dB.FCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dB.LCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dB.MCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dB = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_dB)
              RegAddrDLL : 
                begin
                  reg_dB.DLL = obi_req_iB.a.wdata[RegWidth - 1:0];
                  reg_read_oB.obi_write_dllm = 1'b1;
                end
              RegAddrDLM : 
                begin
                  reg_dB.DLM = obi_req_iB.a.wdata[RegWidth - 1:0];
                  reg_read_oB.obi_write_dllm = 1'b1;
                end
              RegAddrFCR : 
                begin
                  reg_dB.FCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dB.LCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dB.MCR = obi_req_iB.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dB = 1'b1;
                end
            endcase
          end
      end

    if (req_qVotedB&~we_qVotedB)
      begin
        errB = 1'b0;
        if (~reg_qVotedB.LCR[7])
          begin
            case (word_addr_qVotedB)
              RegAddrRHR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.RHR;
                  reg_read_oB.obi_read_rhr = 1'b1;
                end
              RegAddrIER : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.IER;
                end
              RegAddrISR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_write_iB.isr;
                  reg_read_oB.obi_read_isr = 1'b1;
                end
              RegAddrLCR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.LCR;
                end
              RegAddrMCR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.MCR;
                end
              RegAddrLSR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.LSR;
                  reg_read_oB.obi_read_lsr = 1'b1;
                end
              RegAddrMSR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.MSR;
                  reg_dB.MSR = reg_write_iB.modem;
                end
              RegAddrSPR : 
                begin
                  rsp_dataB[RegWidth - 1:0] = '0;
                end
              default : 
                begin
                  errB = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_qVotedB)
              RegAddrDLL : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.DLL;
                end
              RegAddrDLM : 
                begin
                  rsp_dataB[RegWidth - 1:0] = reg_qVotedB.DLM;
                end
              default : 
                begin
                  errB = 1'b1;
                end
            endcase
          end
      end

  end

always_comb
  begin
    errC = w_err_qVotedC;
    w_err_dC = 1'b0;
    reg_read_oC.obi_read_rhr = 1'b0;
    reg_read_oC.obi_read_isr = 1'b0;
    reg_read_oC.obi_read_lsr = 1'b0;
    reg_read_oC.obi_read_msr = 1'b0;
    reg_read_oC.obi_write_thr = 1'b0;
    reg_read_oC.obi_write_dllm = 1'b0;
    rsp_dataC = 32'h0;
    reg_dC = new_regC;
    if (obi_req_iC.req&obi_req_iC.a.we&obi_req_iC.a.be[0])
      begin
        w_err_dC = 1'b0;
        if (~reg_qVotedC.LCR[7])
          begin
            case (word_addr_dC)
              RegAddrTHR : 
                begin
                  reg_dC.THR = obi_req_iC.a.wdata[RegWidth - 1:0];
                  reg_read_oC.obi_write_thr = 1'b1;
                end
              RegAddrIER : 
                begin
                  reg_dC.IER = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrFCR : 
                begin
                  reg_dC.FCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dC.LCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dC.MCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dC = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_dC)
              RegAddrDLL : 
                begin
                  reg_dC.DLL = obi_req_iC.a.wdata[RegWidth - 1:0];
                  reg_read_oC.obi_write_dllm = 1'b1;
                end
              RegAddrDLM : 
                begin
                  reg_dC.DLM = obi_req_iC.a.wdata[RegWidth - 1:0];
                  reg_read_oC.obi_write_dllm = 1'b1;
                end
              RegAddrFCR : 
                begin
                  reg_dC.FCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrLCR : 
                begin
                  reg_dC.LCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrMCR : 
                begin
                  reg_dC.MCR = obi_req_iC.a.wdata[RegWidth - 1:0];
                end
              RegAddrSPR : 
                begin
                end
              default : 
                begin
                  w_err_dC = 1'b1;
                end
            endcase
          end
      end

    if (req_qVotedC&~we_qVotedC)
      begin
        errC = 1'b0;
        if (~reg_qVotedC.LCR[7])
          begin
            case (word_addr_qVotedC)
              RegAddrRHR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.RHR;
                  reg_read_oC.obi_read_rhr = 1'b1;
                end
              RegAddrIER : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.IER;
                end
              RegAddrISR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_write_iC.isr;
                  reg_read_oC.obi_read_isr = 1'b1;
                end
              RegAddrLCR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.LCR;
                end
              RegAddrMCR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.MCR;
                end
              RegAddrLSR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.LSR;
                  reg_read_oC.obi_read_lsr = 1'b1;
                end
              RegAddrMSR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.MSR;
                  reg_dC.MSR = reg_write_iC.modem;
                end
              RegAddrSPR : 
                begin
                  rsp_dataC[RegWidth - 1:0] = '0;
                end
              default : 
                begin
                  errC = 1'b1;
                end
            endcase
          end
        else
          begin
            case (word_addr_qVotedC)
              RegAddrDLL : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.DLL;
                end
              RegAddrDLM : 
                begin
                  rsp_dataC[RegWidth - 1:0] = reg_qVotedC.DLM;
                end
              default : 
                begin
                  errC = 1'b1;
                end
            endcase
          end
      end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        reg_qA <= obi_uart_pkg::RegResetVal;
      end
    else
      begin
        reg_qA <= reg_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        reg_qB <= obi_uart_pkg::RegResetVal;
      end
    else
      begin
        reg_qB <= reg_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        reg_qC <= obi_uart_pkg::RegResetVal;
      end
    else
      begin
        reg_qC <= reg_dC;
      end
  end

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterA (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedA),
    .tmrErr(id_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ($size(reg_qVotedA)) )) reg_qVoterA (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedA),
    .tmrErr(reg_qTmrErrorA)
  );

majorityVoter req_qVoterA (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedA),
    .tmrErr(req_qTmrErrorA)
  );

majorityVoter valid_qVoterA (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedA),
    .tmrErr(valid_qTmrErrorA)
  );

majorityVoter w_err_qVoterA (
    .inA(w_err_qA),
    .inB(w_err_qB),
    .inC(w_err_qC),
    .out(w_err_qVotedA),
    .tmrErr(w_err_qTmrErrorA)
  );

majorityVoter we_qVoterA (
    .inA(we_qA),
    .inB(we_qB),
    .inC(we_qC),
    .out(we_qVotedA),
    .tmrErr(we_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((AddressBits-1)>0) ? (AddressBits-1) : - ( AddressBits-1 ) )+1) )) word_addr_qVoterA (
    .inA(word_addr_qA),
    .inB(word_addr_qB),
    .inC(word_addr_qC),
    .out(word_addr_qVotedA),
    .tmrErr(word_addr_qTmrErrorA)
  );
assign tmrErrorA = id_qTmrErrorA|reg_qTmrErrorA|req_qTmrErrorA|valid_qTmrErrorA|w_err_qTmrErrorA|we_qTmrErrorA|word_addr_qTmrErrorA;

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterB (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedB),
    .tmrErr(id_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ($size(reg_qVotedA)) )) reg_qVoterB (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedB),
    .tmrErr(reg_qTmrErrorB)
  );

majorityVoter req_qVoterB (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedB),
    .tmrErr(req_qTmrErrorB)
  );

majorityVoter valid_qVoterB (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedB),
    .tmrErr(valid_qTmrErrorB)
  );

majorityVoter w_err_qVoterB (
    .inA(w_err_qA),
    .inB(w_err_qB),
    .inC(w_err_qC),
    .out(w_err_qVotedB),
    .tmrErr(w_err_qTmrErrorB)
  );

majorityVoter we_qVoterB (
    .inA(we_qA),
    .inB(we_qB),
    .inC(we_qC),
    .out(we_qVotedB),
    .tmrErr(we_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((AddressBits-1)>0) ? (AddressBits-1) : - ( AddressBits-1 ) )+1) )) word_addr_qVoterB (
    .inA(word_addr_qA),
    .inB(word_addr_qB),
    .inC(word_addr_qC),
    .out(word_addr_qVotedB),
    .tmrErr(word_addr_qTmrErrorB)
  );
assign tmrErrorB = id_qTmrErrorB|reg_qTmrErrorB|req_qTmrErrorB|valid_qTmrErrorB|w_err_qTmrErrorB|we_qTmrErrorB|word_addr_qTmrErrorB;

majorityVoter #(.WIDTH( ((((ObiCfg.IdWidth-1)>0) ? (ObiCfg.IdWidth-1) : - ( ObiCfg.IdWidth-1 ) )+1) )) id_qVoterC (
    .inA(id_qA),
    .inB(id_qB),
    .inC(id_qC),
    .out(id_qVotedC),
    .tmrErr(id_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ($size(reg_qVotedA)) )) reg_qVoterC (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedC),
    .tmrErr(reg_qTmrErrorC)
  );

majorityVoter req_qVoterC (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedC),
    .tmrErr(req_qTmrErrorC)
  );

majorityVoter valid_qVoterC (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedC),
    .tmrErr(valid_qTmrErrorC)
  );

majorityVoter w_err_qVoterC (
    .inA(w_err_qA),
    .inB(w_err_qB),
    .inC(w_err_qC),
    .out(w_err_qVotedC),
    .tmrErr(w_err_qTmrErrorC)
  );

majorityVoter we_qVoterC (
    .inA(we_qA),
    .inB(we_qB),
    .inC(we_qC),
    .out(we_qVotedC),
    .tmrErr(we_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((AddressBits-1)>0) ? (AddressBits-1) : - ( AddressBits-1 ) )+1) )) word_addr_qVoterC (
    .inA(word_addr_qA),
    .inB(word_addr_qB),
    .inC(word_addr_qC),
    .out(word_addr_qVotedC),
    .tmrErr(word_addr_qTmrErrorC)
  );
assign tmrErrorC = id_qTmrErrorC|reg_qTmrErrorC|req_qTmrErrorC|valid_qTmrErrorC|w_err_qTmrErrorC|we_qTmrErrorC|word_addr_qTmrErrorC;
endmodule

