/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_cutTMR.sv                                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 18/11/2025 09:21:48                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_cut.sv                                                                    *
 *           Git SHA           : acdf608049d37209b9ed0e5000b76bba5c53f58c (?? tmrg_src/obi_cut.sv)  *
 *           Modification time : 2025-11-18 08:45:16.391189                                         *
 *           File Size         : 2214                                                               *
 *           MD5 hash          : 811f10ba0409e95fbcc44bd1aa61227e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module obi_cutTMR #(
  parameter obi_pkg::obi_cfg_t ObiCfg = obi_pkg::ObiDefaultConfig,
  parameter type               obi_a_chan_t = logic,
  parameter type               obi_r_chan_t = logic,
  parameter type               obi_req_t    = logic,
  parameter type               obi_rsp_t    = logic,
  parameter bit Bypass = 1'b0,
  parameter bit BypassReq = Bypass,
  parameter bit BypassRsp = Bypass
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input obi_req_t sbr_port_req_iA,
  input obi_req_t sbr_port_req_iB,
  input obi_req_t sbr_port_req_iC,
  output obi_rsp_t sbr_port_rsp_oA,
  output obi_rsp_t sbr_port_rsp_oB,
  output obi_rsp_t sbr_port_rsp_oC,
  output obi_req_t mgr_port_req_oA,
  output obi_req_t mgr_port_req_oB,
  output obi_req_t mgr_port_req_oC,
  input obi_rsp_t mgr_port_rsp_iA,
  input obi_rsp_t mgr_port_rsp_iB,
  input obi_rsp_t mgr_port_rsp_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_req_rtmrErrorC;
wire i_reg_atmrErrorC;
wire i_req_rtmrErrorB;
wire i_reg_atmrErrorB;
wire i_req_rtmrErrorA;
wire i_reg_atmrErrorA;

spill_registerTMR #(.T(obi_a_chan_t), .Bypass(BypassReq)) i_reg_a (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .valid_iA(sbr_port_req_iA.req),
    .valid_iB(sbr_port_req_iB.req),
    .valid_iC(sbr_port_req_iC.req),
    .ready_oA(sbr_port_rsp_oA.gnt),
    .ready_oB(sbr_port_rsp_oB.gnt),
    .ready_oC(sbr_port_rsp_oC.gnt),
    .data_iA(sbr_port_req_iA.a),
    .data_iB(sbr_port_req_iB.a),
    .data_iC(sbr_port_req_iC.a),
    .valid_oA(mgr_port_req_oA.req),
    .valid_oB(mgr_port_req_oB.req),
    .valid_oC(mgr_port_req_oC.req),
    .ready_iA(mgr_port_rsp_iA.gnt),
    .ready_iB(mgr_port_rsp_iB.gnt),
    .ready_iC(mgr_port_rsp_iC.gnt),
    .data_oA(mgr_port_req_oA.a),
    .data_oB(mgr_port_req_oB.a),
    .data_oC(mgr_port_req_oC.a),
    .tmrErrorA(i_reg_atmrErrorA),
    .tmrErrorB(i_reg_atmrErrorB),
    .tmrErrorC(i_reg_atmrErrorC)
  );
logic ready_oA;
logic ready_oB;
logic ready_oC;
logic ready_iA;
logic ready_iB;
logic ready_iC;
if (ObiCfg.UseRReady)
  begin : gen_use_rready
    assign mgr_port_req_oA.rready = ready_oA;
    assign mgr_port_req_oB.rready = ready_oB;
    assign mgr_port_req_oC.rready = ready_oC;
    assign ready_iA = sbr_port_req_iA.rready;
    assign ready_iB = sbr_port_req_iB.rready;
    assign ready_iC = sbr_port_req_iC.rready;
  end

else
  begin : gen_no_use_rready
    assign ready_iA = 1'b1;
    assign ready_iB = 1'b1;
    assign ready_iC = 1'b1;
  end

spill_registerTMR #(.T(obi_r_chan_t), .Bypass(BypassRsp)) i_req_r (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .valid_iA(mgr_port_rsp_iA.rvalid),
    .valid_iB(mgr_port_rsp_iB.rvalid),
    .valid_iC(mgr_port_rsp_iC.rvalid),
    .ready_oA(ready_oA),
    .ready_oB(ready_oB),
    .ready_oC(ready_oC),
    .data_iA(mgr_port_rsp_iA.r),
    .data_iB(mgr_port_rsp_iB.r),
    .data_iC(mgr_port_rsp_iC.r),
    .valid_oA(sbr_port_rsp_oA.rvalid),
    .valid_oB(sbr_port_rsp_oB.rvalid),
    .valid_oC(sbr_port_rsp_oC.rvalid),
    .ready_iA(ready_iA),
    .ready_iB(ready_iB),
    .ready_iC(ready_iC),
    .data_oA(sbr_port_rsp_oA.r),
    .data_oB(sbr_port_rsp_oB.r),
    .data_oC(sbr_port_rsp_oC.r),
    .tmrErrorA(i_req_rtmrErrorA),
    .tmrErrorB(i_req_rtmrErrorB),
    .tmrErrorC(i_req_rtmrErrorC)
  );
assign tmrErrorA = i_reg_atmrErrorA|i_req_rtmrErrorA;
assign tmrErrorB = i_reg_atmrErrorB|i_req_rtmrErrorB;
assign tmrErrorC = i_reg_atmrErrorC|i_req_rtmrErrorC;
endmodule

