/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_uart_txTMR.sv                                                           *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:09                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_uart_tx.sv                                                                *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.663266                                         *
 *           File Size         : 12215                                                              *
 *           MD5 hash          : 9565f8991bd3e91a9ea975932287873e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module obi_uart_txTMR (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic baud_rate_edge_iA,
  input logic baud_rate_edge_iB,
  input logic baud_rate_edge_iC,
  input logic double_rate_edge_iA,
  input logic double_rate_edge_iB,
  input logic double_rate_edge_iC,
  output logic txd_oA,
  output logic txd_oB,
  output logic txd_oC,
  input obi_uart_pkg::reg_read_t reg_read_iA,
  input obi_uart_pkg::reg_read_t reg_read_iB,
  input obi_uart_pkg::reg_read_t reg_read_iC,
  output obi_uart_pkg::tx_reg_write_t reg_write_oA,
  output obi_uart_pkg::tx_reg_write_t reg_write_oB,
  output obi_uart_pkg::tx_reg_write_t reg_write_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import obi_uart_pkg::*;
wire txd_qTmrErrorC;
wire tsr_qTmrErrorC;
wire tsr_count_qTmrErrorC;
wire thr_full_qTmrErrorC;
wire state_qTmrErrorC;
wire i_fifo_v3tmrErrorC;
wire txd_qTmrErrorB;
wire tsr_qTmrErrorB;
wire tsr_count_qTmrErrorB;
wire thr_full_qTmrErrorB;
wire state_qTmrErrorB;
wire i_fifo_v3tmrErrorB;
wire txd_qTmrErrorA;
wire tsr_qTmrErrorA;
wire tsr_count_qTmrErrorA;
wire thr_full_qTmrErrorA;
wire state_qTmrErrorA;
wire i_fifo_v3tmrErrorA;
logic fifo_clearA;
logic fifo_clearB;
logic fifo_clearC;
logic fifo_fullA;
logic fifo_fullB;
logic fifo_fullC;
logic fifo_emptyA;
logic fifo_emptyB;
logic fifo_emptyC;
logic [7:0] fifo_data_iA;
logic [7:0] fifo_data_iB;
logic [7:0] fifo_data_iC;
logic [7:0] fifo_data_oA;
logic [7:0] fifo_data_oB;
logic [7:0] fifo_data_oC;
logic fifo_pushA;
logic fifo_pushB;
logic fifo_pushC;
logic fifo_popA;
logic fifo_popB;
logic fifo_popC;
logic [3:0] fifo_usageA;
logic [3:0] fifo_usageB;
logic [3:0] fifo_usageC;
logic thr_full_qA;
logic thr_full_qB;
logic thr_full_qC;
logic thr_full_dA;
logic thr_full_dB;
logic thr_full_dC;
logic thr_full_qVotedA;
logic thr_full_qVotedB;
logic thr_full_qVotedC;
state_type_tx_e state_qA;
state_type_tx_e state_qB;
state_type_tx_e state_qC;
state_type_tx_e state_dA;
state_type_tx_e state_dB;
state_type_tx_e state_dC;
state_type_tx_e state_qVotedA;
state_type_tx_e state_qVotedB;
state_type_tx_e state_qVotedC;
logic [2:0] word_len_bitsA;
logic [2:0] word_len_bitsB;
logic [2:0] word_len_bitsC;
logic [7:0] word_len_maskA;
logic [7:0] word_len_maskB;
logic [7:0] word_len_maskC;
logic tsr_emptyA;
logic tsr_emptyB;
logic tsr_emptyC;
logic tsr_finishA;
logic tsr_finishB;
logic tsr_finishC;
logic [7:0] tsr_qA;
logic [7:0] tsr_qB;
logic [7:0] tsr_qC;
logic [7:0] tsr_dA;
logic [7:0] tsr_dB;
logic [7:0] tsr_dC;
logic [7:0] tsr_qVotedA;
logic [7:0] tsr_qVotedB;
logic [7:0] tsr_qVotedC;
logic [2:0] tsr_count_qA;
logic [2:0] tsr_count_qB;
logic [2:0] tsr_count_qC;
logic [2:0] tsr_count_dA;
logic [2:0] tsr_count_dB;
logic [2:0] tsr_count_dC;
logic [2:0] tsr_count_qVotedA;
logic [2:0] tsr_count_qVotedB;
logic [2:0] tsr_count_qVotedC;
logic txd_qA;
logic txd_qB;
logic txd_qC;
logic txd_dA;
logic txd_dB;
logic txd_dC;
logic txd_qVotedA;
logic txd_qVotedB;
logic txd_qVotedC;

fifo_v3TMR #(.FALL_THROUGH(1'b0), .DATA_WIDTH(8), .DEPTH(16)) i_fifo_v3 (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_iA(fifo_clearA),
    .flush_iB(fifo_clearB),
    .flush_iC(fifo_clearC),
    .testmode_iA(1'b0),
    .testmode_iB(1'b0),
    .testmode_iC(1'b0),
    .full_oA(fifo_fullA),
    .full_oB(fifo_fullB),
    .full_oC(fifo_fullC),
    .empty_oA(fifo_emptyA),
    .empty_oB(fifo_emptyB),
    .empty_oC(fifo_emptyC),
    .usage_oA(fifo_usageA),
    .usage_oB(fifo_usageB),
    .usage_oC(fifo_usageC),
    .data_iA(fifo_data_iA),
    .data_iB(fifo_data_iB),
    .data_iC(fifo_data_iC),
    .push_iA(fifo_pushA),
    .push_iB(fifo_pushB),
    .push_iC(fifo_pushC),
    .data_oA(fifo_data_oA),
    .data_oB(fifo_data_oB),
    .data_oC(fifo_data_oC),
    .pop_iA(fifo_popA),
    .pop_iB(fifo_popB),
    .pop_iC(fifo_popC),
    .tmrErrorA(i_fifo_v3tmrErrorA),
    .tmrErrorB(i_fifo_v3tmrErrorB),
    .tmrErrorC(i_fifo_v3tmrErrorC)
  );

always_comb
  begin
    thr_full_dA = thr_full_qVotedA;
    word_len_maskA = '0;
    fifo_clearA = 1'b0;
    fifo_pushA = 1'b0;
    fifo_data_iA = '0;
    reg_write_oA = '0;
    state_dA = state_qVotedA;
    txd_oA = txd_qVotedA&~reg_read_iA.lcr.set_break;
    txd_dA = txd_qVotedA;
    fifo_popA = 1'b0;
    tsr_dA = tsr_qVotedA;
    tsr_count_dA = tsr_count_qVotedA;
    tsr_finishA = 1'b0;
    tsr_emptyA = 1'b0;
    case (reg_read_iA.lcr.word_len)
      2'b00 : word_len_bitsA = 3'b100;
      2'b01 : word_len_bitsA = 3'b101;
      2'b10 : word_len_bitsA = 3'b110;
      2'b11 : word_len_bitsA = 3'b111;
      default : word_len_bitsA = 3'b111;
    endcase
    for(int i = 0; i<=word_len_bitsA; i = i + 1)
    begin
      word_len_maskA[i] = 1'b1;
    end
    if (reg_read_iA.obi_write_thr)
      begin
        thr_full_dA = 1'b1;
      end

    if (reg_read_iA.obi_write_thr)
      begin
        reg_write_oA.thr_empty = 1'b0;
        reg_write_oA.tx_empty = 1'b0;
        reg_write_oA.thr_valid = 1'b1;
        reg_write_oA.empty_valid = 1'b1;
      end

    if (state_qVotedA==TXDATA&(tsr_count_qVotedA<=word_len_bitsA))
      begin
        txd_dA = tsr_qVotedA[tsr_count_qVotedA];
        if (baud_rate_edge_iA)
          begin
            tsr_count_dA = tsr_count_qVotedA + 1;
            tsr_finishA = (tsr_count_qVotedA==word_len_bitsA) ? 1'b1 : 1'b0;
          end

      end

    case (state_qVotedA)
      TXIDLE : 
        begin
          txd_dA = 1'b1;
          tsr_dA = '0;
          tsr_count_dA = 1'b0;
          tsr_emptyA = 1'b1;
          if (reg_read_iA.fcr.fifo_en)
            begin
              if (~fifo_emptyA&baud_rate_edge_iA)
                begin
                  tsr_dA = fifo_data_oA;
                  fifo_popA = 1'b1;
                  state_dA = TXSTART;
                end

            end
          else
            begin
              if (thr_full_qVotedA&baud_rate_edge_iA)
                begin
                  tsr_dA = reg_read_iA.thr.char_tx&word_len_maskA;
                  thr_full_dA = 1'b0;
                  state_dA = TXSTART;
                end

            end
        end
      TXSTART : 
        begin
          txd_dA = 1'b0;
          if (baud_rate_edge_iA)
            begin
              state_dA = TXDATA;
            end

        end
      TXDATA : 
        begin
          if (tsr_finishA)
            begin
              if (reg_read_iA.lcr.par_en)
                begin
                  state_dA = TXPAR;
                end
              else
                begin
                  state_dA = TXSTOP1;
                end
            end

        end
      TXPAR : 
        begin
          case (reg_read_iA.lcr[5:4])
            2'b00 : txd_dA = ~ (^ tsr_qVotedA ) ;
            2'b01 : txd_dA = ^tsr_qVotedA;
            2'b10 : txd_dA = 1'b1;
            2'b11 : txd_dA = 1'b0;
            default : txd_dA = 1'b0;
          endcase
          if (baud_rate_edge_iA)
            begin
              state_dA = TXSTOP1;
            end

        end
      TXSTOP1 : 
        begin
          txd_dA = 1'b1;
          if (reg_read_iA.lcr.stop_bits)
            begin
              state_dA = TXIDLE;
            end
          else
            if (baud_rate_edge_iA)
              begin
                state_dA = TXSTOP2;
              end

        end
      TXSTOP2 : 
        begin
          txd_dA = 1'b1;
          if (word_len_bitsA==3'b100)
            begin
              if (double_rate_edge_iA)
                begin
                  state_dA = TXIDLE;
                end

            end
          else
            begin
              state_dA = TXIDLE;
            end
        end
      default : state_dA = TXIDLE;
    endcase
    if (reg_read_iA.fcr.fifo_en)
      begin
        fifo_clearA = 1'b0;
        if (reg_read_iA.fcr.tx_fifo_rst)
          begin
            fifo_clearA = 1'b1;
            reg_write_oA.fifo_rst = 1'b0;
            reg_write_oA.fifo_rst_valid = 1'b1;
          end

        if (fifo_emptyA)
          begin
            reg_write_oA.thr_empty = 1'b1;
            reg_write_oA.thr_valid = 1'b1;
            if (tsr_emptyA)
              begin
                reg_write_oA.tx_empty = 1'b1;
                reg_write_oA.empty_valid = 1'b1;
              end

          end

        if (thr_full_qVotedA&(~ fifo_fullA ))
          begin
            fifo_pushA = 1'b1;
            fifo_data_iA = reg_read_iA.thr.char_tx&word_len_maskA;
            thr_full_dA = 1'b0;
          end

      end

    if (~reg_read_iA.fcr.fifo_en)
      begin
        fifo_clearA = 1'b1;
        if (~thr_full_qVotedA)
          begin
            reg_write_oA.thr_empty = 1'b1;
            reg_write_oA.thr_valid = 1'b1;
            if (tsr_emptyA)
              begin
                reg_write_oA.tx_empty = 1'b1;
                reg_write_oA.empty_valid = 1'b1;
              end

          end

      end

  end

always_comb
  begin
    thr_full_dB = thr_full_qVotedB;
    word_len_maskB = '0;
    fifo_clearB = 1'b0;
    fifo_pushB = 1'b0;
    fifo_data_iB = '0;
    reg_write_oB = '0;
    state_dB = state_qVotedB;
    txd_oB = txd_qVotedB&~reg_read_iB.lcr.set_break;
    txd_dB = txd_qVotedB;
    fifo_popB = 1'b0;
    tsr_dB = tsr_qVotedB;
    tsr_count_dB = tsr_count_qVotedB;
    tsr_finishB = 1'b0;
    tsr_emptyB = 1'b0;
    case (reg_read_iB.lcr.word_len)
      2'b00 : word_len_bitsB = 3'b100;
      2'b01 : word_len_bitsB = 3'b101;
      2'b10 : word_len_bitsB = 3'b110;
      2'b11 : word_len_bitsB = 3'b111;
      default : word_len_bitsB = 3'b111;
    endcase
    for(int i = 0; i<=word_len_bitsB; i = i + 1)
    begin
      word_len_maskB[i] = 1'b1;
    end
    if (reg_read_iB.obi_write_thr)
      begin
        thr_full_dB = 1'b1;
      end

    if (reg_read_iB.obi_write_thr)
      begin
        reg_write_oB.thr_empty = 1'b0;
        reg_write_oB.tx_empty = 1'b0;
        reg_write_oB.thr_valid = 1'b1;
        reg_write_oB.empty_valid = 1'b1;
      end

    if (state_qVotedB==TXDATA&(tsr_count_qVotedB<=word_len_bitsB))
      begin
        txd_dB = tsr_qVotedB[tsr_count_qVotedB];
        if (baud_rate_edge_iB)
          begin
            tsr_count_dB = tsr_count_qVotedB + 1;
            tsr_finishB = (tsr_count_qVotedB==word_len_bitsB) ? 1'b1 : 1'b0;
          end

      end

    case (state_qVotedB)
      TXIDLE : 
        begin
          txd_dB = 1'b1;
          tsr_dB = '0;
          tsr_count_dB = 1'b0;
          tsr_emptyB = 1'b1;
          if (reg_read_iB.fcr.fifo_en)
            begin
              if (~fifo_emptyB&baud_rate_edge_iB)
                begin
                  tsr_dB = fifo_data_oB;
                  fifo_popB = 1'b1;
                  state_dB = TXSTART;
                end

            end
          else
            begin
              if (thr_full_qVotedB&baud_rate_edge_iB)
                begin
                  tsr_dB = reg_read_iB.thr.char_tx&word_len_maskB;
                  thr_full_dB = 1'b0;
                  state_dB = TXSTART;
                end

            end
        end
      TXSTART : 
        begin
          txd_dB = 1'b0;
          if (baud_rate_edge_iB)
            begin
              state_dB = TXDATA;
            end

        end
      TXDATA : 
        begin
          if (tsr_finishB)
            begin
              if (reg_read_iB.lcr.par_en)
                begin
                  state_dB = TXPAR;
                end
              else
                begin
                  state_dB = TXSTOP1;
                end
            end

        end
      TXPAR : 
        begin
          case (reg_read_iB.lcr[5:4])
            2'b00 : txd_dB = ~ (^ tsr_qVotedB ) ;
            2'b01 : txd_dB = ^tsr_qVotedB;
            2'b10 : txd_dB = 1'b1;
            2'b11 : txd_dB = 1'b0;
            default : txd_dB = 1'b0;
          endcase
          if (baud_rate_edge_iB)
            begin
              state_dB = TXSTOP1;
            end

        end
      TXSTOP1 : 
        begin
          txd_dB = 1'b1;
          if (reg_read_iB.lcr.stop_bits)
            begin
              state_dB = TXIDLE;
            end
          else
            if (baud_rate_edge_iB)
              begin
                state_dB = TXSTOP2;
              end

        end
      TXSTOP2 : 
        begin
          txd_dB = 1'b1;
          if (word_len_bitsB==3'b100)
            begin
              if (double_rate_edge_iB)
                begin
                  state_dB = TXIDLE;
                end

            end
          else
            begin
              state_dB = TXIDLE;
            end
        end
      default : state_dB = TXIDLE;
    endcase
    if (reg_read_iB.fcr.fifo_en)
      begin
        fifo_clearB = 1'b0;
        if (reg_read_iB.fcr.tx_fifo_rst)
          begin
            fifo_clearB = 1'b1;
            reg_write_oB.fifo_rst = 1'b0;
            reg_write_oB.fifo_rst_valid = 1'b1;
          end

        if (fifo_emptyB)
          begin
            reg_write_oB.thr_empty = 1'b1;
            reg_write_oB.thr_valid = 1'b1;
            if (tsr_emptyB)
              begin
                reg_write_oB.tx_empty = 1'b1;
                reg_write_oB.empty_valid = 1'b1;
              end

          end

        if (thr_full_qVotedB&(~ fifo_fullB ))
          begin
            fifo_pushB = 1'b1;
            fifo_data_iB = reg_read_iB.thr.char_tx&word_len_maskB;
            thr_full_dB = 1'b0;
          end

      end

    if (~reg_read_iB.fcr.fifo_en)
      begin
        fifo_clearB = 1'b1;
        if (~thr_full_qVotedB)
          begin
            reg_write_oB.thr_empty = 1'b1;
            reg_write_oB.thr_valid = 1'b1;
            if (tsr_emptyB)
              begin
                reg_write_oB.tx_empty = 1'b1;
                reg_write_oB.empty_valid = 1'b1;
              end

          end

      end

  end

always_comb
  begin
    thr_full_dC = thr_full_qVotedC;
    word_len_maskC = '0;
    fifo_clearC = 1'b0;
    fifo_pushC = 1'b0;
    fifo_data_iC = '0;
    reg_write_oC = '0;
    state_dC = state_qVotedC;
    txd_oC = txd_qVotedC&~reg_read_iC.lcr.set_break;
    txd_dC = txd_qVotedC;
    fifo_popC = 1'b0;
    tsr_dC = tsr_qVotedC;
    tsr_count_dC = tsr_count_qVotedC;
    tsr_finishC = 1'b0;
    tsr_emptyC = 1'b0;
    case (reg_read_iC.lcr.word_len)
      2'b00 : word_len_bitsC = 3'b100;
      2'b01 : word_len_bitsC = 3'b101;
      2'b10 : word_len_bitsC = 3'b110;
      2'b11 : word_len_bitsC = 3'b111;
      default : word_len_bitsC = 3'b111;
    endcase
    for(int i = 0; i<=word_len_bitsC; i = i + 1)
    begin
      word_len_maskC[i] = 1'b1;
    end
    if (reg_read_iC.obi_write_thr)
      begin
        thr_full_dC = 1'b1;
      end

    if (reg_read_iC.obi_write_thr)
      begin
        reg_write_oC.thr_empty = 1'b0;
        reg_write_oC.tx_empty = 1'b0;
        reg_write_oC.thr_valid = 1'b1;
        reg_write_oC.empty_valid = 1'b1;
      end

    if (state_qVotedC==TXDATA&(tsr_count_qVotedC<=word_len_bitsC))
      begin
        txd_dC = tsr_qVotedC[tsr_count_qVotedC];
        if (baud_rate_edge_iC)
          begin
            tsr_count_dC = tsr_count_qVotedC + 1;
            tsr_finishC = (tsr_count_qVotedC==word_len_bitsC) ? 1'b1 : 1'b0;
          end

      end

    case (state_qVotedC)
      TXIDLE : 
        begin
          txd_dC = 1'b1;
          tsr_dC = '0;
          tsr_count_dC = 1'b0;
          tsr_emptyC = 1'b1;
          if (reg_read_iC.fcr.fifo_en)
            begin
              if (~fifo_emptyC&baud_rate_edge_iC)
                begin
                  tsr_dC = fifo_data_oC;
                  fifo_popC = 1'b1;
                  state_dC = TXSTART;
                end

            end
          else
            begin
              if (thr_full_qVotedC&baud_rate_edge_iC)
                begin
                  tsr_dC = reg_read_iC.thr.char_tx&word_len_maskC;
                  thr_full_dC = 1'b0;
                  state_dC = TXSTART;
                end

            end
        end
      TXSTART : 
        begin
          txd_dC = 1'b0;
          if (baud_rate_edge_iC)
            begin
              state_dC = TXDATA;
            end

        end
      TXDATA : 
        begin
          if (tsr_finishC)
            begin
              if (reg_read_iC.lcr.par_en)
                begin
                  state_dC = TXPAR;
                end
              else
                begin
                  state_dC = TXSTOP1;
                end
            end

        end
      TXPAR : 
        begin
          case (reg_read_iC.lcr[5:4])
            2'b00 : txd_dC = ~ (^ tsr_qVotedC ) ;
            2'b01 : txd_dC = ^tsr_qVotedC;
            2'b10 : txd_dC = 1'b1;
            2'b11 : txd_dC = 1'b0;
            default : txd_dC = 1'b0;
          endcase
          if (baud_rate_edge_iC)
            begin
              state_dC = TXSTOP1;
            end

        end
      TXSTOP1 : 
        begin
          txd_dC = 1'b1;
          if (reg_read_iC.lcr.stop_bits)
            begin
              state_dC = TXIDLE;
            end
          else
            if (baud_rate_edge_iC)
              begin
                state_dC = TXSTOP2;
              end

        end
      TXSTOP2 : 
        begin
          txd_dC = 1'b1;
          if (word_len_bitsC==3'b100)
            begin
              if (double_rate_edge_iC)
                begin
                  state_dC = TXIDLE;
                end

            end
          else
            begin
              state_dC = TXIDLE;
            end
        end
      default : state_dC = TXIDLE;
    endcase
    if (reg_read_iC.fcr.fifo_en)
      begin
        fifo_clearC = 1'b0;
        if (reg_read_iC.fcr.tx_fifo_rst)
          begin
            fifo_clearC = 1'b1;
            reg_write_oC.fifo_rst = 1'b0;
            reg_write_oC.fifo_rst_valid = 1'b1;
          end

        if (fifo_emptyC)
          begin
            reg_write_oC.thr_empty = 1'b1;
            reg_write_oC.thr_valid = 1'b1;
            if (tsr_emptyC)
              begin
                reg_write_oC.tx_empty = 1'b1;
                reg_write_oC.empty_valid = 1'b1;
              end

          end

        if (thr_full_qVotedC&(~ fifo_fullC ))
          begin
            fifo_pushC = 1'b1;
            fifo_data_iC = reg_read_iC.thr.char_tx&word_len_maskC;
            thr_full_dC = 1'b0;
          end

      end

    if (~reg_read_iC.fcr.fifo_en)
      begin
        fifo_clearC = 1'b1;
        if (~thr_full_qVotedC)
          begin
            reg_write_oC.thr_empty = 1'b1;
            reg_write_oC.thr_valid = 1'b1;
            if (tsr_emptyC)
              begin
                reg_write_oC.tx_empty = 1'b1;
                reg_write_oC.empty_valid = 1'b1;
              end

          end

      end

  end

always_ff @( posedge ( clk_iA ) or negedge ( rst_niA ) )
  begin
    if (!rst_niA)
      begin
        thr_full_qA <=  ('0) ;
      end
    else
      begin
        thr_full_qA <=  (thr_full_dA) ;
      end
  end

always_ff @( posedge ( clk_iB ) or negedge ( rst_niB ) )
  begin
    if (!rst_niB)
      begin
        thr_full_qB <=  ('0) ;
      end
    else
      begin
        thr_full_qB <=  (thr_full_dB) ;
      end
  end

always_ff @( posedge ( clk_iC ) or negedge ( rst_niC ) )
  begin
    if (!rst_niC)
      begin
        thr_full_qC <=  ('0) ;
      end
    else
      begin
        thr_full_qC <=  (thr_full_dC) ;
      end
  end

always_ff @( posedge ( clk_iA ) or negedge ( rst_niA ) )
  begin
    if (!rst_niA)
      begin
        tsr_qA <=  ('0) ;
      end
    else
      begin
        tsr_qA <=  (tsr_dA) ;
      end
  end

always_ff @( posedge ( clk_iB ) or negedge ( rst_niB ) )
  begin
    if (!rst_niB)
      begin
        tsr_qB <=  ('0) ;
      end
    else
      begin
        tsr_qB <=  (tsr_dB) ;
      end
  end

always_ff @( posedge ( clk_iC ) or negedge ( rst_niC ) )
  begin
    if (!rst_niC)
      begin
        tsr_qC <=  ('0) ;
      end
    else
      begin
        tsr_qC <=  (tsr_dC) ;
      end
  end

always_ff @( posedge ( clk_iA ) or negedge ( rst_niA ) )
  begin
    if (!rst_niA)
      begin
        tsr_count_qA <=  ('0) ;
      end
    else
      begin
        tsr_count_qA <=  (tsr_count_dA) ;
      end
  end

always_ff @( posedge ( clk_iB ) or negedge ( rst_niB ) )
  begin
    if (!rst_niB)
      begin
        tsr_count_qB <=  ('0) ;
      end
    else
      begin
        tsr_count_qB <=  (tsr_count_dB) ;
      end
  end

always_ff @( posedge ( clk_iC ) or negedge ( rst_niC ) )
  begin
    if (!rst_niC)
      begin
        tsr_count_qC <=  ('0) ;
      end
    else
      begin
        tsr_count_qC <=  (tsr_count_dC) ;
      end
  end

always_ff @( posedge ( clk_iA ) or negedge ( rst_niA ) )
  begin
    if (!rst_niA)
      begin
        txd_qA <=  ('1) ;
      end
    else
      begin
        txd_qA <=  (txd_dA) ;
      end
  end

always_ff @( posedge ( clk_iB ) or negedge ( rst_niB ) )
  begin
    if (!rst_niB)
      begin
        txd_qB <=  ('1) ;
      end
    else
      begin
        txd_qB <=  (txd_dB) ;
      end
  end

always_ff @( posedge ( clk_iC ) or negedge ( rst_niC ) )
  begin
    if (!rst_niC)
      begin
        txd_qC <=  ('1) ;
      end
    else
      begin
        txd_qC <=  (txd_dC) ;
      end
  end

always_ff @( posedge ( clk_iA ) or negedge ( rst_niA ) )
  begin
    if (!rst_niA)
      begin
        state_qA <=  (TXIDLE) ;
      end
    else
      begin
        state_qA <=  (state_dA) ;
      end
  end

always_ff @( posedge ( clk_iB ) or negedge ( rst_niB ) )
  begin
    if (!rst_niB)
      begin
        state_qB <=  (TXIDLE) ;
      end
    else
      begin
        state_qB <=  (state_dB) ;
      end
  end

always_ff @( posedge ( clk_iC ) or negedge ( rst_niC ) )
  begin
    if (!rst_niC)
      begin
        state_qC <=  (TXIDLE) ;
      end
    else
      begin
        state_qC <=  (state_dC) ;
      end
  end

majorityVoter #(.WIDTH( ($size(state_qVotedA)) )) state_qVoterA (
    .inA(state_qA),
    .inB(state_qB),
    .inC(state_qC),
    .out({state_qVotedA}),
    .tmrErr(state_qTmrErrorA)
  );

majorityVoter thr_full_qVoterA (
    .inA(thr_full_qA),
    .inB(thr_full_qB),
    .inC(thr_full_qC),
    .out(thr_full_qVotedA),
    .tmrErr(thr_full_qTmrErrorA)
  );

majorityVoter #(.WIDTH(3)) tsr_count_qVoterA (
    .inA(tsr_count_qA),
    .inB(tsr_count_qB),
    .inC(tsr_count_qC),
    .out(tsr_count_qVotedA),
    .tmrErr(tsr_count_qTmrErrorA)
  );

majorityVoter #(.WIDTH(8)) tsr_qVoterA (
    .inA(tsr_qA),
    .inB(tsr_qB),
    .inC(tsr_qC),
    .out(tsr_qVotedA),
    .tmrErr(tsr_qTmrErrorA)
  );

majorityVoter txd_qVoterA (
    .inA(txd_qA),
    .inB(txd_qB),
    .inC(txd_qC),
    .out(txd_qVotedA),
    .tmrErr(txd_qTmrErrorA)
  );
assign tmrErrorA = i_fifo_v3tmrErrorA|state_qTmrErrorA|thr_full_qTmrErrorA|tsr_count_qTmrErrorA|tsr_qTmrErrorA|txd_qTmrErrorA;

majorityVoter #(.WIDTH( ($size(state_qVotedA)) )) state_qVoterB (
    .inA(state_qA),
    .inB(state_qB),
    .inC(state_qC),
    .out({state_qVotedB}),
    .tmrErr(state_qTmrErrorB)
  );

majorityVoter thr_full_qVoterB (
    .inA(thr_full_qA),
    .inB(thr_full_qB),
    .inC(thr_full_qC),
    .out(thr_full_qVotedB),
    .tmrErr(thr_full_qTmrErrorB)
  );

majorityVoter #(.WIDTH(3)) tsr_count_qVoterB (
    .inA(tsr_count_qA),
    .inB(tsr_count_qB),
    .inC(tsr_count_qC),
    .out(tsr_count_qVotedB),
    .tmrErr(tsr_count_qTmrErrorB)
  );

majorityVoter #(.WIDTH(8)) tsr_qVoterB (
    .inA(tsr_qA),
    .inB(tsr_qB),
    .inC(tsr_qC),
    .out(tsr_qVotedB),
    .tmrErr(tsr_qTmrErrorB)
  );

majorityVoter txd_qVoterB (
    .inA(txd_qA),
    .inB(txd_qB),
    .inC(txd_qC),
    .out(txd_qVotedB),
    .tmrErr(txd_qTmrErrorB)
  );
assign tmrErrorB = i_fifo_v3tmrErrorB|state_qTmrErrorB|thr_full_qTmrErrorB|tsr_count_qTmrErrorB|tsr_qTmrErrorB|txd_qTmrErrorB;

majorityVoter #(.WIDTH( ($size(state_qVotedA)) )) state_qVoterC (
    .inA(state_qA),
    .inB(state_qB),
    .inC(state_qC),
    .out({state_qVotedC}),
    .tmrErr(state_qTmrErrorC)
  );

majorityVoter thr_full_qVoterC (
    .inA(thr_full_qA),
    .inB(thr_full_qB),
    .inC(thr_full_qC),
    .out(thr_full_qVotedC),
    .tmrErr(thr_full_qTmrErrorC)
  );

majorityVoter #(.WIDTH(3)) tsr_count_qVoterC (
    .inA(tsr_count_qA),
    .inB(tsr_count_qB),
    .inC(tsr_count_qC),
    .out(tsr_count_qVotedC),
    .tmrErr(tsr_count_qTmrErrorC)
  );

majorityVoter #(.WIDTH(8)) tsr_qVoterC (
    .inA(tsr_qA),
    .inB(tsr_qB),
    .inC(tsr_qC),
    .out(tsr_qVotedC),
    .tmrErr(tsr_qTmrErrorC)
  );

majorityVoter txd_qVoterC (
    .inA(txd_qA),
    .inB(txd_qB),
    .inC(txd_qC),
    .out(txd_qVotedC),
    .tmrErr(txd_qTmrErrorC)
  );
assign tmrErrorC = i_fifo_v3tmrErrorC|state_qTmrErrorC|thr_full_qTmrErrorC|tsr_count_qTmrErrorC|tsr_qTmrErrorC|txd_qTmrErrorC;
endmodule

