/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_uart_modemTMR.sv                                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 21/11/2025 17:11:13                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_cut.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_uart_modem.sv                                                             *
 *           Git SHA           : 447415eb81dc2b4b7207859bd13a526ebb52ed0b                           *
 *           Modification time : 2025-11-12 14:35:25.614265                                         *
 *           File Size         : 5316                                                               *
 *           MD5 hash          : 2921dd1abadfdd57a930d1914a68f8eb                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module obi_uart_modemTMR import obi_uart_pkg::*; (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic cts_niA,
  input logic cts_niB,
  input logic cts_niC,
  input logic dsr_niA,
  input logic dsr_niB,
  input logic dsr_niC,
  input logic ri_niA,
  input logic ri_niB,
  input logic ri_niC,
  input logic cd_niA,
  input logic cd_niB,
  input logic cd_niC,
  output logic rts_noA,
  output logic rts_noB,
  output logic rts_noC,
  output logic dtr_noA,
  output logic dtr_noB,
  output logic dtr_noC,
  output logic out1_noA,
  output logic out1_noB,
  output logic out1_noC,
  output logic out2_noA,
  output logic out2_noB,
  output logic out2_noC,
  input reg_read_t reg_read_iA,
  input reg_read_t reg_read_iB,
  input reg_read_t reg_read_iC,
  output msr_bits_t reg_write_oA,
  output msr_bits_t reg_write_oB,
  output msr_bits_t reg_write_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire sync_ri_n_qTmrErrorC;
wire sync_dsr_n_qTmrErrorC;
wire sync_cts_n_qTmrErrorC;
wire sync_cd_n_qTmrErrorC;
wire i_sync_ritmrErrorC;
wire i_sync_dsrtmrErrorC;
wire i_sync_ctstmrErrorC;
wire i_sync_cdtmrErrorC;
wire sync_ri_n_qTmrErrorB;
wire sync_dsr_n_qTmrErrorB;
wire sync_cts_n_qTmrErrorB;
wire sync_cd_n_qTmrErrorB;
wire i_sync_ritmrErrorB;
wire i_sync_dsrtmrErrorB;
wire i_sync_ctstmrErrorB;
wire i_sync_cdtmrErrorB;
wire sync_ri_n_qTmrErrorA;
wire sync_dsr_n_qTmrErrorA;
wire sync_cts_n_qTmrErrorA;
wire sync_cd_n_qTmrErrorA;
wire i_sync_ritmrErrorA;
wire i_sync_dsrtmrErrorA;
wire i_sync_ctstmrErrorA;
wire i_sync_cdtmrErrorA;
logic sync_cts_nA;
logic sync_cts_nB;
logic sync_cts_nC;
logic sync_cts_n_dA;
logic sync_cts_n_dB;
logic sync_cts_n_dC;
logic sync_cts_n_qA;
logic sync_cts_n_qB;
logic sync_cts_n_qC;
logic sync_cts_n_qVotedA;
logic sync_cts_n_qVotedB;
logic sync_cts_n_qVotedC;
logic sync_dsr_nA;
logic sync_dsr_nB;
logic sync_dsr_nC;
logic sync_dsr_n_dA;
logic sync_dsr_n_dB;
logic sync_dsr_n_dC;
logic sync_dsr_n_qA;
logic sync_dsr_n_qB;
logic sync_dsr_n_qC;
logic sync_dsr_n_qVotedA;
logic sync_dsr_n_qVotedB;
logic sync_dsr_n_qVotedC;
logic sync_ri_nA;
logic sync_ri_nB;
logic sync_ri_nC;
logic sync_ri_n_dA;
logic sync_ri_n_dB;
logic sync_ri_n_dC;
logic sync_ri_n_qA;
logic sync_ri_n_qB;
logic sync_ri_n_qC;
logic sync_ri_n_qVotedA;
logic sync_ri_n_qVotedB;
logic sync_ri_n_qVotedC;
logic sync_cd_nA;
logic sync_cd_nB;
logic sync_cd_nC;
logic sync_cd_n_dA;
logic sync_cd_n_dB;
logic sync_cd_n_dC;
logic sync_cd_n_qA;
logic sync_cd_n_qB;
logic sync_cd_n_qC;
logic sync_cd_n_qVotedA;
logic sync_cd_n_qVotedB;
logic sync_cd_n_qVotedC;

syncTMR #(.STAGES(NrSyncStages)) i_sync_cts (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .serial_iA(cts_niA),
    .serial_iB(cts_niB),
    .serial_iC(cts_niC),
    .serial_oA(sync_cts_nA),
    .serial_oB(sync_cts_nB),
    .serial_oC(sync_cts_nC),
    .tmrErrorA(i_sync_ctstmrErrorA),
    .tmrErrorB(i_sync_ctstmrErrorB),
    .tmrErrorC(i_sync_ctstmrErrorC)
  );

syncTMR #(.STAGES(NrSyncStages)) i_sync_dsr (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .serial_iA(dsr_niA),
    .serial_iB(dsr_niB),
    .serial_iC(dsr_niC),
    .serial_oA(sync_dsr_nA),
    .serial_oB(sync_dsr_nB),
    .serial_oC(sync_dsr_nC),
    .tmrErrorA(i_sync_dsrtmrErrorA),
    .tmrErrorB(i_sync_dsrtmrErrorB),
    .tmrErrorC(i_sync_dsrtmrErrorC)
  );

syncTMR #(.STAGES(NrSyncStages)) i_sync_ri (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .serial_iA(ri_niA),
    .serial_iB(ri_niB),
    .serial_iC(ri_niC),
    .serial_oA(sync_ri_nA),
    .serial_oB(sync_ri_nB),
    .serial_oC(sync_ri_nC),
    .tmrErrorA(i_sync_ritmrErrorA),
    .tmrErrorB(i_sync_ritmrErrorB),
    .tmrErrorC(i_sync_ritmrErrorC)
  );

syncTMR #(.STAGES(NrSyncStages)) i_sync_cd (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .serial_iA(cd_niA),
    .serial_iB(cd_niB),
    .serial_iC(cd_niC),
    .serial_oA(sync_cd_nA),
    .serial_oB(sync_cd_nB),
    .serial_oC(sync_cd_nC),
    .tmrErrorA(i_sync_cdtmrErrorA),
    .tmrErrorB(i_sync_cdtmrErrorB),
    .tmrErrorC(i_sync_cdtmrErrorC)
  );

always_comb
  begin
    if (reg_read_iA.mcr.loopback==1'b1)
      begin
        rts_noA = 1'b1;
        dtr_noA = 1'b1;
        out1_noA = 1'b1;
        out2_noA = 1'b1;
        sync_cts_n_dA = ~reg_read_iA.mcr.rts;
        sync_dsr_n_dA = ~reg_read_iA.mcr.dtr;
        sync_ri_n_dA = ~reg_read_iA.mcr.out1;
        sync_cd_n_dA = ~reg_read_iA.mcr.out2;
      end
    else
      begin
        rts_noA = ~reg_read_iA.mcr.rts;
        dtr_noA = ~reg_read_iA.mcr.dtr;
        out1_noA = ~reg_read_iA.mcr.out1;
        out2_noA = ~reg_read_iA.mcr.out2;
        sync_cts_n_dA = sync_cts_nA;
        sync_dsr_n_dA = sync_dsr_nA;
        sync_ri_n_dA = sync_ri_nA;
        sync_cd_n_dA = sync_cd_nA;
      end
  end

always_comb
  begin
    if (reg_read_iB.mcr.loopback==1'b1)
      begin
        rts_noB = 1'b1;
        dtr_noB = 1'b1;
        out1_noB = 1'b1;
        out2_noB = 1'b1;
        sync_cts_n_dB = ~reg_read_iB.mcr.rts;
        sync_dsr_n_dB = ~reg_read_iB.mcr.dtr;
        sync_ri_n_dB = ~reg_read_iB.mcr.out1;
        sync_cd_n_dB = ~reg_read_iB.mcr.out2;
      end
    else
      begin
        rts_noB = ~reg_read_iB.mcr.rts;
        dtr_noB = ~reg_read_iB.mcr.dtr;
        out1_noB = ~reg_read_iB.mcr.out1;
        out2_noB = ~reg_read_iB.mcr.out2;
        sync_cts_n_dB = sync_cts_nB;
        sync_dsr_n_dB = sync_dsr_nB;
        sync_ri_n_dB = sync_ri_nB;
        sync_cd_n_dB = sync_cd_nB;
      end
  end

always_comb
  begin
    if (reg_read_iC.mcr.loopback==1'b1)
      begin
        rts_noC = 1'b1;
        dtr_noC = 1'b1;
        out1_noC = 1'b1;
        out2_noC = 1'b1;
        sync_cts_n_dC = ~reg_read_iC.mcr.rts;
        sync_dsr_n_dC = ~reg_read_iC.mcr.dtr;
        sync_ri_n_dC = ~reg_read_iC.mcr.out1;
        sync_cd_n_dC = ~reg_read_iC.mcr.out2;
      end
    else
      begin
        rts_noC = ~reg_read_iC.mcr.rts;
        dtr_noC = ~reg_read_iC.mcr.dtr;
        out1_noC = ~reg_read_iC.mcr.out1;
        out2_noC = ~reg_read_iC.mcr.out2;
        sync_cts_n_dC = sync_cts_nC;
        sync_dsr_n_dC = sync_dsr_nC;
        sync_ri_n_dC = sync_ri_nC;
        sync_cd_n_dC = sync_cd_nC;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        sync_cts_n_qA <= '1;
      end
    else
      begin
        sync_cts_n_qA <= sync_cts_n_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        sync_cts_n_qB <= '1;
      end
    else
      begin
        sync_cts_n_qB <= sync_cts_n_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        sync_cts_n_qC <= '1;
      end
    else
      begin
        sync_cts_n_qC <= sync_cts_n_dC;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        sync_dsr_n_qA <= '1;
      end
    else
      begin
        sync_dsr_n_qA <= sync_dsr_n_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        sync_dsr_n_qB <= '1;
      end
    else
      begin
        sync_dsr_n_qB <= sync_dsr_n_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        sync_dsr_n_qC <= '1;
      end
    else
      begin
        sync_dsr_n_qC <= sync_dsr_n_dC;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        sync_ri_n_qA <= '1;
      end
    else
      begin
        sync_ri_n_qA <= sync_ri_n_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        sync_ri_n_qB <= '1;
      end
    else
      begin
        sync_ri_n_qB <= sync_ri_n_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        sync_ri_n_qC <= '1;
      end
    else
      begin
        sync_ri_n_qC <= sync_ri_n_dC;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        sync_cd_n_qA <= '1;
      end
    else
      begin
        sync_cd_n_qA <= sync_cd_n_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        sync_cd_n_qB <= '1;
      end
    else
      begin
        sync_cd_n_qB <= sync_cd_n_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        sync_cd_n_qC <= '1;
      end
    else
      begin
        sync_cd_n_qC <= sync_cd_n_dC;
      end
  end
assign reg_write_oA.cts = ~sync_cts_n_dA;
assign reg_write_oB.cts = ~sync_cts_n_dB;
assign reg_write_oC.cts = ~sync_cts_n_dC;
assign reg_write_oA.dsr = ~sync_dsr_n_dA;
assign reg_write_oB.dsr = ~sync_dsr_n_dB;
assign reg_write_oC.dsr = ~sync_dsr_n_dC;
assign reg_write_oA.ri = ~sync_ri_n_dA;
assign reg_write_oB.ri = ~sync_ri_n_dB;
assign reg_write_oC.ri = ~sync_ri_n_dC;
assign reg_write_oA.cd = ~sync_cd_n_dA;
assign reg_write_oB.cd = ~sync_cd_n_dB;
assign reg_write_oC.cd = ~sync_cd_n_dC;
assign reg_write_oA.d_cts = sync_cts_n_dA^sync_cts_n_qVotedA;
assign reg_write_oB.d_cts = sync_cts_n_dB^sync_cts_n_qVotedB;
assign reg_write_oC.d_cts = sync_cts_n_dC^sync_cts_n_qVotedC;
assign reg_write_oA.d_dsr = sync_dsr_n_dA^sync_dsr_n_qVotedA;
assign reg_write_oB.d_dsr = sync_dsr_n_dB^sync_dsr_n_qVotedB;
assign reg_write_oC.d_dsr = sync_dsr_n_dC^sync_dsr_n_qVotedC;
assign reg_write_oA.te_ri = sync_ri_n_dA&~sync_ri_n_qVotedA;
assign reg_write_oB.te_ri = sync_ri_n_dB&~sync_ri_n_qVotedB;
assign reg_write_oC.te_ri = sync_ri_n_dC&~sync_ri_n_qVotedC;
assign reg_write_oA.d_cd = sync_cd_n_dA^sync_cd_n_qVotedA;
assign reg_write_oB.d_cd = sync_cd_n_dB^sync_cd_n_qVotedB;
assign reg_write_oC.d_cd = sync_cd_n_dC^sync_cd_n_qVotedC;

majorityVoter sync_cd_n_qVoterA (
    .inA(sync_cd_n_qA),
    .inB(sync_cd_n_qB),
    .inC(sync_cd_n_qC),
    .out(sync_cd_n_qVotedA),
    .tmrErr(sync_cd_n_qTmrErrorA)
  );

majorityVoter sync_cts_n_qVoterA (
    .inA(sync_cts_n_qA),
    .inB(sync_cts_n_qB),
    .inC(sync_cts_n_qC),
    .out(sync_cts_n_qVotedA),
    .tmrErr(sync_cts_n_qTmrErrorA)
  );

majorityVoter sync_dsr_n_qVoterA (
    .inA(sync_dsr_n_qA),
    .inB(sync_dsr_n_qB),
    .inC(sync_dsr_n_qC),
    .out(sync_dsr_n_qVotedA),
    .tmrErr(sync_dsr_n_qTmrErrorA)
  );

majorityVoter sync_ri_n_qVoterA (
    .inA(sync_ri_n_qA),
    .inB(sync_ri_n_qB),
    .inC(sync_ri_n_qC),
    .out(sync_ri_n_qVotedA),
    .tmrErr(sync_ri_n_qTmrErrorA)
  );
assign tmrErrorA = i_sync_cdtmrErrorA|i_sync_ctstmrErrorA|i_sync_dsrtmrErrorA|i_sync_ritmrErrorA|sync_cd_n_qTmrErrorA|sync_cts_n_qTmrErrorA|sync_dsr_n_qTmrErrorA|sync_ri_n_qTmrErrorA;

majorityVoter sync_cd_n_qVoterB (
    .inA(sync_cd_n_qA),
    .inB(sync_cd_n_qB),
    .inC(sync_cd_n_qC),
    .out(sync_cd_n_qVotedB),
    .tmrErr(sync_cd_n_qTmrErrorB)
  );

majorityVoter sync_cts_n_qVoterB (
    .inA(sync_cts_n_qA),
    .inB(sync_cts_n_qB),
    .inC(sync_cts_n_qC),
    .out(sync_cts_n_qVotedB),
    .tmrErr(sync_cts_n_qTmrErrorB)
  );

majorityVoter sync_dsr_n_qVoterB (
    .inA(sync_dsr_n_qA),
    .inB(sync_dsr_n_qB),
    .inC(sync_dsr_n_qC),
    .out(sync_dsr_n_qVotedB),
    .tmrErr(sync_dsr_n_qTmrErrorB)
  );

majorityVoter sync_ri_n_qVoterB (
    .inA(sync_ri_n_qA),
    .inB(sync_ri_n_qB),
    .inC(sync_ri_n_qC),
    .out(sync_ri_n_qVotedB),
    .tmrErr(sync_ri_n_qTmrErrorB)
  );
assign tmrErrorB = i_sync_cdtmrErrorB|i_sync_ctstmrErrorB|i_sync_dsrtmrErrorB|i_sync_ritmrErrorB|sync_cd_n_qTmrErrorB|sync_cts_n_qTmrErrorB|sync_dsr_n_qTmrErrorB|sync_ri_n_qTmrErrorB;

majorityVoter sync_cd_n_qVoterC (
    .inA(sync_cd_n_qA),
    .inB(sync_cd_n_qB),
    .inC(sync_cd_n_qC),
    .out(sync_cd_n_qVotedC),
    .tmrErr(sync_cd_n_qTmrErrorC)
  );

majorityVoter sync_cts_n_qVoterC (
    .inA(sync_cts_n_qA),
    .inB(sync_cts_n_qB),
    .inC(sync_cts_n_qC),
    .out(sync_cts_n_qVotedC),
    .tmrErr(sync_cts_n_qTmrErrorC)
  );

majorityVoter sync_dsr_n_qVoterC (
    .inA(sync_dsr_n_qA),
    .inB(sync_dsr_n_qB),
    .inC(sync_dsr_n_qC),
    .out(sync_dsr_n_qVotedC),
    .tmrErr(sync_dsr_n_qTmrErrorC)
  );

majorityVoter sync_ri_n_qVoterC (
    .inA(sync_ri_n_qA),
    .inB(sync_ri_n_qB),
    .inC(sync_ri_n_qC),
    .out(sync_ri_n_qVotedC),
    .tmrErr(sync_ri_n_qTmrErrorC)
  );
assign tmrErrorC = i_sync_cdtmrErrorC|i_sync_ctstmrErrorC|i_sync_dsrtmrErrorC|i_sync_ritmrErrorC|sync_cd_n_qTmrErrorC|sync_cts_n_qTmrErrorC|sync_dsr_n_qTmrErrorC|sync_ri_n_qTmrErrorC;
endmodule

