/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_uart_baudgenTMR.sv                                                      *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:07                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_uart_baudgen.sv                                                           *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.582265                                         *
 *           File Size         : 5060                                                               *
 *           MD5 hash          : a25752950d3841564cf8f9ffc23e102e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module obi_uart_baudgenTMR import obi_uart_pkg::*; (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  output logic oversample_rate_edge_oA,
  output logic oversample_rate_edge_oB,
  output logic oversample_rate_edge_oC,
  output logic double_rate_edge_oA,
  output logic double_rate_edge_oB,
  output logic double_rate_edge_oC,
  output logic baud_rate_edge_oA,
  output logic baud_rate_edge_oB,
  output logic baud_rate_edge_oC,
  input reg_read_t reg_read_iA,
  input reg_read_t reg_read_iB,
  input reg_read_t reg_read_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_oversample_countertmrErrorC;
wire i_baudrate_countertmrErrorC;
wire clear_double_qTmrErrorC;
wire i_oversample_countertmrErrorB;
wire i_baudrate_countertmrErrorB;
wire clear_double_qTmrErrorB;
wire i_oversample_countertmrErrorA;
wire i_baudrate_countertmrErrorA;
wire clear_double_qTmrErrorA;
logic [15:0] divisorA;
logic [15:0] divisorB;
logic [15:0] divisorC;
logic divisor_validA;
logic divisor_validB;
logic divisor_validC;
logic oversample_is_divisorA;
logic oversample_is_divisorB;
logic oversample_is_divisorC;
logic oversample_clearA;
logic oversample_clearB;
logic oversample_clearC;
logic [15:0] oversample_countA;
logic [15:0] oversample_countB;
logic [15:0] oversample_countC;
logic clear_double_dA;
logic clear_double_dB;
logic clear_double_dC;
logic clear_double_qA;
logic clear_double_qB;
logic clear_double_qC;
logic clear_double_qVotedA;
logic clear_double_qVotedB;
logic clear_double_qVotedC;
logic count_is_doubleA;
logic count_is_doubleB;
logic count_is_doubleC;
logic baud_clearA;
logic baud_clearB;
logic baud_clearC;
logic [3:0] baud_countA;
logic [3:0] baud_countB;
logic [3:0] baud_countC;
logic baud_count_overflowA;
logic baud_count_overflowB;
logic baud_count_overflowC;
assign divisorA = {reg_read_iA.dlm, reg_read_iA.dll} - 16'd1;
assign divisorB = {reg_read_iB.dlm, reg_read_iB.dll} - 16'd1;
assign divisorC = {reg_read_iC.dlm, reg_read_iC.dll} - 16'd1;
assign divisor_validA = ~ (divisorA==0) ;
assign divisor_validB = ~ (divisorB==0) ;
assign divisor_validC = ~ (divisorC==0) ;
assign oversample_is_divisorA =  (oversample_countA==divisorA) &divisor_validA;
assign oversample_is_divisorB =  (oversample_countB==divisorB) &divisor_validB;
assign oversample_is_divisorC =  (oversample_countC==divisorC) &divisor_validC;
assign oversample_clearA = oversample_is_divisorA|reg_read_iA.obi_write_dllm;
assign oversample_clearB = oversample_is_divisorB|reg_read_iB.obi_write_dllm;
assign oversample_clearC = oversample_is_divisorC|reg_read_iC.obi_write_dllm;

counterTMR #(.WIDTH(16), .STICKY_OVERFLOW(0)) i_oversample_counter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .clear_iA(oversample_clearA),
    .clear_iB(oversample_clearB),
    .clear_iC(oversample_clearC),
    .en_iA(divisor_validA),
    .en_iB(divisor_validB),
    .en_iC(divisor_validC),
    .load_iA(1'b0),
    .load_iB(1'b0),
    .load_iC(1'b0),
    .down_iA(1'b0),
    .down_iB(1'b0),
    .down_iC(1'b0),
    .d_iA('0),
    .d_iB('0),
    .d_iC('0),
    .q_oA(oversample_countA),
    .q_oB(oversample_countB),
    .q_oC(oversample_countC),
    .overflow_oA(),
    .overflow_oB(),
    .overflow_oC(),
    .tmrErrorA(i_oversample_countertmrErrorA),
    .tmrErrorB(i_oversample_countertmrErrorB),
    .tmrErrorC(i_oversample_countertmrErrorC)
  );
assign oversample_rate_edge_oA =  (oversample_countA=='0) &divisor_validA;
assign oversample_rate_edge_oB =  (oversample_countB=='0) &divisor_validB;
assign oversample_rate_edge_oC =  (oversample_countC=='0) &divisor_validC;
assign baud_clearA = baud_count_overflowA|reg_read_iA.obi_write_dllm;
assign baud_clearB = baud_count_overflowB|reg_read_iB.obi_write_dllm;
assign baud_clearC = baud_count_overflowC|reg_read_iC.obi_write_dllm;

counterTMR #(.WIDTH(4), .STICKY_OVERFLOW(0)) i_baudrate_counter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .clear_iA(baud_clearA),
    .clear_iB(baud_clearB),
    .clear_iC(baud_clearC),
    .en_iA(oversample_is_divisorA),
    .en_iB(oversample_is_divisorB),
    .en_iC(oversample_is_divisorC),
    .load_iA(1'b0),
    .load_iB(1'b0),
    .load_iC(1'b0),
    .down_iA(1'b0),
    .down_iB(1'b0),
    .down_iC(1'b0),
    .d_iA('0),
    .d_iB('0),
    .d_iC('0),
    .q_oA(baud_countA),
    .q_oB(baud_countB),
    .q_oC(baud_countC),
    .overflow_oA(baud_count_overflowA),
    .overflow_oB(baud_count_overflowB),
    .overflow_oC(baud_count_overflowC),
    .tmrErrorA(i_baudrate_countertmrErrorA),
    .tmrErrorB(i_baudrate_countertmrErrorB),
    .tmrErrorC(i_baudrate_countertmrErrorC)
  );
assign baud_rate_edge_oA = baud_count_overflowA;
assign baud_rate_edge_oB = baud_count_overflowB;
assign baud_rate_edge_oC = baud_count_overflowC;
assign count_is_doubleA =  (baud_countA[2:0]=='0) ;
assign count_is_doubleB =  (baud_countB[2:0]=='0) ;
assign count_is_doubleC =  (baud_countC[2:0]=='0) ;
assign clear_double_dA = count_is_doubleA;
assign clear_double_dB = count_is_doubleB;
assign clear_double_dC = count_is_doubleC;
assign double_rate_edge_oA = count_is_doubleA&~clear_double_qVotedA;
assign double_rate_edge_oB = count_is_doubleB&~clear_double_qVotedB;
assign double_rate_edge_oC = count_is_doubleC&~clear_double_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        clear_double_qA <= '0;
      end
    else
      begin
        clear_double_qA <= clear_double_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        clear_double_qB <= '0;
      end
    else
      begin
        clear_double_qB <= clear_double_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        clear_double_qC <= '0;
      end
    else
      begin
        clear_double_qC <= clear_double_dC;
      end
  end

majorityVoter clear_double_qVoterA (
    .inA(clear_double_qA),
    .inB(clear_double_qB),
    .inC(clear_double_qC),
    .out(clear_double_qVotedA),
    .tmrErr(clear_double_qTmrErrorA)
  );
assign tmrErrorA = clear_double_qTmrErrorA|i_baudrate_countertmrErrorA|i_oversample_countertmrErrorA;

majorityVoter clear_double_qVoterB (
    .inA(clear_double_qA),
    .inB(clear_double_qB),
    .inC(clear_double_qC),
    .out(clear_double_qVotedB),
    .tmrErr(clear_double_qTmrErrorB)
  );
assign tmrErrorB = clear_double_qTmrErrorB|i_baudrate_countertmrErrorB|i_oversample_countertmrErrorB;

majorityVoter clear_double_qVoterC (
    .inA(clear_double_qA),
    .inB(clear_double_qB),
    .inC(clear_double_qC),
    .out(clear_double_qVotedC),
    .tmrErr(clear_double_qTmrErrorC)
  );
assign tmrErrorC = clear_double_qTmrErrorC|i_baudrate_countertmrErrorC|i_oversample_countertmrErrorC;
endmodule

