/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/obi_uartTMR.sv                                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:07                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/obi_uart.sv                                                                   *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.566265                                         *
 *           File Size         : 5850                                                               *
 *           MD5 hash          : 1635937e765a4b24998d7fb352ffe63e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module obi_uartTMR #(
  parameter obi_pkg::obi_cfg_t ObiCfg = obi_pkg::ObiDefaultConfig,
  parameter type               obi_req_t = logic,
  parameter type               obi_rsp_t = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input obi_req_t obi_req_iA,
  input obi_req_t obi_req_iB,
  input obi_req_t obi_req_iC,
  output obi_rsp_t obi_rsp_oA,
  output obi_rsp_t obi_rsp_oB,
  output obi_rsp_t obi_rsp_oC,
  output logic irq_oA,
  output logic irq_oB,
  output logic irq_oC,
  output logic irq_noA,
  output logic irq_noB,
  output logic irq_noC,
  input logic rxd_iA,
  input logic rxd_iB,
  input logic rxd_iC,
  output logic txd_oA,
  output logic txd_oB,
  output logic txd_oC,
  input logic cts_niA,
  input logic cts_niB,
  input logic cts_niC,
  input logic dsr_niA,
  input logic dsr_niB,
  input logic dsr_niC,
  input logic ri_niA,
  input logic ri_niB,
  input logic ri_niC,
  input logic cd_niA,
  input logic cd_niB,
  input logic cd_niC,
  output logic rts_noA,
  output logic rts_noB,
  output logic rts_noC,
  output logic dtr_noA,
  output logic dtr_noB,
  output logic dtr_noC,
  output logic out1_noA,
  output logic out1_noB,
  output logic out1_noC,
  output logic out2_noA,
  output logic out2_noB,
  output logic out2_noC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import obi_uart_pkg::*;
wor i_uart_txtmrErrorC;
wor i_uart_rxtmrErrorC;
wor i_uart_registertmrErrorC;
wor i_uart_modemtmrErrorC;
wor i_uart_interruptstmrErrorC;
wor i_uart_baudgentmrErrorC;
wor i_uart_txtmrErrorB;
wor i_uart_rxtmrErrorB;
wor i_uart_registertmrErrorB;
wor i_uart_modemtmrErrorB;
wor i_uart_interruptstmrErrorB;
wor i_uart_baudgentmrErrorB;
wor i_uart_txtmrErrorA;
wor i_uart_rxtmrErrorA;
wor i_uart_registertmrErrorA;
wor i_uart_modemtmrErrorA;
wor i_uart_interruptstmrErrorA;
wor i_uart_baudgentmrErrorA;
logic rxdA;
logic rxdB;
logic rxdC;
logic txdA;
logic txdB;
logic txdC;
logic rx_fifo_triggerA;
logic rx_fifo_triggerB;
logic rx_fifo_triggerC;
logic rx_timeoutA;
logic rx_timeoutB;
logic rx_timeoutC;
reg_read_t reg_readA;
reg_read_t reg_readB;
reg_read_t reg_readC;
reg_write_t reg_writeA;
reg_write_t reg_writeB;
reg_write_t reg_writeC;
logic oversample_rate_edgeA;
logic oversample_rate_edgeB;
logic oversample_rate_edgeC;
logic double_rate_edgeA;
logic double_rate_edgeB;
logic double_rate_edgeC;
logic baud_rate_edgeA;
logic baud_rate_edgeB;
logic baud_rate_edgeC;

obi_uart_registerTMR #(.obi_req_t(obi_req_t), .obi_rsp_t(obi_rsp_t)) i_uart_register (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .obi_req_iA(obi_req_iA),
    .obi_req_iB(obi_req_iB),
    .obi_req_iC(obi_req_iC),
    .obi_rsp_oA(obi_rsp_oA),
    .obi_rsp_oB(obi_rsp_oB),
    .obi_rsp_oC(obi_rsp_oC),
    .reg_read_oA(reg_readA),
    .reg_read_oB(reg_readB),
    .reg_read_oC(reg_readC),
    .reg_write_iA(reg_writeA),
    .reg_write_iB(reg_writeB),
    .reg_write_iC(reg_writeC),
    .tmrErrorA(i_uart_registertmrErrorA),
    .tmrErrorB(i_uart_registertmrErrorB),
    .tmrErrorC(i_uart_registertmrErrorC)
  );

obi_uart_modemTMR i_uart_modem (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .cts_niA(cts_niA),
    .cts_niB(cts_niB),
    .cts_niC(cts_niC),
    .dsr_niA(dsr_niA),
    .dsr_niB(dsr_niB),
    .dsr_niC(dsr_niC),
    .ri_niA(ri_niA),
    .ri_niB(ri_niB),
    .ri_niC(ri_niC),
    .cd_niA(cd_niA),
    .cd_niB(cd_niB),
    .cd_niC(cd_niC),
    .rts_noA(rts_noA),
    .rts_noB(rts_noB),
    .rts_noC(rts_noC),
    .dtr_noA(dtr_noA),
    .dtr_noB(dtr_noB),
    .dtr_noC(dtr_noC),
    .out1_noA(out1_noA),
    .out1_noB(out1_noB),
    .out1_noC(out1_noC),
    .out2_noA(out2_noA),
    .out2_noB(out2_noB),
    .out2_noC(out2_noC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.modem),
    .reg_write_oB(reg_writeB.modem),
    .reg_write_oC(reg_writeC.modem),
    .tmrErrorA(i_uart_modemtmrErrorA),
    .tmrErrorB(i_uart_modemtmrErrorB),
    .tmrErrorC(i_uart_modemtmrErrorC)
  );
assign txd_oA = (reg_readA.mcr.loopback==1'b1) ? 1'b1 : txdA;
assign txd_oB = (reg_readB.mcr.loopback==1'b1) ? 1'b1 : txdB;
assign txd_oC = (reg_readC.mcr.loopback==1'b1) ? 1'b1 : txdC;
assign rxdA = (reg_readA.mcr.loopback==1'b1) ? txdA : rxd_iA;
assign rxdB = (reg_readB.mcr.loopback==1'b1) ? txdB : rxd_iB;
assign rxdC = (reg_readC.mcr.loopback==1'b1) ? txdC : rxd_iC;

obi_uart_baudgenTMR i_uart_baudgen (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .oversample_rate_edge_oA(oversample_rate_edgeA),
    .oversample_rate_edge_oB(oversample_rate_edgeB),
    .oversample_rate_edge_oC(oversample_rate_edgeC),
    .double_rate_edge_oA(double_rate_edgeA),
    .double_rate_edge_oB(double_rate_edgeB),
    .double_rate_edge_oC(double_rate_edgeC),
    .baud_rate_edge_oA(baud_rate_edgeA),
    .baud_rate_edge_oB(baud_rate_edgeB),
    .baud_rate_edge_oC(baud_rate_edgeC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .tmrErrorA(i_uart_baudgentmrErrorA),
    .tmrErrorB(i_uart_baudgentmrErrorB),
    .tmrErrorC(i_uart_baudgentmrErrorC)
  );

obi_uart_rxTMR i_uart_rx (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .oversample_rate_edge_iA(oversample_rate_edgeA),
    .oversample_rate_edge_iB(oversample_rate_edgeB),
    .oversample_rate_edge_iC(oversample_rate_edgeC),
    .baud_rate_edge_iA(baud_rate_edgeA),
    .baud_rate_edge_iB(baud_rate_edgeB),
    .baud_rate_edge_iC(baud_rate_edgeC),
    .rxd_iA(rxdA),
    .rxd_iB(rxdB),
    .rxd_iC(rxdC),
    .trigger_oA(rx_fifo_triggerA),
    .trigger_oB(rx_fifo_triggerB),
    .trigger_oC(rx_fifo_triggerC),
    .timeout_oA(rx_timeoutA),
    .timeout_oB(rx_timeoutB),
    .timeout_oC(rx_timeoutC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.rx),
    .reg_write_oB(reg_writeB.rx),
    .reg_write_oC(reg_writeC.rx),
    .tmrErrorA(i_uart_rxtmrErrorA),
    .tmrErrorB(i_uart_rxtmrErrorB),
    .tmrErrorC(i_uart_rxtmrErrorC)
  );

obi_uart_txTMR i_uart_tx (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .baud_rate_edge_iA(baud_rate_edgeA),
    .baud_rate_edge_iB(baud_rate_edgeB),
    .baud_rate_edge_iC(baud_rate_edgeC),
    .double_rate_edge_iA(double_rate_edgeA),
    .double_rate_edge_iB(double_rate_edgeB),
    .double_rate_edge_iC(double_rate_edgeC),
    .txd_oA(txdA),
    .txd_oB(txdB),
    .txd_oC(txdC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.tx),
    .reg_write_oB(reg_writeB.tx),
    .reg_write_oC(reg_writeC.tx),
    .tmrErrorA(i_uart_txtmrErrorA),
    .tmrErrorB(i_uart_txtmrErrorB),
    .tmrErrorC(i_uart_txtmrErrorC)
  );

obi_uart_interruptsTMR i_uart_interrupts (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .rx_fifo_triggerA(rx_fifo_triggerA),
    .rx_fifo_triggerB(rx_fifo_triggerB),
    .rx_fifo_triggerC(rx_fifo_triggerC),
    .rx_timeoutA(rx_timeoutA),
    .rx_timeoutB(rx_timeoutB),
    .rx_timeoutC(rx_timeoutC),
    .irq_oA(irq_oA),
    .irq_oB(irq_oB),
    .irq_oC(irq_oC),
    .irq_noA(irq_noA),
    .irq_noB(irq_noB),
    .irq_noC(irq_noC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_iA(reg_writeA),
    .reg_write_iB(reg_writeB),
    .reg_write_iC(reg_writeC),
    .reg_isr_oA(reg_writeA.isr),
    .reg_isr_oB(reg_writeB.isr),
    .reg_isr_oC(reg_writeC.isr),
    .tmrErrorA(i_uart_interruptstmrErrorA),
    .tmrErrorB(i_uart_interruptstmrErrorB),
    .tmrErrorC(i_uart_interruptstmrErrorC)
  );
assign tmrErrorA = i_uart_baudgentmrErrorA|i_uart_interruptstmrErrorA|i_uart_modemtmrErrorA|i_uart_registertmrErrorA|i_uart_rxtmrErrorA|i_uart_txtmrErrorA;
assign tmrErrorB = i_uart_baudgentmrErrorB|i_uart_interruptstmrErrorB|i_uart_modemtmrErrorB|i_uart_registertmrErrorB|i_uart_rxtmrErrorB|i_uart_txtmrErrorB;
assign tmrErrorC = i_uart_baudgentmrErrorC|i_uart_interruptstmrErrorC|i_uart_modemtmrErrorC|i_uart_registertmrErrorC|i_uart_rxtmrErrorC|i_uart_txtmrErrorC;
endmodule

