/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/periph_to_regTMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:05                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/periph_to_reg.sv                                                              *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.694266                                         *
 *           File Size         : 3977                                                               *
 *           MD5 hash          : 3d6fd4e621517b161a22f9b2d0a6b087                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module periph_to_regTMR #(
  parameter int unsigned AW = 32,
  parameter int unsigned DW = 32,
  parameter int unsigned BW = 8,
  parameter int unsigned IW = 0,
  parameter type         req_t = logic,
  parameter type         rsp_t = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic req_iA,
  input logic req_iB,
  input logic req_iC,
  input logic [AW - 1:0] add_iA,
  input logic [AW - 1:0] add_iB,
  input logic [AW - 1:0] add_iC,
  input logic wen_iA,
  input logic wen_iB,
  input logic wen_iC,
  input logic [DW - 1:0] wdata_iA,
  input logic [DW - 1:0] wdata_iB,
  input logic [DW - 1:0] wdata_iC,
  input logic [DW / BW - 1:0] be_iA,
  input logic [DW / BW - 1:0] be_iB,
  input logic [DW / BW - 1:0] be_iC,
  input logic [IW - 1:0] id_iA,
  input logic [IW - 1:0] id_iB,
  input logic [IW - 1:0] id_iC,
  output logic gnt_oA,
  output logic gnt_oB,
  output logic gnt_oC,
  output logic [DW - 1:0] r_rdata_oA,
  output logic [DW - 1:0] r_rdata_oB,
  output logic [DW - 1:0] r_rdata_oC,
  output logic r_opc_oA,
  output logic r_opc_oB,
  output logic r_opc_oC,
  output logic [IW - 1:0] r_id_oA,
  output logic [IW - 1:0] r_id_oB,
  output logic [IW - 1:0] r_id_oC,
  output logic r_valid_oA,
  output logic r_valid_oB,
  output logic r_valid_oC,
  output req_t reg_req_oA,
  output req_t reg_req_oB,
  output req_t reg_req_oC,
  input rsp_t reg_rsp_iA,
  input rsp_t reg_rsp_iB,
  input rsp_t reg_rsp_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire r_valid_qTmrErrorC;
wire r_rdata_qTmrErrorC;
wire r_opc_qTmrErrorC;
wire r_id_qTmrErrorC;
wire r_valid_qTmrErrorB;
wire r_rdata_qTmrErrorB;
wire r_opc_qTmrErrorB;
wire r_id_qTmrErrorB;
wire r_valid_qTmrErrorA;
wire r_rdata_qTmrErrorA;
wire r_opc_qTmrErrorA;
wire r_id_qTmrErrorA;
logic [IW - 1:0] r_id_dA;
logic [IW - 1:0] r_id_dB;
logic [IW - 1:0] r_id_dC;
logic [IW - 1:0] r_id_qA;
logic [IW - 1:0] r_id_qB;
logic [IW - 1:0] r_id_qC;
logic [IW - 1:0] r_id_qVotedA;
logic [IW - 1:0] r_id_qVotedB;
logic [IW - 1:0] r_id_qVotedC;
logic r_opc_dA;
logic r_opc_dB;
logic r_opc_dC;
logic r_opc_qA;
logic r_opc_qB;
logic r_opc_qC;
logic r_opc_qVotedA;
logic r_opc_qVotedB;
logic r_opc_qVotedC;
logic r_valid_dA;
logic r_valid_dB;
logic r_valid_dC;
logic r_valid_qA;
logic r_valid_qB;
logic r_valid_qC;
logic r_valid_qVotedA;
logic r_valid_qVotedB;
logic r_valid_qVotedC;
logic [DW - 1:0] r_rdata_dA;
logic [DW - 1:0] r_rdata_dB;
logic [DW - 1:0] r_rdata_dC;
logic [DW - 1:0] r_rdata_qA;
logic [DW - 1:0] r_rdata_qB;
logic [DW - 1:0] r_rdata_qC;
logic [DW - 1:0] r_rdata_qVotedA;
logic [DW - 1:0] r_rdata_qVotedB;
logic [DW - 1:0] r_rdata_qVotedC;

always_comb
  begin : proc_logicA
    r_id_dA = id_iA;
    r_opc_dA = reg_rsp_iA.error;
    r_valid_dA = gnt_oA;
    r_rdata_dA = reg_rsp_iA.rdata;
  end

always_comb
  begin : proc_logicB
    r_id_dB = id_iB;
    r_opc_dB = reg_rsp_iB.error;
    r_valid_dB = gnt_oB;
    r_rdata_dB = reg_rsp_iB.rdata;
  end

always_comb
  begin : proc_logicC
    r_id_dC = id_iC;
    r_opc_dC = reg_rsp_iC.error;
    r_valid_dC = gnt_oC;
    r_rdata_dC = reg_rsp_iC.rdata;
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : proc_seqA
    if (!rst_niA)
      begin
        r_id_qA <= '0;
        r_opc_qA <= '0;
        r_valid_qA <= '0;
        r_rdata_qA <= '0;
      end
    else
      begin
        r_id_qA <= r_id_dA;
        r_opc_qA <= r_opc_dA;
        r_valid_qA <= r_valid_dA;
        r_rdata_qA <= r_rdata_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : proc_seqB
    if (!rst_niB)
      begin
        r_id_qB <= '0;
        r_opc_qB <= '0;
        r_valid_qB <= '0;
        r_rdata_qB <= '0;
      end
    else
      begin
        r_id_qB <= r_id_dB;
        r_opc_qB <= r_opc_dB;
        r_valid_qB <= r_valid_dB;
        r_rdata_qB <= r_rdata_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : proc_seqC
    if (!rst_niC)
      begin
        r_id_qC <= '0;
        r_opc_qC <= '0;
        r_valid_qC <= '0;
        r_rdata_qC <= '0;
      end
    else
      begin
        r_id_qC <= r_id_dC;
        r_opc_qC <= r_opc_dC;
        r_valid_qC <= r_valid_dC;
        r_rdata_qC <= r_rdata_dC;
      end
  end
assign reg_req_oA.addr = add_iA;
assign reg_req_oB.addr = add_iB;
assign reg_req_oC.addr = add_iC;
assign reg_req_oA.write = ~wen_iA;
assign reg_req_oB.write = ~wen_iB;
assign reg_req_oC.write = ~wen_iC;
assign reg_req_oA.wdata = wdata_iA;
assign reg_req_oB.wdata = wdata_iB;
assign reg_req_oC.wdata = wdata_iC;
assign reg_req_oA.wstrb = be_iA;
assign reg_req_oB.wstrb = be_iB;
assign reg_req_oC.wstrb = be_iC;
assign reg_req_oA.valid = req_iA;
assign reg_req_oB.valid = req_iB;
assign reg_req_oC.valid = req_iC;
assign gnt_oA = req_iA&reg_rsp_iA.ready;
assign gnt_oB = req_iB&reg_rsp_iB.ready;
assign gnt_oC = req_iC&reg_rsp_iC.ready;
assign r_rdata_oA = r_rdata_qVotedA;
assign r_rdata_oB = r_rdata_qVotedB;
assign r_rdata_oC = r_rdata_qVotedC;
assign r_opc_oA = r_opc_qVotedA;
assign r_opc_oB = r_opc_qVotedB;
assign r_opc_oC = r_opc_qVotedC;
assign r_id_oA = r_id_qVotedA;
assign r_id_oB = r_id_qVotedB;
assign r_id_oC = r_id_qVotedC;
assign r_valid_oA = r_valid_qVotedA;
assign r_valid_oB = r_valid_qVotedB;
assign r_valid_oC = r_valid_qVotedC;

majorityVoter #(.WIDTH( ((((IW-1)>0) ? (IW-1) : - ( IW-1 ) )+1) )) r_id_qVoterA (
    .inA(r_id_qA),
    .inB(r_id_qB),
    .inC(r_id_qC),
    .out(r_id_qVotedA),
    .tmrErr(r_id_qTmrErrorA)
  );

majorityVoter r_opc_qVoterA (
    .inA(r_opc_qA),
    .inB(r_opc_qB),
    .inC(r_opc_qC),
    .out(r_opc_qVotedA),
    .tmrErr(r_opc_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((DW-1)>0) ? (DW-1) : - ( DW-1 ) )+1) )) r_rdata_qVoterA (
    .inA(r_rdata_qA),
    .inB(r_rdata_qB),
    .inC(r_rdata_qC),
    .out(r_rdata_qVotedA),
    .tmrErr(r_rdata_qTmrErrorA)
  );

majorityVoter r_valid_qVoterA (
    .inA(r_valid_qA),
    .inB(r_valid_qB),
    .inC(r_valid_qC),
    .out(r_valid_qVotedA),
    .tmrErr(r_valid_qTmrErrorA)
  );
assign tmrErrorA = r_id_qTmrErrorA|r_opc_qTmrErrorA|r_rdata_qTmrErrorA|r_valid_qTmrErrorA;

majorityVoter #(.WIDTH( ((((IW-1)>0) ? (IW-1) : - ( IW-1 ) )+1) )) r_id_qVoterB (
    .inA(r_id_qA),
    .inB(r_id_qB),
    .inC(r_id_qC),
    .out(r_id_qVotedB),
    .tmrErr(r_id_qTmrErrorB)
  );

majorityVoter r_opc_qVoterB (
    .inA(r_opc_qA),
    .inB(r_opc_qB),
    .inC(r_opc_qC),
    .out(r_opc_qVotedB),
    .tmrErr(r_opc_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((DW-1)>0) ? (DW-1) : - ( DW-1 ) )+1) )) r_rdata_qVoterB (
    .inA(r_rdata_qA),
    .inB(r_rdata_qB),
    .inC(r_rdata_qC),
    .out(r_rdata_qVotedB),
    .tmrErr(r_rdata_qTmrErrorB)
  );

majorityVoter r_valid_qVoterB (
    .inA(r_valid_qA),
    .inB(r_valid_qB),
    .inC(r_valid_qC),
    .out(r_valid_qVotedB),
    .tmrErr(r_valid_qTmrErrorB)
  );
assign tmrErrorB = r_id_qTmrErrorB|r_opc_qTmrErrorB|r_rdata_qTmrErrorB|r_valid_qTmrErrorB;

majorityVoter #(.WIDTH( ((((IW-1)>0) ? (IW-1) : - ( IW-1 ) )+1) )) r_id_qVoterC (
    .inA(r_id_qA),
    .inB(r_id_qB),
    .inC(r_id_qC),
    .out(r_id_qVotedC),
    .tmrErr(r_id_qTmrErrorC)
  );

majorityVoter r_opc_qVoterC (
    .inA(r_opc_qA),
    .inB(r_opc_qB),
    .inC(r_opc_qC),
    .out(r_opc_qVotedC),
    .tmrErr(r_opc_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((DW-1)>0) ? (DW-1) : - ( DW-1 ) )+1) )) r_rdata_qVoterC (
    .inA(r_rdata_qA),
    .inB(r_rdata_qB),
    .inC(r_rdata_qC),
    .out(r_rdata_qVotedC),
    .tmrErr(r_rdata_qTmrErrorC)
  );

majorityVoter r_valid_qVoterC (
    .inA(r_valid_qA),
    .inB(r_valid_qB),
    .inC(r_valid_qC),
    .out(r_valid_qVotedC),
    .tmrErr(r_valid_qTmrErrorC)
  );
assign tmrErrorC = r_id_qTmrErrorC|r_opc_qTmrErrorC|r_rdata_qTmrErrorC|r_valid_qTmrErrorC;
endmodule

