/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/rr_arb_treeTMR.sv                                                           *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:06                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/rr_arb_tree.sv                                                                *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.742267                                         *
 *           File Size         : 13104                                                              *
 *           MD5 hash          : 913e4c07d7d4993316f9ea01e95ebf9b                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module rr_arb_treeTMR #(
  parameter int unsigned NumIn = 64,
  parameter int unsigned DataWidth = 32,
  parameter type         DataType   = logic [DataWidth-1:0],
  parameter bit ExtPrio = 1'b0,
  parameter bit AxiVldRdy = 1'b0,
  parameter bit LockIn = 1'b0,
  parameter bit FairArb = 1'b1,
  parameter int unsigned IdxWidth = (NumIn>32'd1) ? unsigned ' ( $clog2(NumIn) )  : 32'd1,
  parameter type         idx_t      = logic [IdxWidth-1:0]
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  input idx_t rr_iA,
  input idx_t rr_iB,
  input idx_t rr_iC,
  input logic [NumIn - 1:0] req_iA,
  input logic [NumIn - 1:0] req_iB,
  input logic [NumIn - 1:0] req_iC,
  output logic [NumIn - 1:0] gnt_oA,
  output logic [NumIn - 1:0] gnt_oB,
  output logic [NumIn - 1:0] gnt_oC,
  input DataType [NumIn - 1:0] data_iA,
  input DataType [NumIn - 1:0] data_iB,
  input DataType [NumIn - 1:0] data_iC,
  output logic req_oA,
  output logic req_oB,
  output logic req_oC,
  input logic gnt_iA,
  input logic gnt_iB,
  input logic gnt_iC,
  output DataType data_oA,
  output DataType data_oB,
  output DataType data_oC,
  output idx_t idx_oA,
  output idx_t idx_oB,
  output idx_t idx_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
localparam int unsigned NumLevels = unsigned' ($clog2(NumIn)) ;
wire rr_qTmrErrorC;
wire req_qTmrErrorC;
wire lock_qTmrErrorC;
wire rr_qTmrErrorB;
wire req_qTmrErrorB;
wire lock_qTmrErrorB;
wire rr_qTmrErrorA;
wire req_qTmrErrorA;
wire lock_qTmrErrorA;
idx_t [2**NumLevels - 2:0] index_nodesA;
idx_t [2**NumLevels - 2:0] index_nodesB;
idx_t [2**NumLevels - 2:0] index_nodesC;
DataType [2**NumLevels - 2:0] data_nodesA;
DataType [2**NumLevels - 2:0] data_nodesB;
DataType [2**NumLevels - 2:0] data_nodesC;
logic [2**NumLevels - 2:0] gnt_nodesA;
logic [2**NumLevels - 2:0] gnt_nodesB;
logic [2**NumLevels - 2:0] gnt_nodesC;
logic [2**NumLevels - 2:0] req_nodesA;
logic [2**NumLevels - 2:0] req_nodesB;
logic [2**NumLevels - 2:0] req_nodesC;
idx_t rr_qA;
idx_t rr_qB;
idx_t rr_qC;
idx_t rr_qVotedA;
idx_t rr_qVotedB;
idx_t rr_qVotedC;
logic [NumIn - 1:0] req_dA;
logic [NumIn - 1:0] req_dB;
logic [NumIn - 1:0] req_dC;
idx_t rr_dA;
idx_t rr_dB;
idx_t rr_dC;
logic lock_dA;
logic lock_dB;
logic lock_dC;
logic lock_qA;
logic lock_qB;
logic lock_qC;
logic lock_qVotedA;
logic lock_qVotedB;
logic lock_qVotedC;
logic [NumIn - 1:0] req_qA;
logic [NumIn - 1:0] req_qB;
logic [NumIn - 1:0] req_qC;
logic [NumIn - 1:0] req_qVotedA;
logic [NumIn - 1:0] req_qVotedB;
logic [NumIn - 1:0] req_qVotedC;
logic [NumIn - 1:0] upper_maskA;
logic [NumIn - 1:0] upper_maskB;
logic [NumIn - 1:0] upper_maskC;
logic [NumIn - 1:0] lower_maskA;
logic [NumIn - 1:0] lower_maskB;
logic [NumIn - 1:0] lower_maskC;
idx_t upper_idxA;
idx_t upper_idxB;
idx_t upper_idxC;
idx_t lower_idxA;
idx_t lower_idxB;
idx_t lower_idxC;
idx_t next_idxA;
idx_t next_idxB;
idx_t next_idxC;
logic upper_emptyA;
logic upper_emptyB;
logic upper_emptyC;
logic lower_emptyA;
logic lower_emptyB;
logic lower_emptyC;
if (NumIn==unsigned'(1))
  begin : gen_pass_through
    assign req_oA = req_iA[0];
    assign req_oB = req_iB[0];
    assign req_oC = req_iC[0];
    assign gnt_oA[0] = gnt_iA;
    assign gnt_oB[0] = gnt_iB;
    assign gnt_oC[0] = gnt_iC;
    assign data_oA = data_iA[0];
    assign data_oB = data_iB[0];
    assign data_oC = data_iC[0];
    assign idx_oA = '0;
    assign idx_oB = '0;
    assign idx_oC = '0;
  end

else
  begin : gen_arbiter
    assign req_oA = req_nodesA[0];
    assign req_oB = req_nodesB[0];
    assign req_oC = req_nodesC[0];
    assign data_oA = data_nodesA[0];
    assign data_oB = data_nodesB[0];
    assign data_oC = data_nodesC[0];
    assign idx_oA = index_nodesA[0];
    assign idx_oB = index_nodesB[0];
    assign idx_oC = index_nodesC[0];
    if (ExtPrio)
          begin : gen_ext_rr
        assign rr_qA = rr_iA;
        assign rr_qB = rr_iB;
        assign rr_qC = rr_iC;
        assign req_dA = req_iA;
        assign req_dB = req_iB;
        assign req_dC = req_iC;
      end

    else
          begin : gen_int_rr
        if (LockIn)
                  begin : gen_lock
            assign lock_dA = req_oA&~gnt_iA;
            assign lock_dB = req_oB&~gnt_iB;
            assign lock_dC = req_oC&~gnt_iC;
            assign req_dA = (lock_qVotedA) ? req_qVotedA : req_iA;
            assign req_dB = (lock_qVotedB) ? req_qVotedB : req_iB;
            assign req_dC = (lock_qVotedC) ? req_qVotedC : req_iC;

            always_ff @( posedge clk_iA or negedge rst_niA )
              begin : p_lock_regA
                if (!rst_niA)
                  begin
                    lock_qA <= '0;
                  end
                else
                  begin
                    if (flush_iA)
                      begin
                        lock_qA <= '0;
                      end
                    else
                      begin
                        lock_qA <= lock_dA;
                      end
                  end
              end

            always_ff @( posedge clk_iB or negedge rst_niB )
              begin : p_lock_regB
                if (!rst_niB)
                  begin
                    lock_qB <= '0;
                  end
                else
                  begin
                    if (flush_iB)
                      begin
                        lock_qB <= '0;
                      end
                    else
                      begin
                        lock_qB <= lock_dB;
                      end
                  end
              end

            always_ff @( posedge clk_iC or negedge rst_niC )
              begin : p_lock_regC
                if (!rst_niC)
                  begin
                    lock_qC <= '0;
                  end
                else
                  begin
                    if (flush_iC)
                      begin
                        lock_qC <= '0;
                      end
                    else
                      begin
                        lock_qC <= lock_dC;
                      end
                  end
              end

            always_ff @( posedge clk_iA or negedge rst_niA )
              begin : p_req_regsA
                if (!rst_niA)
                  begin
                    req_qA <= '0;
                  end
                else
                  begin
                    if (flush_iA)
                      begin
                        req_qA <= '0;
                      end
                    else
                      begin
                        req_qA <= req_dA;
                      end
                  end
              end

            always_ff @( posedge clk_iB or negedge rst_niB )
              begin : p_req_regsB
                if (!rst_niB)
                  begin
                    req_qB <= '0;
                  end
                else
                  begin
                    if (flush_iB)
                      begin
                        req_qB <= '0;
                      end
                    else
                      begin
                        req_qB <= req_dB;
                      end
                  end
              end

            always_ff @( posedge clk_iC or negedge rst_niC )
              begin : p_req_regsC
                if (!rst_niC)
                  begin
                    req_qC <= '0;
                  end
                else
                  begin
                    if (flush_iC)
                      begin
                        req_qC <= '0;
                      end
                    else
                      begin
                        req_qC <= req_dC;
                      end
                  end
              end
          end

        else
                  begin : gen_no_lock
            assign req_dA = req_iA;
            assign req_dB = req_iB;
            assign req_dC = req_iC;
          end
        if (FairArb)
                  begin : gen_fair_arb
            for(genvar i = 0; i<NumIn; i++)
                          begin : gen_mask
                assign upper_maskA[i] = (i>rr_qVotedA) ? req_dA[i] : 1'b0;
                assign upper_maskB[i] = (i>rr_qVotedB) ? req_dB[i] : 1'b0;
                assign upper_maskC[i] = (i>rr_qVotedC) ? req_dC[i] : 1'b0;
                assign lower_maskA[i] = (i<=rr_qVotedA) ? req_dA[i] : 1'b0;
                assign lower_maskB[i] = (i<=rr_qVotedB) ? req_dB[i] : 1'b0;
                assign lower_maskC[i] = (i<=rr_qVotedC) ? req_dC[i] : 1'b0;
              end

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_upperA (
                .in_i(upper_maskA),
                .cnt_o(upper_idxA),
                .empty_o(upper_emptyA)
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_upperB (
                .in_i(upper_maskB),
                .cnt_o(upper_idxB),
                .empty_o(upper_emptyB)
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_upperC (
                .in_i(upper_maskC),
                .cnt_o(upper_idxC),
                .empty_o(upper_emptyC)
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_lowerA (
                .in_i(lower_maskA),
                .cnt_o(lower_idxA),
                .empty_o()
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_lowerB (
                .in_i(lower_maskB),
                .cnt_o(lower_idxB),
                .empty_o()
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_lowerC (
                .in_i(lower_maskC),
                .cnt_o(lower_idxC),
                .empty_o()
              );
            assign next_idxA = upper_emptyA ? lower_idxA : upper_idxA;
            assign next_idxB = upper_emptyB ? lower_idxB : upper_idxB;
            assign next_idxC = upper_emptyC ? lower_idxC : upper_idxC;
            assign rr_dA = (gnt_iA&&req_oA) ? next_idxA : rr_qVotedA;
            assign rr_dB = (gnt_iB&&req_oB) ? next_idxB : rr_qVotedB;
            assign rr_dC = (gnt_iC&&req_oC) ? next_idxC : rr_qVotedC;
          end

        else
                  begin : gen_unfair_arb
            assign rr_dA = (gnt_iA&&req_oA) ? ((rr_qVotedA==idx_t'(NumIn-1)) ? '0 : rr_qVotedA+1'b1) : rr_qVotedA;
            assign rr_dB = (gnt_iB&&req_oB) ? ((rr_qVotedB==idx_t'(NumIn-1)) ? '0 : rr_qVotedB+1'b1) : rr_qVotedB;
            assign rr_dC = (gnt_iC&&req_oC) ? ((rr_qVotedC==idx_t'(NumIn-1)) ? '0 : rr_qVotedC+1'b1) : rr_qVotedC;
          end

        always_ff @( posedge clk_iA or negedge rst_niA )
          begin : p_rr_regsA
            if (!rst_niA)
              begin
                rr_qA <= '0;
              end
            else
              begin
                if (flush_iA)
                  begin
                    rr_qA <= '0;
                  end
                else
                  begin
                    rr_qA <= rr_dA;
                  end
              end
          end

        always_ff @( posedge clk_iB or negedge rst_niB )
          begin : p_rr_regsB
            if (!rst_niB)
              begin
                rr_qB <= '0;
              end
            else
              begin
                if (flush_iB)
                  begin
                    rr_qB <= '0;
                  end
                else
                  begin
                    rr_qB <= rr_dB;
                  end
              end
          end

        always_ff @( posedge clk_iC or negedge rst_niC )
          begin : p_rr_regsC
            if (!rst_niC)
              begin
                rr_qC <= '0;
              end
            else
              begin
                if (flush_iC)
                  begin
                    rr_qC <= '0;
                  end
                else
                  begin
                    rr_qC <= rr_dC;
                  end
              end
          end
      end
    assign gnt_nodesA[0] = gnt_iA;
    assign gnt_nodesB[0] = gnt_iB;
    assign gnt_nodesC[0] = gnt_iC;
    for(genvar level = 0; unsigned' (level) <NumLevels; level++)
          begin : gen_levels
        for(genvar l = 0; l<2**level; l++)
                  begin : gen_level
logic selA;
logic selB;
logic selC;
localparam int unsigned Idx0 = 2**level - 1 + l;
localparam int unsigned Idx1 = 2** (level+1)  - 1 + l * 2;
            if (unsigned'(level)==NumLevels-1)
                          begin : gen_first_level
                if (unsigned'(l)*2<NumIn-1)
                                  begin : gen_reduce
                    assign req_nodesA[Idx0] = req_dA[l*2]|req_dA[l*2+1];
                    assign req_nodesB[Idx0] = req_dB[l*2]|req_dB[l*2+1];
                    assign req_nodesC[Idx0] = req_dC[l*2]|req_dC[l*2+1];
                    assign selA = ~req_dA[l*2]|req_dA[l*2+1]&rr_qVotedA[NumLevels-1-level];
                    assign selB = ~req_dB[l*2]|req_dB[l*2+1]&rr_qVotedB[NumLevels-1-level];
                    assign selC = ~req_dC[l*2]|req_dC[l*2+1]&rr_qVotedC[NumLevels-1-level];
                    assign index_nodesA[Idx0] = idx_t' (selA) ;
                    assign index_nodesB[Idx0] = idx_t' (selB) ;
                    assign index_nodesC[Idx0] = idx_t' (selC) ;
                    assign data_nodesA[Idx0] = (selA) ? data_iA[l*2+1] : data_iA[l*2];
                    assign data_nodesB[Idx0] = (selB) ? data_iB[l*2+1] : data_iB[l*2];
                    assign data_nodesC[Idx0] = (selC) ? data_iC[l*2+1] : data_iC[l*2];
                    assign gnt_oA[l*2] = gnt_nodesA[Idx0]& (AxiVldRdy|req_dA[l*2]) &~selA;
                    assign gnt_oB[l*2] = gnt_nodesB[Idx0]& (AxiVldRdy|req_dB[l*2]) &~selB;
                    assign gnt_oC[l*2] = gnt_nodesC[Idx0]& (AxiVldRdy|req_dC[l*2]) &~selC;
                    assign gnt_oA[l*2+1] = gnt_nodesA[Idx0]& (AxiVldRdy|req_dA[l*2+1]) &selA;
                    assign gnt_oB[l*2+1] = gnt_nodesB[Idx0]& (AxiVldRdy|req_dB[l*2+1]) &selB;
                    assign gnt_oC[l*2+1] = gnt_nodesC[Idx0]& (AxiVldRdy|req_dC[l*2+1]) &selC;
                  end
                if (unsigned'(l)*2==NumIn-1)
                                  begin : gen_first
                    assign req_nodesA[Idx0] = req_dA[l*2];
                    assign req_nodesB[Idx0] = req_dB[l*2];
                    assign req_nodesC[Idx0] = req_dC[l*2];
                    assign index_nodesA[Idx0] = '0;
                    assign index_nodesB[Idx0] = '0;
                    assign index_nodesC[Idx0] = '0;
                    assign data_nodesA[Idx0] = data_iA[l*2];
                    assign data_nodesB[Idx0] = data_iB[l*2];
                    assign data_nodesC[Idx0] = data_iC[l*2];
                    assign gnt_oA[l*2] = gnt_nodesA[Idx0]& (AxiVldRdy|req_dA[l*2]) ;
                    assign gnt_oB[l*2] = gnt_nodesB[Idx0]& (AxiVldRdy|req_dB[l*2]) ;
                    assign gnt_oC[l*2] = gnt_nodesC[Idx0]& (AxiVldRdy|req_dC[l*2]) ;
                  end
                if (unsigned'(l)*2>NumIn-1)
                                  begin : gen_out_of_range
                    assign req_nodesA[Idx0] = 1'b0;
                    assign req_nodesB[Idx0] = 1'b0;
                    assign req_nodesC[Idx0] = 1'b0;
                    assign index_nodesA[Idx0] = idx_t' ('0) ;
                    assign index_nodesB[Idx0] = idx_t' ('0) ;
                    assign index_nodesC[Idx0] = idx_t' ('0) ;
                    assign data_nodesA[Idx0] = DataType' ('0) ;
                    assign data_nodesB[Idx0] = DataType' ('0) ;
                    assign data_nodesC[Idx0] = DataType' ('0) ;
                  end
              end

            else
                          begin : gen_other_levels
                assign req_nodesA[Idx0] = req_nodesA[Idx1]|req_nodesA[Idx1+1];
                assign req_nodesB[Idx0] = req_nodesB[Idx1]|req_nodesB[Idx1+1];
                assign req_nodesC[Idx0] = req_nodesC[Idx1]|req_nodesC[Idx1+1];
                assign selA = ~req_nodesA[Idx1]|req_nodesA[Idx1+1]&rr_qVotedA[NumLevels-1-level];
                assign selB = ~req_nodesB[Idx1]|req_nodesB[Idx1+1]&rr_qVotedB[NumLevels-1-level];
                assign selC = ~req_nodesC[Idx1]|req_nodesC[Idx1+1]&rr_qVotedC[NumLevels-1-level];
                assign index_nodesA[Idx0] = (selA) ? idx_t ' ( {1'b1, index_nodesA[Idx1+1][NumLevels - unsigned' (level)  - 2:0]} )  : idx_t ' ( {1'b0, index_nodesA[Idx1][NumLevels - unsigned' (level)  - 2:0]} ) ;
                assign index_nodesB[Idx0] = (selB) ? idx_t ' ( {1'b1, index_nodesB[Idx1+1][NumLevels - unsigned' (level)  - 2:0]} )  : idx_t ' ( {1'b0, index_nodesB[Idx1][NumLevels - unsigned' (level)  - 2:0]} ) ;
                assign index_nodesC[Idx0] = (selC) ? idx_t ' ( {1'b1, index_nodesC[Idx1+1][NumLevels - unsigned' (level)  - 2:0]} )  : idx_t ' ( {1'b0, index_nodesC[Idx1][NumLevels - unsigned' (level)  - 2:0]} ) ;
                assign data_nodesA[Idx0] = (selA) ? data_nodesA[Idx1+1] : data_nodesA[Idx1];
                assign data_nodesB[Idx0] = (selB) ? data_nodesB[Idx1+1] : data_nodesB[Idx1];
                assign data_nodesC[Idx0] = (selC) ? data_nodesC[Idx1+1] : data_nodesC[Idx1];
                assign gnt_nodesA[Idx1] = gnt_nodesA[Idx0]&~selA;
                assign gnt_nodesB[Idx1] = gnt_nodesB[Idx0]&~selB;
                assign gnt_nodesC[Idx1] = gnt_nodesC[Idx0]&~selC;
                assign gnt_nodesA[Idx1+1] = gnt_nodesA[Idx0]&selA;
                assign gnt_nodesB[Idx1+1] = gnt_nodesB[Idx0]&selB;
                assign gnt_nodesC[Idx1+1] = gnt_nodesC[Idx0]&selC;
              end
          end
      end
  end

majorityVoter lock_qVoterA (
    .inA(lock_qA),
    .inB(lock_qB),
    .inC(lock_qC),
    .out(lock_qVotedA),
    .tmrErr(lock_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((NumIn-1)>0) ? (NumIn-1) : - ( NumIn-1 ) )+1) )) req_qVoterA (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedA),
    .tmrErr(req_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ($size(rr_qVotedA)) )) rr_qVoterA (
    .inA(rr_qA),
    .inB(rr_qB),
    .inC(rr_qC),
    .out(rr_qVotedA),
    .tmrErr(rr_qTmrErrorA)
  );
assign tmrErrorA = lock_qTmrErrorA|req_qTmrErrorA|rr_qTmrErrorA;

majorityVoter lock_qVoterB (
    .inA(lock_qA),
    .inB(lock_qB),
    .inC(lock_qC),
    .out(lock_qVotedB),
    .tmrErr(lock_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((NumIn-1)>0) ? (NumIn-1) : - ( NumIn-1 ) )+1) )) req_qVoterB (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedB),
    .tmrErr(req_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ($size(rr_qVotedA)) )) rr_qVoterB (
    .inA(rr_qA),
    .inB(rr_qB),
    .inC(rr_qC),
    .out(rr_qVotedB),
    .tmrErr(rr_qTmrErrorB)
  );
assign tmrErrorB = lock_qTmrErrorB|req_qTmrErrorB|rr_qTmrErrorB;

majorityVoter lock_qVoterC (
    .inA(lock_qA),
    .inB(lock_qB),
    .inC(lock_qC),
    .out(lock_qVotedC),
    .tmrErr(lock_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((NumIn-1)>0) ? (NumIn-1) : - ( NumIn-1 ) )+1) )) req_qVoterC (
    .inA(req_qA),
    .inB(req_qB),
    .inC(req_qC),
    .out(req_qVotedC),
    .tmrErr(req_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ($size(rr_qVotedA)) )) rr_qVoterC (
    .inA(rr_qA),
    .inB(rr_qB),
    .inC(rr_qC),
    .out(rr_qVotedC),
    .tmrErr(rr_qTmrErrorC)
  );
assign tmrErrorC = lock_qTmrErrorC|req_qTmrErrorC|rr_qTmrErrorC;
endmodule : rr_arb_treeTMR

