/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/spill_registerTMR.sv                                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:06                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/spill_register.sv                                                             *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.774267                                         *
 *           File Size         : 1510                                                               *
 *           MD5 hash          : fc3936d89e210d9fd84c4c83155bb745                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module spill_registerTMR #(
  parameter type T      = logic,
  parameter bit Bypass = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  output logic ready_oA,
  output logic ready_oB,
  output logic ready_oC,
  input T data_iA,
  input T data_iB,
  input T data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output T data_oA,
  output T data_oB,
  output T data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor spill_register_flushable_itmrErrorC;
wor spill_register_flushable_itmrErrorB;
wor spill_register_flushable_itmrErrorA;

spill_register_flushableTMR #(.T(T), .Bypass(Bypass)) spill_register_flushable_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .valid_iA(valid_iA),
    .valid_iB(valid_iB),
    .valid_iC(valid_iC),
    .flush_iA(1'b0),
    .flush_iB(1'b0),
    .flush_iC(1'b0),
    .ready_oA(ready_oA),
    .ready_oB(ready_oB),
    .ready_oC(ready_oC),
    .data_iA(data_iA),
    .data_iB(data_iB),
    .data_iC(data_iC),
    .valid_oA(valid_oA),
    .valid_oB(valid_oB),
    .valid_oC(valid_oC),
    .ready_iA(ready_iA),
    .ready_iB(ready_iB),
    .ready_iC(ready_iC),
    .data_oA(data_oA),
    .data_oB(data_oB),
    .data_oC(data_oC),
    .tmrErrorA(spill_register_flushable_itmrErrorA),
    .tmrErrorB(spill_register_flushable_itmrErrorB),
    .tmrErrorC(spill_register_flushable_itmrErrorC)
  );
assign tmrErrorA = spill_register_flushable_itmrErrorA;
assign tmrErrorB = spill_register_flushable_itmrErrorB;
assign tmrErrorC = spill_register_flushable_itmrErrorC;
endmodule

