/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/syncTMR.sv                                                                  *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:09                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/sync.sv                                                                       *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.806267                                         *
 *           File Size         : 1367                                                               *
 *           MD5 hash          : c681eec2dbd89a24e910ca957b133069                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module syncTMR #(
  parameter int unsigned STAGES = 2,
  parameter bit ResetValue = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic serial_iA,
  input logic serial_iB,
  input logic serial_iC,
  output logic serial_oA,
  output logic serial_oB,
  output logic serial_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor reg_qTmrErrorC;
wor reg_qTmrErrorB;
wor reg_qTmrErrorA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qB;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qC;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qVotedA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qVotedB;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qVotedC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        reg_qA <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qA <= {reg_qA[STAGES - 2:0], serial_iA};
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        reg_qB <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qB <= {reg_qB[STAGES - 2:0], serial_iB};
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        reg_qC <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qC <= {reg_qC[STAGES - 2:0], serial_iC};
      end
  end
assign serial_oA = reg_qVotedA[STAGES-1];
assign serial_oB = reg_qVotedB[STAGES-1];
assign serial_oC = reg_qVotedC[STAGES-1];

majorityVoter #(.WIDTH( ((((STAGES-1)>0) ? (STAGES-1) : - ( STAGES-1 ) )+1) )) reg_qVoterA (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedA),
    .tmrErr(reg_qTmrErrorA)
  );
assign tmrErrorA = reg_qTmrErrorA;

majorityVoter #(.WIDTH( ((((STAGES-1)>0) ? (STAGES-1) : - ( STAGES-1 ) )+1) )) reg_qVoterB (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedB),
    .tmrErr(reg_qTmrErrorB)
  );
assign tmrErrorB = reg_qTmrErrorB;

majorityVoter #(.WIDTH( ((((STAGES-1)>0) ? (STAGES-1) : - ( STAGES-1 ) )+1) )) reg_qVoterC (
    .inA(reg_qA),
    .inB(reg_qB),
    .inC(reg_qC),
    .out(reg_qVotedC),
    .tmrErr(reg_qTmrErrorC)
  );
assign tmrErrorC = reg_qTmrErrorC;
endmodule

