/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/timer_unit_counter_prescTMR.sv                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 12/11/2025 14:57:05                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/tmrg_croc                                                              *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv *
 *           tmrg_src/timer_unit.sv tmrg_src/timer_unit_counter.sv tmrg_src/timer_unit_counter_presc.sv *
 *           tmrg_src/tc_sram_impl.sv tmrg_src/soc_ctrl_reg_top.sv tmrg_src/prim_subreg.sv          *
 *           tmrg_src/prim_subreg_arb.sv tmrg_src/periph_to_reg.sv tmrg_src/obi_xbar.sv             *
 *           tmrg_src/obi_demux.sv tmrg_src/obi_mux.sv tmrg_src/obi_err_sbr.sv                      *
 *           tmrg_src/delta_counter.sv tmrg_src/fifo_v3.sv tmrg_src/rr_arb_tree.sv tmrg_src/lzc.sv  *
 *           tmrg_src/spill_register.sv tmrg_src/spill_register_flushable.sv tmrg_src/obi_uart.sv   *
 *           tmrg_src/obi_uart_baudgen.sv tmrg_src/counter.sv tmrg_src/obi_uart_interrupts.sv       *
 *           tmrg_src/obi_uart_modem.sv tmrg_src/obi_uart_register.sv tmrg_src/obi_uart_rx.sv       *
 *           tmrg_src/obi_uart_tx.sv tmrg_src/obi_sram_shim.sv tmrg_src/gpio.sv                     *
 *           tmrg_src/gpio_reg_top.sv tmrg_src/sync.sv tmrg_src/dmi_jtag.sv tmrg_src/dm_obi_top.sv  *
 *           tmrg_src/core_wrap.sv tmrg_src/cve2_core.sv tmrg_src/cve2_cs_registers.sv              *
 *           tmrg_src/cve2_counter.sv tmrg_src/cve2_csr.sv tmrg_src/cve2_ex_block.sv                *
 *           tmrg_src/cve2_alu.sv tmrg_src/cve2_multdiv_fast.sv tmrg_src/cve2_multdiv_slow.sv       *
 *           tmrg_src/cve2_id_stage.sv tmrg_src/cve2_controller.sv tmrg_src/cve2_decoder.sv         *
 *           tmrg_src/cve2_if_stage.sv tmrg_src/cve2_compressed_decoder.sv                          *
 *           tmrg_src/cve2_prefetch_buffer.sv tmrg_src/cve2_fetch_fifo.sv                           *
 *           tmrg_src/cve2_load_store_unit.sv tmrg_src/cve2_pmp.sv tmrg_src/cve2_register_file_ff.sv *
 *           tmrg_src/cve2_wb.sv tmrg_src/rstgen.sv tmrg_src/croc_domain.sv tmrg_src/user_domain.sv *
 *           tmrg_src/croc_soc.sv --top-module=croc_soc --tmr-dir=tmrg_files                        *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/timer_unit_counter_presc.sv                                                   *
 *           Git SHA           : 513877024c58ce622d9f33836c5b6fe0e7ba47dc                           *
 *           Modification time : 2025-11-12 14:35:25.886268                                         *
 *           File Size         : 2359                                                               *
 *           MD5 hash          : 8a18092f25d6c43f2558f697b5f49350                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module timer_unit_counter_prescTMR (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic write_counter_iA,
  input logic write_counter_iB,
  input logic write_counter_iC,
  input logic [31:0] counter_value_iA,
  input logic [31:0] counter_value_iB,
  input logic [31:0] counter_value_iC,
  input logic reset_count_iA,
  input logic reset_count_iB,
  input logic reset_count_iC,
  input logic enable_count_iA,
  input logic enable_count_iB,
  input logic enable_count_iC,
  input logic [31:0] compare_value_iA,
  input logic [31:0] compare_value_iB,
  input logic [31:0] compare_value_iC,
  output logic [31:0] counter_value_oA,
  output logic [31:0] counter_value_oB,
  output logic [31:0] counter_value_oC,
  output logic target_reached_oA,
  output logic target_reached_oB,
  output logic target_reached_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire target_reached_qTmrErrorC;
wire s_count_regTmrErrorC;
wire target_reached_qTmrErrorB;
wire s_count_regTmrErrorB;
wire target_reached_qTmrErrorA;
wire s_count_regTmrErrorA;
logic [31:0] s_countA;
logic [31:0] s_countB;
logic [31:0] s_countC;
logic [31:0] s_count_regA;
logic [31:0] s_count_regB;
logic [31:0] s_count_regC;
logic [31:0] s_count_regVotedA;
logic [31:0] s_count_regVotedB;
logic [31:0] s_count_regVotedC;
logic target_reached_qA;
logic target_reached_qB;
logic target_reached_qC;
logic target_reached_qVotedA;
logic target_reached_qVotedB;
logic target_reached_qVotedC;
assign target_reached_oA = target_reached_qVotedA;
assign target_reached_oB = target_reached_qVotedB;
assign target_reached_oC = target_reached_qVotedC;

always_comb
  begin
    s_countA = s_count_regVotedA;
    if (reset_count_iA==1||target_reached_oA==1)
      s_countA = 0;
    else
      begin
        if (write_counter_iA==1)
          s_countA = counter_value_iA;
        else
          begin
            if (enable_count_iA==1)
              s_countA = s_count_regVotedA + 1;

          end
      end
  end

always_comb
  begin
    s_countB = s_count_regVotedB;
    if (reset_count_iB==1||target_reached_oB==1)
      s_countB = 0;
    else
      begin
        if (write_counter_iB==1)
          s_countB = counter_value_iB;
        else
          begin
            if (enable_count_iB==1)
              s_countB = s_count_regVotedB + 1;

          end
      end
  end

always_comb
  begin
    s_countC = s_count_regVotedC;
    if (reset_count_iC==1||target_reached_oC==1)
      s_countC = 0;
    else
      begin
        if (write_counter_iC==1)
          s_countC = counter_value_iC;
        else
          begin
            if (enable_count_iC==1)
              s_countC = s_count_regVotedC + 1;

          end
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (rst_niA==0)
      s_count_regA <= 0;
    else
      s_count_regA <= s_countA;
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (rst_niB==0)
      s_count_regB <= 0;
    else
      s_count_regB <= s_countB;
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (rst_niC==0)
      s_count_regC <= 0;
    else
      s_count_regC <= s_countC;
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (rst_niA==0)
      target_reached_qA <= 1'b0;
    else
      if (s_countA==compare_value_iA)
        target_reached_qA <= 1'b1;
      else
        target_reached_qA <= 1'b0;
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (rst_niB==0)
      target_reached_qB <= 1'b0;
    else
      if (s_countB==compare_value_iB)
        target_reached_qB <= 1'b1;
      else
        target_reached_qB <= 1'b0;
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (rst_niC==0)
      target_reached_qC <= 1'b0;
    else
      if (s_countC==compare_value_iC)
        target_reached_qC <= 1'b1;
      else
        target_reached_qC <= 1'b0;
  end
assign counter_value_oA = s_count_regVotedA;
assign counter_value_oB = s_count_regVotedB;
assign counter_value_oC = s_count_regVotedC;

majorityVoter #(.WIDTH(32)) s_count_regVoterA (
    .inA(s_count_regA),
    .inB(s_count_regB),
    .inC(s_count_regC),
    .out(s_count_regVotedA),
    .tmrErr(s_count_regTmrErrorA)
  );

majorityVoter target_reached_qVoterA (
    .inA(target_reached_qA),
    .inB(target_reached_qB),
    .inC(target_reached_qC),
    .out(target_reached_qVotedA),
    .tmrErr(target_reached_qTmrErrorA)
  );
assign tmrErrorA = s_count_regTmrErrorA|target_reached_qTmrErrorA;

majorityVoter #(.WIDTH(32)) s_count_regVoterB (
    .inA(s_count_regA),
    .inB(s_count_regB),
    .inC(s_count_regC),
    .out(s_count_regVotedB),
    .tmrErr(s_count_regTmrErrorB)
  );

majorityVoter target_reached_qVoterB (
    .inA(target_reached_qA),
    .inB(target_reached_qB),
    .inC(target_reached_qC),
    .out(target_reached_qVotedB),
    .tmrErr(target_reached_qTmrErrorB)
  );
assign tmrErrorB = s_count_regTmrErrorB|target_reached_qTmrErrorB;

majorityVoter #(.WIDTH(32)) s_count_regVoterC (
    .inA(s_count_regA),
    .inB(s_count_regB),
    .inC(s_count_regC),
    .out(s_count_regVotedC),
    .tmrErr(s_count_regTmrErrorC)
  );

majorityVoter target_reached_qVoterC (
    .inA(target_reached_qA),
    .inB(target_reached_qB),
    .inC(target_reached_qC),
    .out(target_reached_qVotedC),
    .tmrErr(target_reached_qTmrErrorC)
  );
assign tmrErrorC = s_count_regTmrErrorC|target_reached_qTmrErrorC;
endmodule

